### ISSUE TITLE
Bug: Maximum slider setting of `Micro CHP`, residences

### ISSUE THREAD

**Issue by Richard-Deuchler** [quintel/etmodel#1585]
I noticed the following behaviour of the `Micro_CHP` slider in Residences: 
- In an NL **2020** scenario, I can set it to **80%**
- In an NL **2030** scenario, I can set it to **70%**
- in an NL **2050** scenario, I can set it to only **50%**... 

The maximum of that slider is tied to a function that depends on the future target year of the scenario. Obviously, the idea is that the technology becomes 'more available' in the future, but the current implementation does the opposite: The installation of new technology is cut back in more distant scenarios. 

According to @ChaelKruip, the slider maximum is calculated with 
max_value_gql = present:PRODUCT(100,SUM(0.9,NEG(DIVIDE(GRAPH(number_of_years),100))))

![screen shot 2013-08-29 at 4 44 09 pm](https://f.cloud.github.com/assets/2749265/1050422/8800922c-10b9-11e3-80d9-6921370a4364.png)

**Comment by RobTerwel** [comment]
This issue is still present; reopened on @jorisberkhout 's advice. In space heating in a clean Netherlands 2050 scenario, `micro CHP` (combined with hot water) cannot be set higher than 52% 

![screen shot 2015-09-28 at 11 46 07](https://cloud.githubusercontent.com/assets/14106387/10132540/32425c4c-65d7-11e5-9fb5-ad3ef2ced415.png)
As noted above in this issue, in `hot water` (combined with space heating), one can set  `micro CHP` to be 100% *in the same scenario*.


![screen shot 2015-09-28 at 11 52 01](https://cloud.githubusercontent.com/assets/14106387/10132689/17c2964c-65d8-11e5-9bea-0d29e84aaded.png)

**Low priority.**

**Comment by ChaelKruip** [comment]
I think this is not worth the effort at the moment. Closing. Please re-open if still needed.
