### ISSUE TITLE
CHP table totals are not correct for scaled scenario

### ISSUE THREAD

**Issue by ChaelKruip** [quintel/etmodel#1854]
![energy_transition_model_-_your_free__independent__comprehensive__fact-based_scenario_builder_](https://cloud.githubusercontent.com/assets/1303760/5450675/0dce62de-8509-11e4-9a5b-e7cc173f5c99.png)

I'll try to find out if this is a GQL problem and also occurs in unscaled scenario's.

Including @antw

**Comment by ChaelKruip** [comment]
The queries give the correct numbers. It seems that the numbers are multiplied by 1000 by the ETModel interface for the individual technologies but not for the totals. 

Assigning to @antw because this is more his expertise.

**Comment by jorisberkhout** [comment]
Assigning @grdw .

**Comment by grdw** [comment]
I know why this is. It's because it doesn't scale.

In order to do this nicely and for the other static tables aswell, we could give every [static table](https://github.com/quintel/etmodel/tree/master/app/views/output_elements/tables) an extra `data-attribute` called `scaledown` which determines if it takes part in [scaling down](https://github.com/quintel/etmodel/blob/master/app/assets/javascripts/lib/views/html_table_chart_view.coffee#L59) or not. However this also implies that the corresponding table header unit needs to be updated accordingly.

**Comment by grdw** [comment]
.. to continue. Also the static tables "don't know" about the units in the headers which is what makes the scaling a little tougher.

**Comment by ChaelKruip** [comment]
@antw can you make an estimate of how much work this would be? I think we hardly every scale scenario's anyways so perhaps we should not bother with this?

**Comment by antw** [comment]
> make an estimate of how much work this would be?

I've been able to do this...

<img width="613" alt="screen shot 2018-06-27 at 10 26 56" src="https://user-images.githubusercontent.com/4383/41965518-a7102408-79f4-11e8-85ca-4401160118c9.png">

... but this is just a proof-of-concept and the code needs some tidying up and testing if you want to go ahead. I'm guessing there will also have to be adjustments to the other tables. I expect we're looking at about a day to do this.

**Comment by ChaelKruip** [comment]
> I expect we're looking at about a day to do this.

Given the fact that we are moving toward using the ETM for more local (smaller) datasets I think this is a worthwhile investment. @antw can you make this happen at a moment that suits you?

**Comment by michieldenhaan** [comment]
Closing, scaling option has been removed.
