### ISSUE TITLE
Info text for scaled scenario's should be translated to Dutch and typo corrected

### ISSUE THREAD

**Issue by ChaelKruip** [quintel/etmodel#1859]
![energietransitiemodel_-_je_eigen_onafhankelijke__volledige_en_op_feiten_gebaseerde_energiescenario_](https://cloud.githubusercontent.com/assets/1303760/5643280/a2f6b790-9656-11e4-83d9-a18b56ee7a8b.png)

**Comment by antw** [comment]
I got rid of the apostrophe, and moved the text [into a locale file](https://github.com/quintel/etmodel/blob/25851b387415a06dc41e4dc4de0199e3617c218e/config/locales/nl_etm.yml#L112-L129). Could someone provide the translation itself?

I'll remove the milestone since I don't think this is urgent (scaled scenarios are not *yet* an officially-supported feature of the ETM).
