### ISSUE TITLE
Coal price/cost seems inconsistent between front-end and back-end

### ISSUE THREAD

**Issue by ChaelKruip** [quintel/etmodel#1864]
I have loaded the fuel price updates into my local etsource by checking out https://github.com/quintel/etsource/commit/03e9ea5ceadadb32b9596278a51e18327fee134b.

Next, I tinkered with the coal price slider until the ```weighted_carrier_cost_per_mj``` for coal was identical between my local machine and the LIVE server. I also convinced myself that the marginal costs of coal plants was the same between `local' and `LIVE'. In the front-end, however, a different price is shown for coal...

Local machine:
![energy_transition_model_-_your_free__independent__comprehensive__fact-based_scenario_builder_](https://cloud.githubusercontent.com/assets/1303760/5858352/d0075020-a252-11e4-817a-2bdbd831f883.png)
LIVE:
![energy_transition_model_-_your_free__independent__comprehensive__fact-based_scenario_builder_](https://cloud.githubusercontent.com/assets/1303760/5858363/e810d3a8-a252-11e4-9ae5-b9595b382719.png)

Conversely, when I make them equal in the front-end, the back-end shows different coal costs. 

Including @jorisberkhout @AlexanderWirtz @dennisschoenmakers

**Comment by antw** [comment]
I've updated the ETEngine carrier page to also show the future values. Previously it showed only the present values – which caused me much confusion when I couldn't figure out why the slider had no effect.

quintel/etsource@03e9ea5 also [changed dollar_per_euro](https://github.com/quintel/etsource/commit/03e9ea5ceadadb32b9596278a51e18327fee134b#diff-6afd5df1ad74c952a68d45bfade70625L1#diff-17). ETE shows the price in euros while the ETM shows it in dollars; is the difference between live and local due to the new currency conversion rate?

If not, I need a bit more information because I'm not really sure what values are wrong. Could you point me to the relevant ETE and ETM pages and tell me which numbers are not as you expected? It might also help if you could create a scenario on the live server which I can then compare with a local copy.

**Comment by AlexanderWirtz** [comment]
@antw beat me to it. The dollar_per_euro value is quite different between LIve and Beta. Something like 1.35 and 1.18. The Euro has slid in value considerably, mostly due to the Greek debacle, but also other structural weaknesses in Southern Europe / France. Yeah, you really needed to know that.

**Comment by ChaelKruip** [comment]
@antw @AlexanderWirtz thanks for pointing this out. Yesterday I wasn't fresh enough to spot the difference price definitions. I think everything is correct as it is now!
