### ISSUE TITLE
Solar PV potential seem to be doubled when creating technologies from scaled scenario

### ISSUE THREAD

**Issue by ChaelKruip** [quintel/etmodel#1873]
I created a scenario of 100 houses with 50% of the roof surface available to solar PV used (and 50% EV).
When inspecting the technology YAML, there are 100 PV installations and 50 EV (as expected). 
![ivy](https://cloud.githubusercontent.com/assets/1303760/7293259/7ba90af8-e9a3-11e4-9b82-d0e1b497676d.png)

**Comment by ChaelKruip** [comment]
Assigned @grdw to pick this up ASAP.

**Comment by antw** [comment]
I think the problem is that the installed `number_of_units` in ETEngine is [determined by the available roof area](https://github.com/quintel/etsource/blob/588763feef0b8744e61a3ff8d94c654024749217/gqueries/input_elements/max_value/households_potential_electricity_production_of_solar_roof_pv.gql#L4-L7). In an NL scenario scaled to 100 households, with [solar PV potential](http://beta.pro.et-model.com/scenario/demand/households/solar-panels) set to 100%, there are **197** installed solar panels. ETLoader instead [assumes 1 unit = 1 household](https://github.com/quintel/etloader/blob/master/app/models/export.rb#L35).

We could add a "multiplier" attribute to `Technology` to fix this, so that we can alter the value sent back to ETEngine. It would default to 1.0 (so as to have no effect on most technologies) and be set to 0.507 for solar panels: `197 * 0.507 ≈ 100 (%)`.

That's not foolproof though: other regions may have differences in available roof area, but it would probably be good enough for now.

**Comment by ChaelKruip** [comment]
@antw thanks for pointing that out! I never realised that the `number_of_units` of solar panels did not add up to the `number_of_residences`.

> We could add a "multiplier" attribute to Technology to fix this

That is probably the quickest way to solve this. Another (IMO neater) solution would be to redefine the capacities and roof-areas of a 'unit' of solar PV to match the number of residences in each region.

@jorisberkhout @AlexanderWirtz what do you think?

**Comment by ChaelKruip** [comment]
I think this is not an issue as long as we realise that a household typically can have 2 solar panels.
