### ISSUE TITLE
Profitability calculation and chart seem broken in beta. At least for all the optimized scenarios.

### ISSUE THREAD

**Issue by AlexanderWirtz** [quintel/etmodel#1875]
Both the chart and calculation for profitability do not work for these scenarios. 

The merit calculation, table and chart seem to work just fine, as does the LOLE calculation and chart. @ChaelKruip can you have a look at this with high priority as JK has to send a report to RLI including this parameter by 12.00 tomorrow (Thursday the 30th of April)?

# Screenshots for [this scenario](http://beta.pro.et-model.com/scenarios/406793):

Merit order works:
![image](https://cloud.githubusercontent.com/assets/308563/7398311/8eba85ee-eeae-11e4-8cf9-c1180581cee8.png)

![image](https://cloud.githubusercontent.com/assets/308563/7398320/9e3759f2-eeae-11e4-8bdf-b40b163d240d.png)

LOLE works:
![image](https://cloud.githubusercontent.com/assets/308563/7398333/b2924b00-eeae-11e4-81a2-afd04e61c40f.png)

Profitability does this, even though way more installed capacity in listed in the MO table:
![image](https://cloud.githubusercontent.com/assets/308563/7398352/c3556c38-eeae-11e4-9828-2d7a3f5503df.png)

Notifying @dennisschoenmakers and @antw

**Comment by AlexanderWirtz** [comment]
Other scenarios:

http://beta.pro.et-model.com/scenarios/406774
http://beta.pro.et-model.com/scenarios/406777
http://beta.pro.et-model.com/scenarios/406782
http://beta.pro.et-model.com/scenarios/406790

etc

**Comment by antw** [comment]
I checked out the first scenario ([406793](http://beta.pro.et-model.com/scenarios/406793)). Of the technologies which may appear in the profitability table, only coal CHPs, co-firing coal, solar PV, wind turbines, and hydro have any installed capacity in the future. Technologies with no capacity (i.e., all the others) are omitted from the table.

Solar PV, wind, and hydro are not included in the profitability table regardless of whether they have capacity. Don't know if this is intentional.

Co-firing coal was not included in the table as the converter wasn't in the "merit order converters for dashboard" group. I have rectified this, and it now appears. I'm not sure if this omission was *also* intentional; etsource@d2fd7695 can be reverted if so.

The profitability was not being calculated because of a conflict between FCE values (in these scenarios specifically, setting the the source of gas) and the merit order plugin. In short: changing the source of fuel causes the wrong merit order plugin to be loaded, and dispatchables end up omitted from the calculation. The table thus shows their profit as €0. I have created new versions of the scenarios with the gas FCE settings removed. This fixes the lack of profitability information, but causes scenarios 1A and 1B to narrowly miss their 80% CO2 reduction target.

| Scenario | Old ID | New ID |
| ------- | ------- | ------- |
| 3: 99% hernieuwbaar scenario 2050 met... | [406793](http://beta.pro.et-model.com/scenarios/406793) | [407234](http://beta.pro.et-model.com/scenarios/407234) |
| 1A: 80% CO2 reductie zonder kern,... | [406774](http://beta.pro.et-model.com/scenarios/406774) | [407235](http://beta.pro.et-model.com/scenarios/407235) |
| 1B: 80% CO2 reductie scenario met CCS... | [406777](http://beta.pro.et-model.com/scenarios/406777) | [407236](http://beta.pro.et-model.com/scenarios/407236) |
| 1C: 80% CO2 reductie scenario met... | [406782](http://beta.pro.et-model.com/scenarios/406782) | [407237](http://beta.pro.et-model.com/scenarios/407237) |
| 2B: 95% CO2 reductie zonder kern en... | [406790](http://beta.pro.et-model.com/scenarios/406790) | [407238](http://beta.pro.et-model.com/scenarios/407238) |

--

Incidentally, this means that *all* scenarios with custom FCE values are failing to calculate the merit order correctly. The fix for this will be to remove [the input](https://github.com/quintel/etsource/blob/master/inputs/misc/settings_enable_merit_order.ad) which enables and disables the merit order, and convert it to a "proper" attribute on the Scenario model. Which it should have been all along. Like `use_fce` *already* is. :angry: 

However, this change, combined with the need to adapt other applications (ETM, MTurk, and maybe others), is at least a 1-2 day task and not do-able by the midday deadline.

**Comment by ChaelKruip** [comment]
>  I have rectified this, and it now appears. I'm not sure if this omission was also intentional; etsource@d2fd769 can be reverted if so.

That was indeed intentional as the co-firing plant is not an 'actual' plant.It always fires 50% wood-pellets. When the user changes the amount of co-firing, the change is interpreted as a different ratio of this 50-50 plant and the normal 100% coal plant.

**Comment by ChaelKruip** [comment]
> Incidentally, this means that all scenarios with custom FCE values are failing to calculate the merit order correctly.

I suggest that the scenario's be re-run with the optimiser using fixed FCE sliders. Starting from the new IDs that @antw provided (thanks!) this should not take too many iteration I think.

**Comment by ChaelKruip** [comment]
> Merit order works:

Unfortunately that is not the case! As you can see in the merit order table, there are no 'positions' assigned to the plants. The merit order is just turned off (although the button suggests otherwise).

**Comment by antw** [comment]
> The profitability was not being calculated because of a conflict between FCE values and the merit order plugin.

To clarify a bit further: setting FCE values, and using the merit order, are not *intended* to be mutually exclusive. This is an ETEngine bug. A bit of background:

The ETEngine calculation process goes a bit like this:

1. Initial graph setup.
2. Set user values with inputs.
3. Finish graph setup.
4. Calculate GQueries.

The graph has [a range of plugins](https://github.com/quintel/etengine/tree/master/app/models/qernel/plugins) which may be used to add custom behaviour to a scenario; one of these plugins is the Merit Order, another is Fuel Chain Emissions. The graph typically determines which plugins to use during step 3, *after* inputs have been set.

In fact, the Merit Order is split into two separate plugins: one which is best summarised as "[merit order on](https://github.com/quintel/etengine/blob/master/app/models/qernel/plugins/merit_order.rb)", and another which is "[merit order off](https://github.com/quintel/etengine/blob/master/app/models/qernel/plugins/simple_merit_order.rb)". "Merit order off" is used to calculate loss-of-load and the demand curve – features provided by the Merit gem – without the performance penalty of an unnecessary full merit order calculation.

[An input](https://github.com/quintel/etsource/blob/master/inputs/misc/settings_enable_merit_order.ad), set during step 2, sets the `use_merit_order_demands` attribute to be true. We get to step 3, the graph sees that the attribute has been set to true, and it loads the "merit order on" plugin. If the value is false, or not set at all, it loads "merit order off".

Unfortunately, we have FCE-related inputs which call the [`UPDATE_FCE` GQL function](https://github.com/quintel/etengine/blob/master/app/models/gql/runtime/functions/update.rb#L317); it accesses the FCE plugin in order to set the values provided by the user. This causes the graph to set up its plugins prematurely (during step 2 instead of step 3); *before* it knows to enable "merit order on".

1. Initial graph setup.
2. Set user values with inputs.
3. Finish graph setup.
4. Calculate GQueries.

Since we can't guarantee the order-of-execution of inputs, the solution will be to remove the input which sets the merit order on, and convert it to an attribute of the Scenario model, like the `use_fce` attribute which already exists. If we do that, the graph will know whether to enable the merit order much sooner in the process.

**Comment by antw** [comment]
> The profitability was not being calculated because of a conflict between FCE values and the merit order plugin.

To clarify a bit further: setting FCE values, and using the merit order, are not *intended* to be mutually exclusive. This is an ETEngine bug. A bit of background:

The ETEngine calculation process goes a bit like this:

1. Initial graph setup.
2. Set user values with inputs.
3. Finish graph setup.
4. Calculate GQueries.

The graph has [a range of plugins](https://github.com/quintel/etengine/tree/master/app/models/qernel/plugins) which may be used to add custom behaviour to a scenario; one of these plugins is the Merit Order, another is Fuel Chain Emissions. The graph typically determines which plugins to use during step 3, *after* inputs have been set.

In fact, the Merit Order is split into two separate plugins: one which is best summarised as "[merit order on](https://github.com/quintel/etengine/blob/master/app/models/qernel/plugins/merit_order.rb)", and another which is "[merit order off](https://github.com/quintel/etengine/blob/master/app/models/qernel/plugins/simple_merit_order.rb)". "Merit order off" is used to calculate loss-of-load and the demand curve – features provided by the Merit gem – without the performance penalty of an unnecessary full merit order calculation.

[An input](https://github.com/quintel/etsource/blob/master/inputs/misc/settings_enable_merit_order.ad), set during step 2, sets the `use_merit_order_demands` attribute to be true. We get to step 3, the graph sees that the attribute has been set to true, and it loads the "merit order on" plugin. If the value is false, or not set at all, it loads "merit order off".

Unfortunately, we have FCE-related inputs which call the [`UPDATE_FCE` GQL function](https://github.com/quintel/etengine/blob/master/app/models/gql/runtime/functions/update.rb#L317); it accesses the FCE plugin in order to set the values provided by the user. This causes the graph to set up its plugins prematurely (during step 2 instead of step 3); *before* it knows to enable "merit order on".

Since we can't guarantee the order-of-execution of inputs, this is effectively what happens:

1. Initial graph setup.
2. Set user values with inputs.
  1. Run FCE inputs.
    1. Set up plugins.
  2. Run other inputs (including merit order=on).
3. Finish graph setup.
4. Calculate GQueries.

The solution will be to remove the input which sets the merit order on, and convert it to an attribute on the Scenario model, like the `use_fce` attribute which already exists. If we do that, the graph will know whether to enable the merit order much sooner in the process.

**Comment by ChaelKruip** [comment]
Thanks @antw for the clear explanation!

**Comment by ChaelKruip** [comment]
Closing as this has been fixed.
