### ISSUE TITLE
Considerations before we add efficiency sliders to the ETM for electricity producers

### ISSUE THREAD

**Issue by ChaelKruip** [quintel/etmodel#1893]
# Background

Users have been requesting the option to change efficiencies for electricity producing technologies, most notably solar PV panels. In https://github.com/quintel/etmodel/issues/1870, a list of technologies that may be interesting to have such a slider for is given.
# Simplifying circumstances

Many power plants in the ETM are actually based on the same type of process and their efficiencies can therefore be updated by a single slider. 
# Complicating circumstances
- Volatiles (wind, solar, hydro) are not demand driven. Changing their efficiencies naively will result in less 'wind', 'sun' and 'hydro' used. This is not what a typical user would expect, which is that an improvement in efficiency results in a higher output (capacity). In other words, changing the efficiency of, for example, a solar panel, the same surface area of solar PV leads to more electricity production (capacity).
- Changing the efficiency of a power plant makes it cheaper (if you keep the output fixed). With less steel, concrete and fuel, you can make the same amount of electricity. This means that the cost sliders that we have for the same plants will become (partially) redundant. Making the plant more efficient will reduce its investment costs, fuel costs and O&M costs. However, efficiency sliders will also reduce  CO2 emissions, while the sliders for cost just update one of these each. So, we have an entanglement of sliders which might confuse some users. 
# Interface

Because of the last point, the cost section of the ETM might be the most logical place for the efficiency sliders.
# Comments

Because of the impact on the usability and transparency of the ETM, I will invite you to have a meeting about this soon.

**Comment by ChaelKruip** [comment]
Including @dennisschoenmakers @AlexanderWirtz @jorisberkhout

**Comment by AlexanderWirtz** [comment]
We thought it is best to offer users the following:

1. Fuel costs changes
2. Efficiency changes per technology type
3. Investment and O&M costs changes

@2: 

1. Updating the efficiency of solar PV will lead to increased solar power production for the same are of installed PV
2. Updating the efficiency of pulverized coal / or USC coal plants will also update the E and H efficiencies of related CHP plants and co-firing plants. Their installed capacity will remain the same and fuel use and CO2 emissions will drop. Of course, only the `merit` calculation can determine exactly wat will happen, since the marginal costs for these plant types will change.
