### ISSUE TITLE
Calculated Changes and Symbols

### ISSUE THREAD

**Issue by RobTerwel** [quintel/etmodel#1908]
The change in quantities on the bottom of the screen (`Energy use`, `Costs` etc.) is also visualized by downward or upward arrows. However, if such a quantity is not affected, what happens? In the following image, there is a hyphen (-) for `Energy imports` but no sign for `Bio-footprint`. Is there a difference, or do both indicate there are no changes?

![screen shot 2015-09-28 at 11 40 54](https://cloud.githubusercontent.com/assets/14106387/10134139/fcb5ac8e-65e3-11e5-8cff-0bf85d7322da.png)

**Comment by ChaelKruip** [comment]
Re-assigning to @antw because I don't know what exactly the difference in behaviour between these items is and if it is intentional.

**Comment by antw** [comment]
This happens because the bio-footprint value doesn't change *at all*; the energy imports and renewability values change, but by less than 1e<sup>-5</sup>. When that happens, you get the "—" icon. The UI framework we use (Backbone) simply won't trigger a `change` event if the new value is identical to the old one.

How would people feel about removing the neutral "—" icon, and only showing ↑ and ↓?

*(including @dennisschoenmakers)*

**Comment by ChaelKruip** [comment]
> How would people feel about removing the neutral "—" icon

Fine by me!

**Comment by RobTerwel** [comment]
Yes, seems like a good suggestion to me!

**Comment by jorisberkhout** [comment]
Sounds good to me!
