### ISSUE TITLE
'Dead' sliders for efficiency improvement in Demand - Other

### ISSUE THREAD

**Issue by RobTerwel** [quintel/etmodel#1911]
In `Demand - Other`, there are sliders for efficiency improvement of `electricity`, `heat`and `non-energetic`. The current quantities come from the energy balance; however, changing the sliders for efficiency improvement of `electricity` and `heat` does not change the dashboard nor the chart associated with them.   

![screen shot 2015-09-29 at 09 26 56](https://cloud.githubusercontent.com/assets/14106387/10157666/4a6330b6-668c-11e5-804b-9e9d44aa9365.png)

@ChaelKruip , what shall we do with these sliders?

Moreover, the `Final energy demand in other sector` chart mentions many (more) possible energy carriers, but for the starting scenario only contains one: `oil and derivates`. That is the one that changes when the user changes the `non energetic` slider.

Perhaps we can clear up some of the chart and make it more in line with the sliders on the left, e.g. by using the same terms (not `oil and derivates` ánd `non-energetic`)? What do you think, @ChaelKruip ?

**update: these sliders should not be removed as they are needed for other countries (e.g. EU-27).**

**Comment by ChaelKruip** [comment]
> @ChaelKruip , what shall we do with these sliders?

This section of the model for NL is very boring because in the statistics for our country there is almost no 'uncharted/miscellaneous/other' energy reported. For other countries the other sector is more significant.

> Perhaps we can clear up some of the chart and make it more in line with the sliders on the left, e.g. by using the same terms (not oil and derivates ánd non-energetic)? What do you think, @ChaelKruip ?

I see where you're coming from but I advice against it for the following reason: we know very little about the 'other' sector, electricity, heat and non-energetic use is about the best we can do distinguishing between energy uses. On the other hand, I want to keep final demand charts consistent so all possible carriers are shown.

Closing.
