### ISSUE TITLE
Renewable el. chart from the dashboard does not show the penetration of different RES

### ISSUE THREAD

**Issue by georgiasavvidou** [quintel/etmodel#1919]
The renewable el. chart from the dashboard does not show the penetration of different RES in the renewable electricity. The user might be interested to see the mix of renewable sources in the renewable electricity. 
![image](https://cloud.githubusercontent.com/assets/12493788/10161687/125e355c-66a6-11e5-9ae7-f59a519d23a8.png)

The chart can be similar to the renewables share chart which differentiates between energy sources (see screenshot)
![image](https://cloud.githubusercontent.com/assets/12493788/10163621/7d43b32a-66b4-11e5-9d30-2ad2c2f764e8.png)

**Comment by ChaelKruip** [comment]
Nice suggestion @georgiasavvidou! I will pick this up in the next deploy.

**Comment by ChaelKruip** [comment]
I have made a preliminary attempt at creating queries for this chart. The following complication made me decide that the work involved is disproportionate to the benefits of having this chart at the moment:

Power plants can have a mix of inputs, some of them fossil, others sustainable, others even partially fossil and partially sustainable. In order to determine how much electricity is produced from `wood_pellets`, for example, not only do we need to identify which converters have `wood_pellets` as an input, but also how much of their electricity is produced from these `wood_pellets`. The resulting queries are going to be quite complex and will likely need much manual work.

**Comment by ChaelKruip** [comment]
Putting 'on hold'

**Comment by ChaelKruip** [comment]
Removing milestone "Deploy Feb 2016".
