### ISSUE TITLE
In some cases, scaling a scenario gives 0 inhabitants per residence

### ISSUE THREAD

**Issue by RobTerwel** [quintel/etmodel#1934]
To reproduce this, do the following:

- open a new scenario (e.g. Netherlands 2050)
- set `residences built before 1992` to 4.0 (million)
- scale to 10000 residences 
- go to `population` and view the chart

You should see this:

![screen shot 2015-10-01 at 12 00 19](https://cloud.githubusercontent.com/assets/14106387/10218207/550805f0-6835-11e5-8527-db52d333d110.png)

And `number of inhabitants per residence` is 0.0, even though it's clear from the values above it that it cannot be. This did not occur when I did the same but scaled to 250 000 residences instead.

Moreover, I noted that `number of residences` in the 2050 scenario is suspiciously high. Maybe the problem lies in the input for that entry.

Re-assign at will.

**Comment by dennisschoenmakers** [comment]
Good catch @RobTerwel !

**Comment by jorisberkhout** [comment]
After discussing with @grdw, assigning him.

**Comment by grdw** [comment]
Allright, this is a rounding "problem". 

`29625.7 / 1654327.8` returns `0.017907998644524983` which is `0.0`. Maybe we could round down to two digits? Or add the full number in the title of the table-cell to clearify that it's not actually `0.0`.

But I have no idea where the `1654327.8` comes from and how to change it.

**Comment by grdw** [comment]
![screen shot 2016-01-15 at 3 29 36 pm](https://cloud.githubusercontent.com/assets/2676542/12355421/cdfd338a-bb9c-11e5-8d15-b81b3ee578a2.png)

After dragging this slider the residences jumps to the correct amount.

**Comment by grdw** [comment]
![screen shot 2016-01-15 at 3 59 37 pm](https://cloud.githubusercontent.com/assets/2676542/12356083/003cfd9a-bba1-11e5-988e-72e50bccfcbd.png)

After some more digging it has to be a problem at Et-engine. I'll see if I can reproduce it with et-engine locally.

**Comment by grdw** [comment]
Since the numbers are directly coming from `etsource` there has to be a gquery that's being called that gives me the [households_number_of_residences](https://github.com/quintel/etsource/gqueries/output_elements/output_series/table_145_population_residences_overview/households_number_of_residences.gql). 

Returns:1654327.8001886636

However I think the problem is before that step - in the scaling itself. My guess would be that in the scaling step the numbers have to  be updated (ie. divided by x).

**Comment by antw** [comment]
The "area" attributes [are scaled here](https://github.com/quintel/etengine/blob/d67fef8bfaa001abde8ad51facf71233e00eb307/app/models/scenario_scaling.rb#L149-L151). I think if that were wrong then *all* of the scaled values would be wrong, which isn't the case. Also, the "present" (2012) value looks to be correct.

It's odd that `number_of_residences` is the attribute affected, because thats the same attribute used to scale the scenario.

**Comment by grdw** [comment]
> It's odd that number_of_residences is the attribute affected, because thats the same attribute used to scale the scenario.

Couldn't it be that it's a caching thing than? It looks and feels like a caching problem - however I can't point my finger to it in the code.
