### ISSUE TITLE
Scaling a scenario results in incorrect rounding of inhabitants per residence

### ISSUE THREAD

**Issue by ChaelKruip** [quintel/etmodel#1949]
![etmoses_schalings_waarde_-_chael_kruip_quintel_com_-_quintel_com_mail](https://cloud.githubusercontent.com/assets/1303760/10995132/f9f9e48c-847a-11e5-8225-d6131e4b97ab.png)

**Comment by antw** [comment]
Any chance you have a scenario ID? Or remember the steps you took to get to this result?

**Comment by ChaelKruip** [comment]
> Any chance you have a scenario ID? Or remember the steps you took to get to this result?

Unfortunately this is done by external users and I only got this screenshot to work with...

**Comment by antw** [comment]
Okay thanks; will investigate soon. The population slider being 0 is strange: even with number of residences set to 1 (the minimum), the slider shouldn't go below 1.14.

I did find a similar bug however:

1. Set number of old residences to 0
2. Set number of new residences to 0
3. Scale to 1 residence (number probably doesn't matter)

The result is that sliders don't load (due to a "non-numeric GQL result" error) and:

![screen shot 2015-11-06 at 13 02 42](https://cloud.githubusercontent.com/assets/4383/10997676/d2c6632a-8486-11e5-9691-1fbafcac7843.png)

**Comment by jorisberkhout** [comment]
After discussing with @grdw, assigning him.
