### ISSUE TITLE
An 'ordering' of storage options needs to added to the front-end

### ISSUE THREAD

**Issue by ChaelKruip** [quintel/etmodel#1965]
Part of https://github.com/quintel/etmodel/issues/1868

The user should be able to drag the following options for dealing with excess electricity into an order:

- [ ] P2P in batteries
- [ ] P2P in EV
- [ ] P2G
- [ ] P2H
- [ ] Export

Curtailment will be the last option which is the last resort and cannot be dragged by the user.

**Comment by grdw** [comment]
> the following options

Are these options somewhere present in ETE? Or are these static?

**Comment by jorisberkhout** [comment]
> Are these options somewhere present in ETE? Or are these static?

So far, they are static.

**Comment by grdw** [comment]
Update: I can drag them in an order.

- [ ] Styling
- [ ] Store order of elements

How would I store the order? And what has to happen with the order?

**Comment by jorisberkhout** [comment]
> How would I store the order? And what has to happen with the order?

@antw, could you weigh in here?

**Comment by grdw** [comment]
Quick question is "Curtailment will be the last option" the same as "Export" or is "Curtailment" an extra option?

**Comment by grdw** [comment]
![screen shot 2016-01-20 at 3 07 25 pm](https://cloud.githubusercontent.com/assets/2676542/12451073/894fe996-bf87-11e5-8a36-c5a23beb3d7e.png)

Small preview

**Comment by jorisberkhout** [comment]
I like the preview!

> Quick question: Is "Curtailment (will be the last option)" the same as "Export" or is "Curtailment" an extra option?

"Curtailment" is an extra option, but is always the last resort. Could you perhaps make it the last option in the list, grey it out and make it not-selectable?

**Comment by antw** [comment]
> How would I store the order?

An new table in ETEngine would be my preference (like `scenario_scalings` in ETEngine, or `selected_strategy` in Moses). I think a single column containing a serialized array of technology keys (P2P, P2G, etc) would do the job. There are *better* designs from the perspective of database normalisation, but I think a serialized array is good enough here.

I suggest that curtailment be shown in the front end, but not included as an option in the new table (I'll configure it manually to be the last option in the Merit order).

> Quick question: Is "Curtailment (will be the last option)" the same as "Export" or is "Curtailment" an extra option?

I believe they are separate concepts. Export is excess energy sent to another country, curtailment is deciding not to use energy (e.g. "I'll turn off my heating and add another layer of clothing").

**Comment by ChaelKruip** [comment]
> curtailment is deciding not to use energy (e.g. "I'll turn off my heating and add another layer of clothing")

One small correction: in this context, "curtailment" is throwing away the energy at the production site (stopping the wind turbine for instance).

**Comment by jorisberkhout** [comment]
I like what we've got so far. As discussed with John, we could make it a bit more clear to the user that he can / needs to drag the options in the desired order. Could you add an icon to each of the rows, @grdw ?

Also, could you make the options stand out a little more by making the box around them thicker and/or darker?

I prefer something like this.

<img width="445" alt="screen shot 2016-02-03 at 12 03 06" src="https://cloud.githubusercontent.com/assets/4669028/12780651/64bcc08e-ca6f-11e5-802e-15ee3f1acec1.png">

BTW, I found these two icons, in case that is useful.

![drag_reorder](https://cloud.githubusercontent.com/assets/4669028/12780571/f03399a4-ca6e-11e5-88cc-2b8fcee7d711.png)
![images](https://cloud.githubusercontent.com/assets/4669028/12780576/f48a6e74-ca6e-11e5-8a14-06ae6c12996f.png)

Notifying our style-guru, @dennisschoenmakers .

**Comment by grdw** [comment]
> BTW, I found these two icons, in case that is useful.

Usually it's just the three stripes (at least for mobile devices).

**Comment by antw** [comment]
> Usually it's just the three stripes (without the arrows)

:+1:

**Comment by dennisschoenmakers** [comment]
### iOS style:

![image](https://cloud.githubusercontent.com/assets/104830/12785115/24663120-ca8b-11e5-8d1a-62889e240a1c.png)

### Materialize-ish

![image](https://cloud.githubusercontent.com/assets/104830/12785240/d165d902-ca8b-11e5-9786-537b72dcf41e.png)

**Comment by antw** [comment]
Materialize-ish is nice, especially with the icons. I wonder if we could find suitable icons for each of the flexible technologies?

**Comment by dennisschoenmakers** [comment]
Don't we already have a bunch of icons for the sidebar items?

**Comment by jorisberkhout** [comment]
As demonstrated, the new functionality does not always work on Chrome (`Version 48.0.2564.97 (64-bit)`).

**Comment by grdw** [comment]
![screen shot 2016-02-05 at 10 02 57 am](https://cloud.githubusercontent.com/assets/2676542/12841915/a8ae7dce-cbef-11e5-94cf-630f5751d976.png)

Minor preview. 

Now I still see an ongoing discussion about the icons. But I'm guessing it's also about the 'dragging' itself. That it feels like you're pushing the blocks away instead of the 'ghostly' way? (I'm hoping I make myself clear here).

**Comment by dennisschoenmakers** [comment]
In all: It still doesn't look like the items are **draggable** at first sight, and it is unclear to me (and the user IMO) what he/she can do at this page:

How we can improve this IMO:
* The 'drag' icons can be a bit wider and less black: it can be subtler: compare [the icons](http://cl.ly/3T001i2P1s0Z) by @antw 
* You might want to either put numbers in front of the options to make it more clear that there is an order to it, or move the icon to the left of the text (also see example below)
* You need a bit of margin between the boxes, because now it doesn't convey to the eye that they are individual items, it now looks like a table with (thicker) lines in between
* (besides): give the boxes more padding, especially horizontally: on the left and right it is to close to the borders: that always makes a design feel cramped

For example, in [this jQuery example](https://jqueryui.com/sortable/) the 'draggability' it is more obvious.

**Comment by grdw** [comment]
![screen shot 2016-02-05 at 10 31 16 am](https://cloud.githubusercontent.com/assets/2676542/12842521/a1d4e0de-cbf3-11e5-8f5d-1a6144179b2b.png)

Preview 2.0

> The 'drag' icons can be a bit wider and less black: it can be subtler: compare the icons by @antw

Making them 'wider' is going to be a bit of a hassle since we're using font-awesome. I can make them larger in both height and width not width only (unless there's maybe a css property, which I don't know of, which can take care of that). 

> You might want to either put numbers in front of the options to make it more clear that there is an order to it, or move the icon to the left of the text (also see example below)

I might. But if I could take the screenshot with the mouse-pointer in it, it would already become a lot clearer (I used the `grab` and `grabbing` icons - that already works in Firefox unfortunately there's some special `-webkit-` prefix needed for Chrome which I added).

> You need a bit of margin between the boxes, because now it doesn't convey to the eye that they are individual items, it now looks like a table with (thicker) lines in between

In [this first example](https://github.com/quintel/etmodel/issues/1965#issuecomment-179268535) that's also not the case. In the second example I see a clever use of borders (making the outer box a bit more fat to make it not look like table-ish). Might want to try that? Call me lazy, but dragging that extra margin will burn more calories than necessary.

> (besides): give the boxes more padding, especially horizontally: on the left and right it is to close to the borders: that always makes a design feel cramped

I agree.

**Comment by dennisschoenmakers** [comment]
> In this first example that's also not the case. In the second example I see a clever use of borders (making the outer box a bit more fat to make it not look table-ish). Might want to try that? Call me lazy, but dragging that extra margin will burn more calories than necessary.

LOL good point about calories. How about loosing the ugly double border then? I kinda like the Materialize design here:

![image](https://cloud.githubusercontent.com/assets/104830/12843004/d01f963e-cbf6-11e5-8d47-69da7c0cb3f9.png)

And also: do we need to 'convey' to the eye of the user that Curtailment is ALWAYS the last option, and thus cannot be moved? (i.o.w.: 'explain' why it is immovable?)

**Comment by grdw** [comment]
> I kinda like the Materialize design here:

Is there also  an 'outer glow' or is that the background-color of the screenshot? 

I did remove the 'double-border':

![screen shot 2016-02-05 at 11 01 27 am](https://cloud.githubusercontent.com/assets/2676542/12843178/efee26e6-cbf7-11e5-8114-278d75db5855.png)

**Comment by grdw** [comment]
I did manage to make the icons wider :dancers: 

![screen shot 2016-02-05 at 11 14 41 am](https://cloud.githubusercontent.com/assets/2676542/12843445/b0c15b80-cbf9-11e5-9d4b-c089d11e96c0.png)

**Comment by antw** [comment]
I think that's looking a lot better. :+1:

OCD nitpicking:

![screen-shot-2016-02-05-at-10 23 36](https://cloud.githubusercontent.com/assets/4383/12843760/58248e08-cbf3-11e5-94e3-cff5142842b9.png)

**Comment by grdw** [comment]
> And also: do we need to 'convey' to the eye of the user that Curtailment is ALWAYS the last option, and thus cannot be moved? (i.o.w.: 'explain' why it is immovable?)

> Curtailment will be the last option which is the last resort and cannot be dragged by the user.

Well yes! :smile: but I think @ChaelKruip can explain better why that is.

**Comment by dennisschoenmakers** [comment]
> Well yes! :smile: but I think @ChaelKruip can explain better why that is.

Ah I see, you want to provide the user with a small, digital ChaelKruip?

![image](https://cloud.githubusercontent.com/assets/104830/12845967/fb0f2f68-cc09-11e5-8bce-339d714cb4ea.png)

**Comment by grdw** [comment]
> Ah I see, you want to provide the user with a small, digital ChaelKruip?

Yes!

![chael-clippy](https://cloud.githubusercontent.com/assets/2676542/12846157/26f9443c-cc0b-11e5-9c53-441df397bed2.png)

**Comment by grdw** [comment]
On a more serious note. What I think you (@dennisschoenmakers) are trying to say is that there needs to be some text explaining why `curtailment` is greyed-out?

**Comment by dennisschoenmakers** [comment]
Well, not too much text please, for instance:

![image](https://cloud.githubusercontent.com/assets/104830/12846750/93b48232-cc0e-11e5-81e0-b9d308b21f25.png)

Or any better ideas?

**Comment by jorisberkhout** [comment]
It is already explained in the text above the drag-and-drop menu (might need some rewording). I would say that that is enough for now.

**Comment by grdw** [comment]
> It is already explained in the text above the drag-and-drop menu (might need some rewording). I would say that that is enough for now.

I agree for the most part. I think at most there could be an extra-information popover.
