### ISSUE TITLE
How do we show the user the amount of hydrogen which is mixed into the gas network?

### ISSUE THREAD

**Issue by ChaelKruip** [quintel/etmodel#1966]
Currently, the front-end show the fraction of green-gas in the gas-network:
![energietransitiemodel_-_je_eigen_onafhankelijke__volledige_en_op_feiten_gebaseerde_energiescenario_](https://cloud.githubusercontent.com/assets/1303760/11953268/2350a6ca-a89f-11e5-809d-f6f480882f81.png)

If P2G produces hydrogen, and we mix this into the national gas network, the resulting mix should be communicated to the user.

**Comment by ChaelKruip** [comment]
After discussion with @jorisberkhout I think there are various options here but none of them without its drawback:

## OPTION 1: Third slider
Adding a third slider (H2) to the slider-group shown above. This slider would not be an input, however, but rather an output of the P2G calculation. This would introduce back into the ETM the old 'grayed-out' sliders that are magically updated by the model itself. Moreover, the green-gas and natural gas sliders would be updated accordingly (to balance the group). So, a scenario cannot have a fixed percentage of green-gas in the network anymore.

## OPTION 2: Use H2 in industry exclusively
Produced H2 gas would be subtracted from the gas-use in industry. If more is produced than demanded, export is used as an overflow.
This keeps the % of green-gas in the gas network unchanged and requires no extra sliders. One dis-advantage is consistency with ETMoses: When scaling a scenario, the industry is taken out by default while using P2G in ETMoses explicitly mixes H2 into the local gas network. This seems ugly to me.

## OPTION 3: Convert H2 into green-gas
This option assumes methanisation and adds the produced gas to the green-gas reservoir. This keeps the sliders above working as expected. The disadvantage of this approach is that people need to actively use (increase the % of green-gas in the gas-network) the H2 which is produced by P2G, or it will be exported.

@AlexanderWirtz @jorisberkhout @dennisschoenmakers @RobTerwel Please give your opinion (if you have any) on the above options. Also, if you have a better idea, don;t hold back either :smile:

**Comment by AlexanderWirtz** [comment]
To be blunt: 

I don't like **OPTION 1**. It creates the potential to add a lot of H2 to the gas network. This will rightly cause a bit of criticism: as it is far from certain that this would work and is currently not legally allowed. Also, the greyed-out slider is ugly IMO. Just a percentage indicator is less ugly, but still suffers from the problem of unlimited H2 feed-in into the gas network.
It sufers from a more fundamental problem that it makes no sense to feed H2 gas into the gas network, when the very future of gas networks is being debated and we can use the H2 better in industry. H2 in households is something I would not be very comfortable with.

I like **OPTION 2**. ETMoses may do something different, but the very implementation of P2G in ETMoses is different in the first place. It is LOCAL and small scale, whereas in the ETM we use it as large-scale stabilization for wind surpluses, i.e. large installations that would never live anywhere close to houses etc. It is highly debatable that we will ever want to make H2 locally, where only low-temperature heat demand and H2-cars are obvious users, whereas we have a HUGE demand for high-temperature heat in Industry that we thus far can only make by burning stuff and could also use H2 non-energetically. IMO the ugliness arises from making the wrong choices for ETMoses (understandable since it contains no Industry), rather than that option 2 is in some way 'wrong'.   

**OPTION 3** is a silly fantasy by the gas industry. There is no CO2 available for this shift reaction (ecept maybe close to blast furnaces). Even if there were. Makes CH4 by using captured CO2 and then burning is a rather moronic idea that only makes sense if you work at a gas company, at least if you believe in climate change. If you have pure CO2 available (probably from costly capture or energetically intense iron-ore reduction) then it would be far more logical to use it to make products from syn-gas (H2 + CO) thereby locking the CO2 in place.  

There are other options. @dennisschoenmakers mentioned:

# OPTION 4: Use a slider to set a cap for how much H2 to mix into the gas network
This does not set how much would be fed in, but merely caps the amount. The rest would have to be exported, I think, as feeding it into an `industry_gas_network` à la **OPTION 3** would create a circular calculation.

**Comment by dennisschoenmakers** [comment]
To elaborate a bit on the fourth option: All though it is unfeasable to replace all CH4 with H2 for the gas network, it is possible to mix a small fraction, and since this option is discussed widely, I think we should be able to allow it in the ETM, even though there might be objections or better uses.

**Comment by AlexanderWirtz** [comment]
> To elaborate a bit on the fourth option: All though it is unfeasable to replace all CH4 with H2 for the gas network, it is possible to mix a small fraction, and since this option is discussed widely, I think we should be able to allow it in the ETM, even though there might be objections or better uses.

I agree

**Comment by ChaelKruip** [comment]
> it is possible to mix a small fraction, and since this option is discussed widely, I think we should be able to allow it in the ETM

Agree! But we still have the issue of how to 'balance' the slider group shown [above](https://github.com/quintel/etmodel/issues/1966#issue-123455226). I think it is bad practice in general to to allow sliders to be moved by the model rather than the user.

A way around this is to rename that slider groups to 'composition of non-H2 gas in the network'. This does not deserve any awards for elegance either but at least we don't need spooky-slider-movements.

**Comment by dennisschoenmakers** [comment]
> I think it is bad practice in general to to allow sliders to be moved by the model rather than the user. at [...] at least we don't need spooky-slider-movements.

To be clear: not something I had a mind (either) and I agree 100% that we should not have this 'magic' in the ETM.

**Comment by jorisberkhout** [comment]
> I think it is bad practice in general to to allow sliders to be moved by the model rather than the user. at [...] at least we don't need spooky-slider-movements.

I full agree as well.

> A way around this is to rename that slider groups to 'composition of non-H2 gas in the network'. This does not deserve any awards for elegance either but at least we don't need spooky-slider-movements.

I don't want to be negative Nancy, but this solution feels counter-intuitive as well. Although the slider settings remain the same, the absolute amounts of both green gas and natural gas will change when you feed more or less hydrogen into the gas network. I would find it most intuitive that feeding more hydrogen into the gas network (capped by a slider setting, I like that idea, @dennisschoenmakers ), the less natural gas you have to produce / import, leaving the absolute amount of green gas untouched.

What about the following solution? Why don't we remove the 'Natural gas' slider altogether and make it clear to the user that any gas in the gas network that is not green gas or hydrogen will be natural gas? That way would don't have to update siders settings based on results of the model.

So the user would set the following:

- the demand for 'network gas' (through all demand sliders in the network)
- the percentage of green gas in the gas network
- the cap on the percentage of hydrogen that can be fed into the gas network

Any remaining gas demand will automatically be fulfilled by feeding natural gas into the gas network. As we do now, the user can also set where this natural gas will come from (natural gas or regasified LNG as well as the countries of origin of this gas). 

The 'Green gas in gas network' chart will show the user (in absolute terms) how much green gas, hydrogen and natural gas are fed into the gas network. Any hydrogen that cannot be fed into the gas network will be exported.

**Comment by jorisberkhout** [comment]
I realised that there is one minor issue with the above solution. If the amount of green gas and hydrogen add up to more than 100% of the gas demand, we would have to cut one of them. I would say that in that case we cut the amount of hydrogen fed into the gas network and export the excess hydrogen.

**Comment by AlexanderWirtz** [comment]
> I realised that there is one minor issue with the above solution. If the amount of green gas and hydrogen add up to more than 100% of the gas demand, we would have to cut one of them. I would say that in that case we cut the amount of hydrogen fed into the gas network and export the excess hydrogen.

Agreed. That would be consistent with the fact that you do not specify how much hydrogen is to be produced, but only a cap.

**Comment by ChaelKruip** [comment]
I like the solution proposed by @jorisberkhout 

One question though:

> * the percentage of green gas in the gas network

Do you adjust the **absolute** amount of green-gas when hydrogen input changes due to P2G to keep the % of green-gas constant? Otherwise the slider is moved by the model again...

**Comment by jorisberkhout** [comment]
> Do you adjust the absolute amount of green-gas when hydrogen input changes due to P2G to keep the % of green-gas constant? Otherwise the slider is moved by the model again...

No, I don't think that is necessary. The user sets the percentage of green gas in the gas network which, combined with the demand for gas from the gas network, sets the absolute amount of green gas in the gas network. The percentage of green gas will stay the same (unless the user changes it), but the absolute amount will change when the user changes the demand of gas from the gas network.

If more hydrogen is fed into the gas network, this only reduces the absolute amount of natural gas in the gas network and therefore also the percentage of natural gas in the gas network. For this reason I suggested hiding the natural gas percentage slider.

Does this answer your question, @ChaelKruip ?

**Comment by ChaelKruip** [comment]
Yes! You are 100% right! I agree with your suggestion :+1:

**Comment by AlexanderWirtz** [comment]
:+1:

**Comment by jorisberkhout** [comment]
As our original approach proved a lot harder than expected, we decided to go for an alternative solution. The hydrogen that is produced by the P2G plants will be used in the transport sector. This implementation will follow the following rules:

- the hydrogen from the P2G plants can only be used by hydrogen cars
- if hydrogen cars demand more hydrogen than produced by P2G, the remainder will be supplied by the hydrogen producing technologies that @RobTerwel implemented, using the shares set by users
- if more hydrogen is produced by P2G than needed by hydrogen cars, the excess will be exported

Assigning @RobTerwel as he is currently implementing this.
