### ISSUE TITLE
JS: Why the separation between App.settings and globals.settings?

### ISSUE THREAD

**Issue by grdw** [quintel/etmodel#1988]
Is this intentional and which one is prefered?

**Comment by antw** [comment]
Use `App.settings` in the JS code. `globals` [is set here](https://github.com/quintel/etmodel/blob/6e95fc94fff8e29a9202a18d48fe8dec35c428e6/app/views/layouts/etm/_javascript_globals.html.erb); I believe it is used to communicate the application settings from the Rails app to the JS app.

`globals` is used in some placed in the JS, but I'm guessing that's because `App.settings` [haven't been set yet](https://github.com/quintel/etmodel/blob/6e95fc94fff8e29a9202a18d48fe8dec35c428e6/app/views/scenarios/play.html.haml#L17) at that point in the code execution.
