### ISSUE TITLE
Some numbers are incorrectly 'rounded'

### ISSUE THREAD

**Issue by ChaelKruip** [quintel/etmodel#1994]
In the investment table, very small numbers (e-16) are incorrectly rounded and represented as being much larger.

The [query for the delta of district heating](https://github.com/quintel/etsource/blob/master/gqueries/output_elements/output_series/table_142_investments/households_heat_network_connection_steam_hot_water_delta_in_investment_cost_table.gql) in the sandbox:

![energytransitionmodel](https://cloud.githubusercontent.com/assets/1303760/12577771/f061f0ea-c41c-11e5-8df9-217bb5dc8521.png)
and in the front-end:
![energy_transition_model_-_your_free__independent__comprehensive__fact-based_scenario_builder_](https://cloud.githubusercontent.com/assets/1303760/12577763/e837c160-c41c-11e5-8714-d6ce2c956713.png)

**Comment by grdw** [comment]
The actual value you would want to see would be 0 I'd guess?

**Comment by ChaelKruip** [comment]
> The actual value you would want to see would be 0 I'd guess?

Yes, if rounded to 4 numbers behind the comma, this would become 0.

**Comment by ChaelKruip** [comment]
@antw please take note. I'm worried that whatever is causing this might affect other charts/tables/outputs as well...

**Comment by grdw** [comment]
For which scenario does this problem arise? Because this is my result which is not saying much:
![screen shot 2016-01-26 at 11 20 50 am](https://cloud.githubusercontent.com/assets/2676542/12578079/e0d6952a-c41e-11e5-90bc-a3262df8b0ff.png)
Also, is this on `beta` or on `production`?

*On an accounting note:*
Why is this issue registered in etmodel, isn't this a problem for etengine (judging by the GQL sandbox)? Or is the result also visible in etmodel?

**Comment by antw** [comment]
I pushed a quick fix for the rounding of very small numbers. It could use some testing though.

> I'm worried that whatever is causing this might affect other charts/tables/outputs as well...

The bug was in `Metric.autoscale_value` which is not frequently used these days. That's not to say that there weren't other numbers which were incorrectly rounded, but it shouldn't be common.

> Why is this issue registered in etmodel, isn't this a problem for etengine (judging by the GQL sandbox)? Or is the result also visible in etmodel?

It was a rounding bug in the ETM; ETEngine was returning the correct number.

**Comment by grdw** [comment]
> It was a rounding bug in the ETM; ETEngine was returning the correct number.

I found out :+1: 

Thanks for solving though.

**Comment by jorisberkhout** [comment]
> It could use some testing though.

Assigning @ChaelKruip to do this.

**Comment by antw** [comment]
I pushed a better version, not much testing should be required now since I'm fairly confident it's correct. :laughing: 

For @grdw's sake: the issue was in [Metric.autoscale_unit](https://github.com/quintel/etmodel/blob/44d25f048326ec1f84d62ff71a63937e094037f8/app/assets/javascripts/lib/models/metric.coffee#L35-L120) which is intended to take values from ETEngine and format them for display in the front-end. For example, if you were to give it 0.003 and the unit 'MJ', it would return "3 kJ". This method was long and ugly, so about 18 months ago it was replaced with the [Quantity](https://github.com/quintel/etmodel/blob/44d25f048326ec1f84d62ff71a63937e094037f8/app/assets/javascripts/lib/models/quantity.coffee) class instead. The Quantity class is the standard in all new code, and was (luckily) unaffected by this rounding problem.
