### ISSUE TITLE
[Overview issue] Improving all tables in the ETM

### ISSUE THREAD

**Issue by jorisberkhout** [quintel/etmodel#2015]
Recently quite some issues have been raised about the formatting of tables in the front end of the ETM, in particular the custom HTML-tables (charts 54, 75, 98, 116, 140, 141, 142, 145 and 164). I suggest that we use this issue to discuss how the tables should be formatted and implement the decision for all tables. This will avoid having to fix each table individually.

As @grdw pointed out to me, the code generating these tables needs to be cleaned up as well.

The resulting decision from this issue should at least fix the following issues:
- https://github.com/quintel/etmodel/issues/2005
- https://github.com/quintel/etmodel/issues/1945
- https://github.com/quintel/etmodel/issues/1854

**Comment by grdw** [comment]
> custom HTML-tables (charts 54, 75, 98, 116, 140, 141, 142, 145 and 164)

This is starting to sound like a feature and not like something 'custom'. Considering that those tables all have the same or somewhat same layout (with gqueries). I'd guess that there will be one 'general' way those tables should be displayed (preferably exactly the same as the tables that belong to the charts). 

My preference for this (in order to keep it customizable by Joris/Chael/Possible-future-employee-who-never-has-seen-a-line-of-haml-and-is-scared) would be a yml file where there's a list of gqueries that should be performed in order to generate the table (don't know what thes structure would look like but after some thinking I might). Also in that yml file you'd be able to specify the precision etc.

**Comment by jorisberkhout** [comment]
Assigning @grdw (also for all linked issues). This has very low priority though.
