### ISSUE TITLE
Transport demands behaving erratically on Live 

### ISSUE THREAD

**Issue by AlexanderWirtz** [quintel/etmodel#2079]
I am trying to make some quick adjustments to the Groningen regional scenarios and am finding the impact of efficiency sliders in the transport section to be somewhat erratic.

For example: http://pro.et-model.com/scenarios/277819

In the transport section I wanted to change the setting of the `transport_useful_demand_ships_efficiency` slider. I noticed it had no impact. Only the first time it is set, the `Fuel for inland navigation` value changes. After that it is frozen.

For trains the efficiency slider can even result in negative demand when changing it from 1% to 0% annual efficiency improvement.

![image](https://cloud.githubusercontent.com/assets/308563/13635247/cfc45bac-e5fa-11e5-8fb5-e216e3cee8a4.png)

I suppose this issue might also be an etsource issue. I cannot fin anything wrong with the input statements, though. 

Notifying @dennisschoenmakers @jorisberkhout @RobTerwel

**Comment by RobTerwel** [comment]
I looked into this: everything is fine when it comes to the inputs and calculations, but the problem lies with the gqueries for <a href="https://github.com/quintel/etsource/tree/master/gqueries/output_elements/output_series/bezier_23_use_of_final_demand_in_transport"a>Bezier 23 Use of Final Demand in Transport<a/>. 

Efficiency sliders update the final demand of the individual vehicle technologies, but most these gqueries are defined as the *final demand of the useful demand* - which doesn't change with these sliders. In the case of the negative demand for trains, that's because we subtract the final demand of electricity for trains from the final demand of the useful demand for trains.

**Comment by AlexanderWirtz** [comment]
So @RobTerwel , has this mistake always existed?

**Comment by RobTerwel** [comment]
> So @RobTerwel , has this mistake always existed?

In short, yes, but because it was consistent with another mistake, it wasn't noticed earlier. In
https://github.com/quintel/etsource/pull/1025 we corrected and redefined some efficiency inputs; as a result, this mistake has become (more) noticeable.

**Comment by AlexanderWirtz** [comment]
> In short, yes, but because it was consistent with another mistake, it wasn't noticed earlier. In
quintel/etsource#1025 we corrected and redefined some efficiency inputs; as a result, this mistake has become (more) noticeable.

So the 'other' mistake will need correcting. Is there an issue for this?

**Comment by RobTerwel** [comment]
> So the 'other' mistake will need correcting. Is there an issue for this?

Sorry, my post might not have been fully clear - the 'first' issue has already been solved in https://github.com/quintel/etsource/pull/1025 . The second and 'other' mistake is the one we are discussing here - incorrect gqueries. Would you like me to create a separate issue for it?

**Comment by ChaelKruip** [comment]
@RobTerwel are you able to pick this up with low-priority as you are already sufficiently on top of this?

**Comment by RobTerwel** [comment]
> @RobTerwel are you able to pick this up with low-priority as you are already sufficiently on top of this?

Yes, sir!
