### ISSUE TITLE
Add chart showing the hourly electricity supply and demand

### ISSUE THREAD

**Issue by jorisberkhout** [quintel/etmodel#2081]
#### Introduction

In order to give the user of the ETM more insight into the merit order calculation, we want to add a chart showing the hourly electricity supply per technology and hourly demand curve. This would make it possible to study how the electricity production varies over the year and to determine when there is excess electricity. This chart should not show the profiles for the flexibility technologies, which will be subject of a separate chart (see #2082).

#### Example

Below is an example of what this chart should look like in a much simplified scenario with only solar  (green), coal (blue) and gas (purple) for one week of the year. Note that this chart is lacking the demand curve, which should be drawn as a red line.

![simplified2](https://cloud.githubusercontent.com/assets/4669028/13852066/dfca0a1c-ec60-11e5-966a-77dec8dd6782.png)

#### Proposed implementation

Visualising hourly load profiles for an entire year is quite a challenge, which fortunately has been solved in the context of ETMoses. We propose to re-use the implementation from ETMoses in the ETM. An additional complication in the ETM is that the merit order calculation returns profiles for about 50 different technologies. Below is my proposal on how display all this data in a comprehensible way:

- Only the profiles for those plants that participate in the merit order should be shown. In other words, if a certain type of plant is not installed in the user's scenario, it should not show up. This behaviour is identical to that of the merit order table.
- It should be possible to switch between a view for the entire year and a view for a specific week in that year, just like in ETMoses.
- It should be possible to toggle between a view where the profiles for the individual technologies are grouped into the main merit categories (`VolatileProducer`, `MustRunProducer`, `DisplatchableProducer`, the flexibility technologies will be shown in a different chart, see #2082).
- As a default, the chart should show the grouped profiles. This greatly reduces the number of profiles shown and, hopefully, the potential confusion for the user.
- For consistency, I would suggest to make the order in which the profiles are shown identical to the order in which the corresponding technologies show up in the merit order table (see table below). If the user uses the toggle switch to display all profiles, the order of these profiles within their respective category does not matter.

| Demand curve |
| --- |
| `DisplatchableProducer` |
| `MustRunProducer` |
| `VolatileProducer` |

- It goes without saying, that this chart should only be displayed when the merit order is switched on.
- All profiles and related data are available in ETEngine.

As discussed with @AlexanderWirtz , @dennisschoenmakers and @ChaelKruip . Notifying @antw . I would be happy to hear your feedback!

Assigning @grdw to implement this. Talk to @ChaelKruip and me about the planning.

**Comment by grdw** [comment]
In order to be fully complete this is going to take some time. Mainly because displaying > 5000 points in D3 is going to be slow. Either we're going to downsample it - like in ETMoses and make a week selector like in ETMoses (Still have a question if need it though or if we're just going to show a downsampled version of the whole year?). 

Another technical hurdle is that the ETMoses parts responsible for the drawing of the charts are written in plain Javascript (which is obviously faster) and ETModel is written in Coffeescript (which takes an initial compile step to convert it to somewhat poor Javascript (FYI: this is an opinion not a fact)). So there's some semantical 'this and that' which I need to consider. Nothing to heavy just want to state it right here.

I'm guessing and this is a ball park figure (which is usually the case with making time estimates) that this is about ~5-7 days work. We need 3 charts and 1 table. The charts take data from et-engine. It needs to be downsampled and we need some creative D3 magic (especially for #2082). If you want me to specify it in hours than please ask. I don't know if I'll be faster or slower than the initial estimate considering that there's already a lot of existing code in ETModel which I can reuse.

**Comment by AlexanderWirtz** [comment]
I say we re-use as many simplifications from ETMoses as we can:

- Yes, downsampled version of the whole year
- Yes, possibility to zoom in on parts of that year to get the actual numbers per hour, using week selector

**Comment by jorisberkhout** [comment]
> I say we re-use as many simplifications from ETMoses as we can:
> 
> Yes, down-sampled version of the whole year
> Yes, possibility to zoom in on parts of that year to get the actual numbers per hour, using week selector

I fully agree with @AlexanderWirtz . As also (somewhat poorly) specified in the original issue.

> - It should be possible to switch between a view for the entire year and a view for a specific week in that year, just like in ETMoses.

**Comment by antw** [comment]
> ETModel is written in Coffeescript

For what it's worth, I would be very much in favour of using plain JavaScript for all *new* ETM code.

> We propose to re-use the implementation from ETMoses in the ETM.

The ETM has helpful classes for handling chart data (like `ChartSerie`, `Gquery`, etc) as well as existing base charts which take care of creating legends and hover tooltips. It would be a pity to simply lift the chart out of Moses, and miss out on what the ETM already offers.

**Comment by grdw** [comment]
> It would be a pity to simply lift the chart out of Moses, and miss out on what the ETM already offers.

Yes, I'm not going to do `cp ../etmoses/app/assets/javascripts/... app/assets/javascripts/..` :sweat_smile:  I'm going to see which specific parts of code are 'reusable'.

**Comment by jorisberkhout** [comment]
Thanks for your input, @antw .

@grdw discussed that it is best to start with #2083 (add a chart displaying the price curve), which is relatively easy with respect to the data (just one curve). Once @grdw gets the week view and yearly view working for this one, he can focus on #2081 and #2082 .

**Comment by grdw** [comment]
![screen shot 2016-04-26 at 11 30 10](https://cloud.githubusercontent.com/assets/2676542/14813499/42efe48a-0ba2-11e6-8926-03f28c99de7f.png)

Some teasing. Don't mind the colors though .. they're ugly/duplicate and I know it. Also some labels are a bit lengthy.

**Comment by grdw** [comment]
![screen shot 2016-04-26 at 11 38 00](https://cloud.githubusercontent.com/assets/2676542/14813731/59c63b86-0ba3-11e6-8559-77ac92e2ae42.png)

In order to spike some discussion. The year view in my opinion doesn't add that much value in the current state. I'm not a scientist but I guess that you can't really get that much value from a chart in this year view except that you can come to the conclusion that it's really spikey. 

Also from a technical point of view: it's really slow in my browser. The queries and etmodel are actually pretty decent but the rendering is really tough.

My suggestion would be: downsample the curve (like in ETMoses to 365 points; i.e. 1 point per day, instead of showing all 8760 points) or don't show the year curve at all and start at Week 1 and let the user switch between weeks to discover what the merit does in a summer week, winter week etc.

Including; @antw @ChaelKruip @jorisberkhout @AlexanderWirtz

**Comment by antw** [comment]
> Also from a technical point of view: it's really slow in my browser. The queries from etengine and etmodel are actually pretty decent performance wise, but the rendering in the browser is really tough.

Definitely agree with downsampling the data for the annual view.

**Comment by jorisberkhout** [comment]
> Definitely agree with downsampling the data for the annual view.

So do I!

As discussed with @grdw , it would be very useful if we can show the daily average (in other words the average of the 24 datapoints per day) for all curves in the annual view. That way you can get a feel for seasonal influences on the load profiles. 

Displaying a daily average for the price curve (#2083) in the annual would be interesting for the same reasons.

**Comment by jorisberkhout** [comment]
Love it, @grdw ! Based on the screenshots and the live demo that you gave me, I see the following open action items:

- [ ] fix translations (see https://github.com/quintel/etmodel/issues/2100)
- [ ] display daily average in annual view
- [ ] add power-to-power (batteries and EV) to this chart (only when they are *supplying* electricity) to avoid confusion about the gap between production and demand
- [ ] change the display order to dispatchable, must-run, volatile (from bottom to top)
- [ ] fix the order in which the technologies are displayed within their respective group (dispatchable, must-run or volatile), @ChaelKruip proposed the following approach:
  - display the technology that has the least 'spiky' profile first
  - a measure for the spikiness of a profile is given by `(max - min) / (sum)` for all datapoints in the profile. Would this be feasible to implement, @grdw ? Come talk to me for more details.

**Comment by jorisberkhout** [comment]
As discussed with @AlexanderWirtz and @grdw , we will not implement the following point from the original issue:

> It should be possible to toggle between a view where the profiles for the individual technologies are grouped into the main merit categories (`VolatileProducer`, `MustRunProducer`, `DisplatchableProducer`)

The is quite a lot of work and we are not sure it this adds much information. @AlexanderWirtz proposed to first gather some user experiences and then decide if we want to implement this grouping.

**Comment by jorisberkhout** [comment]
I opened a separate issue for the aforementioned point of discussion (see https://github.com/quintel/etmodel/issues/2106).
