### ISSUE TITLE
Add a chart showing the hourly price data from merit

### ISSUE THREAD

**Issue by jorisberkhout** [quintel/etmodel#2083]
#### Introduction

As described in more detail in #2081, we would like to give the user of the ETM more insight into the results of the merit order calculation. The hourly price curve contains very valuable information and deserves a separate chart.

#### Proposed implementation

- The price curve is readily available in ETEngine.
- It should be possible to switch between a view for the entire year and a view for a specific week in that year, just like in ETMoses.
- All profiles and related data are available in ETEngine.

As discussed with @AlexanderWirtz , @dennisschoenmakers and @ChaelKruip . Notifying @antw . I would be happy to hear your feedback!

Assigning @grdw . Talk to @ChaelKruip and me about the planning.

**Comment by grdw** [comment]
@antw I have a few questions related to the price curves (and the participant load curves) from et-engine. I see that both are formatted as a CSV. The `ChartSerie` defaults to using gqueries to fetch the data from et-engine (?). 

1. Is there another way to grab that data from et-engine or is it just the CSV? 
2. If it's only to possible to fetch those CSV's should I expand on the: [https://github.com/quintel/etmodel/blob/master/app/assets/javascripts/lib/models/chart.coffee#L24-L27](chart serie switch) or should I create a whole new `OutputElementType`?

The CSV sometimes contains Infinity which is a bit of a problem (which I just saw).

**Comment by antw** [comment]
> Is there another way to grab that data from et-engine or is it just the CSV?

It's currently CSV only, but I would suggest expanding on those actions so that they can return CSV *or* JSON. JSON is probably easier to handle in the ETM.

With that in mind, the existing ChartSerie/ChartSeries classes may not be of much use to you since they expect you to be using Gqueries. Perhaps you might be able to get somewhere by creating a new set of classes which are compatible with ChartSerie/Gquery (e.g. implementing things like `color` and `label`) but not limited to just a `present` and `future` value?

**Comment by grdw** [comment]
> e.g. implementing things like color and label

I don't quiet understand where you are going at here (which label and color?). I'm guessing that these classes must do a call to `et-engine` to fetch the actual data (or is that supposed to be handled somehwere else in the backbone stack?). 

We could also make use of [d3 svg](https://github.com/mbostock/d3/wiki/CSV)?

**Comment by antw** [comment]
> I don't quiet understand where you are going at here (which label and color?). I'm guessing that these classes must do a call to et-engine to fetch the actual data (or is that supposed to be handled somehwere else in the backbone stack?).

I wrote a reply to this (included below) but I then realised we already have a chart class which can render time series data: [the existing time_curve chart](https://github.com/quintel/etmodel/blob/master/app/assets/javascripts/d3/time_curve.coffee). That might get you half-way there:

<img width="614" alt="screen shot 2016-04-21 at 11 19 32" src="https://cloud.githubusercontent.com/assets/4383/14705752/fc096f8e-07b2-11e6-95ec-7d15b77ed0fc.png">

It can render multiple series (e.g. coal and lignite on the same chart) and plots one value per year.

--

*Original reply:*

Chart series are part of ETModel (in the `output_element_series` database table) and define the colour, label, and position of each series in a chart. I guess this chart would have one series – price – while the chart from #2081 would have more (one for each technology type).

When a new chart is opened, the Backbone app requests information about the chart – the chart type, name, colours, units, etc – from the server. [Here's an example response](https://pro.energytransitionmodel.com/output_elements/42) which defines the "Heat and cold production" bar chart. This JSON is then converted into a `Chart` object and a collection of `ChartSeries`.

What I'm saying is, you can probably reuse a lot of that. However, the Gquery class is probably *not* reusable because it contains only two numeric values: a `present` and `future` value. For these charts, which have many values, you'll need something different.

**Comment by grdw** [comment]
Thanks for the explanation!

I didn't really look at the `output_element_series` table yet. :+1:  Thanks (explains why the series are empty). I guess I'll keep the gquery column blank for these new rows and figure out a way how to make it all connect to etengine. 

I was already looking at the `time_curve` chart :+1: to see what could be reused.

**Comment by antw** [comment]
The more I think about this, the more I think using Gqueries (as the current time_series charts do) might be the better option. We'd have to add a Gqueries which duplicate [the behaviour of the `MeritController`](https://github.com/quintel/etengine/blob/ca3f2d978e692f78a8bc4c2ce50e7bf9fac177d8/app/controllers/api/v3/merit_controller.rb#L11-L27).

My reason for thinking this is that the ETM is built around requesting data through Gqueries, so it can make life easier in a number of ways:

* The ETM can block parts of the UI while a request to ETEngine is in progress.

* It would (probably) be easier to adapt the time_curve chart.

* When a user moves a slider, the ETM knows which Gqueries it needs to request to refresh the charts and dashboard. It sends the new slider position, and the keys of the Gqueries, so that both can be performed in one HTTP request.

  If we have to go through the MeritController API, then we instead have to perform a slider update, wait for it to respond successfully (and add error-checking in case it doesn't), then go back to ETEngine a second time for the Merit data. Each request takes 1 to 1.5 seconds, so a user may have to wait 2-3 seconds for that chart to update. If we can request the chart data with a Gquery, we can avoid the need for a second request. The front-end can down-sample for the annual view, and chop up the data without down-sample for the weekly view.

  As far as I can tell, there's no need for an ETMoses-style "brush" since 24 hours * 7 days = 168 data points. The chart is ~300px wide, which means we have about 2 pixels per data point.

**However** a downside to this is that we have to send the full year of data; we can't chop it up into weekly data, nor down-sample it on the server. This is not necessarily a bad thing:

1. It's probably still be faster to send the full year of data in a Gquery than to perform a second request asking for down-sampled or chopped-up data.

2. With the full year of data available, it will be faster to change which week is being viewed (again, no need to spend 1.5 seconds waiting for ETEngine).

If this is still not fast enough, there are other compromises which could be made, such having one query which returns low-resolution yearly data, and then having separate queries each returning three months of high-resolution data.

* `merit_price_curve_low`
* `merit_price_curve_high_q1`
* `merit_price_curve_high_q2`
* ...

That might be overkill though; I'd like to see how it performs when sending the full year of data before trying separate queries.

I'm curious what everyone thinks?

**Comment by jorisberkhout** [comment]
I like the approach you propose, @antw !

**Comment by grdw** [comment]
@antw I agree fully with your reasoning :+1: the main thing that caught me was the 'what should happen when somebody touches a slider'.

> We'd have to add a Gqueries which duplicate the behaviour of the MeritController.

How were I to do that exactly? Where would I start exactly. Would it be in the same stretch as creating a gquery in the [gqueries folder](https://github.com/quintel/etsource/tree/master/gqueries). I'm wondering how to format that gquery exactly (syntax wise etc.)?

**Comment by antw** [comment]
> Would it be in the same stretch as creating a gquery in the gqueries folder. I'm wondering how to format that gquery exactly (syntax wise etc.)?

Exactly right. The Gqueries themselves are actually just Ruby, but with [some extra helper methods](https://github.com/quintel/etengine/tree/master/app/models/gql/runtime/functions) like `MAX`, `AVG`, `V`, meant to make things easier for modellers and researchers.

To get the price curve, you can do this in a Gquery:

```ruby
GRAPH().plugin(:merit).order.price_curve.to_a
```

([You can try writing ad-hoc queries here](https://beta-engine.energytransitionmodel.com/data/latest/gqueries/test)).

However that's a bit ugly, and we only really want a price curve for the `future` graph when the merit order is running (the merit order never runs on the `present` graph, so it won't give any meaningful data).

Instead, you might add a new method in `etengine/app/models/gql/runtime/functions/lookup.rb`:

```ruby
# Retrieves the merit order price curve
def MERIT_PRICE_CURVE
  if Qernel::Plugins::MeritOrder.enabled?(scope.graph)
    scope.graph.plugin(:merit).order.price_curve.to_a
  else
    []
  end
end
```

The full Gquery would be very simple:

```
- unit = EUR
- query = MERIT_PRICE_CURVE()
```

This would be placed in a subdirectory of `etsource/gqueries` – I expect @jorisberkhout could suggest a suitable place.

**Comment by grdw** [comment]
Thanks for the pointers. :+1:  I'm really new to gqueries and the most fancy one I ever wrote must have been 30 characters long including a really long name of a converter. 

> Instead, you might add a new method in etengine/app/models/gql/runtime/functions/lookup.rb:

I will. Thanks.

**Comment by jorisberkhout** [comment]
>  meant to make things easier for modellers and researchers
:tada:

> This would be placed in a subdirectory of `etsource/gqueries` – I expect @jorisberkhout could suggest a suitable place.

I would suggest to place the Gqueries in `etsource/gqueries/output_elements/<chart_type>_<chart_id>_<chart_name>/`

**Comment by antw** [comment]
> The Gqueries themselves are actually just Ruby, but with some extra helper methods

I should probably be more precise. :smiley:

Gqueries are the files you see in `etsource/queries`. These contain a `query` attribute and, optionally, a `unit` attribute. They're "ActiveDocument" files just like the others you see in ETSource.

The `query` attribute inside those files is a string which [is evaluated by ETEngine](https://github.com/quintel/rubel); we call this "GQL". *GQL* is Ruby with some helper methods.

**Comment by grdw** [comment]
> Instead, you might add a new method in etengine/app/models/gql/runtime/functions/lookup.rb:

Can I just blindly assume this code to be correct and working? 

Also there's probably another gquery needed for the `load_curves`. But I can somehow guess that that will be:

````ruby
def MERIT_LOAD_CURVES
  if Qernel::Plugins::MeritOrder.enabled?(scope.graph)
    scope.graph.plugin(:merit).order.load_curves.map(&:to_a)
  else
    []
  end
end
````

**Comment by grdw** [comment]
> I would suggest to place the Gqueries in etsource/gqueries/output_elements/<chart_type>_<chart_id>_<chart_name>/

I'm assuming you mean 
`etsource/gqueries/output_elements/output_series/<chart_type>_<chart_id>_<chart_name>/` ?

**Comment by jorisberkhout** [comment]
> I'm assuming you mean 
`etsource/gqueries/output_elements/output_series/<chart_type>_<chart_id>_<chart_name>/` ?

Correct, my bad!

**Comment by antw** [comment]
> Also there's probably another gquery needed for the load_curves. But I can somehow guess that that will be:

I think there are two ways to go about that:

1. Have one query return all the load curves.
2. Have one query *per* technology (and an `output_element_series` in ETModel for each one).

(1) is more future-proof if we add new technologies, but (2) is a much better fit for the way the ETM does things, since you can assign a separate label and colour for each technology without needing any new code.

(1) might look like:

```ruby
def MERIT_LOAD_CURVES
  return {} unless Qernel::Plugins::MeritOrder.enabled?(scope.graph)

  producers = scope.graph.plugin(:merit).order.participants.producers

  producers.each_with_object({}) do |participant, data|
    data[participant.key] = participant.load_curve.to_a
  end
end
```

(2) would be something like:

```ruby
def MERIT_LOAD_CURVES(part_key)
  if Qernel::Plugins::MeritOrder.enabled?(scope.graph)
    if participant = scope.graph.plugin(:merit).order.participants[part_key]
      participant.load_curve.to_a
    else
      fail "No such merit order participant: #{ part_key.inspect }"
    end
  else
    []
  end
end
```

I lean towards (2) just because it's simpler in ETModel.

**Comment by grdw** [comment]
I fully trust your judgement in this case. :+1: I'll add it to the [PR](https://github.com/quintel/etengine/pull/834)

**Comment by grdw** [comment]
*Status update:*

![screen shot 2016-04-22 at 16 16 05](https://cloud.githubusercontent.com/assets/2676542/14744111/a24cbd90-08a5-11e6-9dd2-0d86671444a2.png)
![screen shot 2016-04-22 at 16 16 10](https://cloud.githubusercontent.com/assets/2676542/14744112/a2507a70-08a5-11e6-92f7-0aad8b02f606.png)
![screen shot 2016-04-22 at 16 16 19](https://cloud.githubusercontent.com/assets/2676542/14744113/a251e374-08a5-11e6-945f-3af5610c2605.png)

I'm sort of tending to not start the y-axis at 0 but that might cause some discussion. The select box is working.  Selecting a full year can feel a little slow though (we could downsample it).

**Comment by grdw** [comment]
Furthermore:

- should it remember the date selection or is this a nice to have?
- when does it need to rerender (does etengine know when and how that's suppose to be done the smart way - just asking to be sure: @antw)?

**Comment by grdw** [comment]
![screen shot 2016-04-25 at 09 57 00](https://cloud.githubusercontent.com/assets/2676542/14777236/19296eb8-0acc-11e6-8fba-727cd71be4f9.png)
![screen shot 2016-04-25 at 09 57 07](https://cloud.githubusercontent.com/assets/2676542/14777235/1929627e-0acc-11e6-983b-0f08cc479c66.png)

This is Urgenda's scenario. I moved the select box to the right and fixed the interpolation (which caused the spikes above and below the scope of the chart @jorisberkhout). I'll make a PR for this and await feedback.

**Comment by dennisschoenmakers** [comment]
Great work guys! Could we also add the unit to the chart (I guess it is **€**)?

**Comment by jorisberkhout** [comment]
> Great work guys! Could we also add the unit to the chart (I guess it is €)?

You beat me to it, @dennisschoenmakers :). The unit on the y-axis should be **€ / MWh**.

**Comment by jorisberkhout** [comment]
Other than the y-label, I love the chart, @grdw! Very insightful. I would be happy to hear what @AlexanderWirtz , @ChaelKruip , @antw and @RobTerwel think of it.

**Comment by jorisberkhout** [comment]
@ChaelKruip suggested to add the annual average electricity price to this chart, as this is a parameter that is often discussed. This average electricity price should be displayed as a horizontal line with a y-value that is simply the sum of all datapoints in the merit order price curve divided by 8760. Also in week view, the line should display the annual average electricity price (as opposed to the weekly average electricity price).

Adding this line is a nice to have and #2081 and #2082 have priority. Could you look into how much time it would cost to add this line after you have closed #2081 and #2082, @grdw ?

**Comment by grdw** [comment]
![screen shot 2016-04-25 at 10 32 50](https://cloud.githubusercontent.com/assets/2676542/14778048/14a51b94-0ad1-11e6-8948-15bff03d5970.png)

Label is fixed

**Comment by AlexanderWirtz** [comment]
I like it, but am somewhat concerned by the high prices I am seeing :-)

**Comment by antw** [comment]
The high prices might be an indication that there is insufficient production to meet demand at those times. When this happens, we take the most expensive producer [and multiply its price by 7.22](https://github.com/quintel/merit/issues/66#issuecomment-12317794).

**Comment by dennisschoenmakers** [comment]
Isn't it weird that it is higher than the ['ultimate' fall back price](https://github.com/quintel/merit/blob/5afa92c854b6d4e8d5c754b6206c1148620a91d2/lib/merit/order.rb#L101) of 600 Euro?

**Comment by antw** [comment]
600 Euros is used as the fallback price only if the import interconnect is the price-setting producer. [Import is not currently connected to Merit](https://github.com/quintel/merit/issues/133#issuecomment-182279312).

[Prior to the introduction of storage](https://github.com/quintel/merit/blob/e4ac730454aa3f6fee73075cc30b48bee85c41dc/lib/merit/order.rb#L70-L85), 600 Euros would be the fallback price only if you had no dispatchable production installed.

**Comment by dennisschoenmakers** [comment]
> Prior to the introduction of storage, 600 Euros would be the fallback price only if you had no dispatchable production installed.

Perhaps the 600 is used in ETMoses when you have not included the Energy Sector in your scaled scenario? Then we might have some local volatile production, and you can end up with 600 EUR/MWh price when there is no dispatchable producer available? cc @ChaelKruip

**Comment by AlexanderWirtz** [comment]
I LOVE THIS CHART!! Finally we are seeing the effects of assumptions and short cuts like this one about [the 7.22 multiplier](https://github.com/quintel/merit/issues/66#issuecomment-12317794), which can give funny results

**Comment by jorisberkhout** [comment]
I love the progress so far, @grdw . In my view the remaining actionable items are:
- [ ] make annual view display the daily average
- [ ] (optional) add line displaying annual average electricity price

**Comment by grdw** [comment]
![screen shot 2016-04-29 at 16 21 19](https://cloud.githubusercontent.com/assets/2676542/14918895/6d21dc5a-0e26-11e6-8df5-bef31219e5b4.png)

I'm using [d3.mean](https://github.com/mbostock/d3/wiki/Arrays#d3_mean) function to calculate the average price. I can remember @ChaelKruip talking about wanting a dashed line. 

![screen shot 2016-04-29 at 16 27 25](https://cloud.githubusercontent.com/assets/2676542/14919064/4c7287ba-0e27-11e6-8dfb-2477f74c45b2.png)

I cannot really say that I have a preference though but please tell me what you would like.

**Comment by ChaelKruip** [comment]
> I can remember @ChaelKruip talking about wanting a dashed line.

I ❤️ it @grdw!

**Comment by jorisberkhout** [comment]
I prefer the dashed line as well. Could you add a legend to the chart as well? You can assign me for translations.

**Comment by jorisberkhout** [comment]
And, just to be sure, when you say:

> I'm using d3.mean function to calculate the average price.

This is the average for the entire year and not just the week on display, right?

**Comment by grdw** [comment]
> This is the average for the entire year and not just the week on display, right?

Yes this is for the whole year.

**Comment by antw** [comment]
Is the average line going into today's deploy? I don't think it's in the PR yet.

If it's not finished I can wait, or we can merge without it and add it later.

**Comment by jorisberkhout** [comment]
> Is the average line going into today's deploy? I don't think it's in the PR yet.

I would like to have it in and have seen it working on @grdw machine. @grdw is the average line ready?

**Comment by grdw** [comment]
It's not in this PR -> https://github.com/quintel/etmodel/pull/2097 but it is in the other though. I think I can close off this one: https://github.com/quintel/etmodel/pull/2097 and you can just look at: https://github.com/quintel/etmodel/pull/2105
