### ISSUE TITLE
Make it more explicit that a LES created from the ETM opens in ETMoses

### ISSUE THREAD

**Issue by jorisberkhout** [quintel/etmodel#2090]
As suggested by @MarjoleinSchwachofer , it could be made more explicit that a LES that is created from the ETM opens in ETMoses.

I would suggest to replace the text in the red box below by `Save and create a local energy solution (opens in ETMoses)`. What do you think @MarjoleinSchwachofer , @dennisschoenmakers , @AlexanderWirtz , @antw and @ChaelKruip ?

<img width="243" alt="screen shot 2016-04-12 at 18 04 13" src="https://cloud.githubusercontent.com/assets/4669028/14466974/637feec6-00d9-11e6-86da-befeebc7a423.png">

**Comment by antw** [comment]
> Save and create a local energy solution (opens in ETMoses)

Seems pretty long. For those who know what ETMoses is, I think "local energy solution" implies that it opens in ETMoses. For those who don't, adding "opens in ETMoses" doesn't really tell them anything.

It could be "Save and open in ETMoses", but that's no less cryptic for newcomers.

**Comment by antw** [comment]
I suppose we could do something like this?

![screen shot 2016-04-12 at 17 45 49](https://cloud.githubusercontent.com/assets/4383/14468157/6a515346-00d6-11e6-9daa-0fa181d14782.png)

*(it's kind of irrelevant that you're saving the scenario before opening, so that word could be removed)*

**Comment by dennisschoenmakers** [comment]
Good work @antw. I support your direction!

**Comment by MarjoleinSchwachofer** [comment]
I think atw provided a good solution. 

One other thing. With the menu item 'settings', you cannot only see current settings (language, year) but also use options to save, rest , scale etc. Perhaps another word would capture the different functions in this menu item more? 
Do you have ideas on this? (I cannot find the right word, only 'options' comes to mind.)

**Comment by ChaelKruip** [comment]
> Do you have ideas on this? (I cannot find the right word, only 'options' comes to mind.)

I think 'options' would work here fine

**Comment by jorisberkhout** [comment]
I like @antw 's suggestion and I like changing `settings` to `options`. Any objections?

**Comment by antw** [comment]
@jorisberkhout I pushed a branch to implement this – [settings-menu-sections](https://github.com/quintel/etmodel/tree/settings-menu-sections) but am I need of appropriate NL translations for "[Advanced tools](https://github.com/quintel/etmodel/blob/7337f4a166af20a28ba3cbc5a59de0ddb7801326/config/locales/nl_etm.yml#L35)", "[Learn about ETMoses](https://github.com/quintel/etmodel/blob/7337f4a166af20a28ba3cbc5a59de0ddb7801326/config/locales/nl_etm.yml#L49)", and "[Open as local energy solution](https://github.com/quintel/etmodel/blob/7337f4a166af20a28ba3cbc5a59de0ddb7801326/config/locales/nl_etm.yml#L52)".

It's fine if you want to make the changes yourself, otherwise if suitable texts can be provided I'll get this merged.

**Comment by michieldenhaan** [comment]
Closing, no longer support ETMoses
