### ISSUE TITLE
Gquery for MERIT_LOAD_CURVES

### ISSUE THREAD

**Issue by grdw** [quintel/etmodel#2098]
> Have one query per technology (and an output_element_series in ETModel for each one).

@antw A question about [this comment](https://github.com/quintel/etmodel/issues/2083#issuecomment-212927498). I just found out that there are 56 participants. Do you mean query it per participant i.e. 56 gquerties or do you mean something different with ' per technology'?

**Comment by antw** [comment]
A separate query per-participant is indeed what I meant. However, 56 participants is a lot of data. 😨 

@jorisberkhout Do we really need to show each individual participant in the chart? Is there any way we could summarise such as "all coal producers", "all gas producers", ...?

**Comment by jorisberkhout** [comment]
> @jorisberkhout Do we really need to show each individual participant in the chart? Is there any way we could summarise such as "all coal producers", "all gas producers", ...?

Plotting all 56 curves seems a bit to much to me too. My original idea was to only show the curves for those plants that actually participate in the merit order à la the merit order table. This is what I wrote in #2081:

> - Only the profiles for those plants that participate in the merit order should be shown. In other words, if a certain type of plant is not installed in the user's scenario, it should not show up. This behaviour is identical to that of the merit order table.

Since no-one creates a scenario with all 56 merit order plants in it, this will solve the visual noise problem i.m.o. I cannot oversee if this solves the Gquery-issue as well. Do the Gqueries that populate the merit order table provide some clue on how to do it in a smart way, @grdw ? Or do you know by heart, @antw or @ChaelKruip ?

**Comment by grdw** [comment]
![screen shot 2016-04-25 at 17 29 25](https://cloud.githubusercontent.com/assets/2676542/14789093/4ff17bc2-0b0b-11e6-8a14-09f71b1c0b91.png)

I'm a bit concerned about the fact that I think I'm misunderstanding what a participant is. Mainly because some participants don't return any data. Is that because the data is not there (i.e. all the data contains zero's?) Or is it because it's actually not a real participant.

**Comment by antw** [comment]
The participant key should be a Symbol:

```ruby
MERIT_LOAD_CURVES(:agriculture_chp_engine_biogas)
```

**Comment by grdw** [comment]
Thanks! That makes a lot of difference

**Comment by jorisberkhout** [comment]
This is solved and implemented, right @grdw ? Can this issue be closed?

**Comment by grdw** [comment]
Yes
