### ISSUE TITLE
Should we group the profiles in the new merit order supply chart?

### ISSUE THREAD

**Issue by jorisberkhout** [quintel/etmodel#2106]
The new merit order supply and demand chart shows quite a lot of data. Perhaps we could add a simplified view showing just three profiles:

- The sum of all profiles for the `VolatileProducer` producers
- The sum of all profiles for the `MustRunProducer` producers
- The sum of all profiles for the `DisplatchableProducer` producers

It should we possible to switch between showing just these three profiles and showing all profiles. As discussed with @AlexanderWirtz and @grdw , let's first gather some user experiences before we decide if we need this. Putting this issue on hold.

**Comment by grdw** [comment]
Is this still on-hold now it's in the current milestone? Are there actually people that want this except for me finding it a really cool feature.  

And more-over this should be designed very well first 👍  I'm leaning towards the same way we are currently doing this in ETMoses (with a select box) next to the date box. However there's also [this issue](https://github.com/quintel/etmodel/issues/2132). And maybe because there are just two ways to view this chart (grouped or non-grouped) we might also toggle them with a radio-button or with a switch like the merit-order one? I need to draw up a thing or two before deciding what looks right.

**Comment by jorisberkhout** [comment]
As discussed with @grdw
