### ISSUE TITLE
Settings menu falls of the screen on Live and Beta

### ISSUE THREAD

**Issue by jorisberkhout** [quintel/etmodel#2108]
With the ETM open in Google Chrome (Version 50.0.2661.86), this is what I see when I open the settings menu. Could this have to do with the disabling of the search bar (see https://github.com/quintel/etmodel/commit/773026f0a7cc9e8e4611944a7ba4c4cdca1eeac8)?

Assigning @dennisschoenmakers . Re-assign at will.

<img width="1440" alt="screen shot 2016-05-02 at 13 38 15" src="https://cloud.githubusercontent.com/assets/4669028/14953598/628ed0ee-106b-11e6-8b40-9d03ceada714.png">

**Comment by dennisschoenmakers** [comment]
Good catch! If you click **log in**, it is even worse:

![image](https://cloud.githubusercontent.com/assets/104830/14953823/84800c48-106d-11e6-9848-dc878fa38f7c.png)

Can you have a look at this @grdw ?

**Comment by grdw** [comment]
I see. Maybe aligning the  boxes to the right (instead of the left) can solve this problem :) . Or increasing the margin of the "Settings | Log In" menu but that looks really bad.

![screen shot 2016-05-02 at 14 01 05](https://cloud.githubusercontent.com/assets/2676542/14953916/54bfeedc-106e-11e6-8f13-ea9bad7d13b7.png)

I also don't have that triangle thingy like you have? (Firefox 45.0.2 here)

**Comment by dennisschoenmakers** [comment]
> Maybe aligning the boxes to the right (instead of the left) can solve this problem :)

Good idea!

**Comment by grdw** [comment]
![screen shot 2016-05-02 at 14 04 14](https://cloud.githubusercontent.com/assets/2676542/14953968/c68e1714-106e-11e6-87e7-92fef48437fe.png)

It's like this than. However, I still miss the triangle pointer ...

**Comment by dennisschoenmakers** [comment]
I guess I am also missing it in Chrome:

![image](https://cloud.githubusercontent.com/assets/104830/14954031/1989c5b2-106f-11e6-9fed-3723407fa4fa.png)
