### ISSUE TITLE
You can't render two merit related charts next to each other for reason unknown

### ISSUE THREAD

**Issue by dennisschoenmakers** [quintel/etmodel#2127]
You see it when you zoom, but you cannot see it when you do not zoom in. 

### Zoomed in :+1:
 
![image](https://cloud.githubusercontent.com/assets/104830/15505693/d1de53ec-21c4-11e6-97aa-fbc233054fe5.png)

### Not zoomed in

![image](https://cloud.githubusercontent.com/assets/104830/15505729/01a92958-21c5-11e6-82be-2351f7b64675.png)

**Comment by jorisberkhout** [comment]
Assigning @grdw .

**Comment by dennisschoenmakers** [comment]
This is a more prominent bug, that also affects other technologies.

### Missing wind in not-zoomed in chart:

![image](https://cloud.githubusercontent.com/assets/104830/15506496/28022da4-21c8-11e6-9d0e-1212327ace53.png)


### Still shows when you zoom in:

![image](https://cloud.githubusercontent.com/assets/104830/15506482/1b8279c6-21c8-11e6-9603-f5380461ea68.png)

**Comment by grdw** [comment]
Do you do anything fancy or just zoom in and than close the zoomed in chart?

**Comment by grdw** [comment]
<img width="645" alt="screen shot 2016-05-24 at 16 18 59" src="https://cloud.githubusercontent.com/assets/2676542/15507277/3fab58a6-21cb-11e6-9396-bb24ccd31eb9.png">

I try dragging a lot of sliders (in the Urgenda scenario) and clicking on anything that makes the chart change but I don't see anything odd.

What is odd though, is that the dateselect doesn't remember the selection in the zoomed chart (so that when you change the date in the small chart) and than zoom in (the date select is back to the first week and also renders the first week).

I'm sorry but I'm having a really hard time reproducing any of this... is this in Chrome by accident?

**Comment by grdw** [comment]
Oops, hit the wrong button there.

**Comment by ChaelKruip** [comment]
> is this in Chrome by accident?

Yes. Not by accident though 😉

**Comment by dennisschoenmakers** [comment]
Well, I did a lot. 😊 

1. I opened SER 2023 scenario
2. I open a lot of charts at the same time.
3. I lock all these charts
4. I installed a lot of wind turbines offshore, batteries, electric cars.

![image](https://cloud.githubusercontent.com/assets/104830/15507313/6c1426b6-21cb-11e6-8da8-34b832750644.png)

**Comment by dennisschoenmakers** [comment]
My scenario: https://pro.energytransitionmodel.com/scenarios/292927

**Comment by grdw** [comment]
I just want to say out loud and in public that this is probably a 'critical bug' but can we just say that as long as the servers aren't literally on fire or the website isn't completely unmanageable and help is needed right now (and anything, right, anything must pass - dying grandma, disease, rapture, zombie outbreaks etc.) than it is the right time to call something critical? 

Because, fair and square it's a bug, but considering the amount of steps I need to do to reproduce this it's at best some 'high prio' issue but not critical. Just my 2 cents of ranting on the whole word 'critical'.

**Comment by grdw** [comment]
Hmm.. I think you can't really open the Flexibility chart next to the Hourly supply chart and start dragging sliders. It sort of destroys one of the two.

**Comment by dennisschoenmakers** [comment]
> Because, fair and square it's a bug, but considering the amount of steps I need to do to reproduce this it's at best some 'high prio' issue but not critical.

Well, Chael and I were just playing along nicely with the ETM, nothing fancy. 

When a series disappeared in the chart, we created this issue and added a label 'bug' to it. I think it is quite unfortunate if it ever happens. When it happened for the **second** time shortly thereafter, we added the 'critical bug' label. 

I think the use of that term here is justified.

I understand it is annoying if you cannot reproduce the bug easily and it takes a lot of time.

**Comment by dennisschoenmakers** [comment]
> Hmm.. I think you can't really open the Flexibility chart next to the Hourly supply chart and start dragging sliders. It sort of destroys one of the two.

Good catch!

**Comment by grdw** [comment]
Still not figured out technically why it's not working as it should though. Did fix the annoying legend bug #2114 

> I think the use of that term here is justified.

I still have to disagree with you here. Just because you can reproduce the bug twice just doesn't make it critical. But oh well. I'll just have to teach myself not to freak out everytime I read the word critical than...

**Comment by ChaelKruip** [comment]
> I'll just have to teach myself not to freak out everytime I read the word critical than...

I have made this new label for those situations where you need @grdw to really freak out:

![labels_ _quintel_etmodel](https://cloud.githubusercontent.com/assets/1303760/15508495/f1fc092a-21cf-11e6-9271-0638190f5173.png)

**Comment by grdw** [comment]
<img width="1272" alt="screen shot 2016-05-24 at 16 55 43" src="https://cloud.githubusercontent.com/assets/2676542/15508596/634f11b2-21d0-11e6-9ccb-bb3cc6223c93.png">

I added all three charts and started hitting the "Onshore inland (super) slider". It causes really big spikes in the merit order but nothing to strange at first. I can however reproduce the "Battery thing" but I can't make other series dissapear...

**Comment by ChaelKruip** [comment]
Perhaps this is a lead (perhaps another bug) but the battery curve in my not-zoomed chart look very weird in Chrome:
![energy_transition_model_-_your_free__independent__comprehensive__fact-based_scenario_builder_](https://cloud.githubusercontent.com/assets/1303760/15509143/c329fec4-21d2-11e6-8fb6-791505920199.png)
In the zoomed chart:
![energy_transition_model_-_your_free__independent__comprehensive__fact-based_scenario_builder_](https://cloud.githubusercontent.com/assets/1303760/15509166/d8952cf2-21d2-11e6-8341-536be994992d.png)

**Comment by grdw** [comment]
Still not anywhere close near a possible fix ... the values of some series just appear blank all of a sudden which causes the whole rendering to break 😕 I have seriously no friggin clue how to fix this one (calls @antw hotline). After the refresh it does render though (and the values aren't blank) but the first time they are blank causing some of the most random bugs ever.

<img width="1074" alt="screen shot 2016-05-24 at 17 31 41" src="https://cloud.githubusercontent.com/assets/2676542/15509890/6e0c614a-21d5-11e6-8404-e42281d4aa71.png">

@ChaelKruip is this plotted side by side or just a single chart?

**Comment by grdw** [comment]
Okay, wth..

````javascript
serie.future_value()
````

Just returns `undefined` (for the hourly supply chart) when rendering two merit related charts in one view. I just reduced testing with three charts to just two to simlify the whole reproducing.

I still have no clue, I'm just figuring out more wacky things as I go along .. I'll try to see what happens with et-engine in localhost.

**Comment by grdw** [comment]
> I'll try to see what happens with et-engine in localhost.

Nothing changes, still the `values` are blank. All is fine at et-engine side. 🚶 

eh.. 

.. anybody reading?

**Comment by ChaelKruip** [comment]
Single chart

**Comment by dennisschoenmakers** [comment]
> eh..
> .. anybody reading?

I am. A mystery. @antw: can you think along?

**Comment by antw** [comment]
I pushed a quick fix.

| Before | After |
| --- | --- |
| ![screen shot 2016-05-24 at 19 46 34](https://cloud.githubusercontent.com/assets/4383/15515930/5397eb46-21e8-11e6-85db-703cc0ac71ab.png) | ![screen shot 2016-05-24 at 19 46 28](https://cloud.githubusercontent.com/assets/4383/15515945/5d14dbb6-21e8-11e6-89da-1244d9021be1.png) |

#### Steps to reproduce

1. Start a new scenario. NL, 2050.
2. Show the "Merit order hourly supply" chart, and lock it.
3. Demand → Transportation → Car Technology → Electric = 100%
4. Flexibility → Flexibility options → Storage in batteries = 100%
5. Supply → Renewable electricity → Onshore wind = 25000

#### The problem

I believe this was caused by the fact that, when loaded, the chart [filters out any series which have no relevant data](https://github.com/quintel/etmodel/blob/414c28b1d7c0f803fbaa7f014236cea9584c5769/app/assets/javascripts/d3/merit_order_hourly_supply.coffee#L46-L47) (the loads are all zero), and shows only those with values.

When you later add batteries and excess energy to the scenario, the series would not be shown on the chart due to it not having a `path.area` when the chart was first rendered. [Since there is no element in the chart, there's nothing to update](https://github.com/quintel/etmodel/blob/0e7f182dc4538a819f4e4c88a6808620ab392987/app/assets/javascripts/d3/merit_order_hourly_supply.coffee#L89-L99).

#### The (temporary) solution

I disabled the series filtering; all will be shown. This is not very elegant, the legend is now very long, and shows series which are not visible on the chart.

#### Sidenote

I feel the need to support @grdw about the use of the word "critical". To me, critical means that it needs immediate drop-everything-you're-doing attention; "forget the deadline on *that other project*". It means a client is actively using the feature and a contract depends on it being fixed immediately, or a report is being prepared and needs accurate data *right now*. Or, we're doing a workshop in front of a hundred people and this thing being wrong is embarrassing.

If this is one of those issues, fair enough.

This is the criteria I use to judge which issues get attention:

* Something which is "critical" is an immediate priority.
* An issue which isn't will get attention as soon as schedules permit (which might be tomorrow, or might be a month from now).
* If it isn't critical, but has the "priority" label, it'll be first in line to get sorted when time is available.

**Comment by dennisschoenmakers** [comment]
Ah, sorry @antw, i see you already did in 0e7f182

**Comment by antw** [comment]
By the way, I couldn't reproduce any issues regarding multiple merit charts being visible simultaneously. Every time I tested, both charts updated correctly every time.

**Comment by dennisschoenmakers** [comment]
On the whole label issue: I guess I confused 'critical bugs' with the 'Priority' label. Sorry about that. I will reserve 'critical bugs' for the kind of critical situations described very lively.

> *"Everytime I read critical I'm getting a stroke and I assume somebody is dying in the office."*
