### ISSUE TITLE
Electricity stored in EV should also be shown in merit order hour chart

### ISSUE THREAD

**Issue by dennisschoenmakers** [quintel/etmodel#2128]
### Merit order hourly supply:

![image](https://cloud.githubusercontent.com/assets/104830/15505790/433cd892-21c5-11e6-8c2a-288222da9d2c.png)

### Merit Order hourly flexibility

![image](https://cloud.githubusercontent.com/assets/104830/15505829/6441d646-21c5-11e6-8f25-7e09d604199a.png)

**Comment by jorisberkhout** [comment]
Well spotted. Assigning @grdw .

**Comment by grdw** [comment]
Is there a carrier for this that I can simply include in the `outout_element_series` table? Somehow I can remember that we withheld from this original idea because it was a bit more complex than that. If somebody could refresh my memory on this subject?

**Comment by antw** [comment]
My guess is that [this query](https://github.com/quintel/etsource/blob/master/gqueries/output_elements/output_series/d3_172_merit_order_hourly_supply/transport_car_using_electricity.gql) needs to be changed to look for the curve on `transport_car_flexibility_p2p_electricity`, because that node is the one which represents energy stored in electric vehicles.

**Comment by grdw** [comment]
I'll check to see what happens if I change that :) thanks!

**Comment by grdw** [comment]
Hmmm this gives me an error: No such merit order participant: `:transport_car_flexibility_p2p_electricity`.

**Comment by antw** [comment]
> Hmmm this gives me an error:

My bad, sorry. The original query likely is correct, since the merit order participant *is* called `transport_car_using_electricity`.
