### ISSUE TITLE
Order in the legend should be the same as order in the chart

### ISSUE THREAD

**Issue by ChaelKruip** [quintel/etmodel#2145]
Now the legend of charts seems to be a bit random...

**Comment by jorisberkhout** [comment]
Is this something you can do as part of https://github.com/quintel/etmodel/issues/2187, @grdw ?

**Comment by grdw** [comment]
What is the "order in the chart"? I don't think that's a generic term you can use.

<img width="620" alt="screen shot 2016-09-09 at 09 42 27" src="https://cloud.githubusercontent.com/assets/2676542/18379253/c19a1866-7671-11e6-86fc-bb49cfa18743.png">

This order is clearly reversed if you start looking from the top to the bottom.

<img width="618" alt="screen shot 2016-09-09 at 09 45 12" src="https://cloud.githubusercontent.com/assets/2676542/18379312/2175499a-7672-11e6-8ae0-7e7d1fc36f6b.png">

In here the order of the legend is scrambled accross the chart.

So what do you mean with 'the order in the chart'? And for what chart?

**Comment by jorisberkhout** [comment]
@ChaelKruip , could you clarify this issue / your original comment?

**Comment by ChaelKruip** [comment]
> This order in the image above is clearly reversed if you start looking from the top to the bottom.

Yes. I think it would be more natural to have 'appliances' at the bottom of the chart and at the bottom of the legend. 

> In this example howver the order of the legend is scrambled accross the chart.

Not really, I think the order here is:
1. hydrogen
2. hot water
3. electricity
4. geothermal
5. solar thermal
6. coal
7. natural gas
8. oil
9. biogenic waste

both in the legend and in the chart. This is the 'natural' way of displaying it in my opinion.

**Comment by grdw** [comment]
> Yes. I think it would be more natural to have 'appliances' at the bottom of the chart and at the bottom of the legend. 

The only way I see that happening is when somebody reverses the `order_by` column by hand.

**Comment by ChaelKruip** [comment]
> The only way I see that happening is when somebody reverses the order_by column by hand.

No. Because than the series are also plotted in the reverse order.

**Comment by grdw** [comment]
> No. Because than the series are also plotted in the reverse order.

Eh, ok. learn something new everyday. 😅 

We could solve it by adding another column called `legend_order_by` and specify the order of the legend in there? Or we could `reverse()` the order as a patch fix for that one single chart but that's just a cheap shot.

**Comment by ChaelKruip** [comment]
> Or we could reverse() the order as a patch fix for that one single chart but that's just a cheap shot.

Why would that be a cheap patch? Personally I think that would be a big improvement. 

Curious about other opinions though... @jorisberkhout @antw @DorinevanderVlies @AlexanderWirtz  @dennisschoenmakers ?

**Comment by grdw** [comment]
> Why would that be a cheap patch? P

Because I haven't looked at the behavior of other chart types and their legends yet.

**Comment by antw** [comment]
> Why would that be a cheap patch? Personally I think that would be a big improvement.
>
> Curious about other opinions though... @jorisberkhout @antw @DorinevanderVlies @AlexanderWirtz @dennisschoenmakers ?

I agree with @grdw that it would be a "cheap patch" to simply `reverse()` the order of the legend without first understanding *why* the legend order is correct in some charts but not in others.

My guess is that [stacked bar charts](https://cloud.githubusercontent.com/assets/4383/18447136/438cb7e0-791d-11e6-9753-d4dd601efce4.png) and line charts plot the first series at the bottom of the chart and grow upwards `↥` (Geothermal → Biomass → Ambient heat → ... → Coal → Oil), whereas the mekko charts start at the top-left and grow diagonally down/right `↘`.

The reason cheap fixes are worrisome is that things get missed:

* Changing the stacked bar and stacked line charts would be an improvement, but the merit order and "CO<sub>2</sub> emissions biomass" charts would still have legends in the wrong order.
* The ["Electricity production per hour" chart](https://cloud.githubusercontent.com/assets/4383/18447596/3c1e8b4e-791f-11e6-8fae-81315f83152b.png) also needs to have the legend reversed (and is neither a `StackedBar` nor `StackedLine` chart) – but I think it should still show the "Demand" series first.
* In some charts the order of series' may change ("Merit order capacities and marginal costs"), but I'm not convinced the legends should be re-sorted when that happens (that chart is particularly quirky since it grows form the bottom-left, up/right `↗`).

I'm bike-shedding a bit, but you get the idea. :dash:

--

*(Since there is insufficient time before the deploy, I think it's okay to fix the main issue – stacked line and stacked bar charts – and come back to the special-case charts later).*

**Comment by ChaelKruip** [comment]
> I agree with @grdw that it would be a "cheap patch" to simply reverse() the order of the legend without first understanding why the legend order is correct in some charts but not in others.

Point taken (although I did not aim to suggest that we should implement something we don't fully understand the effects of)!

**Comment by jorisberkhout** [comment]
Let's remove this from the deploy milestone as it is not critical.

**Comment by jorisberkhout** [comment]
This has been implemented, right @grdw? If so, could you close this issue?

**Comment by grdw** [comment]
Relevant issue: https://github.com/quintel/etmodel/issues/2562
