### ISSUE TITLE
Could we make it possible to display more dashboard items at once?

### ISSUE THREAD

**Issue by jorisberkhout** [quintel/etmodel#2172]
As suggested by John.

By now, we have so many interesting dashboard items the user can choose from, that it could be interesting to display more than seven at the same time. In addition, it could be interesting to show more dashboard items from the same category which is currently impossible.

John and I came up with the two possible solutions described below, but I would be happy to hear from @AlexanderWirtz , @dennisschoenmakers , @ChaelKruip , @antw , @grdw , @RobTerwel and @DorinevanderVlies how they feel about it.
### Solution 1: Allow the user to add a second row of dashboard items

We could give the user the option to add a second row of dashboard items and fill these with the dashboard items he is interested in. The dashboard items would have to become smaller in order not to take up to much of the screen.
### Solutions 2: More dynamic dashboard

I drew inspiration from the way this works on Garmin Edge devices. There, the 'dashboard' takes up a fixed amount of space. The user can select how many items he wants to display and the app will decide on the best arrangement. The downside of selecting more items, is that they become smaller in size. Once the user has selected the number of items, he can select which items to display on each of the positions. See the image below where the user has selected 10 items to display.

![garmin edge 1000 unboxing - profiles - data screen max 10](https://cloud.githubusercontent.com/assets/4669028/16523198/669916d4-3fa2-11e6-9489-8e7ea912ea53.jpg)

Assigning myself to keep track of the discussion.

**Comment by RobTerwel** [comment]
First off, I really like this idea of reorganising our dashboard! 😄 

I'm in favour of option two, because of its customisability: it would allow the user to change the quantity and _order_ of dashboard items. Depending on what the ETM is used for, it can display a few main characteristics of the energy system studied (thus resulting in a 'cleaner' screen) or offer a more detailed picture of blackout hours and such. Besides, it would become possible to change which items are displayed _freely_ (as opposed to having to pick one item from an incomplete list for every dashboard item spot, as is the case now).

**Comment by ChaelKruip** [comment]
I like option two as well!

Now that we are talking about re-designing the dashboard I would also like to bring up something that has bothered me for a long time: the arrows for the dashboard items confuse me sometimes (also see https://github.com/quintel/etmodel/issues/1127). I'll make a new issue for this.

**Comment by DorinevanderVlies** [comment]
I also like option two, as long as the maximum amount of items still yields a readable dashboard.

**Comment by AlexanderWirtz** [comment]
2

**Comment by dennisschoenmakers** [comment]
In favour of **2** as well.
