### ISSUE TITLE
Building more wind should not increase the blackout hours

### ISSUE THREAD

**Issue by ChaelKruip** [quintel/etmodel#2179]
Right @jorisberkhout?

With a lot of wind:
![energy_transition_model_-_your_free__independent__comprehensive__fact-based_scenario_builder_](https://cloud.githubusercontent.com/assets/1303760/17023028/8b0e2d2e-4f51-11e6-81a4-a6f55b72d496.png)

with more wind:
![energy_transition_model_-_your_free__independent__comprehensive__fact-based_scenario_builder_](https://cloud.githubusercontent.com/assets/1303760/17023042/9b295e2c-4f51-11e6-80b4-b0edb4a3abd2.png)

Including @grdw

**Comment by grdw** [comment]
If there's no physical reason for this to happen it might be a rounding problem. We check if a blackout happens if the `net_load` (production - consumption) drops below `1e-10` (this is to prevent rounding problems with numbers like -0.000000001). It might be that something is dropping is to `1e-11` and that still counts as a blackout hour but it seems unlikely.

**Comment by jorisberkhout** [comment]
> If there's no physical reason for this to happen it might be a rounding problem.

I have a sneaky suspicion this might be the case. I have downloaded the load curves for several scenario and performed the following analysis

> We check if a blackout happens if the `net_load` (production - consumption) drops below `1e-10`

This gives different results if I check for `<1e-11`, `<1e-10` or `<1e-9`, which seems to suggest that the increasing number of blackout hours might be an artefact. I will test this locally!

**Comment by jorisberkhout** [comment]
Hmm, can't get this to work locally and will ask @grdw for help when he's back from his holidays.
