### ISSUE TITLE
X-labels of mekko's need improvement

### ISSUE THREAD

**Issue by jorisberkhout** [quintel/etmodel#2186]
As can be seen in the examples below, the x-labels of the mekko's are cut off by the boundary box of the chart. Also, the x-labels overlap with the legend.

<img width="300" alt="screen shot 2016-08-16 at 10 04 54" src="https://cloud.githubusercontent.com/assets/4669028/17692915/afaf5b62-639c-11e6-8596-2fac3e7f9ab9.png">

<img width="300" alt="screen shot 2016-08-16 at 10 26 29" src="https://cloud.githubusercontent.com/assets/4669028/17692918/b3737788-639c-11e6-9292-45cb00dc444a.png">

I would suggest to display the x-labels vertically instead of under an angle and place the legend below the longest x-label. I realise that some x-labels are quite long; I suggest to make the label two lines instead of one like:

```
Transport
2.05 Mm2
```
instead of `Transport 2.05 Mm2`

I would be happy to hear any other ideas from @ChaelKruip , @antw , @RobTerwel, @grdw or @dennisschoenmakers?

Assigning @grdw . Re-assign at will.

**Comment by ChaelKruip** [comment]
> I suggest to make the label two lines instead of one

👍 

> I would suggest to display the x-labels vertically instead of under an angle

I think this is going to take a lot of space and would not improve readability. Moving the industry sector left might solve the cut-off problems in 90% of the cases as it is so big. Unfortunately, I don't know how to order the sectors horizontally in the Mekko's. There seems not to be any logic to how they are ordered in the database and in the front-end 😢

**Comment by dennisschoenmakers** [comment]
> I would suggest to display the x-labels vertically instead of under an angle and place the legend below the longest x-label. 

:+1:

**Comment by grdw** [comment]
> I would suggest to display the x-labels vertically instead of under an angle

Sounds good and easy.

> and place the legend below the longest x-label.

That's not as easy as it sounds.

> I realise that some x-labels are quite long; I suggest to make the label two lines instead of one like:

This is where I'm currently at.

![screen shot 2016-09-07 at 11 12 06](https://cloud.githubusercontent.com/assets/2676542/18306394/f3fb7e30-74eb-11e6-9867-adf942f3ad0d.png)

😢 It works, but I'd suggest to make the font-size of the 'total' label at most 75% of the text label.

**Comment by grdw** [comment]
Is Other now making up 0 pixels in the mekko chart but still showing a label?

![screen shot 2016-09-07 at 11 20 36](https://cloud.githubusercontent.com/assets/2676542/18306667/221704e6-74ed-11e6-8274-68ad7802724a.png)
![screen shot 2016-09-07 at 11 20 44](https://cloud.githubusercontent.com/assets/2676542/18306668/22179ffa-74ed-11e6-9fdc-0e3dd0aa309b.png)

**Comment by grdw** [comment]
I talked to both @dennisschoenmakers and @jorisberkhout . @dennisschoenmakers suggested to determine how much space would be needed according to the minimum amount of width a certain label needed. This is rather hard. 

A simpler wat was suggested by @jorisberkhout to just divide the labels evenly accross the width of the mekko chart and draw lines from the center of the block to the label like this:

![screen shot 2016-09-08 at 11 36 28](https://cloud.githubusercontent.com/assets/2676542/18344676/8f3e9b62-75b8-11e6-85e5-5fc4eece659e.png)

What I would suggest is that the lines are default `opacity: 0.5` and when you hover the label you see where the line is pointing to. Right now I can imagine people could have a hard time seeing which area belongs to "Transport" in the example.

Also I'd like some opinions. 👼

**Comment by antw** [comment]
> A simpler wat was suggested by @jorisberkhout to just divide the labels evenly accross the width of the mekko chart and draw lines from the center of the block to the label like this:

I like it.

> What I would suggest is that the lines are default opacity: 0.5 and when you hover the label you see where the line is pointing to.

This too. :+1:

It would be nice if hovering over a series in the chart would also highlight the relevant line; that's not too important though, since the pop-over gives the details of whichever series the mouse is over.

**Comment by grdw** [comment]
I'm trying to figure out how to smooth the line properly.

The standard CSS `shape-rendering: crispEdges;` option is off the table because that makes the line even more pixelated. However, there's a genius at [Stackoverflow](http://stackoverflow.com/questions/6621518/how-to-smooth-a-freehand-drawn-svg-path) who answered how to do it, however this sounds more complicated than it should be in my opinion 😅

**Comment by grdw** [comment]
![screen shot 2016-09-08 at 12 19 07](https://cloud.githubusercontent.com/assets/2676542/18346037/94be1620-75be-11e6-8153-57e30574b1ff.png)

Turns out going fully vertical is not a golden solution either... Going back to a -30 degree angle is even weirder considering the angel of the lines. And considering this:

![screen shot 2016-09-08 at 12 28 47](https://cloud.githubusercontent.com/assets/2676542/18346413/4ac86118-75c0-11e6-97fc-eb304c4a0514.png)

This is again solveable by moving the label down a few pixels..

**Comment by dennisschoenmakers** [comment]
IMO the evenly distributed labels are doing more harm than good. It makes a 'simple' Mekko really hard to read, see if you can 'see' where the **other** or the **food** column is:

![image](https://cloud.githubusercontent.com/assets/104830/18347759/ae677edc-75c7-11e6-958a-ae0272f0b7dd.png)

😵

**Comment by grdw** [comment]
I agree with @dennisschoenmakers however the solution to start detecting collision and adjusting the label accordingly is even harder. I tried today (most of the day) with [this example(http://bl.ocks.org/larskotthoff/11406992) in mind but didn't really understand what he did. I came so far as to know how to detect a collision but than I was unsuccessfull in moving the label in the correct position.

````javascript
min_label_width = 25;
svg.selectAll(".label").each(function() {
  var that = this,
       a = $(this).data('x') 
       // I had to determine the x-value by hand, the x-value is the center of the label (so in between the two tspan elements)
  
  svg.selectAll(".label").each(function() {
    if(this != that) {
      var b = $(this).data('x')
      if(Math.abs(a - b) < min_label_width) {
          // overlap, move labels
          var dx =  ??????,
            tt = d3.transform(d3.select(this).attr("transform")),
            to = d3.transform(d3.select(that).attr("transform"))
            
          to.translate = [ to.translate[0], to.translate[1] + dx ];
          tt.translate = [ tt.translate[0], tt.translate[1] - dx ];
          d3.select(this).attr("transform", "translate(" + tt.translate + ")");
          d3.select(that).attr("transform", "translate(" + to.translate + ")");
          $(this).data('x', a - dx);
          $(that).data('x', b + dx)
      }
    }
  });
});
````

**Comment by antw** [comment]
I pushed a branch with my go: **[mekko-label-overlap-antw](https://github.com/quintel/etmodel/tree/mekko-label-overlap-antw)**. [I commented `arrangeLabels` fairly heavily](https://github.com/quintel/etmodel/commit/4e329dfec434cf3e7a72e02a343c69d178ba8b3c#diff-c59853f8baef1bb9db0f09a81ffeb30aR228), so hopefully it's not too magic. My geometry is a bit rough, so there might be ways to simplify it further.

It's based heavily on that bl.ocks code, but simplified since it only needs to modify on the horizontal axis. I made a couple of other changes to prevent labels from moving outside the chart boundary, and to exit the algorithm after a maximum of 200 iterations (which could happen if there isn't enough space for all the labels).

I'm not sure whether I like it since the labels don't always appear under the series. Perhaps if we added the lines from @grdw earlier experiments it would make more sense?

![screen shot 2016-09-08 at 18 46 54](https://cloud.githubusercontent.com/assets/4383/18360157/c9813596-75f4-11e6-964c-ca376d24edc6.png)

It could probably still use some fine-tuning; the Central ICT label is too far from the right here:

![screen shot 2016-09-08 at 18 47 30](https://cloud.githubusercontent.com/assets/4383/18360153/c61dd1b6-75f4-11e6-9256-6cee6b9094e2.png)

> Ofcourse I needed to convert this to CoffeeScript which gave me bad headaches... The difference between -> and => ....

ES6/ES7 on future projects? :grinning:

* `->` = `function(){}`
* `=>` = `function(){}.bind(this)`

**Comment by antw** [comment]
I also had to comment-out a couple of calls to `transition().duration(500)`. These are responsible for the chart animating nicely when gqueries change; with them removed, the chart updates immediately whenever a value changes. This is not really ideal. However it *was* necessary – at least in this prototype – in order to get the correct position of each label in `arrangeLabels`.

With the animation enabled, fetching the position of each label with `getBoundingClientRect` would return the wrong values: the labels were all in their starting positions at the bottom left of 
chart, instead of in their post-animation positions.

**Comment by antw** [comment]
After a bit of thought, [I've pushed a much better alternative](https://github.com/quintel/etmodel/commit/931572cdc6b17d74a0a9430eb1222b5802d7738d) (to the same branch) which has the added benefit of O(n) time complexity instead of O(n<sup>2</sup>). The previous version needed ~60 passes on a chart with 6 sectors; the new one needs 12. :tada:

You might still be interested in [the commented version of the (simpler) bl.ocks code](https://github.com/quintel/etmodel/commit/472af1f16a0341707fca9572aa662970591d1ba3#diff-c59853f8baef1bb9db0f09a81ffeb30aR228) if you want to understand how that works, but I think that was a red herring. The original is trying to position labels on a map in two dimensions (x and y), whereas our labels only move in one direction (x). With that in mind, the labels can be repositioned with only two passes.

Here's a starting situation with three overlapping labels, visualised on top of each other for simplicity:

| Starting situation |
| :---: |
| ![labels-1](https://cloud.githubusercontent.com/assets/4383/18367523/8045c36e-7613-11e6-9ea8-e5b80eeb1f84.jpg) |

*I know, I know. Try not to too startled by the beauty of my artwork.*

Label 1 overlaps label 0, and label 2 overlaps 1.

Check pairs of labels for overlaps, starting with the left-most pair. If the *left*-edge of label 1 is to the left of the *right*-edge of label 0, we know the label must to moved to the right until the left-edge meets the right edge of 0:

| After iteration 1 |
| :---: |
| ![labels-2](https://cloud.githubusercontent.com/assets/4383/18367563/aef3f4d8-7613-11e6-8819-291cc2228e45.jpg) |

Then we take the next pair: Label 1 and label 2. Those labels overlap, so label 2 must be moved:

| After iteration 2 |
| :---: |
| ![labels-3](https://cloud.githubusercontent.com/assets/4383/18367604/e4ac32ac-7613-11e6-8fa8-f23072b378d6.jpg) |

... and so on, until we run out of labels.

Since this doesn't fix labels which are pressed against the right-side of the chart, [repeat the process in reverse](https://github.com/quintel/etmodel/commit/931572cdc6b17d74a0a9430eb1222b5802d7738d#diff-c59853f8baef1bb9db0f09a81ffeb30aR273):

| Starting situation (reverse, right-to-left) |
| :---: |
| ![labels-rev-1](https://cloud.githubusercontent.com/assets/4383/18367773/9cc04478-7614-11e6-910b-d8c0b3c63f96.jpg) |

| After iteration 1 (reverse, right-to-left) |
| :---: |
| ![labels-rev-2](https://cloud.githubusercontent.com/assets/4383/18367776/a0538f3c-7614-11e6-9d27-93f328935173.jpg) |

![screen shot 2016-09-08 at 22 44 34](https://cloud.githubusercontent.com/assets/4383/18368054/dbbd7b22-7615-11e6-87ae-01bc90b5da2a.png)

**Comment by grdw** [comment]
Thanks. I don't know how to do any of that to begin with :') I did it with drawing two labels on a really large white board. I did finally got the theory in my head but didn't know any code to write that would solve it. Also considering the edges of the screen, etc.

> With the animation enabled, fetching the position of each label with getBoundingClientRect would return the wrong values:

This cost me so much damn time... I was really frustrated that the x and y for every label were the same everytime but now it makes sense why 😃

**Comment by grdw** [comment]
<img width="605" alt="screen shot 2016-09-09 at 11 14 45" src="https://cloud.githubusercontent.com/assets/2676542/18381855/a37ca3e6-767e-11e6-8134-b90897896f95.png">

I edited the lines back in :)

**Comment by dennisschoenmakers** [comment]
Great job guys! :+1:

**Comment by ChaelKruip** [comment]
Love it! 👍

**Comment by grdw** [comment]
Closing due to -> https://github.com/quintel/etmodel/pull/2210

**Comment by AlexanderWirtz** [comment]
@grdw and @jorisberkhout I am impressed with how much this has progressed, but the x-labels still overlap with the legend, especially in Dutch. Is this something we have decided not to fix this time, or did I miss something in this lengthy issue.
 
![image](https://cloud.githubusercontent.com/assets/308563/18435130/aff3e5ce-78f1-11e6-8024-376d4bb3263d.png)

**Comment by grdw** [comment]
> Is this something we have decided not to fix this time, or did I miss something in this lengthy issue.

It's someting we decided to fix but sort of returns an error on beta (if you drag one of the sliders). I'll see to it, to fix it.
