### ISSUE TITLE
It should be possible to increase the storage volume of batteries with a slider

### ISSUE THREAD

**Issue by jorisberkhout** [quintel/etmodel#2189]
As indicated by John, the assumption that we use state-of-the-art technology is especially limiting when it comes to battery storage for two reasons:

- the storage volume of batteries is increasing very rapidly in real life
- even if you equip all households with a battery, this is far from enough to deal with the excess electricity in extreme scenario's

John suggested to add a slider that allows the user to increase the storage volume (the `kWh`) of the batteries by up to 10 times the current storage volume. This is technically not very difficult to do, but is in a way a departure from the way we normally model technologies, so I would like to hear what you think about adding these sliders, @AlexanderWirtz , @ChaelKruip .

This applies to:

- [ ] household batteries
- [ ] batteries in electric vehicles

**Comment by jorisberkhout** [comment]
As discussed with John and @ChaelKruip , we do will not add this slider as it will have too much technical fall-out. Instead, we will change the storage volumes of these technologies to real state of the art, i.e.
- [ ] `100 kWh` for EV
- [ ] `50 kWh` for household batteries

Assigning @DorinevanderVlies to research the parameters of these technologies in more detail.

**Comment by DorinevanderVlies** [comment]
After some research on EV's I propose the following:

## Background
### Current EV's
The current weighed average of EV's in The Netherlands is 50 kWh.
Tesla Model S has a maximum battery storage volume of 100 kWh.

### Future EV's
Tesla Model 3 and Chevrolet Bolt will both have a battery capacity of 60 kWh.
This corresponds to a reach of roughly 300 km.

## Proposal
Set the battery storage volume of EV's in ETM to 60 kWh.
This seems to be the default volume for mainstream EV's of the (near) future. 
Battery price will decrease, but I assume this will lead to lower costs instead of higher volume.

There will of course be high level cars with higher battery volume, but I think there will also be city cars with a smaller battery.

@RobTerwel and @AlexanderWirtz I am curious about your opinion on this.

**Comment by RobTerwel** [comment]
If the Tesla S has a max. storage volume of 100 kWh and there is no commercial alternative with a higher storage volume, I think the state-of-the-art capacity should be 100 kWh, as @jorisberkhout initially suggested. 

Generally speaking, the ETM uses state-of-the-art technology; that means there will be outliers, granted. The driving range of an electric car, however, is generally considered a salient feature by consumers. Since it is relatively hard to further increase the efficiency of an electric car (they are very efficient already), and there is more progress to be expected in battery size development, it is safe to assume car manufacturers will work on increasing the battery size to meet the consumers' demands. So both for consistency and for this development, I would opt for a battery storage volume of 100 kWh.

**Comment by DorinevanderVlies** [comment]
After discussions with @jorisberkhout, @RobTerwel and John the following changes have been applied:

### Storage volume EV's
This is set to `100 kWh`. Following the storage volume of the newly release Tesla Model S P100D.
Commit: https://github.com/quintel/etsource/commit/526e1960f599b5409147be8352b77722b425c5ce


### Storage volume household batteries
This has been set to `20 kWh` (from `9.6 kWh`) to enable more electricity storage in batteries. 
Commit: https://github.com/quintel/etsource/commit/be790979f47995a04bf3054544b68b7b9fb648c8

Note:
20 kWh is a large battery as the average electricity consumption of a household is `10 kWh`. Implementing a bigger battery will be unrealistic. If more battery storage has to be implemented I propose to create a new attribute/converter for commercial batteries. Once that attribute/converter has been created I think it would be good to reset the household battery to the more realistic storage volume of `9.6 kWh`.

**Comment by jorisberkhout** [comment]
Closed by https://github.com/quintel/etsource/commit/be790979f47995a04bf3054544b68b7b9fb648c8 and https://github.com/quintel/etsource/commit/526e1960f599b5409147be8352b77722b425c5ce.
