### ISSUE TITLE
Using hydrogen from power to gas in transport sector results in strange dashboard values

### ISSUE THREAD

**Issue by jorisberkhout** [quintel/etmodel#2205]
As witnessed by John in [this scenario](https://beta-pro.energytransitionmodel.com/scenarios/572361), using hydrogen form power to gas in the transport results in:
- increased bio-footprint
- increased energy import
- decreased renewability percentage

Which are all opposite to what you would expect.

**Comment by DorinevanderVlies** [comment]
I think the following might be happening:

In this scenario all transport technologies (except Domestic navigation technology) are electric.
So, no hydrogen is used in this sector.

> increased energy import


If P2G for transport is used as a flexibility option this results in export of hydrogen. Due to 33.28% losses in this process, in this scenario energetically less Hydrogen is exported than was the case without the P2G conversion.

> increased bio-footprint
> increased energy import
> decreased renewability percentage

P2G for transport is higher in the flexibility order than P2Heat. The hydrogen is exported and the heat that was used before is no longer produced with excess energy. 

### Without P2G
![image](https://cloud.githubusercontent.com/assets/19907658/18311898/3d931ede-7507-11e6-86c4-d5d4c26d9e2e.png)

### With P2G (slider setting 100,000)
![image](https://cloud.githubusercontent.com/assets/19907658/18311917/5ed79af2-7507-11e6-8969-06c0dba074ee.png)
