### ISSUE TITLE
Why is the cost_batteries sidebar item on staging set to always_hidden?

### ISSUE THREAD

**Issue by RobTerwel** [quintel/etmodel#2208]
See title.

Interestingly, investments cost input statements don't exist for flex technologies on <a href="https://github.com/quintel/etsource/tree/master/inputs/costs">ETSource<a/>, while their names do exist on <a href="https://github.com/quintel/etmodel/blob/master/config/locales/en_input_elements.yml#L257-L259">ETModel<a/>. I presume that either these names can be deleted, or these input statements should be added.

Including @jorisberkhout @ChaelKruip @AlexanderWirtz

**Comment by jorisberkhout** [comment]
Well spotted by @RobTerwel . It took us quite some time to implement flexibility in the ETM. In March 2015 we have created sidebar item, slides and sliders, a.o. for the investment costs in flex technologies. Because we did not want the flexibility features to show up before it was completely implemented, we have set everything to `_always_hidden`. Apparently we never implemented the investment cost side of things. I will create a new actionable issue for this. In view of time this has to be picked up after the deploy.
