### ISSUE TITLE
Labels are cut off by legend for Mekko's

### ISSUE THREAD

**Issue by ChaelKruip** [quintel/etmodel#2235]
The label in the Mekko below should read "Export and curtailment":
![energy_transition_model_-_your_free__independent__comprehensive__fact-based_scenario_builder_](https://cloud.githubusercontent.com/assets/1303760/18466992/6cf7c86e-799e-11e6-96fc-dc6b53201900.png)

Can we plot long labels over multiple lines?

**Comment by dennisschoenmakers** [comment]
Another one I just found on beta:

![image](https://cloud.githubusercontent.com/assets/104830/18472414/a87baea0-79b7-11e6-83df-747bef3181c9.png)

**Comment by grdw** [comment]
I already flagged this issue [here](https://github.com/quintel/etmodel/issues/2186#issuecomment-245558279).

The way I would solve this is to turn the labels into `<div>` elements and give them a static width (or height depending on how you look at it). This will cause them to span over multiple lines if the label becomes too long. The downside of this approach is that the labels would need to be manually positioned because a `<div>` element can't live within an `<svg>` element.

**Comment by jorisberkhout** [comment]
> The downside of this approach is that the labels would need to be manually positioned because a `<div>` element can't live within an `<svg>` element.

😕 What does that mean, or what are the implications, @grdw ?

**Comment by grdw** [comment]
Well right now the idea is like this (simpified ofcourse):

````
svg
  chart-block
    label
  chart-block
    label
````

Because the label is part of the chart-block the position is rather easy to determine since it goes along with the position of the chart-block. However, the label's don't know how to span over multiple lines. 

if you switch to the `<div>` approach it goes like this:

````
svg
  chart-block
  chart-block

labels
  label
  label
````

The labels can't no longer live inside the svg element so they have no idea what the positions are.

However, before going to do it the complicated way, I stumbled upon this [magically technical document](https://www.w3.org/TR/SVG2/text.html) which specifies that for SVG2 there should be a possibility to make multiline text-elements. However, I'm not sure we are using the correct SVG version? So I need to check that. It would become rather easy though if we did. I'm also not sure if the versioning is determined by the browser of by D3? I need to figure that out first.

**Comment by grdw** [comment]
> which specifies that for SVG2 there should be a possibility to make multiline

Ok, it seems that there's [no support](https://developer.mozilla.org/en/docs/Web/CSS/inline-size#Browser_compatibility) for `inline-size` yet 😞

**Comment by grdw** [comment]
Allright I found something useful [here](https://bl.ocks.org/mbostock/7555321). I manage to implement it for our own uses and tada:

![screen shot 2016-09-13 at 16 42 36](https://cloud.githubusercontent.com/assets/2676542/18478392/58ace4ba-79d1-11e6-8727-74e3cfd49665.png)

**Comment by grdw** [comment]
There is still one minor tit-bit which I haven't mentioned. Which is that the current implementation leans on the fact that a long label can be split up into multiple 'words' by spitting upon space. So a label like "Households" in @ChaelKruip example won't fix itself automagically.

**Comment by ChaelKruip** [comment]
> There is still one minor tit-bit which I haven't mentioned. Which is that the current implementation leans on the fact that a long label can be split up into multiple 'words' by splitting upon space. So a label like "Households" in @ChaelKruip example won't fix itself automagically.

Could we mode the legend down to make sufficient room for the longest single word (Households, curtailment etc.) in the labels? Can this be done dynamically?

**Comment by dennisschoenmakers** [comment]
> Allright I found something useful here. I manage to implement it for our own uses and tada:

Could you also refer to the commit that implements this technique here please?

**Comment by grdw** [comment]
> Could we mode the legend down to make sufficient room for the longest single word (Households, curtailment etc.) in the labels? Can this be done dynamically?

This sounds a little troubling. That is, if someone makes a really really long one-word label somebody can totally destroy the layout of a mekko chart. For now I increased the label space with 5 extra pixels so the word 'Households' can just fit. Ofcourse this is a little patchy, but I think restraining the labels for becoming to large is actually good. 

We could ofcourse also split upon a certain length of characters instead of spaces but this will cause the question, [where do you split the word in two](http://english.stackexchange.com/questions/385/what-are-the-rules-for-splitting-words-at-the-end-of-a-line)? 

Come to think of it, we could also let the splitting happen in the translations, that is editing the `Yaml` to become:

````yaml
translation_key: > 
  House-
  holds
````

Than when rendering you'd have to split upon newlines (`\n`) and create `<tspan>` elements that way. The downside of this approach is that you'd manually have to check if a label goes over the height.

> Could you also refer to the commit that implements this technique here please?

https://github.com/quintel/etmodel/pull/2242/commits/42cdb359fec52d35b14e9faff8b8777bbecc19c8

**Comment by jorisberkhout** [comment]
John pointed out that this issue still occurs. This is what you need to do to let this happen:
1. Open the `Primary energy use` mekko
2. Zoom in
3. Close the zoom view

The labels will be cut off as before.

Could you look into this, @grdw ?
