### ISSUE TITLE
Four decimal digits is too much for the flexibility table

### ISSUE THREAD

**Issue by ChaelKruip** [quintel/etmodel#2241]
<img width="623" alt="energy_transition_model_-_your_free__independent__comprehensive__fact-based_scenario_builder_" src="https://cloud.githubusercontent.com/assets/1303760/18479106/ff72405e-79d3-11e6-90f6-cb7458827870.png">

I think one would be more than enough... @jorisberkhout do you agree?

**Comment by jorisberkhout** [comment]
The problem is that the number formatting in the table is static. If numbers are small (like for the Energieakkoord 2020 scenario as shown below), you lose information if you restrict the number of decimals to 1 or 2.

The real solution is to make the number formatting in the table more dynamic, which is included in [this overview issue](https://github.com/quintel/etmodel/issues/2015). I suggest to keep 4 decimals for now and solve this issue properly as part of #2015. Re-open if you disagree.

<img width="617" alt="screen shot 2016-09-13 at 17 17 11" src="https://cloud.githubusercontent.com/assets/4669028/18479677/2e3ec8c4-79d6-11e6-886f-fb505479f6f2.png">
