### ISSUE TITLE
It should be possible to not produce any biodiesel

### ISSUE THREAD

**Issue by ChaelKruip** [quintel/etmodel#2250]
Currently, about 60 PJ of biodiesel is alway produced in Dutch scenarios's. If you don't use it, it is exported. Because biodiesel has an (unrealistically see https://github.com/quintel/etdataset/issues/681) large In many cases, this dominates the bio-footprint:
![energy_transition_model_-_your_free__independent__comprehensive__fact-based_scenario_builder_](https://cloud.githubusercontent.com/assets/1303760/18512258/8dd26018-7a88-11e6-84de-fee2d7846a3c.png)

Could we somehow allow the user to phase out biodiesel production? Or should we treat exported energy differently in the bio-footprint calculations (see  https://github.com/quintel/etsource/issues/1094)

**Comment by AlexanderWirtz** [comment]
I think we should re-think the bio-footprint. The biodiesel production is the by-product of necessary crop rotation to re-fertilize soil. So it uses land, but does not compete with food production, in fact it keeps arable land productive.

**Comment by marliekeverweij** [comment]
During the last biomass project we found that 90% of the biodiesel consumed in the Netherlands is produced from waste fats ([NEA](https://www.rijksoverheid.nl/documenten/rapporten/2018/07/03/bijlage-1-rapportage-energie-voor-vervoer-in-nederland-2017)) and waste fats have no biofootprint as biodiesel from waste fats is a second generation biofuel. Therefore, I think that this issue is not relevant anymore.
