### ISSUE TITLE
How to deal with tourism for localities

### ISSUE THREAD

**Issue by dennisschoenmakers** [quintel/etmodel#2265]
Some regions/municipalities have an aim to transition their own local community. But tourism crosses different sectors:
- buildings:
  - touristy: hotels, holiday parts
  - not touristy: public utility, like libraries, municipality buildings
  - partially touristy: shops, restaurants, swimming pools
- transportation

**Comment by ChaelKruip** [comment]
* Buildings: if tourism is important for a scenario, you can capture the effect in the ETM by increasing the relevant demands in the sector such as 'electricity per building' 'heating per building' etc.
On a more detailed level (ETM-SA) you could create profiles that take into account the timing of tourism (as we did for Ameland).
* Transport: the demand would increase in case of tourism as well. 

Perhaps I'm not understanding your question properly @dennisschoenmakers?

**Comment by dennisschoenmakers** [comment]
Good points @ChaelKruip, but what I mean is that the outcome, all the charts, the dashboard etc. has a breakdown which is confusing, or does not align properly, with the mind of a local actor.

**Comment by AlexanderWirtz** [comment]
@dennisschoenmakers I think your point: 

>what I mean is that the outcome, all the charts, the dashboard etc. has a breakdown which is confusing, or does not align properly, with the mind of a local actor.

is valid, but I would create a more high-level issue that discusses how the front end (mostly charts) might address this issue. From a data point of view it is quite hard to know what part of energy consumption tourism represents. [Klimaatmonitor](https://klimaatmonitor.databank.nl/) does list Commercial services >> lodging as a separate category, but this is often empty in my experience and probably just a guestimate based on number of hotel beds. 

Imagine for example the situation of Amsterdam, where anywhere between 5-25% of tourists make use of services like airbnb, which probably do not show up in these statistics. Trying to show such numbers in charts is likely to misinform users rather than help them if you do not have the right numbers.

**Comment by dennisschoenmakers** [comment]
> From a data point of view it is quite hard to know what part of energy consumption tourism represents. 

True, sometimes you need. Perhaps an 'edit your dataset' function where the user or dataset owner can adjust these type of divisions is worth investigating. A local actor usually knows a lot more about the local situation. Of course, this is a bit a 'out of the box' for the ETM for obvious reasons.

**Comment by AlexanderWirtz** [comment]
shall we close this issue?
