### ISSUE TITLE
Step value for solar pv parks is extremely small

### ISSUE THREAD

**Issue by dennisschoenmakers** [quintel/etmodel#2268]
One click on plus increases the amount of solar pv parks from 0.3000 to with 0.3001, and I would like to go to 0.6. 😒 

![image](https://cloud.githubusercontent.com/assets/104830/19035345/4ba99e14-8969-11e6-841d-cc80391ea262.png)

Perhaps a good idea to rethink the slider caps, and steps for scaled scenarios as a whole? 😃

**Comment by antw** [comment]
I made it so that the (-) and (+) buttons move the slider by at least 1% of its value each time they're clicked. You can always click the slider value at set the value manually if you have something specific in mind.

> Perhaps a good idea to rethink the slider caps, and steps for scaled scenarios as a whole? 😃

:+1:

I'm not a fan of the very small numbers we often see for inputs in scaled scenarios, but I'm not sure what the alternative is... New ideas are welcome!

**Comment by ChaelKruip** [comment]
> New ideas are welcome!

Perhaps we can make the step-size relative to the range? So, if a slider ranges from 0 to 2, a step-size of 100 would imply steps of 0.02. This might be more robust to scaled scenario's.
