### ISSUE TITLE
Import does not show up on LIVE after deploy

### ISSUE THREAD

**Issue by ChaelKruip** [quintel/etmodel#2286]
LIVE:
![energy_transition_model_-_your_free__independent__comprehensive__fact-based_scenario_builder_](https://cloud.githubusercontent.com/assets/1303760/19734331/7c2ff8e4-9ba7-11e6-92ab-1b47f40c2105.png)
BETA:
![energy_transition_model_-_your_free__independent__comprehensive__fact-based_scenario_builder_](https://cloud.githubusercontent.com/assets/1303760/19734350/8a8ba10e-9ba7-11e6-87d9-ec29d4c25ceb.png)

**Comment by antw** [comment]
Seems to be true for NL too. Probably all regions.

**`energy_interconnector_imported_electricity`:**

| [Beta](https://beta-engine.energytransitionmodel.com/data/593582/converters/energy_interconnector_imported_electricity) | [Production](https://engine.energytransitionmodel.com/data/304325/converters/energy_interconnector_imported_electricity) |
| --- | --- |
| ![screen shot 2016-10-26 at 17 30 00](https://cloud.githubusercontent.com/assets/4383/19735073/f14bdcca-9ba1-11e6-8ebf-6c73d15a91a3.png) | ![screen shot 2016-10-26 at 17 30 06](https://cloud.githubusercontent.com/assets/4383/19735080/f7432fd4-9ba1-11e6-9220-8a2d70d3c956.png) |

Same ETEngine revision, same ETSource revision; this is confusing. 😕

**Comment by antw** [comment]
I believe this is because production ETEngine is sorting the `energy_power_hv_network_electricity` input links differently. Beta and my local copy show `imported_electricity` before the `hv_network_shortage` link; production has them the other way around.

This is not unexpected, there's no guarantee as to the other in which edges will appear. Since neither edge has a priority, production is assigning energy to the "shortage" link before "import".

I tried assigning priorities but now Refinery is complaining. I'll investigate further...

**Comment by antw** [comment]
This is now fixed. A priority has been assigned to the "interconector" edge to ensure that it gets preference over the "shortage" edge. Refinery (rightly) complained because `priority` requires that you also specify a `max_demand` on the supplier node.

Long story short, you may now use `~ max_demand = infinity` in Node documents in order to circumvent this restriction.

<img width="604" alt="screen shot 2016-10-27 at 11 32 42" src="https://cloud.githubusercontent.com/assets/4383/19764092/1dd52a34-9c39-11e6-9864-2a735bb3560d.png">

**Comment by ChaelKruip** [comment]
@antw do you have any clue why this has not happened before?

**Comment by antw** [comment]
> @antw do you have any clue why this has not happened before?

Luck? I'm not sure really. Without an explicit priority assigned to the edges, I'm guessing it's determined by the order in which Atlas loaded the .ad files. Since Atlas has no opinion about this, it's probably down to the operating or file system.

> Note that case sensitivity depends on your system [...], as does the order in which the results are returned. – [Dir.glob](https://ruby-doc.org/core-2.2.3/Dir.html#method-c-glob)
