### ISSUE TITLE
Spec failing  - scenarios controller compare

### ISSUE THREAD

**Issue by grdw** [quintel/etmodel#2289]
````
  1) ScenariosController a regular user with an active scenario #compare should compare them
     Failure/Error: get :compare, scenario_ids: [s1.id, s2.id]
     ActionView::Template::Error:
       undefined method `[]' for nil:NilClass
     # ./app/views/scenarios/compare.html.haml:60:in `block (6 levels) in _app_views_scenarios_compare_html_haml__3464828545212421607_70105632521580'
     # ./app/views/scenarios/compare.html.haml:60:in `map'
     # ./app/views/scenarios/compare.html.haml:60:in `block (5 levels) in _app_views_scenarios_compare_html_haml__3464828545212421607_70105632521580'
     # ./app/views/scenarios/compare.html.haml:57:in `block (4 levels) in _app_views_scenarios_compare_html_haml__3464828545212421607_70105632521580'
     # ./app/views/scenarios/compare.html.haml:45:in `block (3 levels) in _app_views_scenarios_compare_html_haml__3464828545212421607_70105632521580'
     # ./app/views/scenarios/compare.html.haml:34:in `block (2 levels) in _app_views_scenarios_compare_html_haml__3464828545212421607_70105632521580'
     # ./app/views/scenarios/compare.html.haml:8:in `block in _app_views_scenarios_compare_html_haml__3464828545212421607_70105632521580'
     # ./app/views/scenarios/compare.html.haml:5:in `_app_views_scenarios_compare_html_haml__3464828545212421607_70105632521580'
     # ./spec/controllers/scenarios_controller_spec.rb:95:in `block (5 levels) in <top (required)>'
````

First question. Is comparing even used nowadays? 
Second question: how to properly fix this? Executing ruby code from the Haml is a bit .. ancient 😆

**Comment by antw** [comment]
> how to properly fix this? Executing ruby code from the Haml is a bit .. ancient 

This passes for me. The error suggests that `@default_values` is nil, but when I run the test it looks like: `{}`. `@default_values` is set in the controller:

```ruby
@default_values = @scenarios.first.all_inputs
```

That line doesn't raise an error, so try to figure out why it returns nil instead of an empty hash.

I guess that `@scenarios` will be returning an array of scenarios, `first` gives you just one, and that both of those are working correctly since neither complains about a Nil object. Normally I would say this means that [`Api::Scenario#all_inputs`](https://github.com/quintel/etmodel/blob/83f153f34bca1fa40ac2c3e8a10483b3df60a3b6/app/models/api/scenario.rb#L95-L98) is returning nil for some reason, but apparently this test doesn't use a real scenario object [and instead uses a mock](https://github.com/quintel/etmodel/blob/83f153f34bca1fa40ac2c3e8a10483b3df60a3b6/spec/support/mocks/ete_scenario.rb#L9).

On the one hand, that's not great since it means code like `all_inputs` isn't getting tested (and because it ordinarily returns `{}` most of the comparison page is also not tested); on the other hand, it's very strange that it would be returning `nil` for you since the mock is quite clear about the return value.

**Comment by grdw** [comment]
I checked out `master` again and synchronized with the recent changes. Now the error has become:

````
  1) ScenariosController a regular user with an active scenario #compare should compare them
     Failure/Error: get :compare, scenario_ids: [s1.id, s2.id]
       Double "api_scenario" received unexpected message :user_values with (no args)
     # ./app/views/scenarios/compare.html.haml:60:in `block (6 levels) in _app_views_scenarios_compare_html_haml___1981896799128774232_70164278114380'
     # ./app/views/scenarios/compare.html.haml:60:in `map'
     # ./app/views/scenarios/compare.html.haml:60:in `block (5 levels) in _app_views_scenarios_compare_html_haml___1981896799128774232_70164278114380'
     # ./app/views/scenarios/compare.html.haml:57:in `block (4 levels) in _app_views_scenarios_compare_html_haml___1981896799128774232_70164278114380'
     # ./app/views/scenarios/compare.html.haml:45:in `block (3 levels) in _app_views_scenarios_compare_html_haml___1981896799128774232_70164278114380'
     # ./app/views/scenarios/compare.html.haml:34:in `block (2 levels) in _app_views_scenarios_compare_html_haml___1981896799128774232_70164278114380'
     # ./app/views/scenarios/compare.html.haml:8:in `block in _app_views_scenarios_compare_html_haml___1981896799128774232_70164278114380'
     # ./app/views/scenarios/compare.html.haml:5:in `_app_views_scenarios_compare_html_haml___1981896799128774232_70164278114380'
     # ./spec/controllers/scenarios_controller_spec.rb:94:in `block (5 levels) in <top (required)>'
````

It's weird, because in my previous example I decided to mock `user_values` for this spec but than I got the previous error. Hmm. 🤔 It's also weird that you don't seem to have this problem but I do.

**Comment by grdw** [comment]
Closing, not relevant anymore
