### ISSUE TITLE
THOUGHT: Scaling of scenario from the user's perspective

### ISSUE THREAD

**Issue by dennisschoenmakers** [quintel/etmodel#2301]
With regards to the local datasets: in this stage, I think It's worthwhile thinking about an approach that starts from the (current) user's perspective. 

What if the user can input all the necessary data to set the present for a local dataset through the [user's interface](https://pro.energytransitionmodel.com/scaled)?

### Prefiled database
Since this is all based on real Dutch provinces, municipalities, neighbourhoods etc, we can fill a database with region information. (e.g. in the neighbourhood of Paddepoel there are 504 households). This will help the user enormously and radiates confidence.

### Steps for the user to complete in [user's interface](https://pro.energytransitionmodel.com/scaled)?

Just my first thoughts:

1. What do you want to model? -> Select [provincie, gemeente, wijk, buurt, custom]
2. User selects e.g. 'buurt'
2. (Unless custom): which buurt do you like to model?
3. User fills in e.g. 'Paddepoel'
4. And all the inputs are pre-filled.
   * some of them will be taken from the database (e.g. number of households, number of cars per household)
   * some of them will be taken from the Dutch average (e.g. technology share)
5. User can adjust inputs

### Setting present technology mixes though etmodel's GUI?

I think one of the challenges is the technology mix: it is a group of sliders. Perhaps the current GUI can be of help, in a way that @antw [**suggested already before**](https://github.com/quintel/etmodel/issues/2099#issuecomment-215413480). 

### Disadvantages

* No version control for obvious reasons
* This still does not deal with the fact that local scenarios should not be based relatively on the dutch dataset and does not exclude input statements per se.

cc @DorinevanderVlies @antw @jorisberkhout @AlexanderWirtz

**Comment by grdw** [comment]
We're currently documenting our ideas and thought in [here](https://github.com/quintel/internal/tree/local-datasets/planning/projects/local-datasets). This idea hasn't occurred to us.

> What if the user can input all the necessary data to set the present for a local dataset through the user's interface?

I'm currently thinking that that's not where you want the user to do this in all honesty. I already proposed an idea in the documentation to create a completely seperate application which can take numbers [? vague statement alert] and output an ETsource dataset (a bit like a user-friendly ETdataset?). Ofcourse this is an ambitious time-consuming project I can imagine. But it might be worth doing though, although I'm not sure what it will look like because I have not enough knowledge yet about the current way a dataset is created.

**Comment by ploh** [comment]
1. A _prefilled database_ would definitely be nice, but it is probably more of a second version than an initial version. So I suggest we should keep it in mind but design something now that also works without it.
2. For whom are we designing this? For our own research about provinces, municipalities etc in order to generate etm data for them analogous to national data? Or for users to easily scale down and adjust a national dataset to their local circumstances?
For the former we probably need to have version control and do not need the GUI. For the latter a GUI is almost a necessity... but version control is also still nice - at least some change tracking when the user modifies his local scenario.
