### ISSUE TITLE
How can the ETM better quantify energy neutrality?

### ISSUE THREAD

**Issue by ChaelKruip** [quintel/etmodel#2332]
What are the current questions from our clients and local initiatives which we cannot answer easily with the ETM?

**Comment by dennisschoenmakers** [comment]
Good question. The ambition that many have to be 'energy neutral' is also broader then the scope of the ETM, think in products that we buy, the food that we import. Sometimes people just say 'energy neutral' without having thought it through. I actually think the term is so vague that we really should not adopt it ourselves. :grin:

**Comment by DorinevanderVlies** [comment]
"Climate neutrality" is also used (by us and others). I think the same considerations @dennisschoenmakers mentions regarding "energy neutrality" apply to this term.

However, I do understand the desire to have a name for a goal. 
imo, the terms can be used, as long as is is always made clear how it is defined in that particular case. 

Due to the vagueness of the terms I'm not a huge fan of quantifying them in the ETM. To do this we would have to take a stand in how we define the terms.
