### ISSUE TITLE
Menu for local datasets

### ISSUE THREAD

**Issue by BerendSmits** [quintel/etmodel#2352]
The collection of local datasets is growing nicely, there are four now. They are all still listed as countries, if the list continues to grow this might start looking a bit messy. 
Can we create a nicer looking menu for local datasets, perhaps also at different levels (province-municipality-neighbourhood or something)?

**Comment by grdw** [comment]
> Can we create a nicer looking menu for local datasets, perhaps also at different levels (province-municipality-neighbourhood or something)?

Yes we can. I would want a google maps map to be used as a menu. Where you can zoom and hover over certain regions - click a region and than create a scenario. A select box with a name of a region is a bit to basic and can get quiet messy.

Obviously my 'google maps menu' is going to  be a project worth a good 4-5 days (especially drawing the svg points for the regions). Simply adding categories is going to be more easy and less time consuming but still feels a bit like a patchy solution interface wise (for instance what if you have > 100 regions for each category, how are you going to categorize that?)

Maybe @dennisschoenmakers or @antw have an opinion about this matter

**Comment by antw** [comment]
@dennisschoenmakers has already created some early mock-ups of his ideas. Given that this is quite an important page I think we should explore as many options as possible.

A maps-based approach has some merit provided it's also paired with a search field or list of available datasets. However I think we'll need very good coverage before it makes sense to do so, otherwise most of the map will be empty.

**Comment by BerendSmits** [comment]
Fixed by https://github.com/quintel/etmodel/pull/2427
