### ISSUE TITLE
Number formatting in scenario report should be improved

### ISSUE THREAD

**Issue by ChaelKruip** [quintel/etmodel#2355]
A couple of things:

* If a value returns "0.0" it is not rendered:
![energietransitiemodel_-_je_eigen_onafhankelijke__volledige_en_op_feiten_gebaseerde_energiescenario_](https://cloud.githubusercontent.com/assets/1303760/23792342/d5d7583a-0586-11e7-96df-005eb6b62a7b.png)

* It would be great if rounding could be done in the text. For example:
```
Your scenario spans future(scenario_duration).round(1) years.
```

**Comment by antw** [comment]
This is related to the Rails 5 upgrade (or rather: a JS library which was updated at the same time) since [it also affects formatting in charts](https://trello.com/c/IDuuZGpK/15-improve-chart-formatting).

> It would be great if rounding could be done in the text

Thanks for the suggestion; [tracking that here](https://trello.com/c/GvQ0CKTu/17-custom-formatting-for-numbers).
