### ISSUE TITLE
Net import chart does not take exported oil products into account

### ISSUE THREAD

**Issue by ChaelKruip** [quintel/etmodel#2362]
The [query for oil](https://github.com/quintel/etsource/blob/master/gqueries/output_elements/output_series/waterfall_76_future_energy_imports/oil_in_future_energy_imports.gql) in the import chart only considers crude_oil. With the refinery remodelling, oil products can be exported by the ETM. I think the chart should take these energy flows into account.

@AlexanderWirtz @jorisberkhout (@robterwel) what do you think?

![energy_transition_model_-_your_free__independent__comprehensive__fact-based_scenario_builder_](https://cloud.githubusercontent.com/assets/1303760/24194485/94ccdf6c-0ef6-11e7-949a-5c56cf1583d8.png)

**Comment by RobTerwel** [comment]
> what do you think?

This possible `oil_products` excess should probably be visualised indeed. 

The reason behind the existence of this carrier is that most refineries burn the lightest fractions of their output to supply heat to their own processes. This would create a loop in the ETM, so in the current modelling the `crude_oil` carrier, rather than the `oil_products` carrier, feeds into the oil burner. We could therefore consider the `oil_products` to be `crude_oil` insofar as part of the burner `crude_oil` was actually `oil_products`, if you see what I mean. 😄

**Comment by ChaelKruip** [comment]
> The reason behind the existence of this carrier

Thanks for this @robterwel. I was actually referring to all products of the refinery, however like diesel, gasoline etc. These carriers could not be exported previously as their production was driven by national demand only. Now that has changed and I think they should be incorporated in the oil column or in a new 'oil derivatives' column. 

@alexanderwirtz @jorisberkhout what do you think?

**Comment by ChaelKruip** [comment]
A separate column would look like this:
![energy_transition_model_-_your_free__independent__comprehensive__fact-based_scenario_builder_](https://cloud.githubusercontent.com/assets/1303760/24451936/3aaaf074-1481-11e7-8288-ec98d78cebfb.png)

**Comment by ChaelKruip** [comment]
Closing this as it has been fixed.
