### ISSUE TITLE
Query for the profitability percentage of power plants

### ISSUE THREAD

**Issue by ChaelKruip** [quintel/etmodel#2369]
The dashboard query [https://github.com/quintel/etsource/blob/master/gqueries/output_elements/dashboard/dashboard_profitability.gql](https://github.com/quintel/etsource/blob/master/gqueries/output_elements/dashboard/dashboard_profitability.gql) returns a whole array of things and I don't know how to extract the percentage TBH.

**Comment by antw** [comment]
I'm not sure why we have that complex query for the dashboard. It is also used to build the merit order table, but the dashboard doesn't need all the converter data so it's a bit wasteful for ETE to send it. I think we should plan to rename it to something like "merit_order_table", and add a new `dashboard_profitability` with a simple numerical result.

Since that doesn't help you *right now*, here is the numerical query which will provide the profitability:

```ruby
mo_converters = GROUP(merit_order_converters_for_dashboard);
profitable = FILTER(mo_converters, "profitability == :profitable");

PRODUCT(
  DIVIDE(
    SUM(V(profitable, "installed_production_capacity_in_mw_electricity")),
    SUM(V(mo_converters, "installed_production_capacity_in_mw_electricity"))
  ),
  100
)
```

**Comment by ChaelKruip** [comment]
Thanks!
