### ISSUE TITLE
Optionally hide legend of charts in scenario report

### ISSUE THREAD

**Issue by ChaelKruip** [quintel/etmodel#2372]
Sometimes, the legend is not very useful (as you can see all info with mouse-over).
A case in point:
![energy_transition_model_-_your_free__independent__comprehensive__fact-based_scenario_builder_](https://cloud.githubusercontent.com/assets/1303760/24741682/4e08bc4c-1aa7-11e7-9433-e52c51616609.png)

**Comment by ChaelKruip** [comment]
Thinking about the possible implications: in a PDF version we should either
* Always show the legend (poor man's solution)
* Make mouse-over possible in the PDF ([I think this should be possible but not sure](http://khkonsulting.com/2014/07/floating-text-pdf-documents/))

**Comment by antw** [comment]
You can now do this like so:

```diff
- {% chart 57 %}
+ {% chart 57 | legend: false %}
```

> Make mouse-over possible in the PDF (I think this should be possible but not sure)

I rather doubt tooltips will be possible in PDFs since the converter is simply reading the HTML version and producing a PDF representation with the print stylesheet. The more advanced features of Adobe Acrobat (which require you to hand-make each document) aren't available to us. It's my opinion that the "interactive" version of the report should be on our website and that the PDF version should be printable (which it isn't if there are no legends).

We should add the ability to get a permanent link to the report; a visitor can send that to their friends or colleagues who want the interactive version. We could also add the link to the print version.

**Comment by ChaelKruip** [comment]
> We should add the ability to get a permanent link to the report; a visitor can send that to their friends or colleagues who want the interactive version. We could also add the link to the print version.

Great idea!
