### ISSUE TITLE
m2 should become km2 for biofootprint charts

### ISSUE THREAD

**Issue by ChaelKruip** [quintel/etmodel#2375]
Can you show me how to accomplish this @antw ?

**Comment by antw** [comment]
In a default scenario, I can't see this happening. Were you using a massively scaled-down scenario by any chance?

In its default state, [the chart shows values in Mm<sup>2</sup>](https://cloud.githubusercontent.com/assets/4383/24805521/ff2b7ffc-1ba9-11e7-9d8a-eb7a050f21e2.png) and it's not possible to disable auto-scaling of units on a chart-by-chart basis. What we can do, however, is prevent scaling of km<sup>2</sup> values, so that these values *always* show as km<sup>2</sup>. That seems a sensible thing to do; what do you think?

**Comment by ChaelKruip** [comment]
> That seems a sensible thing to do; what do you think?

Perfect!

**Comment by antw** [comment]
I have prevented the scaling of m<sup>2</sup> any higher than km<sup>2</sup> (so full-size scenarios will now use km<sup>2</sup> instead of Mm<sup>2</sup>) but scaling down to m<sup>2</sup> is (for now) still permitted.

Forcing it to use km<sup>2</sup> currently results in useless values in tooltips; for example "0 km<sup>2</sup>" instead of "40 m<sup>2</sup>". An NL region has to be scaled down to 700 households for the biofootprint chart to switch to m<sup>2</sup>, so the impact is pretty low. I do still think there's room for improvement in both the chart and the table view (which shows too *many* decimal places).
