### ISSUE TITLE
The chart "hydrogen production for transport" should not respond to adding power to gas for industry

### ISSUE THREAD

**Issue by DorinevanderVlies** [quintel/etmodel#2402]
Right now, adding power to gas for industry influences the "Hydrogen production for transport" chart.

The [p2g_in_hydrogen_production gquery](https://github.com/quintel/etsource/blob/master/gqueries/output_elements/output_series/vertical_stacked_bar_169_hydrogen_production/p2g_in_hydrogen_production.gql
) seems to include all P2G conversion, not just P2G for transport.

I think we should either change the queries to just include P2G for transport, or change the slide (text, chart, etc), to P2G general.

This image shows a scenario with no P2G for transport, but with some P2G for industry.
![image](https://cloud.githubusercontent.com/assets/19907658/26349264/856cd39e-3faf-11e7-98bd-791c908ea730.png)

Including @ChaelKruip and @jorisberkhout

**Comment by ChaelKruip** [comment]
> I think we should either change the queries to just include P2G for transport,

Sounds like the way to go!

**Comment by ChaelKruip** [comment]
I just found out that all queries for this chart are actually more general then transportation. Perhaps we should think a bit more about what we actually want to show.

**Comment by DorinevanderVlies** [comment]
Reconsidering I think that this chart originates from the time that in thet ETM hydrogen was just used for transport.

I think there are two things "wrong" with the queries in combination with the current chart title
1. The chart name is "Hydrogen production for **transport**", but the queries consider all hydrogen production
2. The chart name is "Hydrogen "**production** for transport", but the [P2G in hydrogen production.gql](https://github.com/quintel/etsource/blob/master/gqueries/output_elements/output_series/vertical_stacked_bar_169_hydrogen_production/p2g_in_hydrogen_production.gql) extracts export. So it doesn't show production, but production minus export. Currently excess production results in large 
3. P2G is not part or the queries

2 in combination with 3 results in negative Power-to-gas in the chart when a scenario has excess P2G for industry

My proposal:
- Change the chart title to "Hydrogen production"
- Remove the subtraction of hydrogen export from [P2G in hydrogen production.gql](https://github.com/quintel/etsource/blob/master/gqueries/output_elements/output_series/vertical_stacked_bar_169_hydrogen_production/p2g_in_hydrogen_production.gql)
This way the chart would correspond better to for example the chart showing electricity production in which production is shown and export and curtailment is not subtracted for example from wind.
- Add P2G for industry to P2G for hydrogen production.gql

, so change the query to
`query = DIVIDE((V(energy_flexibility_p2g_electricity,output_of_hydrogen) + V(industry_flexibility_p2g_electricity,output_of_hydrogen)),BILLIONS)`.

**Comment by jorisberkhout** [comment]
Assigning myself as well and adding deploy milestone. I am going to work on related issues (quintel/etmodel#2397, quintel/etmodel#2354, quintel/etmodel#2272 and quintel/etmodel#2257) tomorrow morning and will look into this one as well.

**Comment by jorisberkhout** [comment]
Moved to October deploy.

**Comment by MichielDenHaan** [comment]
We decided to changed the graph such that hydrogen production for transport is shown, rather than all hydrogen production (see: https://github.com/quintel/etsource/pull/1399). The rationale behind this is that the chart is shown on the H2O for transport slide, so the chart now (only) shows how this H2O for transport is produced (p2g, methane reforming, methane reforming ccs, local electrolyses). Ive added a demand bar to show when p2g production exceeds hydrogen for transport demand. I will create a similar graph for hydrogen production for the fertiliser industry.

As @ChaelKruip noted, the queries are more general than transportation (hydrogen production happens in the energy sector) but so far the hydrogen produced there is only used for transport (or export). If this were to change in the future, the queries of this chart have to be updated.
