### ISSUE TITLE
Rename '#<scenario-id>' to 'Link to scenario' or something a little less technical

### ISSUE THREAD

**Issue by grdw** [quintel/etmodel#2433]
![screen shot 2017-07-11 at 09 41 14](https://user-images.githubusercontent.com/2676542/28056391-1aee7eb6-661d-11e7-8da8-79ef7149f89a.png)

The id in the header looks odd to me. It's something that doesn't really 'add that much' to the report. The link to the scenario does however! Maybe the link could be renamed from '#543543' (or any random id) to 'Link to scenario'?

**Comment by antw** [comment]
The intention was for it to be a full link to the scenario (not just the ID) and visible only in the print version. There was also going to be a "Share" option in the header to get a perma-link to the scenario and report. Dropped that due to time. 😞 

Perhaps we might add a short "Share this scenario" section underneath "At a glance..."?

**Comment by ChaelKruip** [comment]
I think we can pick this up as part of a bigger improvement project. I have all kinds of ideas how take the report even further on the coolness scale 😄
