### ISSUE TITLE
If the threshold COP for hot water HHPs is set to max, all water should be made with gas

### ISSUE THREAD

**Issue by ChaelKruip** [quintel/etmodel#2456]
Default NL scenario with 100% HHPs for hot water and threshold-COP = 6.0:

<img width="1091" alt="cursor_and_energy_transition_model_-_your_free__independent__comprehensive__fact-based_scenario_builder_" src="https://user-images.githubusercontent.com/1303760/29703585-7059877a-8976-11e7-9643-3e420928dbdf.png">

**Comment by ChaelKruip** [comment]
Adding a large buffer seems to solve some of the deficit but not all of it:
<img width="1101" alt="cursor_and_energy_transition_model_-_your_free__independent__comprehensive__fact-based_scenario_builder_" src="https://user-images.githubusercontent.com/1303760/29703801-76c445b8-8977-11e7-97fd-b5a2e75e9ad1.png">

**Comment by ChaelKruip** [comment]
Notifying @DorinevanderVlies

**Comment by DorinevanderVlies** [comment]
After this merge (which made the gas part bigger) the same issue is present for space heating

![image](https://user-images.githubusercontent.com/19907658/29706419-17c6b054-8982-11e7-888e-c41b213a980b.png)

![image](https://user-images.githubusercontent.com/19907658/29706337-dedda6bc-8981-11e7-92cf-842a60d9deb2.png)

**Comment by ChaelKruip** [comment]
> After this merge (quintel/etsource#1319), which made the gas part bigger, the same issue is present for space heating

This confuses me as well! Perhaps a valuable clue though...

**Comment by antw** [comment]
A quick fix is on its way to beta.

**Comment by antw** [comment]
The fix is published. Gas demand is now set correctly. 😊 

The culprit was that I avoid changing any of the node demands after running the heat simulation if the demands if there is no deficit; it's a nice easy win to gain a little extra performance.

Unfortunately this is the wrong thing to do for the HHP, because while the demands may not have changed, the share of electricity and gas may have; this issue didn't affect normal heat pumps since they only have one component the electrical part).

I will fine tune this today, but the fix published should have the desired effect:

**HHP, COP cutoff = 6.0**

<img width="609" alt="screen shot 2017-08-25 at 10 05 31" src="https://user-images.githubusercontent.com/4383/29707395-feb5c938-897c-11e7-8847-57e5d3a0b156.png">

<img width="609" alt="screen shot 2017-08-25 at 10 06 24" src="https://user-images.githubusercontent.com/4383/29707418-14d51eda-897d-11e7-8635-f42d861ea364.png">

**Comment by DorinevanderVlies** [comment]
Looks a lot better now!

Threshold COP =1 and =6 show what I expect to happen.

However, some COP values which are in between (around COP = 2.5) show a large increase in ambient heat which I don't understand.

![image](https://user-images.githubusercontent.com/19907658/29708796-51e8721a-898a-11e7-8713-b01cb790cdbb.png)

**Comment by antw** [comment]
Hopefully fixed in quintel/etengine@fb00b155 (already on beta). The ambient heat wasn't increasing: it was a *negative*, which the chart cannot display correctly.

This was because hours when the electric component had a capacity of zero (because of the CoP cutoff) were being treated as if the CoP was 0.0. This made a mess when calculating the electric component annual efficiency.

In the clean-up phase I think I will revisit buffering – because it's a bit too easy to make mistakes like this – and move some of these calculations out of ETEngine and into Fever where they'll be easier to test.

**100% water heating HHPs, CoP cutoff = 2.5**

![screen shot 2017-08-25 at 14 05 28](https://user-images.githubusercontent.com/4383/29715296-a3019a8c-899e-11e7-998e-21a473323ece.png)

**Comment by ChaelKruip** [comment]
> Hopefully fixed in quintel/etengine@fb00b15 (already on beta).

🎉

**Comment by DorinevanderVlies** [comment]
nice fix!
