### ISSUE TITLE
The Percentage of Energy use dashboard is not correct

### ISSUE THREAD

**Issue by karimelbana** [quintel/etmodel#2486]
The Percentage of Energy use dashboard is not the resultant percentage of dividing the total primary energy use in the future by its counterpart in the present in both beta and pro versions

For the pro version as shown below

![screen shot 2017-09-12 at 2 59 03 pm](https://user-images.githubusercontent.com/29379411/30327055-f4e29772-97ca-11e7-83f3-3a82ba4855a1.png)

(3.32961/3.36326) is -1.001% not -1.4%

Also for the beta version as shown below

![screen shot 2017-09-12 at 3 02 14 pm](https://user-images.githubusercontent.com/29379411/30327237-9b42ec02-97cb-11e7-8429-f867a79c6f2c.png)

(3.33002/3.36326) is -0.99% not -1.4%

**Comment by ChaelKruip** [comment]
It turns out that the table uses the `primary_demand_caused_by_final_demand` query is used for the table/chart but the `dashboard_energy_demand_primary_of_final_plus_export_losses` is used for the dashboard item.

We now have the choice to do one of the following:
1. use `dashboard_energy_demand_primary_of_final_plus_export_losses` in the table as well (possibly showing losses separately)
2. use `primary_demand_caused_by_final_demand` for the dashboard item (but this will ignore losses due to exported energy)

1. has my preference. @AlexanderWirtz @jorisberkhout @DorinevanderVlies @BerendSmits what do you think?

**Comment by AlexanderWirtz** [comment]
Agree that option 1 is best!

**Comment by DorinevanderVlies** [comment]
> Option 1. has my preference.

I agree

**Comment by BerendSmits** [comment]
Jess option 1
