### ISSUE TITLE
Add (optional) line for 2013 load to dynamic demand curve

### ISSUE THREAD

**Issue by DorinevanderVlies** [quintel/etmodel#2494]
During the wrap-up meeting for dynamic demand curves we got the idea to add the 2013 demand to the demand curve as well. This way it is easier for the user to interpret the impact of the changes of the demand chart.

The idea is to add a (dashed) line representing the total demand for 2013.

If possible it would be nice if the line is optional (can be switched on and of), but that is definitely not a must-have.

**Comment by DorinevanderVlies** [comment]
notifying @ChaelKruip and @antw

**Comment by antw** [comment]
I don't think this information is currently available in ETEngine, since it retrieves this data from Fever (which is not available for the `present` graph). I'll add myself to the assignees since I'll have to investigate how to create and make available the present heat demand before anything can be done with the chart.
