### ISSUE TITLE
Add interpretation of heat pumps to scenario report

### ISSUE THREAD

**Issue by DorinevanderVlies** [quintel/etmodel#2495]
A warning should be added to the scenario report if a user implements a significant amount of heat pumps (air or ground) without insulating.

@antw I'll try to implement this myself, but might need some help with the statements
notifying @ChaelKruip

**Comment by DorinevanderVlies** [comment]
I added two queries (https://github.com/quintel/etsource/commit/65d4e7f6dc9c2edec5680e6e4dc2e5712af63e9e) and a section to the scenario report (https://github.com/quintel/etmodel/commit/62408ea01a6e7e72c94b284c63d56a64d6e61fcc).

However some parts of the code are still incomplete. @antw can you have a look at that? Let me know if anything is unclear!

**Comment by DorinevanderVlies** [comment]
@antw i think it would be nice to implement this addition to the scenario report before the deploy. Do you have time to take a look at this this week?

**Comment by antw** [comment]
> Do you have time to take a look at this this week?

Yes. Would you like some pointers for what needs to be done, or would you prefer I just take care of it?

**Comment by DorinevanderVlies** [comment]
> Yes. Would you like some pointers for what needs to be done, or would you prefer I just take care of it?

Perhaps if you take care of the English text I can take care of the Dutch text and will in the process learn how to do this.

Again, if it's unclear, let me know!

**Comment by antw** [comment]
I hit a minor snag with this, in that the "increase in insulation" query had something like this:

```ruby
QUERY_DELTA(-> { INPUT_VALUE(...) })
```

... but the input value is the same in the `present` and `future` because it literally just returns whatever value the user has set, so `QUERY_DELTA` would always return 0.0 (`0.5-  0.5 = 0.0`, `3.0 - 3.0 = 0.0`).  I've worked around this for now by [assuming that the start values are the same as the minimum insulation values](https://github.com/quintel/etsource/commit/1ce882c70d4e2b7799ee8579b82663618147c36a#diff-448a7972966a5b1183dbd0aa48812e27) (which is true today, but might not always be).

* ETSource: https://github.com/quintel/etsource/pull/1390
* ETModel: https://github.com/quintel/etmodel/pull/2515

**Comment by DorinevanderVlies** [comment]
@antw thanks!
