### ISSUE TITLE
Drenthe has hot water final demand change in blank scenario

### ISSUE THREAD

**Issue by BerendSmits** [quintel/etmodel#2501]
When you open a blank Drenthe scenario, the hot water final demand graph shows the following change: 

![screen shot 2017-10-05 at 15 39 33](https://user-images.githubusercontent.com/24872776/31230144-6c6cb226-a9e3-11e7-88cf-97495b4b6966.png)

There is a difference between the start and end year, which seems odd. When you disable merit, the change disappears. I could imagine this having something to day with our new p2h in households, but I'm not sure..

**Comment by BerendSmits** [comment]
@AlexanderWirtz  says this goes for all local datasets..

**Comment by AlexanderWirtz** [comment]
I tested it for Friesland, Groningen and Noorderplantsoen

**Comment by DorinevanderVlies** [comment]
I've had a quick look. Some findings:

- When merit is turned off: 2013 = 2050.
- I think the outcome with merit turned on is correct. Changing the shares results in realistic final demand. 
- I think the outcome with merit turned off is incorrect. It seems that any technology that is not a combi-boiler has far too small final demand (only exception is the gas water heater).

All country datasets are fine.

> I could imagine this having something to day with our new p2h in households
I don't think so. We did check local scenario's since than. I that case I would assume that the same happens for local and country datasets

The main change I can think of is that this week both initializer methods and initializer inputs are enabled for local scenario's.

@grdw could this have to do with enabling both initializer methods and initializer inputs?
@antw does this ring a bell?

**Comment by antw** [comment]
> The main change I can think of is that this week both initializer methods and initializer inputs are enabled for local scenario's. [...] could this have to do with enabling both initializer methods and initializer inputs?

Nope; that is not merged yet.

I'm not sure why this would only affect local datasets; I'll take a look.

**Comment by AlexanderWirtz** [comment]
We found this issue because I wanted to do some quick work for local Drenthe scenarios. The eternal issue of us using beta instead of live for actual client work. 

I everyone is very busy. I wonder if you could let me know what you think is required to fix this and how long it would take, so I can let Drenthe know when to expect my output

**Comment by antw** [comment]
> let me know what you think is required to fix this and how long it would take, so I can let Drenthe know when to expect my output

I'm reasonably certain I know what is causing this; if I'm right it will be fixed within the hour.

**Comment by DorinevanderVlies** [comment]
![image](https://user-images.githubusercontent.com/19907658/31234881-58d8bad6-a9f0-11e7-8566-cceb435e446d.png)

Thanks for the super fast fix @antw

**Comment by AlexanderWirtz** [comment]
@antw  
Awesome!
