### ISSUE TITLE
When merging two scenarios: unexpected slider settings 

### ISSUE THREAD

**Issue by AlexanderWirtz** [quintel/etmodel#2502]
I merged two scenarios with equal weight: 741570 and 741572 on the beta server.

This seems to work like a charm except for this slider:
```
households_water_heater_district_heating_steam_hot_water_share
```

This resulted in a non-zero slider setting even though both of its parent scenarios have this slider set tot `0.0`

**Comment by AlexanderWirtz** [comment]
Re-assign as you see fit

**Comment by ChaelKruip** [comment]
I assigned @antw as he knows best how merging of scenario's is done

**Comment by antw** [comment]
I've tried this locally and on beta, and in both cases the resulting district heating share is `0.0`. Are you sure those two scenario IDs are the ones you meant?

![screen shot 2017-10-09 at 12 35 06](https://user-images.githubusercontent.com/4383/31336372-8435fd32-acee-11e7-8806-ef66d4879b02.png)

```ruby
merged = ScenarioMerger.call([
  [Scenario.find(741570), 1.0],
  [Scenario.find(741572), 1.0]
])

merged.user_values['households_water_heater_district_heating_steam_hot_water_share']
# => 0.0
```

**Comment by AlexanderWirtz** [comment]
I have not been able to reproduce it directly either, but I do have an idea what may have caused this:

The merged scenario's sliders for hot water do not add up to 100%, but to 95.1%:

![image](https://user-images.githubusercontent.com/308563/31337807-3c81329a-acfd-11e7-9f99-db8284c1bf19.png)

If you save this scenario and then load it, normally that scenario will re-set the Condensing combi boiler slider to make it add up to 100%. In the scenario I created by merging and then saving (741575) _both_ this slider and the District heating slider have changed. No clue why that happened, but pretty sure it will not happen anymore once we fix the issue causing the sliders to not add up to 100% in the first place.

**Comment by antw** [comment]
> No clue why that happened, but pretty sure it will not happen anymore once we fix the issue causing the sliders to not add up to 100% in the first place.

The first scenario (741570) does not have any values for the hot water sliders, so the defaults are used. The second scenario (741572) *does* have values and they sum up to 90%; which is why the merged scenario – weighting the two starting scenarios equally – ends up with the sliders summing to 95%.

Here are the values for the second scenario:

| Input | Value |
| --- | --: |
| households_water_heater_combined_network_gas_share | 54.0, |
| households_water_heater_district_heating_steam_hot_water_share | 0.0 |
| households_water_heater_heatpump_air_water_electricity_share | 15.0 |
| households_water_heater_heatpump_ground_water_electricity_share | 5.0 |
| households_water_heater_hybrid_heatpump_air_water_electricity_share | 4.0 |
| households_water_heater_micro_chp_network_gas_share | 2.0 |
| households_water_heater_network_gas_share | 5.0 |
| households_water_heater_resistive_electricity_share | 3.0 |
| households_water_heater_wood_pellets_share | 2.0 |
| **Total** | **90.0** |

**Comment by AlexanderWirtz** [comment]
>The first scenario (741570) does not have any values for the hot water sliders, so the defaults are used. The second scenario (741572) does have values and they sum to 90%, which is why the merged scenario – weighting the two starting scenarios equally – ends up with the sliders summing to 95%.

I suppose I should have checked that. Not the only thing I discovered was wrong with that scenario, after all...

Thanks, Anthony!
