### ISSUE TITLE
Data export of demand differs from dynamic demand curve 

### ISSUE THREAD

**Issue by DorinevanderVlies** [quintel/etmodel#2514]
Our customer wants to have the raw data of the dyamic demand curve.

The loads export should provide all required data: `transport_car_using_electricity`, `fever_hot_water`, `fever_space_heating` and `total_demand`.

However a plot of these columns does not result in the total demand .

My first thought is that the EV curve of the chart shows the demand of EV and the EV curve of the export shows the flexibility usage of EV batteries and that this difference also shows in the total demand. If this is indeed the case an option would be export both the flex of EV batteries and the demand of EV.

### Example
[For the Urgenda-scenario:
](https://beta-pro.energytransitionmodel.com/scenarios/155680)

On the left the results of the export, on the right the dynamic demand curve:

![image](https://user-images.githubusercontent.com/19907658/31713780-b48c221e-b3ff-11e7-8f42-8e33450d3ef4.png)

notifying @ChaelKruip

**Comment by antw** [comment]
> My first thought is that the EV curve of the chart shows the demand of EV and the EV curve of the export shows the flexibility usage of EV batteries and that this difference also shows in the total demand.

That is indeed exactly what's going on. `transport_car_using_electricity` is showing the use of EVs **for buffering**:

<img width="592" alt="screen shot 2017-10-18 at 13 15 23" src="https://user-images.githubusercontent.com/4383/31718116-8fdefe62-b406-11e7-93b9-96f1db9b6560.png">

EV demand is not included in the CSV because it is part of `total_demand`, which is not really *total*: it is total demand *minus* the electricity used in heating and hot water (don't confuse it with the "total demand" series in the chart, which really *is* total).

We can work around this by adding `ev_demand` as a separate Merit participant, so that it is no longer part of `total_demand`.

@DorinevanderVlies I could push that to a branch if you'd like to experiment with it first, or it can go straight to beta. What do you prefer?

**Comment by ChaelKruip** [comment]
> EV demand is not included in the CSV because it is part of total_demand, which is not really total: it is total demand minus the electricity used in heating and hot water (don't confuse it with the "total demand" series in the chart, which really is total).

Why is electricity load due to heating and hot water not included in the total_demand and load due to EV not @antw? They seem very similar to me in the sense that all three are being calculated explicitly and shown as curves in the the dynamic demand curve chart.

**Comment by DorinevanderVlies** [comment]
> We can work around this by adding ev_demand as a separate Merit participant, so that it is no longer part of total_demand.
> @DorinevanderVlies I could push that to a branch if you'd like to experiment with it first, or it can go straight to beta. What do you prefer?

I like that idea and would say it can be pushed directly to beta.

> EV demand is not included in the CSV because it is part of total_demand, which is not really total: it is total demand minus the electricity used in heating and hot water (don't confuse it with the "total demand" series in the chart, which really is total).

For my understanding: with this change is`total_demand` in the export the white part of the dynamic demand chart and the sum of the 4 components the real total demand?

**Comment by antw** [comment]
> Why is electricity load due to heating and hot water not included in the total_demand and load due to EV not @antw?

Because the EV demand curve is constant; it is a function of EV demand and the charging strategy options chosen. The *shape* of the EV curve does not change once we start computing Merit.

This is not so for the space heating and hot water demands, whose shape *does* change depending on energy buffered as heat inside Fever. Therefore, the two Fever curves had to be included as separate consumers in Merit.

> with this change is **total_demand in the export the white part of the dynamic demand chart** and the sum of the 4 components the real total demand?

Exactly. I am open to changing the name of this participant to something more appropriate, however as far as I know this CSV is the only place we expose the name publicly.

**Comment by DorinevanderVlies** [comment]
> Exactly. I am open to changing the name of this participant to something more appropriate, however as far as I know this CSV is the only place we expose the name publicly.

Thanks for the clarification and the change!
Maybe "other_demand" would be more appropriate

**Comment by antw** [comment]
This is on beta now, so I'll close the issue. Reopen if you experience any difficulties.
