### ISSUE TITLE
Make it possible to include only part of the international transport in the energy system

### ISSUE THREAD

**Issue by jorisberkhout** [quintel/etmodel#2521]
More detailed background information on this issue can be found on [Basecamp](https://3.basecamp.com/3797409/buckets/4576947/messages/745259588).

As international transport is usually not considered to be part of the national energy system, we would like the user to be able to select what percentage of the sector is included through two sliders, looking roughly like this:

<img width="272" alt="screen shot 2017-10-31 at 10 33 52" src="https://user-images.githubusercontent.com/4669028/32217044-09769d6e-be27-11e7-9251-da258b3a26fe.png">

@marliekeverweij has (locally) implemented international transport is implemented like this in the graph

![screen shot 2017-10-26 at 13 40 37](https://user-images.githubusercontent.com/4669028/32217567-adbf65e4-be28-11e7-8075-3777d3787e46.png)

From the energy balance we can derive what the demands of the four `bunkers_final_demand_for_...` nodes (the third column from the left) are.

The demands of these four nodes in the present graph need to be set by the percentage of the corresponding slider times this demand from the energy balance. The difficulty will be that the user can change this percentage again, implying that the present graph needs to be updated. 

The default values for both sliders need to be `0%`.

**Comment by jorisberkhout** [comment]
Is this doable, @antw and could you give an estimate of the time required to implement this and when you can do it?

**Comment by antw** [comment]
> The difficulty will be that the user can change this percentage again, implying that the present graph needs to be updated.

Including @ChaelKruip. 😈 

> From the energy balance we can derive what the demands of the four bunkers_final_demand_for_... nodes (the third column from the left) are.
>
> The demands of these four nodes in the present graph need to be set by the percentage of the corresponding slider times this demand from the energy balance.

You cannot set final demands in ETEngine (unless the nodes to the left are calculated right-to-left, like power plants). One solution to this might be to add an extra "layer" where you split demand for ships and aviation between local (domestic?) and foreign use:

![untitled diagram 9](https://user-images.githubusercontent.com/4383/32226684-248d0f7e-be41-11e7-9b56-2366a2297ad9.png)

With a slider setting of 0%, the green edge to "foreign" demand would have a share of 1.0. With a slider setting of 50%, the green and purple edges would have shares of 0.5 with 50% of the demand being satisfied by each.

This might be a little tricky in ETSource since you'd need to set demand on the `foreign` node instead of the final demand nodes...

```ruby
# Pseudocode
~ demand =
    SUM(
      EB(bunkers_shipping, lng),
      EB(bunkers_shipping, heavy_fuel_oil)
    )
````

*(However, this assumes that there are no losses between final and useful demand nodes).*

It might be something like this:

![untitled diagram 10](https://user-images.githubusercontent.com/4383/32227041-08c2e38a-be42-11e7-90fe-763c3bd55095.png)

**Comment by ChaelKruip** [comment]
> Including @ChaelKruip. 😈

I kinda anticipating this imp to pop up sooner or later 😆 

What I think you mean @antw is that we would like to move away from updating the present graph rather than relying on it even more. 
At least, that is the direction that ETLocal is moving in: get rid of all inputs and methods that (mis)use ETEngine to manipulate the present graph and do all the initialising before ETEngine comes into the picture. 

@jorisberkhout @marliekeverweij what are the main reasons why you moved away from the 'switch' option where the bunkers are either fully included or excluded?

> One solution to this might be to add an extra "layer" where you split demand for ships and aviation between local (domestic?) and foreign use

Alternatively to this nice idea we could use GQL to add series to each relevant chart and contributions to each relevant dashboard item of the form:
```Ruby
#Pseudocode
- query = 
IF( bunker_switch == TRUE ){
    V(bunkers, demand) 
}
```
or (if you want to use a slider instead of a switch)

```Ruby
#Pseudocode
- query = 
    V(slider_setting) * V(bunkers, demand) 
}
```
This is perhaps a bit clunkier than having an ETEngine method to 'zero-out' a whole region but it would not need the present graph to change.

**Comment by marliekeverweij** [comment]
Thank you for your nice ideas!

> @jorisberkhout @marliekeverweij what are the main reasons why you moved away from the 'switch' option where the bunkers are either fully included or excluded? 

The main reason for this is that the sliders can also fulfil the purpose of the switch. Because when the slider is put on 0% this means that international transportation should not be included in the final demands, so this is the same as toggling the switch to OFF. Also when the slider is given is certain percentage this is similar to toggling the switch to ON.

**Comment by ChaelKruip** [comment]
> Also when the slider is given is certain percentage this is similar to toggling the switch to ON.

Only if that certain percentage is 100% 😉 

To rephrase my question: what is the use case for setting the sliders to 30% for instance? What insight would a user get by using slider settings different from 0% and 100%?

**Comment by marliekeverweij** [comment]
> To rephrase my question: what is the use case for setting the sliders to 30% for instance? What insight would a user get by using slider settings different from 0% and 100%?

Good question. The energy demand of international transportation is a lot and it is questionable whether it should all be allocated to the Netherlands, since for example the bunker fuels are also used for airplanes that transfer here. With the sliders the user could choose to only allocated a part of that energy demand.

Maybe in the description underneath the slider we can give the shares of marine/aviation bunker fuels that are used for what kind of planes/ships (if we can find these numbers). This way the user can make an educated guess.

**Comment by marliekeverweij** [comment]
Update on this issue:

We solved this issue by using `update_period = both` for the two sliders mentioned above. So the .gql-file of both inputs look like this:

![screen shot 2017-11-13 at 14 58 51](https://user-images.githubusercontent.com/32833996/32729183-37e5b6c4-c883-11e7-9db5-61d62c7042df.png)

This works fine, EXCEPT there is still one issue left.... When a new scenario is loaded, the final demand for international transportation is not zero, even though the `start_value = 0.0`. So apparently the slider inputs are not used to update the useful demands in the present and future graph when a new scenario is started.  

Today Joris, Chael, Gerard and I had a short meeting about this issue and came up with two probable solutions:

1. To create an extra node for each useful demand node (`bunkers_useful_demand_planes` and `bunkers_useful_demand_ships`) where other part of the share is put into. Actually the idea @antw pitched before:

> With a slider setting of 0%, the green edge to "foreign" demand would have a share of 1.0. With a slider setting of 50%, the green and purple edges would have shares of 0.5 with 50% of the demand being satisfied by each. 
![](https://user-images.githubusercontent.com/4383/32227041-08c2e38a-be42-11e7-90fe-763c3bd55095.png)

2. To put the energy demands of international transportation in the dataset of a specific country and use the slider-setting to update the demand of the useful demand nodes by: 

`demand = INPUT_VALUE(bunkers_allocated_percentage_aviation) / 100) * AREA(bunkers_useful_demand_planes)`

Could you help us out and let us know what you think, @antw?

**Comment by antw** [comment]
Both of these options require that we can calculate the useful demand *before* calculating the graph (basically, as described at [the end of my previous post](https://github.com/quintel/etmodel/issues/2521#issuecomment-340767945)). Is that likely to be possible? If so, I'm guessing either option would work.

The second might prove to be better since it will avoid any possibility of the "foreign" node and demand ever being included in CO<sub>2</sub> or primary demand calculations.

An alternative to storing the demand in the area file would be to add a disconnected node for each type of transport which stores the total (100%) demand, and we can instead read the value from there.

![untitled diagram 3](https://user-images.githubusercontent.com/4383/32736047-6c604bde-c88e-11e7-92ec-765fa8e26f3d.png)

... then the input looks something like:

```ruby
UPDATE(
  V(bunkers_useful_demand_ships),
  preset_demand
  V(bunkers_total_useful_demand_ships) * USER_INPUT()
)
```

I have no strong preference one way or the other: one pollutes the area with new attributes, the other pollutes the graph with new nodes.

**Comment by marliekeverweij** [comment]
> Both of these options require that we can calculate the useful demand before calculating the graph (basically, as described at the end of my previous post). Is that likely to be possible? If so, I'm guessing either option would work.

Yes, that is exactly what we would like to do. 

I like your idea @antw since this seems to be the most well-ordered option, where least can go wrong. I am going to implement that and see how it works! If you think of a simpler option, let me know.

**Comment by marliekeverweij** [comment]
I have implemented the new nodes (`bunkers_total_useful_demand_ships` & `bunkers_total_useful_demand_planes`) and did not connect them to the rest of the graph like you proposed (so no edges with shares). This is de code of these nodes:

![screen shot 2017-11-14 at 13 43 30](https://user-images.githubusercontent.com/32833996/32780525-dc6e2258-c941-11e7-81d7-a5e288097077.png)

Additionally, I have updated the inputs of the sliders with the code you wrote in the previous message:

![screen shot 2017-11-14 at 13 44 39](https://user-images.githubusercontent.com/32833996/32780577-1448e38e-c942-11e7-948b-24af008ef223.png)

However.... ETEngine does not work yet! We have asked Gerard to help out and he used the 'rake debug' to see what goes wrong in the graph. This is what comes out of that:

![bunkers finished](https://user-images.githubusercontent.com/32833996/32780199-b4952af2-c940-11e7-8417-7c219c0f41dd.png)

Apparently the graph does not recognise these 'loose nodes' since they do not show up!

@antw, do you maybe know how to solve this? Or should we try one of the other options we came up with?

**Comment by antw** [comment]
> @antw, do you maybe know how to solve this?

Have these changes been pushed to GitHub? I can take a look into it.

One thing I'm noticing is that my above query for the input is incorrect. It should be:

```ruby
UPDATE(
  V(bunkers_useful_demand_ships),
  preset_demand
  V(bunkers_total_useful_demand_ships, preset_demand) * USER_INPUT()
)
```

Also make sure that the "total_useful_demand" node belongs to the "preset_demand" group, otherwise it won't have a demand attribute that ETEngine can read.

```
# nodes/.../bunkers_total_useful_demand_ships.ad

- groups = [preset_demand]
...
```

**Comment by MartLubben** [comment]
@jorisberkhout , Is this issue solved and could you close it?

**Comment by jorisberkhout** [comment]
> @jorisberkhout , Is this issue solved and could you close it?

Yes and done.
