### ISSUE TITLE
Electricity price her hour chart - Pricing mechanism doesn't match with documentation

### ISSUE THREAD

**Issue by nairnamratha** [quintel/etmodel#2522]
Regarding the electricity pricing mechanism for the chart "Electricity price per hour":

The documentation on electricity pricing under the Merit Order states that:

"If no 'more expensive' participant is available, the electricity price is determined by **7.22 * operating cost of the most expensive participant.** This reflects the highest market price that can currently be observed in electricity trading during times of extreme shortage (around 600 EUR/MWh)."

Following this statement should result in peaks in electricity price per hour at: 
7.22* 37 €/MWh (Marginal cost of Conventional Gas) = **267.14 €/MW**

![screen shot 2017-10-31 at 11 26 47](https://user-images.githubusercontent.com/32448293/32219860-e51f0aa6-be2f-11e7-9659-28e717274db1.png)

But this does not correspond to the Electricity price per hour chart. As can be seen below, the peaks have a value around 150 €/MWh, not at 267.14 as expected.

![screen shot 2017-10-31 at 11 15 08](https://user-images.githubusercontent.com/32448293/32219840-d57cda92-be2f-11e7-801b-c00014578293.png)

How is this so? Not sure whether it's a bug or question

**Comment by antw** [comment]
Good catch.

The maximum price is €146 which happens to be the price of the import interconnect. This participant isn't included on the "Merit order capacities and marginal costs" chart. I will look into that and see if I can add it with any other missing participants.

The second issue is that the interconnect is considered "price-setting" even though demand vastly exceeds supply. This is because we changed from taking the price from the first (least expensive) *unloaded* merit order participant and instead use the last (most expensive) *loaded* participant, and later discussions indicated what we wanted to use the interconnect price even when it cannot meet demand; see quintel/merit#143 "Case 3".

---

Including @jorisberkhout.

**Comment by michieldenhaan** [comment]
Docs have been updated
