### ISSUE TITLE
Rapid increase in Gas CHP buildings from 2013 to 2015? 

### ISSUE THREAD

**Issue by nairnamratha** [quintel/etmodel#2523]
Comparing the 2013 and 2015 Electricity production per hour graph shows that Gas CHP buildings has popped up in 2015 whereas in 2013 they were negligible/non-existent. 

![screen shot 2017-10-31 at 11 58 37](https://user-images.githubusercontent.com/32448293/32220676-e41a1f3a-be32-11e7-8e95-bad205a21fb4.png)

Following this, the district heating sector shows that in buildings the Centralized district heating share  dropped from 99.7 to 1.0 % while Gas CHP share increased from 0 to 67%. 
![screen shot 2017-10-31 at 12 03 30](https://user-images.githubusercontent.com/32448293/32220924-ccae2052-be33-11e7-9ead-82891935c11e.png)
What is the reasoning for such a large change within a relatively short period of time?

**Comment by ChaelKruip** [comment]
Good questions @nairnamratha!

**Comment by DorinevanderVlies** [comment]
I tried to trace where this change originates, however so far I have not been able to find the source in the 2015 dataset analysis. When I compare the 1_chp_source_analysis for 20113 en 2015 CHP in “C&P services” (tab: CHP - Results by machine) is very similar


**1_chp_source_analysis**
2013 en 2015 CHP in “C&P services” (tab: CHP - Results by machine)

**2013:**
![image](https://user-images.githubusercontent.com/19907658/32217249-aee05902-be27-11e7-9372-875f0dad4655.png)

**2015:**
![image](https://user-images.githubusercontent.com/19907658/32217254-b2a28eac-be27-11e7-8623-508afea0f8f7.png)

**Comment by AlexanderWirtz** [comment]
Well spotted, but not to worry... this is deliberate. I will spare you the arcane arts of CHP and PP analyses. The source analyses do document this change between 2013 and 2015, but you need to know where to look. For good measure, I will tell you:

The final result of the CHP and PP and HP analyses is documenten in the `2_chp_pp_source_analysis.xlsx` file. The sheet `Power Plants and CHPs compare` is the one you want in this case. It shows a comparison between the previous dataset (2013 in this case), the new one (2015) and the 2015 CBS data used as source material. It is impossible to get it exactly right. For 2013, I decided to balance things out differently than for 2015, partly because of how I did it for 2012.
Compare the two screenshots from this sheet below. 

**2015 dataset**:
![image](https://user-images.githubusercontent.com/308563/32237783-2d2992e0-be66-11e7-9b0b-c206e8f73895.png)

**2013 dataset:** 
![image](https://user-images.githubusercontent.com/308563/32237859-62c1d35e-be66-11e7-9336-9494a0e8e320.png)

**Comment by DorinevanderVlies** [comment]
Thanks @alexanderwirtz!
