### ISSUE TITLE
80PJ of Industry_locally_available_refinery_gas_for_chemical is not an input in any process and not an export

### ISSUE THREAD

**Issue by MartLubben** [quintel/etmodel#2539]
![screen shot 2017-11-15 at 11 31 59](https://user-images.githubusercontent.com/33415156/32831455-aefb2138-c9f8-11e7-9ea6-a2d782faff5a.png)

**Comment by ChaelKruip** [comment]
@jorisberkhout @AlexanderWirtz is this refinery_gas actually used for heat in industry? Should we add it to own use (and therefore to the final_demand_group?)

**Comment by AlexanderWirtz** [comment]
@ChaelKruip I haven't a clue. Refinery gas is typically sent right back to be fired for extra heat production, but I am too unfamiliar with the way refineries are modeled to be able to say what this is.

**Comment by jorisberkhout** [comment]
Good find, @MartLubben . As @AlexanderWirtz , in real life, the refinery gas is fed right back into the burners to produce part of the heat required for the refinery gas. We couldn't model it in the same way as this would introduce a circularity (i.e. part output of the refinery determines part of the input of the refinery). 

The amount of refinery gas that is burned to provide additional heat can be found from the energy balance and is regarded as input of the refinery (although it is treated as if it were natural gas since we do not have refinery gas burners). The refinery gas that exits the refinery is ignored as it has already been included in the input of the refinery, which explains why the node that you pointed out is not connected to anything.

So, even thought the modelling is not ideal, it is not very far from the truth.

Does this answer your question, @MartLubben (and yours, @ChaelKruip)?

**Comment by ChaelKruip** [comment]
> Does this answer your question, @MartLubben (and yours, @ChaelKruip)? 

Yep. Closing.
