### ISSUE TITLE
Local dataset do not load on Beta-server

### ISSUE THREAD

**Issue by DorinevanderVlies** [quintel/etmodel#2542]
I get errors on Beta when trying to load a local dataset.

Perhaps this has to do with the implementation of international aviation.

Notifying @jorisberkhout, @marliekeverweij @ChaelKruip 
@antw please reassign when appropriate

![image](https://user-images.githubusercontent.com/19907658/32852851-8d84707c-ca39-11e7-8b63-8aee986c3d09.png)

**Comment by antw** [comment]
I think this is because [dashboard_reduction_of_co2_emissions_versus_1990 ](https://github.com/quintel/etsource/blob/7dac27c83afe183823ba88e7dc7923dd85072ce1/gqueries/output_elements/dashboard/dashboard_reduction_of_co2_emissions_versus_1990.gql) references `AREA(co2_emission_1990_marine_bunkers)` and `AREA(co2_emission_1990_aviation_bunkers)`, and these attributes are not set on the local datasets.
