### ISSUE TITLE
Use direct air capture as source for CO/CO2 if other sources are insufficient

### ISSUE THREAD

**Issue by ChaelKruip** [quintel/etmodel#2611]
Currently, the user can build a scenario with P2Kerosine where a part of the CO/CO2 is not accounted for:
![energy_transition_model_-_your_free__independent__comprehensive__fact-based_scenario_builder_](https://user-images.githubusercontent.com/1303760/34208908-74389798-e590-11e7-9694-ea7d7fab6ec6.png)
More CO is used than the steel industry actually produces.

I think it would be nice if direct air capture could be used as a 'back-up' option that produces the deficit of CO/CO2 if other options are insufficient.

I am not sure if this is technically possible and how to communicate this to the user. The table could show the amount of DAC easily but what to do with the slider settings?

**Comment by marliekeverweij** [comment]
This is a nice idea! I am not sure how to implement it though. Let me think.... 

The table is also not automatically shown when you are on the power-to-kerosene slide, I think that should be adjusted (I will do that now). However, the kerosene production chart (that is now connected to the slide) is also interesting to see....

**Comment by jorisberkhout** [comment]
Good suggestion to change the way this part of the model works, @ChaelKruip . As discussed in person this morning, I would propose to implement a slightly modified version of your proposal, which would be as follows:

- Keep two sliders: one for point source CO and one for point source CO2
- Make the slider caps of these sliders `0%`and `100%`and remove them from the slider group they are in
- The user can now select what percentage of the available CO and CO2 from the point source is used
- Remove the slider for direct air capture and make this the backup option in case more CO is needed than is available from the point source
- Keep the table as default chart with this slide as that table is very insightful

**Comment by marliekeverweij** [comment]
I am trying to implement what Joris suggested in the previous post, but I am facing a problem. I have already consulted @grdw  and @antw , but they advised to ask @jorisberkhout, @ChaelKruip and @AlexanderWirtz since it is a modelling-question.

What I have done so far is:

1.  Create two input statements (for point source CO and CO2) that runs from 0-100%. In the input statement this percentage is multiplied with the maximum possible share for a point source CO/CO2 based on the CO/CO2 that is emitted by the steel industry. The product is used to set the share for the related edge. For point source CO the input statement looks like this:

```
- query =
    UPDATE(
      LINK(bunkers_p2l_point_source_CO, bunkers_p2l_mixer_co),
      share,
      future:Q(max_share_of_point_source_CO_in_p2l_in_bunkers) * DIVIDE(USER_INPUT(),100))
    )
- priority = 0
- max_value = 100.0
- min_value = 0.0
- start_value = 100.0
- step_value = 0.1
- unit = %
- update_period = future
```

2. Calculate the maximum possible share in a separate file `max_share_of_point_source_CO_in_p2l_in_bunkers`:

```
# This query calculates the maximum share of CO for power-to-kerosene production
# in bunkers that can come from point sources of CO (steel industry).

- query =
    DIVIDE(
        SUM(V(LINK(energy_steel_blastfurnace_current_transformation_cokes,energy_distribution_coal_gas),demand) * 0.881,
            V(LINK(energy_steel_blastfurnace_bat_transformation_cokes,energy_distribution_coal_gas),demand) * 0.881),
        V(bunkers_p2l_mixer_co, demand)
    )
```


The problem now is that this does not work: the share of the edge stays zero, despite the fact that when I test `future:Q(max_share_of_point_source_CO_in_p2l_in_bunkers)` in the sandbox, this gives the correct value. 

Anthony's explanation for this is: _''I imagine that you cannot do that because inputs are run before the scenario is calculated (therefore the demands will also not yet have been calculated).''_

**Do you have an idea how to make this work?** :relaxed:

(I hope I have clearly stated the problem....)

**Comment by marliekeverweij** [comment]
@ChaelKruip and I just discussed about it, but we couldn't figure it out yet. We agreed that it would be better if the available CO/CO2 from industries would be calculated in the graph and not in queries. But HOW we do not know yet! 

- Only for the available CO it would be possible to take a share of the `coal_gas` coming from `energy_steel_blastfurnace_current_transformation_cokes` + `energy_steel_blastfurnace_bat_transformation_cokes` and create an edge that goes from the industries to the P2L-section. This because CO really contains energy! However I think we still would have some troubles connecting that edge to the current P2L-section.

- CO2 does not have any energy, so therefor an edge would not be possible. We were thinking of using the `weighted_carrier_co2_per_mj` attribute and calculate the 'on-the-spot-emissions' (which we need) of the `energy_steel_blastfurnace_current_transformation_cokes` + `energy_steel_blastfurnace_bat_transformation_cokes`. However, then we still need queries to calculate the available CO2....

We also thought of very big interventions; modeling co2-streams in a mass-balance-graph separately from the current energetic graph. But that would maybe be too much work before the meeting on Friday :joy:

**Comment by marliekeverweij** [comment]
I have just talked with Joris and we would like to carry out the last idea:
> We thought that it would be nice to help the user a little more than just showing table with used/available CO/CO2. This can be done by making the numbers in the table red when the demand exceeds the supply, so the following numbers:

This is also done in the plant profitability table:

![screen shot 2018-01-10 at 11 58 28](https://user-images.githubusercontent.com/32833996/34769274-9edf91cc-f5fd-11e7-80c1-d93d1a76068b.png)

@antw, could this be implemented before Friday morning? Since then we have a meeting where we would like to show this feature! Sorry for the bad planning!!

**Comment by marliekeverweij** [comment]
Thanks @antw for fixing this! 
![screen shot 2018-01-11 at 14 46 23](https://user-images.githubusercontent.com/32833996/34828546-3a60e516-f6de-11e7-89d4-0cd22b860c30.png)

Shall I leave this issue open @jorisberkhout, since we haven't fixed it like we wanted to?

**Comment by jorisberkhout** [comment]
Let's leave this issue open for now.

**Comment by marliekeverweij** [comment]
https://github.com/quintel/etsource/tree/changing-carbon-sliders

This is btw the branch in which I have tried to fix this issue. Then we know where the work is saved!

**Comment by michieldenhaan** [comment]
No longer relevant/possible after: https://github.com/quintel/etengine/pull/1134
