### ISSUE TITLE
International transport is missing from the primary energy use table:

### ISSUE THREAD

**Issue by grdw** [quintel/etmodel#2621]
![screen shot 2018-01-03 at 09 56 26](https://user-images.githubusercontent.com/2676542/34514188-61ea1c60-f06c-11e7-8947-61a1c104417f.png)

I was testing things for https://github.com/quintel/etmodel/issues/2618 

In a random scenario I increased the "International aviation" slider to about 40%. This caused the graph to expand, however this isn't reflected in the table:

![screen shot 2018-01-03 at 09 55 34](https://user-images.githubusercontent.com/2676542/34514207-882684c2-f06c-11e7-833e-595f4fc3936c.png)

*I'm missing the Oil - International transport*

**Comment by marliekeverweij** [comment]
It is called 'oil - bunkers', but indeed it is not clear, because nowhere else in the ETM the term 'bunkers' is used. So I will change it to 'international transport'.

**Comment by marliekeverweij** [comment]
It seems like the table directly uses the group name ('bunkers') and does not apply any translation from ETModel ('International transport'). Therefore, 'export_and_curtailment' is also not translated to 'Export and curtailment'. Could it maybe be realized that the translations are used instead of directly the group name, @grdw?

**Comment by grdw** [comment]
> Could it maybe be realized that the translations are used instead of directly the group name, @grdw?

Yes, I'll take a look into it
