### ISSUE TITLE
Shall we try to show the energy neutrality to user?

### ISSUE THREAD

**Issue by ChaelKruip** [quintel/etmodel#2643]
Regardless if it is a good idea or not, more and more people are talking about making their region 'energy neutral'. There are two flavours:

* year averaged: the region produces as many PJ's as it consumes over the whole year
* instantaneous: the region produces as many PJ's as it consumes every hour

How could we inform the user about how energy neutral his/her scenario is?

Some ideas:

For the year-averaged version:
* We might be able to 'collapse' the import/export waterfall chart as the resulting (last column) of that chart basically is the net import/export
* We could express the 'neutrality' as a percentage of local (primary) demand and display it as a dashboard item

For the hourly version:
* We could show for how many hours in the year the scenario still needs import (dashboard item)
* We could show a chart where we show the (hourly) match between supply and demand so the user can also learn *why* the scenario is not energy neutral yet

Curious about your opinions @AlexanderWirtz @DorinevanderVlies @jorisberkhout @MartLubben @michieldenhaan @antw @grdw @marliekeverweij @nairnamratha!

**Comment by nairnamratha** [comment]
I think it's a very nice idea to include the "energy neutrality" concept to the ETM!

I personally think that the hourly version you suggested is very insightful and would give users a  clearer perception about the scenario. 

> We could show a chart where we show the (hourly) match between supply and demand so the user can also learn why the scenario is not energy neutral yet

Really like this! This will give users a better understanding of how to make the scenario energy neutral.

> We could express the 'neutrality' as a percentage of local (primary) demand and display it as a dashboard item

However, it may be nice to have the year-averaged version on the dashboard as well as it gives an impression of the overall status for the scenario (and also since most of the dashboard items are shown as yearly values).
