### ISSUE TITLE
New technologies for public transport and kerosene should be added to datadump

### ISSUE THREAD

**Issue by DorinevanderVlies** [quintel/etmodel#2650]
Assigning @marliekeverweij, I am happy to help you to get started!

Notifying @ChaelKruip

**Comment by jorisberkhout** [comment]
Moved to 'Deploy June 2018' milestone.

**Comment by marliekeverweij** [comment]
@Dorine and I just checked the datadump and found out that the new nodes for public transport and synthetic kerosene have already been added to the relevant datadumps. 
In the application-demands-datadump some transport technologies were added and we have chosen to only include the hydrogen car en electric car since for these nodes the investment_costs can change with a slider (and the other transport technologies do not have any costs).
