### ISSUE TITLE
Browser support header needs to be parsed as HTML

### ISSUE THREAD

**Issue by grdw** [quintel/etmodel#2686]
![screen shot 2018-03-01 at 13 07 08](https://user-images.githubusercontent.com/2676542/36844071-7a025fda-1d51-11e8-9884-c80e2061bed2.png)

**Comment by antw** [comment]
Hmm, this message is quite annoying; because it's a flash message it keeps reappearing after you close it. It also overwrites any other flash messages such as "you have been logged out".

I reckon we'd be better putting this as a separate message on the home (root) page only. What do you think @grdw?

**Comment by grdw** [comment]
> I reckon we'd be better putting this as a separate message on the home (root) page only. What do you think @grdw?

Yes. That would make the most sense. Although I would like to argue that it would also be practical to have it on a scenario's page. I can see people going directly to a single scenario and not entering from the front-page. However, I can't say that for sure because #2653 hasn't been implemented yet 😅

**Comment by jorisberkhout** [comment]
Moved to 'Deploy June 2018' milestone.
