### ISSUE TITLE
Future natural gas production is read from production curve and overwrites dataset assumption

### ISSUE THREAD

**Issue by jorisberkhout** [quintel/etmodel#2703]
For most local datasets, we set the extraction of natural gas and other carriers to zero in the dataset. For the future, however, the extraction is read from a scaled production curve for that carrier, resulting in a non-zero extraction of natural gas in the future. See the screenshot below for an example.

![screen shot 2018-03-07 at 11 20 19](https://user-images.githubusercontent.com/4669028/37087111-a12bffce-21f9-11e8-8b03-59c2232bf9a0.png)

Assigning @michieldenhaan . Reassign at will.

**Comment by MartLubben** [comment]
@jorisberkhout I am checking this for Utrecht Province and gemeente Maasdriel. In both cases I cannot reproduce it. @michieldenhaan did you fix this issue already?

![Uploading Screen Shot 2018-06-27 at 10.42.12.png…]()

**Comment by michieldenhaan** [comment]
I've manually set the curves to zero for a bunch of datasets, but this isn't a long term solution (see https://github.com/quintel/etsource/blob/master/datasets/utrecht_province/time_curves/energy_extraction_crude_oil_time_curve.csv). I'm not sure what a good solution would be, as production curves are typically not very relevant for derived datasets. Two options I see are:
- Set derived dataset curves to zero by default for all carriers/all years (2010 till 2050)
- Set derived dataset curves equal to the numbers provided by the user for all years. That is, if the user sets biomass production equal to 454 TJ (see screenshot below), biomass production for each year equals 454 TJ (flat profile)

Not sure how difficult it is to implement either solution. Can you estimate this @antw?


![etlocal httpsbeta-local energytransitionmodel com 2018-06-27 10-52-55](https://user-images.githubusercontent.com/32056448/41963611-4a1d6a40-79f8-11e8-8110-ad53ace7cbab.png)

**Comment by antw** [comment]
> For the future, however, the extraction is read from a scaled production curve for that carrier

Indeed: it's set using the curve via the [initial_updates_preset_demands](https://github.com/quintel/etsource/blob/d073f7e31cadf48a3cd2a3e684fc545ed7d022ad/inputs/misc/initial_updates_preset_demands.ad) input.

> * Set derived dataset curves to zero by default for all carriers/all years (2010 till 2050)
> * Set derived dataset curves equal to the numbers provided by the user for all years. That is, if the user sets biomass production equal to 454 TJ (see screenshot below), biomass production for each year equals 454 TJ (flat profile)

Setting to zero would seem to be incorrect as, presumably, there will be local datasets whose extraction should not be zero. Making the curve flat also seems incorrect as most of the curves decay over time; making the curve flat assumes that production in the future will be the same as the present.

I expect the ideal solution would be to create a new curve with the user value describing the present year, and the rest extrapolated using the shape of the original curve.

For example:

| Year | NL | Local |
|--:|--:|--:|
| 2015 | 100 | (ETLocal user value) **25** |
| 2016 | 90 | 22.5 |
| 2017 | 85 | 21.25 |
| 2018 | 82 | 20.5 |
| ... | ... | ... |
| 2050 | 0 | 0 |

> Not sure how difficult it is to implement either solution. Can you estimate this @antw?

Honestly have no idea how long this will take. As far as I know, modifying curves is a whole new ballpark for ETLocal which can currently only edit area attributes and node/edge attributes (via graph_values.yml). I can look into it more; how high priority is this?

**Comment by michieldenhaan** [comment]
In terms of priority: From my experience it is difficult to find local information about production and extraction and the majority of our local dataset users are currently not prioritizing this. They mainly don't want scaled profiles to influence their scenario's/charts etc (e.g. gas production in a municipality with no gas reserves). That's why we typically overwrite the scaled curves with 'all zero' curves.

I agree that flat profiles are not so nice; your solution sounds very appealing and I think that ultimately we should go that way. But from a user's perspective I guess that the priority for this is fairly low. For us it would be quite convenient if we don't have to copy over 'all zero' time curves every time we create a dataset. Maybe it's worth investigating whether ``rake etsource:export`` can be modified such that it creates 'all zero' curves rather than scaled curves by default? For individual datasets, we can then manually modify these curves if there's a need for it.
