### ISSUE TITLE
Could we remove most DIVIDE( < query> / BILLIONS)?

### ISSUE THREAD

**Issue by ChaelKruip** [quintel/etmodel#2752]
A lot of queries use

- unit = PJ

and need to divide the query result (in MJ) by BILLIONS. This is overhead for ETEngine obviously.

@antw could we remove all these divisions and let ETModel deal with the scaling (which it already does most of the time anyways)?

**Comment by antw** [comment]
I see no harm in doing this. In fact I think it would be an improvement to consistently use MJ for every query.

Random thoughts:

* Perhaps we'll have to adjust the unit on some charts to reflect the change in the query, but the ETM should otherwise cope just fine.
* We'll also need to check other apps like ETFlex and ETMoses in case those apps use these queries.
