### ISSUE TITLE
The CO2-sheet always directs you towards a 2040 scenario

### ISSUE THREAD

**Issue by MartLubben** [quintel/etmodel#2759]

**Comment by MartLubben** [comment]
![screen shot 2018-04-06 at 09 17 26](https://user-images.githubusercontent.com/33415156/38407866-72308e62-397b-11e8-9ebf-d724441c18c6.png)
![screen shot 2018-04-06 at 09 17 36](https://user-images.githubusercontent.com/33415156/38407871-7396e86e-397b-11e8-9792-10fe4c370bb2.png)
![screen shot 2018-04-06 at 09 17 54](https://user-images.githubusercontent.com/33415156/38407872-73c1af72-397b-11e8-9ead-c1befde6135e.png)

**Comment by grdw** [comment]
Unfortunately, I know about this. Somehow - while on holiday - the "Bekijk CO2-voetafdruk" button was put next to the "Start" button. I know it looks nice, but it implies that the year you select actually has an impact on the scenario you can start from the factsheet. We can:

- Connect the two (3 hours of work)
- Move the button back to where it was to remove this implication (1 hour)

**Comment by antw** [comment]
> Unfortunately, I know about this. Somehow - while on holiday - the "Bekijk CO2-voetafdruk" button was put next to the "Start" button. I know it looks nice

@jorisberkhout and I discussed the placement of the button when the factsheet went live, and [I wrote up why I wasn't a fan in the PR](https://github.com/quintel/etmodel/pull/2740) (and also mentioned possible confusion about the end year). In short: while the factsheet is of course of value to the client who sponsored it, I didn't think it worth disrupting the flow of the most important form in the entire application. Personally I'd rather it wasn't in that form *at all* but that's a discussion I'm going to lose. 😄

> The ugly way: store the year you select in the url as a get parameter

Personally I think this is fine, and potentially more future-proof should the factsheet ever need to show future values (although I'm struggling to imagine why this would be the case).

> The downside here is that we don't have any support from IE versions lower then 11.

IE < 11 so far makes up 0.9% of visitors since the analytics were configured.

I don't have a strong preference how this is done, but I do have a preference to not move the button back to where it was.
