### ISSUE TITLE
Sankey not correctly displaying H2

### ISSUE THREAD

**Issue by AlexanderWirtz** [quintel/etmodel#2795]
The Sankey currently does not seem to correctly show all H2 in a system. 

For example [this scenario](https://beta-pro.energytransitionmodel.com/scenarios/865980) that creates only hydrogen from excess electricity and imports hydrogen:
![image](https://user-images.githubusercontent.com/308563/40658150-93750d7a-634a-11e8-8d7a-ee2a7071dcc3.png)

There is only primary hydrogen (105 PJ of imported hydrogen is indeed primary, but the Sankey shows more, namely 290 PJ of primary hydrogen) and there is no electricity --> hydrogen visible in the Sankey.

Notifying @ChaelKruip and @michieldenhaan.
Discussed with @ChaelKruip to assign @marliekeverweij

**Comment by marliekeverweij** [comment]
Oops! But I am not sure how we want hydrogen to be displayed in this sankey. 

Only primary carriers are shown in this sankey. Except for electricity and heat, they are produced from primary carriers in the middle of this sankey through electricity production and CHPs. Do we also want to display secundary hydrogen? Then we have to add many different conversion-blocks to the sankey I think (because now all produced hydrogen is being displayed in the left row but this actually should only be the imported hydrogen). For example we should add:
- conversion from electricity --> hydrogen with an `electrolyzer`-block right of `electricity production`
- conversion from gas --> hydrogen with an `SMR`-block underneath `CHPs`-block
- conversion from hydrogen -> electricity in an `gas turbine`-block

Is this how we want it? 

Then another question; how will we separate the produced hydrogen streams into the different sectors? Do we give each produced hydrogen stream the same split as shown in the 'demand/supply hydrogen mekko'?

Sorry lot of questions ;-)

There is also the easy option to only show the imported hydrogen and not the produced hydrogen from other sources, but I don't think that we want this.

**Comment by AlexanderWirtz** [comment]
> Except for electricity and heat, they are produced from primary carriers in the middle of this sankey through electricity production and CHPs. Do we also want to display secundary hydrogen? 

I say yes: hydrogen plays a similar role in the system to electricity. It is interesting to know how much electricity goes into hydrogen production. This is probably complicated by the wish of Gasunie and GasTerra to make _dedicated_ hydrogen production primary hydrogen production and to show hydrogen produced from excess power as secondary hydrogen. Any other hydrogen is secondary anyway.

> For example we should add:
- conversion from electricity --> hydrogen with an `electrolyzer`-block right of `electricity production`
- conversion from gas --> hydrogen with an `SMR`-block underneath `CHPs`-block
- conversion from hydrogen -> electricity in an `gas turbine`-block
> 

- conversion from electricity: only as described above, not the dedicated hydrogen.
- conversion from (natural) gas: YES
- conversion of hydrogen into electricity: YES

> Then another question; how will we separate the produced hydrogen streams into the different sectors? Do we give each produced hydrogen stream the same split as shown in the 'demand/supply hydrogen mekko'?

That sounds like a good idea.

**Comment by marliekeverweij** [comment]
> This is probably complicated by the wish of Gasunie and GasTerra to make dedicated hydrogen production primary hydrogen production and to show hydrogen produced from excess power as secondary hydrogen. Any other hydrogen is secondary anyway.

Okay! The one thing I am thinking of is that P2H from excess electricity is now not included in the Sankey. Shall I also include that? 

(Maybe @ChaelKruip also wants to join this discussion)

**Comment by ChaelKruip** [comment]
> (Maybe @ChaelKruip also wants to join this discussion)

Yes. But I don't have time for this now unfortunately. We can wait with this until next week.

**Comment by marliekeverweij** [comment]
@michieldenhaan and I just discussed about this and we were inspired bij the Sankey of CE Delft:

![screen shot 2018-06-08 at 10 13 24](https://user-images.githubusercontent.com/32833996/41146831-edfae244-6b04-11e8-9fb8-81bfe88f042b.png)

- On the left the primary carriers will be displayed: coal, oil, gas, wind, solar, biomass. green gas, geothermal, waste (so more categories then currently in our Sankey)
- In the middle we are thinking of 4 blocks: hydrogen production, electricity production, heat production and CHPs. 
- On the right the different sectors will be displayed!

We have a question for @antw : is it possible to make a connection from the electricity production block to the hydrogen production and vice versa? (this is also down in the CE Delft sankey above) Like a kind of loop. Currently this doesn't happen in our ETM Sankey.

**Comment by antw** [comment]
> We have a question for @antw : is it possible to make a connection from the electricity production block to the hydrogen production and vice versa? (this is also shown in the CE Delft sankey above) Like a kind of loop. Currently this doesn't happen in our ETM Sankey.

The answer seems to be: yes this is possible, but it will probably require some adjustments to the chart:

>![screen shot 2018-06-08 at 12 52 24](https://user-images.githubusercontent.com/4383/41156685-e24de0c0-6b1a-11e8-9b6d-095b020036b5.png)
>
> *the loop gets drawn outside of the left of the chart, and labels on the right are cut off*

... and needs some care when choosing what columns to show, and in which order to display the blocks:

> ![screen shot 2018-06-08 at 12 53 36](https://user-images.githubusercontent.com/4383/41156712-faedc60e-6b1a-11e8-9eea-6ad511fef296.png)
>
> *if hydrogen is positioned vertically close to electricity production, the loop no longer looks like a loop*

**Comment by marliekeverweij** [comment]
Okay it is done for now! In the end I found more things that had to be changed besides hydrogen ;)
Before:
![screen shot 2018-06-19 at 10 25 29](https://user-images.githubusercontent.com/32833996/41585715-27abb226-73ab-11e8-97cc-939d0932f2e4.png)
After:
![screen shot 2018-06-19 at 10 24 23](https://user-images.githubusercontent.com/32833996/41585650-f8dd0e68-73aa-11e8-9838-3bdca8bf4f07.png)

**Things that have changed:**

1. hydrogen production is added with:
- a link from electricity production to hydrogen production (P2G)
- a link from hydrogen production to electricity production
- a link from hydrogen production to central heat production (incl. CHPs)
- hydrogen import on the left
2. renewables are split into: solar, wind, geothermal & ambient, water
3. industry is split into 'industry' (energetic) and 'feedstock' (non-energetic)
4. the energy sector is added
5. 'CHPs' is renamed to 'central heat production (incl. CHPs)' and thus includes all central heat production technologies used for district heating and the central heat network
6. a link is added from electricity production to 'central heat production (incl. CHPS)' so now collective heat pumps are also correctly displayed
7. I have deleted some links from the sankey (f.e. from nuclear -> households) so that the lists become shorter 
8. I have changed the color used for losses, because it had the same color as hot water. And I have also create a block on the left for losses.

The only thing that still lacks in the Sankey is flexibility, but that was too much for this deploy.  I will include this soon. I have only included P2G.

As you can see the sankey is becoming very full, I have some ideas for improvements to keep it understandable (@antw):
- Now there is no distinction made between electricity and heat in the list of 'central heat production (incl. CHP's). This would be really nice to have! Also for the lists per sector it would be nice to see the difference between heat and electricity from CHPs
![screen shot 2018-06-19 at 09 53 11](https://user-images.githubusercontent.com/32833996/41584867-b4fb0d78-73a8-11e8-8fb5-48cd56c704d7.png)
- It is more intuitive to first show the inputs (<-) and then the outputs (->) in the lists
- It would be better when only the energy flows > 0 PJ would be displayed in the lists and not all flows
- Maybe the blocks in the middle could be more spread out in the middle, then it looks less full

Please test the Sankey thoroughly before merging! @MartLubben @michieldenhaan @ChaelKruip 
Especially the losses; they are not always exactly the inputs - outputs ......

**Comment by AlexanderWirtz** [comment]
Looks like a big improvement @marliekeverweij !

Just checking, but I assume you are using the output of solar, ambient and wind as the primary energy on the left side, right? This because of the statistical convention that electricity output from solar, for example, is primary energy, not the solar energy that goes into the solar panel. 

Maybe a bit pedantic to check, but also an easy mistake to make. :-)

**Comment by marliekeverweij** [comment]
Yes I am using the output of these nodes as the primary energy :)

**Comment by ChaelKruip** [comment]
Great work @marliekeverweij!
Have you checked if the totals per sector and carrier add up to the correct numbers (consistent with the Mekko's for example)?

This is always a good 'sanity check' to perform :)

**Comment by marliekeverweij** [comment]
@Michiel and I will fix the sankey tomorrow and cherry-pick it to live!

**Comment by michieldenhaan** [comment]
The sankey has been updated and is now on BETA (see https://github.com/quintel/etmodel/pull/2819). I put up the 'Under construction' banner as it still needs some testing; I would suggest opening a new issue when concrete bugs are found.
