### ISSUE TITLE
Should we remove the 'Grid investment notification' message?

### ISSUE THREAD

**Issue by jorisberkhout** [quintel/etmodel#2799]
As suggested by @antw in https://github.com/quintel/etsource/pull/1712#pullrequestreview-124005504 and supported by @ChaelKruip in https://github.com/quintel/etsource/pull/1712#issuecomment-392795824.

How do you feel about this @DorinevanderVlies , @michieldenhaan , @marliekeverweij and @MartLubben ?

**Comment by DorinevanderVlies** [comment]
Let's remove it

**Comment by jorisberkhout** [comment]
It is a yes for me too. @AlexanderWirtz , what do you think?

**Comment by AlexanderWirtz** [comment]
Yes!

Sent from my iPhone

On 5 Jun 2018, at 16:57, Joris Berkhout <notifications@github.com> wrote:

It is a yes for me too. @AlexanderWirtz <https://github.com/AlexanderWirtz>
, what do you think?

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/quintel/etmodel/issues/2799#issuecomment-394741488>,
or mute
the thread

**Comment by jorisberkhout** [comment]
@antw , would you mind removing the 'Grid investment notification' when you have some time for it?
