### ISSUE TITLE
Launch ETM in Dutch instead of English

### ISSUE THREAD

**Issue by marliekeverweij** [quintel/etmodel#2815]
@michieldenhaan , @MartLubben and I agree on the fact that it would be better to launch the ETM in Dutch instead of English since almost all of our users/clients are Dutch and the language-setting is not so easy to find. 

So actually this issue is twofold: also the language-setting should be more accessible. For example with two flags like this:

![language](https://user-images.githubusercontent.com/32833996/41473830-b493b9ac-70ba-11e8-9b9b-8709e2c39ef7.png)

What do you think @AlexanderWirtz @ChaelKruip @jorisberkhout @DorinevanderVlies ?

**Comment by antw** [comment]
Forcing it to a language isn't very consistent with web standards (that includes forcing the default to English as we currently do).

When you send a request to a web site, [it includes a list of accepted languages in order of preference](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Accept-Language). In Chrome, you can do this by going to Settings → Advanced → Languages:

<img width="712" alt="screen shot 2018-06-15 at 17 06 54" src="https://user-images.githubusercontent.com/4383/41478160-98e01a44-70be-11e8-9d46-33c757501fa2.png">

What we *should* be doing is respecting that setting: if the visitor's browser says it prefers Dutch, we should default to Dutch, if it says it wants English we should show English. This should do the trick nicely since 76% of visitors' browsers indicate a preference for `nl-nl` or `nl` while 20% want `en-us` or `en`.

**Comment by marliekeverweij** [comment]
@antw, I like your proposed solution!

I would say: let's do it! Are @jorisberkhout , @ChaelKruip and @DorinevanderVlies also okay with this?
