### ISSUE TITLE
Extend modal shift to international transport

### ISSUE THREAD

**Issue by michieldenhaan** [quintel/etmodel#2827]
With the high-speed rail vs. plane discussion becoming more and more prominent, I think it would be nice if we could add international transport to our modal shift functionality in the ETM.

First thoughts on implementation:
Maybe we can add a node after ``bunkers_useful_demand_planes`` that converts energy to passenger kilometres; connect that node to ``transport_useful_demand_passenger_kms``; rename the 'domestic planes' slider to 'planes'; add international aviation to the planes slider -> when the user adds international transport to his or her scenario passenger kilometres for planes will increase and can subsequently be replaced by trains.
Not sure if this will work tho..

**Comment by marliekeverweij** [comment]
Very good idea! Would be cool when people could shift between international trains and planes and see the difference.

We just discussed in a meeting with @Mart, @michieldenhaan and @ChaelKruip that it would be nice to include this modal shift improvement in a proposal to for example 'de Groene Partijen' (Marjolein Demmers) before implementing this, because we thought that they would be interested in this new feature. 

Notifying @AlexanderWirtz and @jorisberkhout

**Comment by michieldenhaan** [comment]
Closing, no plans for implementation atm
