### ISSUE TITLE
Primary energy production curve charts mistakenly show weekly or annual production

### ISSUE THREAD

**Issue by AlexanderWirtz** [quintel/etmodel#2847]
The curves that show the production of primary energy carriers used by the ETM are no longer visible in the ETM front end.

The chart type has changed into the same type as we have for the electricity demand and production curve. This is a mistake, I believe, as these charts should show the predicted production throughout the years until 2050. That is what the data from ETDataset provide. Or did I miss the memo on these charts?

As a result, there is nothing to see in these charts.

![image](https://user-images.githubusercontent.com/308563/42887316-fe324326-8aa5-11e8-8d2d-25b6922ddc96.png)

**Comment by jorisberkhout** [comment]
I can't reproduce this on Beta or on Live.

I look into it because I seemed to remember that @grdw changed the `Electricity production per hour` chart type such that whenever you have two charts of this type open they both respond to the week select box in the same way. I.e. if you change the week on one of them, the other one automatically changes to the same week. I thought this might have an effect on the production curve charts.

Do you recall what steps you took that lead to the production curve chart to look as shown in your original post, @AlexanderWirtz ?

**Comment by antw** [comment]
@AlexanderWirtz: Was this in your local copy of ETModel? If so, it might be something specific to your database; in which case you can find an up-to-date copy of the ETM staging and production databases on Dropbox (Development → Databases) which may be imported with Sequel Pro (let me know if you require instructions). These DBs don't have any personal data from visitors, but will have all the latest settings for charts, sliders, etc.

**Comment by AlexanderWirtz** [comment]
Very strange! I followed a link to a scenario Martijn Douwes created, but if I do so again, I also cannot reproduce it. I am glad I took a screenshot, or none of you would have believed me.

@antw my local copy has been a mess for over a year now. It doesn't work.
