### ISSUE TITLE
No additional HV network capacity should be built for curtailed electricity

### ISSUE THREAD

**Issue by jorisberkhout** [quintel/etmodel#2852]
The HV net is currently laid out to accommodate the highest peak transport capacity is either the demand or the supply of all technologies connected to this network level. This means that, in the case of very high production peaks that are curtailed, the network is expanded such that also this curtailed electricity can be transported which doesn't make sense.

**Comment by ChaelKruip** [comment]
Could this perhaps we solve by connecting `energy_flexibility_curtailment_electricity` to `energy_production_excess_electricity` instead of `energy_power_hv_network_electricity`? 

In my mind, there is no reason for the `energy_flexibility_curtailment_electricity` to be connected to the HV network anyways.

@jorisberkhout @antw curious about your thoughts!

**Comment by antw** [comment]
> Could this perhaps we solve by connecting energy_flexibility_curtailment_electricity to energy_production_excess_electricity [..]

I looked at this prior to the August deploy (and will return to it before the October deploy 😇) and if I remember correctly: no, this won't do the trick. *I agree* that it shouldn't be connected to the HV net, but this alone isn't the reason for the extra network capacity.

The problem is that the HV net peak load is defined as `MAX(MAX(demand), MAX(supply))`. Even if we get rid of curtailment (which is a demand), we'd still have the excess supply from the always-on producers; the peak load will stay the same.

I think the solution is something like changing the network calculation to represent curtailment as a *negative* supply rather than a positive demand. This would have the effect of reducing the always-on supply by removing the energy that would, in reality, be curtailed.

**Comment by ChaelKruip** [comment]
This is still important but not deploy-critical for now. Removing milestone

**Comment by marliekeverweij** [comment]
Revisiting this issue for the iNET deliverable: solar pv curtailment.

> I think the solution is something like changing the network calculation to represent curtailment as a negative supply rather than a positive demand. This would have the effect of reducing the always-on supply by removing the energy that would, in reality, be curtailed.

I am not sure though if this is the way to go. I think the cleanest and most realistic way to model curtailment is the way we will model solar PV curtailment: at the technology itself. Next week we'll have a % sliders that curtail solar panels on households/buildings and solar parks! In this way the peaks will not be transported through the electricity network: instead the peaks will be cut-off from the production curve.

In reality curtailment only applies to volatile electricity production, right? So wind and sun. And in reality curtailment takes place at the technology itself. So we could fix this issue by also adding curtailment sliders for wind turbines that curtail wind peaks 'at the source', next to the new solar PV curtailment sliders. This will give a lot of inside what exactly happens during curtailment: how much electricity is lost? what are the peak loads before and after? etc.

And then we do not have to adjust the excess electricity calculation. The only thing is that the current curtailment-category should be renamed to something like "Electricity surplus (wasted)" as curtailment has taken place already at the solar panels / wind turbines.

Curious about everyone's opinion! 

Including @AlexanderWirtz and @michieldenhaan

**Comment by ChaelKruip** [comment]
> In reality curtailment only applies to volatile electricity production, right? So wind and sun.

It could also happen for must-run production but since we have made all CHP dispatchable that never happens except for the new must-run nuclear power plant!

> So we could fix this issue by also adding curtailment sliders for wind turbines that curtail wind peaks 'at the source', next to the new solar PV curtailment sliders. 

Unfortunately, it's not that easy. Currently, curtailment of electricity is a last-resort option that reduces the *sum* of all left over electricity if no other means of flexibility is left. This can result in wind peaks being curtailed if they exceed capacity A in hour 1 and capacity B in hour 2.
Curtailing at the source has a fixed cut-off at capacity instead. These are two different things.

I think the amount of curtailment as we currently model it is only known after we have ran the total Merit calculation. I still can imagine that we choose not to pass this curtailed electricity through the HV network though as this would be more realistic. To be honest I haven't re-familiarised myself with the issue so I cannot say if @antw's solution makes sense to me at this point.
