### ISSUE TITLE
Energy sankeys should be tested

### ISSUE THREAD

**Issue by michieldenhaan** [quintel/etmodel#2854]
The updated energy sankeys have not yet been tested thoroughly. With today's deploy they will be transferred to the live server. We shouldn't forget to do some testing (soonish).

Some things to check:
- final demand + losses (right hand side) equals primary demand (left hand side)
- total electricity/heat/hydrogen production in Sankey = total production in graph
- flexibility

Maybe we can add some Mechanical Turk tests for this.

**Comment by marliekeverweij** [comment]
I have tested the sankey on the things mentioned above and so far I have come across only one issue:

There is something going on with the renewable energy sources, I will take wind as an example:
To calculate the energy from 'wind' to 'electricity' the following query is used:
```
    DIVIDE(
      SUM(
        V(Q(electricity_producing_converters_sankey).select {|node| node.input_slots.detect { |slot| slot.carrier.wind? }}, primary_demand_of(electricity))
      ),
    BILLIONS
    )
```
This gives the output energy of the wind energy nodes, even though the query calculates the `primary_demand_of(electricity)`. So the 3% losses from the turbine are not included in that query. However, they are included in the energy from 'electricity' to 'conversion losses', therefore there is more energy going out of electricity then going in.

When we take solar it will be more clear, because the losses in that node are bigger (83%):
![screen shot 2018-08-21 at 15 53 09](https://user-images.githubusercontent.com/32833996/44405778-59617900-a55a-11e8-92fd-816fda987a97.png)

So we should think of whether to include the losses on both sides or not. I think we should!

Furthermore, I have one possible minor improvement (@Anthony):
- sometimes the boxes when you move over a sector/conversion only show up very shortly (mostly when they are very small or when they are located on the right hand side) and this way you cannot read the numbers. could this be changed?

> Maybe we can add some Mechanical Turk tests for this.

I think this is a good idea!

**Comment by michieldenhaan** [comment]
Nice catch! I think we should leave those losses out. According to statistical guidelines the electricity produced by renewable sources is considered primary demand, not the 'theoretical' energy contained by solar rays.

**Comment by ChaelKruip** [comment]
> I think we should leave those losses out. According to statistical guidelines the electricity produced by renewable sources is considered primary demand, not the 'theoretical' energy contained by solar rays.

Agree! When can you pick this up @marliekeverweij ?

**Comment by marliekeverweij** [comment]
I can do this next week!
