### ISSUE TITLE
Should 'whole year' view of hourly charts show daily peaks or daily means? 

### ISSUE THREAD

**Issue by MartLubben** [quintel/etmodel#2867]
The yearly overview of the net load charts (lv, mv and hv) is counter intuitive. It shows daily average values while users mainly look at the peaks. It would be a great improvement if we could show the daily max values in these charts.  

Will this be an easy fix @antw ? 

![screen shot 2018-09-11 at 15 51 21](https://user-images.githubusercontent.com/33415156/45364535-ae812f80-b5da-11e8-9ec1-809296f0dc40.png)

**Comment by antw** [comment]
The annual view [already shows the peak load](https://github.com/quintel/etmodel/commit/e01001efbc516c8b997daf32eb22cd2011d1ca2a); it uses `downsampleWith: "max"` rather than `downsampleWith: "mean"`:

![kapture 2018-09-11 at 15 32 27](https://user-images.githubusercontent.com/4383/45366908-eb97f280-b5d7-11e8-8d11-65e804a7e489.gif)

**Comment by ChaelKruip** [comment]
It seems that the demand charts are the ones not using the 'max' approach (in yearly view):
![image](https://user-images.githubusercontent.com/1303760/45370546-c9f33700-b5e8-11e8-805b-ee8f861227dd.png)

I think when displaying the curves *for the whole year*, it makes sense to use the 'max' approach for both these types of charts.

Agree @antw @MartLubben @jorisberkhout ?

**Comment by michieldenhaan** [comment]
One option might be to show the hour in which the cumulated peak occurs for each series. E.g. suppose for the first 3 days of January the highest peak are in hour 2 (day 1), 10 (day 2) and 17 (day 3) then for each production series we can show the load in those hours.

Downside might be that some demand/supply technologies may not show up in the chart if they tend to occur in off-peak hours..

**Comment by ChaelKruip** [comment]
> Downside might be that some demand/supply technologies may not show up in the chart if they tend to occur in off-peak hours..

Any downsampling will have downsides. 
- Taking averages will reproduce the total energy (surface area under the curve) but will not show extremes
- Taking the max of each profile within a day will show extremes (but might even exaggerate them as the extremes (which might occur at different hours!) for multiple profiles are stacked. Also, total energy is no longer reproduced
- Showing the hours where the extreme of the sum occurs (as @michieldenhaan proposes) will show realistic peaks but might filter out some behaviour which occurs in less extreme moments. Also, total energy is no longer reproduced

Personally, I prefer the last option as the goal of these yearly charts is mainly to communicate the extremes.

**Comment by antw** [comment]
Here's what it looks like to sample the peak hour for each day, instead of the daily mean/max of each series:

![kapture 2019-02-13 at 16 15 18](https://user-images.githubusercontent.com/4383/52726244-bb031d00-2faa-11e9-9d6a-4d33dec9a879.gif)

---

> but might filter out some behaviour which occurs in less extreme moments. Also, total energy is no longer reproduced

This is indeed the case. Storage becomes largely invisible in the hydrogen production example:

![screen shot 2019-02-13 at 16 19 37](https://user-images.githubusercontent.com/4383/52726561-54323380-2fab-11e9-9212-1ecc9b796c28.png)

---

I suggest leaving this until after the deploy (we're in feature-freeze, after all) so that we may decide which charts should use the new sampling method.

**Comment by ChaelKruip** [comment]
> Here's what it looks like to sample the peak hour for each day, instead of the daily mean/max of each series:

Nice to see the difference. For load on the infrastructure I really like the peak sampled versions!

> I suggest leaving this until after the deploy (we're in feature-freeze, after all) so that we may decide which charts should use the new sampling method.

👍

**Comment by MartLubben** [comment]
> Nice to see the difference. For load on the infrastructure I really like the peak sampled versions!

Exactly!

**Comment by redekok** [comment]
A follow-up on this issue: one of our clients recently contacted me because the electricity production chart confused him. The top screenshot (A) of the chart was taken a few months ago while the middle screenshot (B) was taken more recently (a few weeks ago). Given that these screenshots were taken for the same scenario, a huge difference in the peaks (8 MW vs. 3 MW) is notable. The bottom screenshot (C) shows the peaks for a specific summer week, which reach 10 MW. Our client only looked at the annual overview of the hourly electricity production chart and got confused by the low (3 MW) peaks because he figured that the peaks should have at least been 8 MW (which they actually were, as screenshot C shows).

Two questions (hopefully @antw can help me out here?):
1. The difference between screenshot A and B surprised me. Did we change the approach for the chart views over the last couple of months?

> I suggest leaving this until after the deploy (we're in feature-freeze, after all) so that we may decide which charts should use the new sampling method.
2. Has this been implemented yet? If not, I would still be in favor to do this. 

![image](https://user-images.githubusercontent.com/5946498/69949852-8ab54c80-14f2-11ea-904d-6a710b2778bc.png)

![image](https://user-images.githubusercontent.com/5946498/69949922-afa9bf80-14f2-11ea-87ce-f63963bfa882.png)

**Comment by antw** [comment]
> The difference between screenshot A and B surprised me. Did we change the approach for the chart views over the last couple of months? 

Values in single-digit MW suggests this is quintel/etengine#1071, and not because of any change in the chart itself. I was planning to revisit that issue last week but didn't get around to it. I'll try to do so this week.

> Has this been implemented yet? If not, I would still be in favor to do this.

It's not on beta yet. I'll dig out the experimental branch shortly, and create a PR for people to try out.

**Comment by ChaelKruip** [comment]
>  I was planning to revisit that issue last week but didn't get around to it. I'll try to do so this week.

@antw would this be a nice issue for @noracato to pick up? Might be quite a challenge but also a very good learning experience.

**Comment by antw** [comment]
I have this completed locally. Enabling it for demand charts has this effect:

| `downsampleWith: "mean"` | `downsampleWith: "max"` (after) |
| :---: | :---: |
| ![Screenshot 2020-03-11 at 15 05 02](https://user-images.githubusercontent.com/4383/76431611-ba090e80-63a9-11ea-8ac1-8249c97b49c0.png) | ![Screenshot 2020-03-11 at 15 05 10](https://user-images.githubusercontent.com/4383/76431622-be352c00-63a9-11ea-9de9-45485cff281c.png) |

This would seem to be a win when the purpose of the chart is to show load rather than demand. It's not so clear cut when the goal is to summarise demand rather than (peak) load:

| `downsampleWith: "mean"` | `downsampleWith: "max"` |
| :---: | :---: |
| ![Screenshot 2020-03-11 at 15 13 00](https://user-images.githubusercontent.com/4383/76432407-d9ed0200-63aa-11ea-90e0-20dbbb50bb5e.png) | ![Screenshot 2020-03-11 at 15 39 46](https://user-images.githubusercontent.com/4383/76435196-97c5bf80-63ae-11ea-8624-d5b7139251a5.png) |

The new method makes it appear that there's a huge difference between demand and production of gas in the early and latter months of the year, when in reality such extreme deficits are short-lived events; only an hour or two per day.

![Screenshot 2020-03-11 at 15 17 38](https://user-images.githubusercontent.com/4383/76432921-86c77f00-63ab-11ea-8578-1edb5ba54f86.png)

Everyone's feedback would be appreciated.

**Comment by michieldenhaan** [comment]
Just to be clear, does 'max' refer here to option 2 or option 3 outlined in @ChaelKruip's post above? See
https://github.com/quintel/etmodel/issues/2867#issuecomment-420912292.

Conceptually I think I would prefer option 3 ('day peak') but curious how that would turn out

**Comment by antw** [comment]
> Conceptually I think I would prefer option 3 ('day peak') but curious how that would turn out

In the latest examples, "max" is option 3.

Previously "max" would find the maximum of each individual series which [would previously give a misleading view of the peak load](https://github.com/quintel/etmodel/issues/2867#issuecomment-420647013) when used on demand charts. My local branch rewrites "max" to implement [your suggestion](https://github.com/quintel/etmodel/issues/2867#issuecomment-420908348): find the hour with the maximum cumulative load, and show the load of each series in that hour.

**Comment by marliekeverweij** [comment]
I am in favor of showing the "max" instead of the "mean" as the peak loads on the networks (gas/electricity/hydrogen) are then clearly visible in the yearly view and that's what most users want to conclude from this chart. I think we should let go that the hourly charts also show the annual demands, we have other charts for that: vertical stacked bars, mekkos (we could link a yearly demand chart to each hourly chart with the "Annual-Hourly"-toggle?)

For the first chart in your post "Electricity demand on the high voltage net" the difference is relatively small because of many flat demand profile. For the second chart in your post "Network gas demand" there's a big difference between the "mean" and "max". I think we can better communicate to the user what is shown in this chart, with the "max" approach we see the daily peak loads in the yearly view. A new title could be "Network gas demand - daily peak loads". However, this title should actually change when going to the weekly view into "Network gas demand - hourly peak loads". I can imagine that that's not easily done

**Comment by redekok** [comment]
> I think we should let go that the hourly charts also show the annual demands, we have other charts for that

What exactly do you mean here with "letting go that the hourly charts also show annual demands"?

What I like about the hourly charts showing values for the whole year is that seasonal effects are visible, even though the peaks between a week-based and a year-based view might differ. The overview in the year-based view can help a user to identify an interesting week to zoom into.

**Comment by marliekeverweij** [comment]
Removing deploy milestone as we do not yet know what we exactly want with this issue!

FYI: at the moment we only show daily peaks (max cumulative load) for the solar pv curtailment chart and for other charts we show daily means. This is noted in the date drop down menu:
![Screenshot 2020-05-25 at 10 52 11](https://user-images.githubusercontent.com/32833996/82796491-ec3cef00-9e75-11ea-8655-16acf57c8eb8.png)

**Comment by ChaelKruip** [comment]
> Removing deploy milestone as we do not yet know what we exactly want with this issue!

Not sure if we considered this idea already but it might be cool if the user can select (with the same day/year selector) which interpolation method to use. This resolves the issue of us having to choose :)

**Comment by marliekeverweij** [comment]
I am reading the issue again and @MartLubben started this issue for only the net load charts. These charts now have interpolation option 2 (max of each profile during a day and stack these). I think it's better to use interpolation option 3 for theses (max sum of profiles), that hasn't happened right @antw ? (see different options [here](https://github.com/quintel/etmodel/issues/2867#issuecomment-420912292)) 

So shall we adjust the interpolation method for only the net load charts? Then we can decide later which interpolation method we want to use for the other demand/production charts.
![Screenshot 2020-05-25 at 11 07 31](https://user-images.githubusercontent.com/32833996/82797919-12638e80-9e78-11ea-89c1-25125b245601.png)

>Not sure if we considered this idea already but it might be cool if the user can select (with the same day/year selector) which interpolation method to use. This resolves the issue of us having to choose :)

I like it!

**Comment by antw** [comment]
> So shall we adjust the interpolation method for only the net load charts?

Currently it's not possible to set the interpolation method on a per-chart basis; only per-chart-type. With the move to YModel it is a little easier for us to support per-chart settings such as this. 

@marliekeverweij I've sent a PR, but I'd be fine delaying merging it until we support per-chart settings. I'm curious about your opinion.
