### ISSUE TITLE
It would be nice to have if we could show supply per net level in a chart

### ISSUE THREAD

**Issue by MartLubben** [quintel/etmodel#2868]
During the internal presentation of the net calculation it was mentioned that a **supply** per net level (lv, mv, hv) chart was a nice to have.

@antw Do you have an estimation how much effort this will take?

As example the **demand** per net level: 
![screen shot 2018-09-11 at 16 49 34](https://user-images.githubusercontent.com/33415156/45368051-ee4c1500-b5e2-11e8-8d85-f1af655e594d.png)

**Comment by antw** [comment]
> @antw Do you have an estimation how much effort this will take?

I imagine modellers could do this without needing much effort from me.

* The chart type used for showing supply needs a small change by me to make it reusable.
* [Queries for many of the electricity suppliers already exist](https://github.com/quintel/etsource/tree/master/gqueries/output_elements/output_series/d3_172_merit_order_hourly_supply). These could probably be sorted into LV, MV, and HV [like we do with demand](https://github.com/quintel/etsource/tree/master/gqueries/general/merit), but otherwise most of the work is already done.

**Comment by MartLubben** [comment]
>I imagine modellers could do this without needing much effort from me.

Great.
