### ISSUE TITLE
Should we add sliders for land / roof surface available for solar?

### ISSUE THREAD

**Issue by marliekeverweij** [quintel/etmodel#2902]
Currently we could only adjust the area / sea available for wind. Wouldn't it be nice to add land / roof surface available for solar?

This would have the following advantages:

- For users it is clear what surface potential is taken into account

- Easy to adjust!

![screen shot 2018-10-31 at 11 14 42](https://user-images.githubusercontent.com/32833996/47781705-aa31e280-dcfe-11e8-8f87-aacb004fb846.png)

Notifying @AlexanderWirtz @antw @ChaelKruip @jorisberkhout @michieldenhaan @DorinevanderVlies @MartLubben

**Comment by MartLubben** [comment]
It would certainly be an improvement! This will make it easier to support spatial discussions with the ETM.

**Comment by ChaelKruip** [comment]
> Wouldn't it be nice to add land / roof surface available for solar?

Yes... but this is complicated because land surface could be used for either solar and wind. We currently have no good way of bookkeeping of land use across different applications. Similarly, we have no good method to calculate the competition between solar PV and solar heaters for roof surface. 

We have not fixed this issue because of the following annoying issue: if solar heaters would compete with solar PV, the slider max for solar PV would depend on the number of solar heaters installed. Alternatively, you could update the AREA variable 'roof_surface_available_for_pv' and keep the slider max constant but this would not be very transparent for the user.

Even worse: arable land can be (partially) used for wind and solar as well with possible reductions of the yield etc.

A possible route forward is to keep track of the total useable land and for each application (solar, wind, biomass) a potential fraction of the total which could be used and if these applications are mutually exclusive or not.

**Comment by marliekeverweij** [comment]
Okay thanks, I understand the issue now! So currently the available onshore land can be used double; by inland wind turbines and solar PV parks?

I tried to find out where the area-attributes `onshore_suitable_for_wind` and `land_available_for_solar` are based on for the Netherlands:

- `onshore_suitable_for_wind = 27539.0` and is based on an Ecofys analysis (I could not really find the exact source in the source analysis)
- `land_available_for_solar = 18457.0` and is based on the 2015 CBS value 'total cultivated land' ([link](http://statline.cbs.nl/Statweb/publication/?DM=SLNL&PA=80780ned&D1=1-11&D2=0&D3=12-13,15&HDR=G1,G2&STB=T&VW=T)) 

(So the available land for solar pv parks is less than the available land for inland wind, I do not really know why)

I like this idea:

> A possible route forward is to keep track of the total useable land and for each application (solar, wind, biomass) a potential fraction of the total which could be used and if these applications are mutually exclusive or not.

Maybe we could choose one value for the total land available for solar pv parks and inland wind?
(Just as that we have one area for the roof surface available for solar PV and solar thermal)

When we would have one total area, then we could make a good chart that could show what part of the total available land is used by solar PV parks and inland wind turbines. Or we could make a dashboard item that let's you know when you are exceeding the available land! 

We could make the same kind of chart/dashboard item for the available roof surface in households and buildings. And we could solve this issue:
> if solar heaters would compete with solar PV, the slider max for solar PV would depend on the number of solar heaters installed. 
by changing the '% of potential'-sliders and make #-sliders or MW-sliders instead.

**Comment by marliekeverweij** [comment]
This issue is not relevant anymore, as we are thinking about implementing issue https://github.com/quintel/etmodel/issues/2912
