### ISSUE TITLE
The primary natural gas in househoulds is lower than the final natural gas demand in households

### ISSUE THREAD

**Issue by MartLubben** [quintel/etmodel#2914]
Region Dronten: 

When comparing the primary natural gas demand in households with the final natural gas demand in household the Final demand (0.67 PJ) > Primary demand (0.66 PJ). 

It is a small, but strange difference. DO you have an explanation @michieldenhaan ?

**Comment by ChaelKruip** [comment]
Including @antw as it is weird that FD > PD. Perhaps a node in the chain has efficiency > 1?

**Comment by michieldenhaan** [comment]
Interesting, I'll investigate. Did you include green gas? Green gas is included in final demand network gas but not in primary demand natural gas.

**Comment by MartLubben** [comment]
>Did you include green gas?

Nope Dronten has no green gas.

**Comment by michieldenhaan** [comment]
It looks like regassified LNG is the culprit here. According to the graph:

673 TJ final demand network gas, consisting of:
- 658 TJ primary natural gas
- 25 TJ primary LNG

So total primary (683 TJ) > total final (673 TJ).


![beta-pro energytransitionmodel com - energy transition model - your free independent comprehensive fact-based scenario build 2018-12-12 15-09-41 1](https://user-images.githubusercontent.com/32056448/49875082-6ca59680-fe20-11e8-94a6-12e99b3eb176.png)

![beta-engine energytransitionmodel com - energytransitionmodel 2018-12-12 15-11-30 1](https://user-images.githubusercontent.com/32056448/49875102-762efe80-fe20-11e8-827e-b20d54e020c8.png)

Note that the graph also shows a tiny bit of greengas, I guess this is due to rounding in a sparse graph query.
