### ISSUE TITLE
The technical specs of the buildings_collective_heatpump_water_water_electricity_share should load

### ISSUE THREAD

**Issue by MartLubben** [quintel/etmodel#2931]
The technical specs of the buildings_collective_heatpump_water_water_electricity_share are not loading. 

{"errors":["undefined method `converter' for nil:NilClass"]}

![screen shot 2019-01-29 at 12 16 50](https://user-images.githubusercontent.com/33415156/51904780-d32a4800-23bf-11e9-80e8-d236827591fb.png)

**Comment by michieldenhaan** [comment]
In the ETModel admin interface you can set a 'related converter'. The specs of the node you set there will show up in the technical specs table. In this case, the related converter was accidentally set to `buildings_collective_heatpump_water_water_electricity_share` instead of `buildings_collective_heatpump_water_water_electricity`

![pro energytransitionmodel com - energytransitionmodel 2019-01-30 11-20-08 1](https://user-images.githubusercontent.com/32056448/51974806-0f71ad00-2481-11e9-9e21-dae3ca7b727c.png)
