### ISSUE TITLE
Renewable energy share is lower on BETA compared to PRO (NvdT national scenario)

### ISSUE THREAD

**Issue by michieldenhaan** [quintel/etmodel#2960]
Not sure why but the difference is quite big:

![pro energytransitionmodel com - energy transition model - your free independent comprehensive fact-based scenario builder 2019-02-11 10-40-22 1](https://user-images.githubusercontent.com/32056448/52555339-b2afb400-2de9-11e9-9ac1-4e44cc8f80f0.png)

There seems to be more fossil gas use on BETA compared to PRO
![beta-pro energytransitionmodel com - energy transition model - your free independent comprehensive fact-based scenario build 2019-02-11 10-41-13 1](https://user-images.githubusercontent.com/32056448/52555321-a7f51f00-2de9-11e9-9893-d269d905fe90.png)

**Comment by ChaelKruip** [comment]
I have excluded that this has to do with the price of imported electricity.

**Comment by marliekeverweij** [comment]
It probably has something to do with the updated heating calculations in households and buildings. I have compared the final demand charts and there are huge differences:

- Network gas households: on BETA final demand is 27 PJ higher
- Hot water households: on BETA final demand is 20 PJ higher
- Hot water buildings: on BETA final demand is 7 PJ higher

The heat demand in houses rises on BETA and decreases on LIVE:

![screen shot 2019-02-12 at 09 51 34](https://user-images.githubusercontent.com/32833996/52623460-9e80bb00-2eac-11e9-887c-bfc4bed14bef.png)

![screen shot 2019-02-12 at 09 52 16](https://user-images.githubusercontent.com/32833996/52623490-b35d4e80-2eac-11e9-820e-f76ae8b807cd.png)

Even though the number of houses in the future is the same. 

I am going to check the insulation calculation now

**Comment by ChaelKruip** [comment]
> It probably has something to do with the updated heating calculations in households and buildings.

It seems that you are onto something big @marliekeverweij!

**Comment by marliekeverweij** [comment]
So far the issue seems to be two-fold:

1. The calculation method for migrating the insulation sliders seems to be incorrect. Therefore, the buildings/households useful heat demand on BETA is higher for most scenarios! So the insulation sliders have to be migrated again, sorry @antw..... @ChaelKruip and I are still figuring out how the insulation sliders could be migrated best.

2. I think that the gquery used for the renewability chart doesn't take into account imported green gas correctly, because somehow the renewable gas used in a scenario is not displayed in the chart. Instead of showing renewable gas, the chart shows natural gas! And therefore the renewability share is so low! (probably fall-out of the biomass project)

The green gas gquery (for the renewability chart) looks like this:
https://engine.energytransitionmodel.com/data/latest/gqueries/final_demand_of_sustainable_natural_gas_and_derivatives_in_renewability
![screen shot 2019-02-12 at 16 02 36](https://user-images.githubusercontent.com/32833996/52645450-1a94f600-2ee1-11e9-8098-cf6f13a7cdd3.png)

@antw, does `supply_of_.....` take into account foreign demand? And how is the `sustainability_share` calculated?

**Comment by antw** [comment]
> @antw, does `supply_of_.....` take into account foreign demand?

I'm not exact sure what you're asking, but `supply_of_...` simply returns the amount of energy being supplied to the node belonging to the named carrier.

In a default scenario, households final demand for network is supplied with 285B network gas, therefore `supply_of_network_gas` returns 285B.

> And how is the `sustainability_share` calculated?

This might need to be adjusted to stop recursing when reaching a primary_energy_demand node; currently it expects to recurse all the way to a domestic dead end (far right of the graph, or border between domestic and abroad). I'll look into it today.

**Comment by marliekeverweij** [comment]
> In a default scenario, households final demand for network gas is supplied with 285B network gas, therefore `supply_of_network_gas` returns 285B.

Okay!

> This might need to be adjusted to stop recursing when reaching a primary_energy_demand node; currently it expects to recurse all the way to a domestic dead end (far right of the graph, or border between domestic and abroad). I'll look into it today.

Thanks for making time for that. Currently the calculated sustainability share is not increasing when green gas is imported in a scenario. Note: the new biomass carriers already have the attribute `- sustainable = 1.0`

**Comment by antw** [comment]
> This might need to be adjusted to stop recursing when reaching a primary_energy_demand node

This change has been published to beta and seems to have largely fixed the calculation of renewables:

* The NvdT national scenario now has 91.9% renewables (vs 93.1% on production).
* Increasing green gas increases renewability, from 5.4% in a default NL2050 scenario to 48.7% when using 100% green gas (vs 48.1% on production).

**Comment by ChaelKruip** [comment]
Closing this issue. There seems to be another issue with incorrect migrations of insulation sliders but I'll open a new ticket for that.
