### ISSUE TITLE
Users should not be able to slide the insulation sliders to the left

### ISSUE THREAD

**Issue by marliekeverweij** [quintel/etmodel#2984]
Currently users could slide the insulation sliders to the left and set a lower insulation percentage than the start value. This 'negative' insulation is not realistic: people will in all probability not remove their insulation. Therefore, we do not want to allow 'negative insulation'.

We just partly fixed this issue by updating the insulation input statements: when the insulation slider setting is lower than the start value, the start value is used for calculation and therefore the insulation costs and heat demand will not change when the slider is slid to the left (https://github.com/quintel/etsource/commit/3952072296eb05944780d3bbaaea6bc1808cb24e). However, the insulation slider still shows the lower percentage, which is confusing for the user. 

One option is to set the `- min_value_gql` of the slider to the start value. This would mean that for every dataset ánd every housing type the start value would be different and this would mean that the image showing the insulation levels should change for every dataset ánd every housing type. So every housing type should then have their own label-image! This would be undoable...

Another option is to keep the `- min_value = 0.0` and somehow limit the insulation slider on the left side: users should not be able to slide the slider to the left. This would be wonderful! @AlexanderWirtz, @ChaelKruip and I were wondering if this would be possible. 

@antw, is this possible and how much time would it cost you to implement this?

**Comment by antw** [comment]
> @antw, is this possible and how much time would it cost you to implement this?

[Our slider library already supports it](http://antw.github.io/quinn/#drawTo), but ETModel doesn't. I guess a day or two would be fine to add this and test it.

**Comment by ChaelKruip** [comment]
> I guess a day or two would be fine to add this and test it.

@antw Could you please schedule this somewhere in the coming weeks? I think it is not terribly urgent but at the same time important enough not to let it linger until the next deploy in half a year.

**Comment by marliekeverweij** [comment]
Just to be sure, these are the sliders for which this is relevant:
- buildings_insulation_level.ad
- households_insulation_level_apartments.ad
- households_insulation_level_corner_houses.ad
- households_insulation_level_detached_houses.ad
- households_insulation_level_semi_detached_houses.ad
- households_insulation_level_terraced_houses.ad

**Comment by antw** [comment]
> * One option is to set the - min_value_gql of the slider to the start value.
> * Another option is to keep the - min_value = 0.0

Which of these two options would you say is the correct one from a modelling perspective?

Should it *always* be invalid to reduce the level of insulation below the starting value for the dataset? If so, it would seem to me that the first option is the better of the two since ETEngine would enforce that no-one ever does this. The second option would allow other applications to reduce insulation below the start value which might not be desirable.

The first option is easier to implement in ETModel, so I might be biased in favour of that. 😉

**Comment by marliekeverweij** [comment]
I am actually in favour of the second option (sorry!):

> Another option is to keep the - min_value = 0.0 and somehow limit the insulation slider on the left side: users should not be able to slide the slider to the left

I think it's good for users to see how the insulation of the different housing types relates to each other and I think that that is better visible when the sliders are set on a certain heat reduction %. And users are also interested in the corresponding energy label. Even though the current energy label image shows the average energy label for all housing types, it still gives a feeling!

When we would go for the first option then all sliders will start in the far left. The value next to the slider would still show the heat reduction %, so users could compare that. But we cannot include an energy label image per sliders....

What do you think @michieldenhaan @ChaelKruip @AlexanderWirtz ?

**Comment by ChaelKruip** [comment]
> What do you think @michieldenhaan @ChaelKruip @AlexanderWirtz ?

Good points @marliekeverweij! I think that having the same range for all sliders is a big advantage.

**Comment by antw** [comment]
> When we would go for the first option then all sliders will start in the far left.

Sorry, I'm realising I didn't explain myself properly at all. With either option, it will be possible to have the slider *start* at zero, but disallow the user from moving the slider to the left. It just turns out to be slightly easier, and more flexible, if we *also* have ETEngine enforcing that `min_value = start_value`. The energy label image will still work correctly, and all the sliders would have the same range.

The way this would work is that ETEngine sets the min and start values to be the same, but we add an option in ETModel allowing you to set the the [drawTo](http://antw.github.io/quinn/#drawTo) option in our slider library. So in this case you could tell ETModel that you want the slider to be *drawn* with a minimum value of 0, but the visitor will not be able to *select* a value lower than the start value.

**Comment by michieldenhaan** [comment]
Epic!

**Comment by marliekeverweij** [comment]
Very nice that it's fixed! Works perfectly👌
