### ISSUE TITLE
Should it be possible to save a scenario under the same scenario ID?

### ISSUE THREAD

**Issue by marliekeverweij** [quintel/etmodel#2985]
Currently when saving a scenario users always create a new scenario ID and have to give a new name. I got feedback from OverMorgen that it would be better to be able to sometimes save a scenario under the same ID and name. In this way you can keep working in the same scenario and you do not have to communicate a new link to your client/coworker every time when the scenario is updated. 

So, maybe we can integrate a 'SAVE' option next to the current 'SAVE AS' option.

What do you think, @antw, @redekok, @MartLubben, @michieldenhaan, @ChaelKruip, @jorisberkhout, @AlexanderWirtz?

A big issue would be when two people are working in the same scenario and both want to save it. How difficult would it be to not allow this, @antw? Just like DB for example, that you get a warning that you you can't save it because somebody else is working in the scenario.

**Comment by redekok** [comment]
I get why it would be useful for OverMorgen to save a scenario under the same id. However, it could also have some drawbacks to allow users to save scenarios under the same ID and name. For example, for the Midden-Holland sessions, we've created some scenarios for which we do not want to allow anyone (other than ourselves) to make changes and save it. We do want to allow (and stimulate) people to play around with the scenarios themselves, provided that they cannot make changes to the original scenario. Hence, in this case it is required that saving the scenario creates a new scenario ID. 

Maybe it could be an option to create a step in the process of creating a scenario that allows to set whether users of the scenario are allowed to overwrite the scenario by saving it (under the same name and id). Some sort of boolean variable?

**Comment by antw** [comment]
I'm not a fan of allowing people to reuse an ID, and in fact quintel/etengine#1043 suggests taking things in the other direction: when a scenario becomes protected (saved), ETEngine would deny *anyone* from making further changes.

One possibility would be to allow users to *replace* a saved scenario, so that the saved scenario list in the ETM points to the new ID, but I'm not convinced it's worth redesigning the whole "Save scenario" page just to enable this. I guess this also doesn't solve OM's problem of wanting to reuse an ID for linking to factsheets.

**Comment by marliekeverweij** [comment]
Okay let's close this issue then 🙂

If people are in favour of saving a scenario under the same ID, we can reopen it again!
