### ISSUE TITLE
Charts that are not used should be hidden/removed from the chart list

### ISSUE THREAD

**Issue by marliekeverweij** [quintel/etmodel#2989]
We have so many charts in the chart list! For us it is already hard to sometimes find the right chart, let alone for first-time users! Would be good to hide/remove charts that are never used, so that we can easily find the charts that are interesting. Please place the charts you want to get rid of below :) 

@antw , is hard to find data on how often charts are used?

Notifying @redekok, @MartLubben , @AlexanderWirtz , @ChaelKruip , @jorisberkhout , @michieldenhaan

**Comment by redekok** [comment]
Anthony provided some [Google Analytics output](https://docs.google.com/spreadsheets/d/11OK0TPJUIYEBwz_8awf8kLD4fYqrLzMC1Y1wgj3rnjo/edit#gid=1595506131) that shows the total (unique) events between March 1st, 2018 and February 28th, 2019. Some first insights:

- The `households_final_demand_per_application` chart has by far the greatest number of events (2404 total events vs. 1595 total unique events), which makes sense because it is the first chart that users get to see when starting a scenario.

![image](https://user-images.githubusercontent.com/5946498/54679448-964d1880-4b07-11e9-9d33-2fa48bd9e12e.png)

- Most of the events are unique (on (non-weighted) average, ~90%)

- There are over 30 charts that have had less than 10 events during the period stated above. We might wanna go over these and decide whether the charts are interesting for the user.

![image](https://user-images.githubusercontent.com/5946498/54680665-bcc08300-4b0a-11e9-809f-403d499d3fc0.png)

In the stacked bar below, an overview is visualized of the number of unique and non-unique events per chart:

![image](https://user-images.githubusercontent.com/5946498/54680791-0ad58680-4b0b-11e9-8327-90395603aa2b.png)

Notifying @marliekeverweij @MartLubben @AlexanderWirtz @ChaelKruip @jorisberkhout @michieldenhaan

**Comment by marliekeverweij** [comment]
I've hidden the following four charts/images, because they are now shown in our documentation https://github.com/quintel/documentation/blob/master/general/import_export.md:

![Screen Shot 2019-04-18 at 13 59 14](https://user-images.githubusercontent.com/32833996/56360058-a24df800-61e3-11e9-8b49-a3a7de611130.png)

And this one as well, since it has only been used once in the past year ;) 

![Screen Shot 2019-04-18 at 14 13 19](https://user-images.githubusercontent.com/32833996/56360213-3d46d200-61e4-11e9-803d-31b69f81b99c.png)

**Comment by marliekeverweij** [comment]
And actually also all FCE-charts and target-charts :)
