### ISSUE TITLE
What would it take to add an "Author" field to the "energy mix factsheet"?

### ISSUE THREAD

**Issue by ChaelKruip** [quintel/etmodel#3034]
Adding an "Author" (based on whomever saved the scenario) makes it easier to distinguish between versions of the Energy Mix made by the client and those made by any other user.

This feature has been requested recently. @antw how much time would it take you to add this you figure?

**Comment by antw** [comment]
> how much time would it take you to add this you figure?

Provided the scenario has been saved and the user has entered their name (and optionally company or school), showing the author name and company is very easy... it could be added in minutes. Unfortunately the ETM workflow messes this up.

When you start a scenario in the ETM it is saved in ETEngine and assigned an ID; for example "1". When you save a scenario, it creates a snapshot of the current settings by creating a _new_ scenario, which is assigned a new ID: "2".

If you return to your scenario, you will be viewing scenario "1"; the name and company will not appear on the factsheet because scenario "1" is not the saved scenario.

Similarly, if you now load scenario "2", you don't get scenario 2. You get a _new_ scenario which inherits all of the inputs and settings of scenario 2.

**Comment by ChaelKruip** [comment]
> Provided the scenario has been saved and the user has entered their name

Could we circumvent all this by using the name or email-adres of the user currently signed in (and leave the author field blank if no user is signed in)?

**Comment by antw** [comment]
> Could we circumvent all this by using the name or email-adres of the user currently signed in

Yes indeed. If the creator of the factsheet were to share the address with someone else, then the author name would not appear (or be incorrect). Perhaps this is not a problem if the users are more concerned with _printing_ factsheets?

**Comment by ChaelKruip** [comment]
> Perhaps this is not a problem if the users are more concerned with printing factsheets?

I think that is the use case which is most used but I'd have to check that.
