### ISSUE TITLE
Add an English and Dutch version of the workflow-image to the ETM landing page

### ISSUE THREAD

**Issue by marliekeverweij** [quintel/etmodel#3036]
1. First of all it should be possible to load a static image in the chart holder instead of a chart. I first thought we did this before with the import/export images (which are gone now! see: https://github.com/quintel/documentation/blob/master/general/import_export.md), but these actually were static charts and not images, right?

2. Then the next step would be to switch between two versions of the workflow (depending on the chosen language): a Dutch and English version of the workflow.

How much work would it be to realise the above two points, @antw ? And how could we do it?

FYI: https://3.basecamp.com/3797409/buckets/11228015/messages/1740072737)

**Comment by antw** [comment]
Since we don't have a way to load images instead of charts _at all_, I don't foresee any problems coding it so that the correct one is loaded depending on the currently selected language. We would just have two versions of the image, for example:

* introduction.en.png
* introduction.nl.png

**Comment by antw** [comment]
I've realised that this is much easier than I thought, since we can (ab)use the system we already have in place for creating HTML tables (merit order table, plant profitability, etc).

@marliekeverweij I can set up the workflow image for you – adding the output element, creating the template, etc – if you can provide the finished images when they're ready. The only constraint is that they should be 600 pixels wide in order to fit into the space where we place charts; any larger or smaller will cause them to appear slightly blurred. *If possible*, it would be nice to also have 1200px wide versions for high-resolution screens (such as on the Macbook).

**Comment by redekok** [comment]
> if you can provide the finished images when they're ready

I've just sent you the link to the images!

**Comment by antw** [comment]
> I've just sent you the link to the images!

Thanks! This is what it looks like:

![Screen Shot 2019-06-12 at 13 14 36](https://user-images.githubusercontent.com/4383/59350524-3768fb00-8d14-11e9-8e41-c235ce4a2c4e.png)

I like the idea of the image a lot, but I'm not 100% sold on how it looks in the page. I have a couple of minor comments:

* Could we crop the image around the edges of the arrows/boxes and remove the extra transparent space?

* I know the dark blue is the same colour as the header text, but it feels a bit out of place to me. Would it be possible to try using the same blue as the dashboard "Change" button (`#70a2cf`)? This might be *too* blue.

* Perhaps we could also try setting the grey boxes to be the very light blue used when a chart is loading (`#f5f8fb`). This also might be too much blue, and it might be too light.

* The first step says "Set a goal", but we've removed the targets tab. I'm not sure it's clear what it means to "set a goal" anymore; this might be confusing.

This is my rather mediocre attempt at photoshopping what that might look like:

![ETM_user_workflow_final-9](https://user-images.githubusercontent.com/4383/59354143-63887a00-8d1c-11e9-8213-e8c32d72ad79.png)

The colours I used are:

* Blue background: `#70a2cf`
* Light blue background: `#f5f8fb`
* "Optional" background: `#9bbfdf`
* Icons and arrows: `#b2c7d9`
* Demand / Supply / Flexibility / etc: `#ffffff`

---

After creating a 600px version, would it also be possible to export an SVG version so that I might try that as a solution for making it look nice on high-res displays?

**Comment by ChaelKruip** [comment]
> This is my rather mediocre attempt at photoshopping what that might look like:

I agree with all your suggestions @antw except that your Photoshopping skills are mediocre!

**Comment by marliekeverweij** [comment]
I also agree with your suggestions @antw !

> The first step says "Set a goal", but we've removed the targets tab. I'm not sure it's clear what it means to "set a goal" anymore; this might be confusing.

True. We should maybe better define what to do here, otherwise the user is already lost in the first step ;) Maybe 'Think of a goal'?

**Comment by redekok** [comment]
Good suggestions, @antw! Your colour scheme definitely suits the rest of the ETM "look and feel" better. 

> After creating a 600px version, would it also be possible to export an SVG version so that I might try that as a solution for making it look nice on high-res displays?

Yes, that's definitely possible! It will have to wait until tonight or tomorrow though, if that's ok?

> Maybe we could do 'Think of a goal (for your scenario)'? Then users will not go looking for a section/slider where to set a goal.

Or maybe: "What's your goal?", although it breaks the "style rule" of only using action phrases (instead of questions). I think it would also help to explain the steps well in the corresponding description left from the workflow.
