### ISSUE TITLE
Local vs. Global: translations of regions are somehow not shown

### ISSUE THREAD

**Issue by marliekeverweij** [quintel/etmodel#3089]
When I pick a region other than the Netherlands, the translation is somehow not shown...
![Screen Shot 2019-07-09 at 09 28 18](https://user-images.githubusercontent.com/32833996/60867891-1f5d9c00-a22c-11e9-9227-bb4f28a0910c.png)

**Comment by antw** [comment]
This is because area name translations aren't available to the JavaScript front-end code. It can be fixed, but not without fallout everywhere that we display area names in ETModel. I'm not confident we'll be able to make this change and find all the places we use area names in time for this milestone. I think we'll have to tackle this after the deploy.

**Comment by ChaelKruip** [comment]
> This is because area name translations aren't available to the JavaScript front-end code.

Including @sfp-kemp as he has some ideas how to improve maintenance of translations and other front-end items (side-bar items etc.).

**Comment by marliekeverweij** [comment]
@antw, how much work would it approximately be to fix this (minor) issue?
