### ISSUE TITLE
Technical and financial parameter table needs update for capacities

### ISSUE THREAD

**Issue by AlexanderWirtz** [quintel/etmodel#3100]
This table still shows the capacity per plant, but this is not obvious anymore, now that we have capacity sliders for plants (yay @DorinevanderVlies!).

I just built 59 GW worth of H2 CCGT, but the table shows this. Perhaps a simple edit would suffice to just point out that these numbers are per typical plant?

![image](https://user-images.githubusercontent.com/308563/61059808-f2f77a80-a3f9-11e9-9cff-88f716bd85bb.png)

@DorinevanderVlies @ChaelKruip reassign at will

**Comment by DorinevanderVlies** [comment]
> Perhaps a simple edit would suffice to just point out that these numbers are per typical plant?

In some slider descriptions we explain how the slider is converted into number of units of typical plants (see example below). Is that the kind of edit you have in mind?

![image](https://user-images.githubusercontent.com/19907658/61062357-61d6d280-a3fe-11e9-93db-ae7423557aa1.png)

**Comment by AlexanderWirtz** [comment]
> Is that the kind of edit you have in mind?

I meant in the table itself

**Comment by marliekeverweij** [comment]
Suggestions to change the table:

- 'Electrical capacity' could be changed into 'Electrical capacity per typical plant'
- 'MW' could be changed into 'MW per typical plant'

We could add 'Installed capacity' to the table! I think that would be interesting to know for users. They could already see it next to the slider, but also good to see it in the table: to have an idea of the costs etc.

**Comment by redekok** [comment]
> 'Electrical capacity' could be changed into 'Electrical capacity per typical plant'
I think I'm in favour of this option because it is more consistent with the other rows of the table.

> We could add 'Installed capacity' to the table!
I like this!

@ChaelKruip @DorinevanderVlies what are your thoughts on this? If you agree with @marliekeverweijs  suggestions, I can update the table.

**Comment by redekok** [comment]
I have changed the 'Electrical capacity' into 'Electrical capacity per unit'. However, I noticed that there is also a note at the bottom of the table mentioning that all values are for one typical unit, which might make it a bit redundant. Nevertheless, I'm still in favour of using 'Electrical capacity per unit` because I think it is more clear this way.

Furthermore, I'm actually not really sure how to include the total installed capacity in the table. @antw would it be possible to use a query in [`converter_presenter_data.rb`](https://github.com/quintel/etengine/blob/master/app/models/api/v3/converter_presenter_data.rb#L15) instead of a converter attribute? 

![image](https://user-images.githubusercontent.com/5946498/61697021-b51e1e80-ad36-11e9-8ba7-1f3a458e7b50.png)
