### ISSUE TITLE
Electricity demand and supply do not match

### ISSUE THREAD

**Issue by michieldenhaan** [quintel/etmodel#3101]
Seems to happen for multiple datasets, e.g. blank NL 2015:

![beta-pro energytransitionmodel com - Energy Transition Model - Your free, independent, comprehensive, fact-based scenario build… 2019-07-11 17-05-17(1)](https://user-images.githubusercontent.com/32056448/61062321-4ff52f80-a3fe-11e9-8c73-e978735eee5c.png)

**Comment by antw** [comment]
I'm not 100% sure, but I think it could be related to electricity technologies in Fever. It looks like electricity demand *after* the merit order has run is lower than *before*. Before merit runs, the total electricity demand is 426.02 PJ, but after it falls to 425.89 PJ. The only electricity demand that may change during the calculation are the dynamic electricity curves produced by Fever.

There does appear to be a very small amount of buffering or time-shifting of household heat demand in a default NL scenario (this is not new). Perhaps I've failed to account for the variable efficiency of heat pumps somewhere, and this is leading to an incorrect demand being set.

However, the electric heater also seems to be affected and its efficiency should be constant. Perhaps it is due to periods of insufficient heating capacity: supply of electricity falls because it isn't needed, but we're forgetting to reflect that in the graph? I don't think that's the case, because both Merit and Fever *do* set the demands of nodes based on the actual production/consumption curves after they are run. 

I'll investigate further.

**Comment by michieldenhaan** [comment]
Interesting. 

> Perhaps it is due to periods of insufficient heating capacity

The ``energy_power_hv_network_electricity`` node shows a bit of shortage, exactly the 'missing' amount:
![beta-engine energytransitionmodel com - EnergyTransitionModel 2019-07-11 23-01-51(1)](https://user-images.githubusercontent.com/32056448/61085182-ef7ee600-a42f-11e9-9ab6-be768bfc7561.png)

When setting the space heating sliders to 100% gas in both households and buildings the deficit disappears. When setting them to 100% electric heaters (which are modelled as 'back-up' heaters, i.e. installed capacity is generally too low to supply a household's full heat demand) the deficit is amplified.

**Comment by antw** [comment]
No luck figuring this out so far. It certainly seems to be related to electricity technologies in Fever, but I don't understand why.

Locally I have:

* Disabled all buffering.
* Disabled all deferring.
* Set the electric heater capacity to 1MW (instead of 6kW).

Yet the electricity shortage still exists, and seems to increase linearly as I increase the share of the electric heater:

```
0%:  0
1%:  24.519 M
2%:  49.049 M
...  ...
10%: 245.18 M
```

The shortage is 0.9% of the demand of the heater: that doesn't seem to correspond to any efficiency or loss that I can find. The demand of the heater is the same before and after the calculation, so Fever isn't changing it in any way.

So far we can say:

* It's not due to buffering, deferring, or insufficient heat capacity.

* It's not a "real" electricity shortage as the Merit supply and demand mach up:

  ```
  Supply: 447,827,383,674.19073  
  Demand: 447,827,383,674.2245
  ```

**Comment by antw** [comment]
I've been able to track this down to between January 28th and 29th this year. Unfortunately that coincides with a fairly large merge for ETEngine and ETSource, including the replacement of separate space heating and hot water inputs with combined inputs.

* [ETEngine changes](https://github.com/quintel/etengine/compare/master@%7B2019-01-28%7D...master@%7B2019-01-29%7D)
* [ETSource changes](https://github.com/quintel/etsource/compare/master@%7B2019-01-28%7D...master@%7B2019-01-29%7D)

Next week I'll aim to narrow it down further.

**Comment by antw** [comment]
I finally have this figured out.

Plain boring electric heaters result in a mismatch due to their not accounting for output losses when calculating their electricity demand curves. I have this fixed locally.

The mismatch due to heat pumps is trickier. It's caused by heat pump efficiency now being dynamic; it changes depending on the ambient temperature. Before the Merit/Fever calculation, heat pumps are defined as having a CoP of 4.5 (electricity input is about 22.2%). However, if the CoP falls or rises, more or less electricity is demanded. This in turn means that HV losses should also change, however HV losses are static in the merit order due to them being calculated before Merit runs.

The solution is to make HV loss dynamic. I'm not yet sure of the optimum way to do this; having to inspect and sum all the other demands is expensive when it has to be done 8760 times. I expect I can update Merit itself – rather then ETEngine – to minimise the performance impact.

---

Notifying @ChaelKruip.

**Comment by ChaelKruip** [comment]
> Plain boring electric heaters result in a mismatch due to their not accounting for output losses when calculating their electricity demand curves. 

I recon this affects the water heaters only (as the space heater has 100% efficiency)?

> The solution is to make HV loss dynamic. I'm not yet sure of the optimum way to do this; having to inspect and sum all the other demands is expensive when it has to be done 8760 times. I expect I can update Merit itself – rather then ETEngine – to minimise the performance impact.

This sounds like quite a big change! Another sign on the wall that we might want to be calculating the entire graph every hour at some point right?!

**Comment by antw** [comment]
> The solution is to make HV loss dynamic.

This isn't working out. I thought that if HV loss was 5.2%, then we could just take 5.2% of total merit order demand[1] to calculate the loss in each hour. In hindsight, this is complete nonsense: not all demand or production in the merit order passes through the HV network. Locally produced electricity should not be included in the HV loss.

It does not appear to be possible to make loss truly dynamic as Merit does not know which producers/consumers are HV. Even though we could theoretically give Merit this information, it wouldn't solve the problem as excess electricity can overflow in the graph from LV→MV→HV. Merit does not have any way of knowing if or when this will occur.

Even without the "overflow" problem, we could not do `SUM(hv_production) * 5.2%` because we don't know what HV production actually is until *after* the merit order has run. The two would also seem to have a cyclical relationship: you cannot say how much loss occurs until you know how much production there is. But you cannot say how much electricity has to be produced until you know how much loss exists.

I feel like I've reached the end of the road: I don't know how to fix this. All three options we have seem to be unacceptable:

1. Remove modelling of HV loss.
2. Remove heat-pump and HHP temperature/CoP behaviour.
3. Accept the mismatch between supply and demand, and that HV losses will incorrect.

---

[1]: Technically `MAX(total_demand, always_on_production) / (1 - 0.052) * 0.052)`

**Comment by ChaelKruip** [comment]
First of all: great investigative work @antw! 😮 

> This isn't working out.

I agree that this seems to be a fundamental issue.

> Remove modelling of HV loss.

Not my favourite option either.

> Remove heat-pump and HHP temperature/CoP behaviour.

This was the focus of a development project a couple of years ago. Although it is technically very cool that the ETM can do this, the actual usefulness of the feature is not overwhelming IMO. Still, it might be unacceptable to sacrifice this feature. 

> Accept the mismatch between supply and demand, and that HV losses will incorrect.

It seems to me we have introduced this mismatch during the dynamic modelling of heat in households then? I am not aware being part of the decision making but it might have been a conscious choice to accept a small mismatch and introduce the `energy_power_hv_network_shortage` node to deal with that. In that case, this option might be still unsatisfactory but the least of three evils. 

Curious about other opinions!

**Comment by michieldenhaan** [comment]
Very nice job @antw. 

> This option might be still unsatisfactory but the least of three evils.

I agree with @ChaelKruip to leave it this way and accept the incorrect losses.

@ChaelKruip @antw Shall I close this or leave it open for future reference?
