### ISSUE TITLE
Is it correct that flh of PV are smaller for weather years than for default settings?

### ISSUE THREAD

**Issue by DorinevanderVlies** [quintel/etmodel#3167]
I notice that for all weather years the flh of PV is smaller than for 2015. 

Are the same sources and methods used for sun?

![image](https://user-images.githubusercontent.com/19907658/68663479-07ca5300-053f-11ea-80a0-fe0814fdba12.png)

**Comment by redekok** [comment]
Yes, I noticed that too. What exactly do you mean with "the same sources and method"? The flh are calculated for the weather years based on the "fit factor" I derived from the NL2015 curve. This "fit factor" is the factor between the total irradiation and the number of flh. In 2015 the total irradiation was higher than in the other weather years, resulting in a higher number of flh.

**Comment by DorinevanderVlies** [comment]
> What exactly do you mean with "the same sources and method"?

I was curious if we use the same source for solar radiation for default and weather years. Judging from your answer we do :-).

> In 2015 the total irradiation was higher than in the other weather years, resulting in a higher number of flh.

That explains the low flh for the weather years.

Is my reasoning correct?

- We always use 867 flh for PV
- If 2015 is a year with high total irradiation we underestimate flh for weather years

If it is, is it worth to check weather 2015 is indeed a year with high total irradiation and use a different value to calculate the "fit factor".

**Comment by redekok** [comment]
Yes, your reasoning is correct. It would indeed be interesting to investigate whether 2015 was a very sunny year. A few ways to go could be:

1. Check if there's any source providing information about (calculated) year-specific full load hours for solar PV in NL based on the irradiation. If this information is available, we could calculate the "fit factor" based on these numbers.
2. Use another (less sunny) year than 2015 to base the "fit factor" on.
3. Take the average of irradiation for a couple of years to base the "fit factor" on.

Option 1 would be the most thorough way to go. However, I am not sure if such a source is available which is why I'm not sure if this option is worth the (investigation) time. Hence, option 3 could be an easy fix for now?

**Comment by DorinevanderVlies** [comment]
> 
> Option 1 would be the most thorough way to go. However, I am not sure if such a source is available 

I think I found a useful source ([KNMI jaaroverzicht 2015](https://www.knmi.nl/nederland-nu/klimatologie/maand-en-seizoensoverzichten/2015/jaar)).

This source states that 2015 was very sunny with 1894 sun hours.
Is also states that the average number of sun hours is 1639.

So, if we combine 867 flh with a standard year 2015 would have 1002 flh.

We can use 1002 to determine the fit factor we use for the weather years.

*Screenshot KNMI Jaaroverzicht 2015*
![image](https://user-images.githubusercontent.com/19907658/68774466-7259bc80-062d-11ea-8c2d-24f9d3c1b59e.png)

**Comment by redekok** [comment]
Nice, thanks for investigating, @DorinevanderVlies!  

I can update the solar pv curves based on this new fit factor tomorrow morning. Is that still in time for the deploy, @marliekeverweij?

**Comment by marliekeverweij** [comment]
> Is that still in time for the deploy, @marliekeverweij? 

Yes :)
