### ISSUE TITLE
Electricity load curves for specific other industry sectors (mainly paper + food) should be added to "Load curves" data dump

### ISSUE THREAD

**Issue by marliekeverweij** [quintel/etmodel#3176]
Currently only the total electricity demand curve of all other industry subsectors is shown in the data dump (`industry_final_demand_for_other_electricity`). A client had the wish to specifically show the electricity curves of the paper and food industry. So it would be great if we could add:
- `industry_final_demand_for_other_food_electricity`
- `industry_final_demand_for_other_paper_electricity`

**Comment by antw** [comment]
The load curves dump automatically includes all the participants in the merit order. However neither of those nodes are members of the merit order, therefore we don't have hourly curves for their loads. I believe the closest we have is [`industry_final_demand_for_other_electricity`](https://beta-engine.energytransitionmodel.com/inspect/1206435/converters/industry_final_demand_for_other_electricity) which includes a lot more than just food and paper.

Personally, I'd not be in favour of adding the individual final demands (construction, food, machinery, etc) due to the impact on performance of Merit and the network calculation.

**Comment by marliekeverweij** [comment]
Okay, I understand that!

Maybe it's time to separate the food and paper sector from the 'other industry' sector...... But that's not something that's quickly done
