### ISSUE TITLE
Flex order doesn't behave as expected

### ISSUE THREAD

**Issue by redekok** [quintel/etmodel#3191]
When I tested the flex order on BETA (for a Province Noord-Holland scenario), it showed some unexpected behavior I couldn't place.

When there is 1) a huge excess of electricity (and curtailment occurs), and 2) OPAC and large-scale battery storage have high positions in the flex order, the storage in EVs shows some strange behavior. When storage in EV is positioned at the bottom of the flex order, 0.014 PJ is stored. When it is moved to the top of the flex order, only 0.005 PJ is stored. When OPAC and large-scale batteries are moved to the bottom of the flex order, the storage in EVS actually increases again to 0.021 PJ. The same behavior takes place when there is no curtailment.

![image](https://user-images.githubusercontent.com/5946498/70898456-fcae8b00-1ff4-11ea-816d-3f7d5eeaa629.png)

![image](https://user-images.githubusercontent.com/5946498/70898576-2c5d9300-1ff5-11ea-97a1-c11d288f3491.png)

![image](https://user-images.githubusercontent.com/5946498/70898681-67f85d00-1ff5-11ea-8dd6-c8a2808a1192.png)

Is there anyone who could explain this behavior to me?

Notifying @antw @noracato @ChaelKruip @marliekeverweij @michieldenhaan @MartLubben @DorinevanderVlies @jorisberkhout @AlexanderWirtz

**Comment by ChaelKruip** [comment]
> Is there anyone who could explain this behavior to me?

We should investigate this further but the following reasoning can be part of the answer:
- If EV's are the 'first' option, they will be fully charged immediately
- Because the large excesses they cannot discharge for long periods of time as there is simply no demand

If they are later in the order, it could be that they have more space left to benefit from other excess moments. 

What I don't know is if options higher in the order also are first to *discharge*. This could invalidate my reasoning. @antw do you know this?

**Comment by antw** [comment]
> What I don't know is if options higher in the order also are first to discharge. This could invalidate my reasoning. @antw do you know this?

The flexibility order only sets the order of charging, and there is no explicit ordering for discharging except that all flexibility will discharge before using any dispatchables.

Although it's not trivial to change this, it's not too difficult to do.

**Comment by ChaelKruip** [comment]
> there is no explicit ordering for discharging except that all flexibility will discharge before using any dispatchables

Is there any hard-coded ordering in this? If both P2P batteries and P2P electric vehicles are fully charged and for instance, one of them must get priority if there is insufficient demand to discharge both right? Or do they both discharge partially?

> Although it's not trivial to change this, it's not too difficult to do.

Good to know!

**Comment by antw** [comment]
>Is there any hard-coded ordering in this?

No. Whichever flex option happens to come first will be fully discharged before taking energy from the next. There is no explicit ordering given that all the flexibility options will have the same dispatchable cost (zero).

The results *will* be consistent between calculations, as it will be based on the order in which Atlas returns a list of nodes, and that order is the same each time.

**Comment by marliekeverweij** [comment]
> The flexibility order only sets the order of charging, and there is no explicit ordering for discharging except that all flexibility will discharge before using any dispatchables.

Do we want to change this? Do we maybe want the order of discharging to be the same as the order of charging?

**Comment by ChaelKruip** [comment]
? Do we want to change this? Do we maybe want the order of discharging to be the same as the order of charging?

If possible I think that would make sense yes.

**Comment by antw** [comment]
> The flexibility order only sets the order of charging, and there is no explicit ordering for discharging except that all flexibility will discharge before using any dispatchables.

I'm not sure what I was thinking when I wrote this. 😊 

Flexibles _are_ ordered when discharging, and they have been [since 2017](https://github.com/quintel/merit/commit/0b8ddfd4421b7930410912c09b6f7784ba389cba). They are ordered inversely from their charging order. So if your flexibility order is P2P → EV when charging, the order when discharging (as a dispatchable producer) will be EV → P2P.

It could be that the inverse order is the reason for the behaviour described by @redekok, but it will be easier to test this hypothesis without a scenario.
