### ISSUE TITLE
The CHP-update creates major changes with the measured starting year. 

### ISSUE THREAD

**Issue by MartLubben** [quintel/etmodel#3242]
Now that the CHPs follow the electricity market the result is that they are turned off in many empty scenario's, while they are part of the mix in the starting year. This creates significant difference between the present and the future without touching a slider. 

In the regional datasets this effect is more extreme and not understandable for users without Quintel supervision. For exmaple in Holland Rijnland the Nuon CHP for the heat network in Leiden and the agricultural CHP's are all turned off. 

A solution could be a toggle for those CHP's with must-run/dispatch-able.

I am curious what you think @AlexanderWirtz 
Notifying @jorisberkhout @ChaelKruip @DorinevanderVlies @michieldenhaan @antw @marliekeverweij @redekok @noracato 

See full load hours future for NL empty scenario:
![Screenshot 2020-02-28 at 10 56 39](https://user-images.githubusercontent.com/33415156/75538563-128af400-5a19-11ea-9cc7-58659e6d440f.png) 

Heat back-up in Holland Rijnland empty scenario.
![Screenshot 2020-02-28 at 09 48 12](https://user-images.githubusercontent.com/33415156/75538971-cc826000-5a19-11ea-83dc-e03bd9394526.png)

**Comment by AlexanderWirtz** [comment]
In my opinion this issue cannot be tackled without looking at the dataset, since the FLH for the present are determined by those. Ultimately the dataset tries to reproduce fuel use for E-production. There are of course many ways of doing so. The issue _might_ be solved merely by coping the FLH for the future dataset in an empty scenario to the present dataset and then tweaking installed capacities etc to reproduce fuel use. I am not saying that is the solution of course. I am merely saying the present FLH are not holy and immutable. 

If we need to solve this urgently, we can introduce a toggle, I suppose, but it is quite an ugly solution. Taking this up in the context of an update to the 2018 data could be advisable.
