### ISSUE TITLE
Solar PV curtailment chart and table should be linked

### ISSUE THREAD

**Issue by marliekeverweij** [quintel/etmodel#3290]
In the admin-interface I tried to link the solar PV curtailment chart and table by adding a 'related (hourly) output element' to the (annual) table (number 256). This is how it usually works. However, the button does not show up in the hourly solar pv curtailment chart. Would be nice if it does!

![Screen Shot 2020-03-24 at 13 52 26](https://user-images.githubusercontent.com/32833996/77427569-ec1d6600-6dd6-11ea-98a3-53b2d734cd85.png)

**Comment by antw** [comment]
> This is how it usually works.

Sorry to be contrary, but no it isn't: the "related output element" field is a one-way relation. It was originally pitched as a "Show time-resolved chart" button for some of our summary charts. For example, the "Electricity production" chart links to the "Electricity production per hour" chart. 

As it was a one-way link from summary-to-time-resolved charts, we instead visualised it as a toggle switch instead of a link. We then thought it would be nice to link back to the previous chart in case the user wished to revert to the summary.

However, there is no link from the hourly chart back to the summary chart _if you load the hourly chart first_ from the chart picker. The reason is showing an "Annual" toggle on the hourly chart wouldn't make any sense (it should instead show "Hourly"). The feature isn't able to tell which chart is the summary and which is the hourly.

Therefore it doesn't make any sense to me to put an Annual/Hourly toggle on the curtailment chart unless we revamp the feature to:

* Track which chart is "Annual" and which is "Hourly".
* Restrict the feature so that each chart can have only one relatee (currently, multiple summary charts can _and do_ link to the same hourly chart).

**Comment by noracato** [comment]
I understand that the way we want to use the toggle here is not in line with how it was originally intended. And I agree we'd have to revamp and rethink the toggle feature if we do want to use it on the curtailment chart.

However I do think having a toggle between the solar curtailment charts (both ways) is helpful, especially because the annual summary table is not linked to any slide right now. So I want to propose to make this revamp happen. I don't know who the original creators of this toggle were, and if they have an opinion about changing it?

In my PR I made sure 'hourly' was shown above the hourly chart as I was basing the toggle on the relatee. But I understand that the toggle may now show up at other charts as well, and that that may have not been the intention of the respective chart creators. So I'll take the PR down!

**Comment by marliekeverweij** [comment]
Thanks for your messages @anthony and @noracato !

I realise now that the reason why I wanted to link the solar PV chart and table is to be able to link them both to one slide. So actually wanted to (mis)use the hourly/annual-toggle for this. In this BC message I wrote down this wish: https://3.basecamp.com/3797409/buckets/6180918/messages/2170362744

@antw you told me once that that's very complicated to show more charts next to a slide, because the chart software should be revised for this. How much time do you think this will take? :)

**Comment by marliekeverweij** [comment]
I had an idea: to link the table with the hourly chart with the table-button

The table-button is only available for stacked bars, beziers and mekkos. We could maybe also make it available for the hourly solar pv chart. It is a separate chart from the other hourly charts, so if we would add the table to the solar pv chart it will not be added to all hourly charts.

What do you think @noracato and @antw? If you also think this is a good idea, I am wondering how much time it would take to implement.

**Comment by marliekeverweij** [comment]
> The table-button is only available for stacked bars, beziers and mekkos. We could maybe also make it available for the hourly solar pv chart. It is a separate chart from the other hourly charts, so if we would add the table to the solar pv chart it will not be added to all hourly charts. What do you think @noracato and @antw? If you also think this is a good idea, I am wondering how much time it would take to implement.

@noracato and @antw, I am curious what you think. If you think that this is a bad idea, then we should maybe close this issue and leave it since the text on the slide already directs the user to the table
![Screenshot 2020-05-25 at 10 24 57](https://user-images.githubusercontent.com/32833996/82794053-286e5080-9e72-11ea-91b2-099d43257498.png)

**Comment by marliekeverweij** [comment]
Not relevant anymore, see https://github.com/quintel/etmodel/pull/3439
