### ISSUE TITLE
Deficits should be included in the merit and heat network data exports

### ISSUE THREAD

**Issue by redekok** [quintel/etmodel#3303]
One of our clients pointed out that the merit data export is imbalanced when the load of a power plant (energy_power_combined_cycle_hydrogen in this case) reaches its maximum. I tried to reproduce it in [this scenario](https://pro.energytransitionmodel.com/scenarios/753299) and indeed ran into the same bug:

![image](https://user-images.githubusercontent.com/5946498/78810210-5aae1680-79c8-11ea-8fab-e69d0042403b.png)

Here's the underlying analysis:
[merit_order.753299.xlsx](https://github.com/quintel/etmodel/files/4451689/merit_order.753299.xlsx)

@antw, would you have any idea what's going on here?

Notifying @ChaelKruip

**Comment by antw** [comment]
I don't have a copy of Excel available, and while the spreadsheet seems to load in Numbers it replaces some formulas with their previously-calculated value. I can see what the formulas _should_ be, but my Excel-fu isn't good enough to decipher them. :wink:

```
=SUMIF($E$1:$EP$1,_xlfn.CONCAT("*",A$1),$E442:$EP442)
```

![tenor](https://user-images.githubusercontent.com/4383/78812811-e7a2a100-79c3-11ea-9c72-26012caaaf9e.gif)

I'm guessing `.input` is the sum of all inputs, and `.output` is the sum of all outputs?

> when the load of a power plant (energy_power_combined_cycle_hydrogen in this case) reaches its maximum.

By this, do you mean the bug is triggered when load of a dispatchable plant equals its capacity? The bug isn't there so long as the load remains lower than the capacity?

**Comment by redekok** [comment]
> I'm guessing .input is the sum of all inputs, and .output is the sum of all outputs?

Indeed!

> By this, do you mean the bug is triggered when load of a dispatchable plant equals its capacity?

Yes!

> The bug isn't there so long as the load remains lower than the capacity?

That's what I'm guessing. When I touch some sliders to make sure there's less demand -- for instance, by increasing the insulation slider values -- and the loads of the dispatchable plant remain below its max capacity, the merit data export seems to balance just fine. 

I'm guessing the

**Comment by antw** [comment]
Good news: this isn't a bug! 😅

There are two hours where input and output are mismatched:

| Time | Demand | Production | Deficit |
| --- | --: | --: | --: |
| 2050-01-19 18:00 (450) | `37289.7550` | `36835.6551` | `454.0999` |
| 2050-01-19 19:00 (451) | `37271.7460` | `36835.6551` | `436.0909` |

**2 mismatches**

This exactly matches the `dashboard_blackout_hours` query: the mismatches are due to insufficient production capacity in the scenario. We don't represent deficits in the merit order, and so they also don't appear in the merit order CSV.

**Comment by ChaelKruip** [comment]
> We don't represent deficits in the merit order, and so they also don't appear in the merit order CSV

This might be confusing for some users (as we have seen). Is there an elegant way to include deficits as a participant and have them show up in the data-dumps?

**Comment by antw** [comment]
> Is there an elegant way to include deficits as a participant

It can surely be done, but I think not _elegantly_.

* Mismatched supply and demand are used to calculate blackout hours and loss of load. A "deficit producer" would mean supply always meets demand.
* Merit relies on _not_ having a producer-of-last-resort when setting the electricity price for those hours where there are deficits.

Solving these would mean having to special-case the deficit producer, and requires that we always remember that the producer must be treated differently when writing merit order related code in the future.

We could add a hard-coded column to the merit CSVs (electricity and heat network) which has the different between all inputs and outputs.

**Comment by redekok** [comment]
Thanks for your clarification @antw. That explains!  

> Solving these would mean having to special-case the deficit producer, and requires that we always remember that the producer must be treated differently when writing merit order related code in the future.

That sounds like a suboptimal solution of which I wouldn't be in favour.

> We could instead add a hard-coded column to the merit CSVs (electricity and heat network), which has the different between all inputs and outputs.

I guess that could be a solution? In addition, we could also add an extra line of explanation on this in the paragraphs on the heat and electricity curves in the front-end?

**Comment by ChaelKruip** [comment]
> I guess that could be a solution? In addition, we could also add an extra line of explanation on this in the paragraphs on the heat and electricity curves in the front-end?

I'm in favour of those two things :)

**Comment by redekok** [comment]
I've renamed and reopened this issue again. I can add an extra line to the front-end. @antw, would be nice if you could add the extra hard-coded column to the data exports.
