### ISSUE TITLE
P2H Heat Pump for district heating should not result in extreme storage losses

### ISSUE THREAD

**Issue by ChaelKruip** [quintel/etmodel#3324]
![image](https://user-images.githubusercontent.com/1303760/79953358-02711d00-847c-11ea-960c-e23e4697b3ae.png)

The storage losses result in a LOT of back-up heater. Especially with lower installed capacity of P2H, the losses for storage are larger than the actual heat produced by the P2H unit!

This scenario shows the issue: https://pro.energytransitionmodel.com/saved_scenarios/9143

**Comment by michieldenhaan** [comment]
Findings so far:

- Only affects P2H heat pumps, not P2H boilers
- There seems to be a weird link between heat pump production and the back-up heater. The scenario has a large heat surplus in storage at the end of the year so you would expect that the back-up heater is not needed. In the scenario, heat pump P2H supply is 34.72 PJ heat. The back-up heater produces 121.48 PJ heat. The heat pump has a COP of 3.5. And back-up heater production seems to be exactly 3.5 times heat pump production... 🤔

**Comment by antw** [comment]
I've pushed a hotfix to both staging and production. The issue appears not to be that storage losses are too high, but that P2H demand/production was set too low. It was based on the electricity input (from Merit), but failed to account for the electricity input conversion, treating it as 1.0 instead of 0.22.

The fix will affect the P2H heat-pump, and any other flexibility option which doesn't have an explicit `merit.subtype`, but other flex options may still be affected. I will double check these today and come up with a more general fix.

<img width="614" alt="Screenshot 2020-04-22 at 10 03 30" src="https://user-images.githubusercontent.com/4383/79962883-8cbb8000-8480-11ea-8a5d-136f7fb6304d.png">
