### ISSUE TITLE
We should remove the household heat pump buffers from the ETM

### ISSUE THREAD

**Issue by marliekeverweij** [quintel/etmodel#3325]
The heat demand profiles for households have been smoothed a month ago. One of the effects is that heat deficits do not occur anymore for all heat pumps (air, ground, hybrid). At least that is what I conclude from the charts below (scenario: https://beta-pro.energytransitionmodel.com/saved_scenarios/4488)
![Screenshot 2020-04-22 at 10 52 52](https://user-images.githubusercontent.com/32833996/79961802-84b30e80-8487-11ea-822a-ef11cc845255.png)

This is what I see when using the heat buffer sliders:

- If I install heat buffers for heat pump **ground** and heat pump **air** (hot water and space heating), only the total costs changes and nothing else (CO2, energy use)
- If I install a heat buffer for the **hybrid** heat pump, also the energy use and % renewables changes. This is interesting, since no heat deficits take place....

![Screenshot 2020-04-22 at 10 56 36](https://user-images.githubusercontent.com/32833996/79962289-263a6000-8488-11ea-8814-2682145634b7.png)

@antw , @DorinevanderVlies do you maybe have time to look into this? 

If heat buffers do not have an effect anymore, we should consider removing this feature!

Notifying @ChaelKruip

**Comment by antw** [comment]
I don't feel qualified to say whether it's right to remove the buffers or not from a modelling point of view. However, anything that makes heat pumps simpler (especially HHPs) gets a big :+1: from me; so...

# :+1:

**Comment by ChaelKruip** [comment]
@AlexanderWirtz @jorisberkhout @michieldenhaan @MartLubben what do you think?

**Comment by DorinevanderVlies** [comment]
Ok for me to remove them.

I remember Gasunie was keen on this addition. So I think we should inform them before removing het buffers. We can explain that the effect is non-existent with the update of the smoothed curves. I have to contact Martijn this afternoon about II3050 presets and will ask/inform him about this.

**Comment by marliekeverweij** [comment]
Gasunie has agreed that we could remove this section! @mabijkerk could you maybe pick this up this week?

This is the section where it's all about: https://beta-pro.energytransitionmodel.com/scenario/flexibility/flexibility_net_load/demand-response-buffers-for-heat-pumps

Removing this section includes removing:
- the slide (ETModel)
- the sliders / input elements (ETModel)
- the slide and slider translations (ETModel)
- the inputs for the sliders (ETSource), these can be found here: https://github.com/quintel/etsource/tree/master/inputs/flexibility/households
- the section about buffers on our documentation: https://docs.energytransitionmodel.com/main/heat-pumps

**Comment by marliekeverweij** [comment]
@antw the back-end should also be removed at some point, but has no hurry. We can keep the issue open until that's sorted

**Comment by mabijkerk** [comment]
@marliekeverweij I created pull request for "remove-heat-pump-buffers" branches in ETModel, ETSource and Documentation.

**Comment by mabijkerk** [comment]
I have removed the household heat pump section as requested. The following graph however still shows the possibility for deficits, and for buffering and time-shifting:

<img width="620" alt="Screenshot 2020-11-12 at 17 06 50" src="https://user-images.githubusercontent.com/67338510/98964734-7868ce80-2509-11eb-982d-ce93f8362257.png">

@antw @DorinevanderVlies does either of you know whether deficits, buffering and time-shifting can still occur for households now that the option to set household heat pump buffers has been removed from the model? I ask this because deficits, buffering and time-shifting does still occur for buildings, even though no sliders can be set manually for heatpumps buffers in buildings:

<img width="633" alt="Screenshot 2020-11-12 at 17 12 46" src="https://user-images.githubusercontent.com/67338510/98965406-4c018200-250a-11eb-91fb-2496d476fbf0.png">

If, with the removal of heat pump buffers for households, deficits and buffering and time-shifting can no longer occur for households, then we can delete those timeseries from the "Heat demand and production in households" graph right?

Finally, we might also need to revise the documentation (https://docs.energytransitionmodel.com/contrib/fever/).

**Comment by antw** [comment]
> @antw @DorinevanderVlies does either of you know whether deficits, buffering and time-shifting can still occur for households

Yes. Space heaters are allowed to defer (time-shift) their demand [up to four hours](https://github.com/quintel/etsource/blob/aa28d24f2d0b542fb2fdaebe9a53241aa6af8d89/graphs/energy/nodes/households/households_space_heater_heatpump_air_water_electricity.converter.ad#L14).

**Comment by mabijkerk** [comment]
> Yes. Space heaters are allowed to defer (time-shift) their demand up to four hours.

Ok, thanks for the explanation! Then this issue can remain open until the back-end is removed.

**Comment by marliekeverweij** [comment]
@antw we maybe want to keep the buffers for hot water heat pumps in households. So could you not remove the back-end of the buffers yet? :)
