### ISSUE TITLE
EV batteries and Household batteries show rather different network impact in iNET scenarios

### ISSUE THREAD

**Issue by AlexanderWirtz** [quintel/etmodel#3327]
@ChaelKruip and I were preparing the iNET meeting on Tuesday evening and found some remarkable differences in how EVs and HH batteries affected the network peak loads at different grid levels. We had expected these batteries to have a similar effect, since they are both connected to the LV grid and EV-flex behaviour or availability is currently not coupled to their charging behaviour (@ChaelKruip has assured me).

Example: scenario: https://pro.energytransitionmodel.com/saved_scenarios/9131
Lots of surpluses and also 25% curtailment of all kinds of solar PV capacity. 
 
I start by setting EV to 0% in Flex >> Storage. Have a look at grid impact on LV and LV/MV:
![image](https://user-images.githubusercontent.com/308563/80082155-4172a180-8554-11ea-94dc-7a98b2030df0.png)

Then is show the impact of 20% EV (5.9 GW). This is the scenario's original setting. EV-batteries in 1st place in the flex merit order:
![image](https://user-images.githubusercontent.com/308563/80082269-66ffab00-8554-11ea-92e2-4e0499796600.png)

Compare this to the impact (almost) the same installed capacity of HH batteries has (1st place in flex merit order):
![image](https://user-images.githubusercontent.com/308563/80082495-c2319d80-8554-11ea-92c6-15f6290684a9.png)

I struggle to explain this difference. @ChaelKruip had already noted that the batteries 'leakage' for EVs and HH batteries seem exactly a factor 10 different.

Unfortunately I do not have time to prepare this issue further, but perhaps this is enough to see what is going on, @michieldenhaan and @antw ?

**Comment by AlexanderWirtz** [comment]
More background:

We are trying to install a certain amount of LV batteries to lower the peak lead on that grid level, without causing lots of power to flow from higher grid levels to the LV-level batteries. This is undesirable. We don't want to overload the grid by storing offshore wind power in HH batteries, after all.

**Comment by ChaelKruip** [comment]
> @ChaelKruip had already noted that the batteries 'leakage' for EVs and HH batteries seem exactly a factor 10 different.

Yes. But upon inspection of the node source analyses, the difference is not exact and both figures are based on different sources. That rules out a simple typo but still raises the question of these sources are reliable.

**Comment by antw** [comment]
I think the answer is that somewhere there has been a misunderstanding about what `reserved_fraction` means.

* ETEngine / Merit _and_ the EV flexibility slider use `reserved_fraction` [to change the size of the EV buffer](https://github.com/quintel/etengine/blob/1ee1db07d11bb2757f302e98ca43519ac3c2f0c5/app/models/qernel/merit_facade/storage_adapter.rb#L79-L80) available for flexibility purposes. Assuming electric vehicles have a 20kWh battery:

  | EV slider | Reserved for driving | Available for flex |
  | :---: | :---: | :---: |
  | 0% | 20kWh | 0kWh |
  | 20% | 16kWh | 4kWh |
  | 50% | 10kWh | 10kWh |
  | 0% | 0kWh | 20kWh |

* [The query which shows installed EV capacity in the flexibility order](https://github.com/quintel/etsource/blob/f0e1a342f0bfe6b224f1c654db0e113041d38e71/gqueries/output_elements/output_series/table_164_storage_options/transport_car_using_electricity_capacity.gql) uses `reserved_fraction` to reduce the input capacity.

The ETEngine implementation is correct; at least based on [what we originally planned to implement](https://github.com/quintel/merit/issues/129): *(emphasis mine)*

> * The 'availability'-slider which quantifies which fraction of EVs is connected to the grid on average. Both capacity and volume of the batteries are to be multiplied by this fraction.
> * **The 'reserved fraction'-slider which quantifies which part of the volume is reserved for driving and cannot be discharged for load balancing. The volume of transport_car_using_electricity needs to be multiplied by 1.0 - reserved_fraction**

We don't have an EV availability slider – only a reserved fraction slider ([which is confusingly called transport_car_using_electricity_**availability**](https://github.com/quintel/etsource/blob/master/inputs/flexibility/transport/transport_car_using_electricity_availability.ad)).

I created a local copy of the above scenario. With P2P batteries at 20% and EV at 13%, here are the input capacities:

| Technology | Capacity in ETEngine and Merit | Capacity in flex order query |
| :---: | ---: | ---: |
| P2P batteries | 5,466.352941176471 | 5,466.352941176471 |
| Electric vehicles | **29,522.6071** | **5,904.521419** |

The capacity of electric vehicles in Merit is controlled by the number of EVs in the scenario, *not* the EV flexibility slider.

The reason for EVs having significantly different results on the network is that they have much higher capacity, and there therefore much more "spikey".

To make matters worse, [the query used to show EV flexibility](https://github.com/quintel/etsource/blob/f0e1a342f0bfe6b224f1c654db0e113041d38e71/gqueries/general/merit/lv/lv_flexibility_load_curve.gql) in the LV demand chart is using the wrong node; it refers to the "driving demand" node rather than the flexibility node. Corrected, the difference between P2P and EV flexibility is quite obvious:

| P2P @ 20% | EV @ 13% |
| :---: | :---: |
|  ![Screenshot 2020-04-23 at 15 50 14](https://user-images.githubusercontent.com/4383/80113408-2f0b5e80-857a-11ea-9c56-d9ed15a60d5d.png) | ![Screenshot 2020-04-23 at 15 50 04](https://user-images.githubusercontent.com/4383/80113432-3599d600-857a-11ea-8c43-741f0bb141a5.png) |

**Comment by AlexanderWirtz** [comment]
bravo, @antw ! So i guess that means there was a bug and then some misunderstanding. I am still not sure I really understand the issue or even how EVs work fully. How do we report back to iNET about the way batteries work in the scenarios, @ChaelKruip ?

**Comment by michieldenhaan** [comment]
Thanks @antw!

So if I understand this correctly, the following is the case:

- The available EV battery **capacity** for flex is always 100% of total EV capacity, regardless of whether the user chooses to use EV batteries for flex or not
- By default, 100% of the available battery **volume** is 'reserved' for driving, so effectively EV batteries aren't used for flex unless the user changes the default.

The slider allows users to change the latter, the reserved fraction.
_Example:_
_Suppose a scenario has 1 million cars. ETM default is 100 kWh per car with a charging capacity of 3.7 kW per hour._

_This means that we have 3.7 GW installed battery capacity with 100 GW volume._
_Suppose the user sets the EV flex slider to 10% -> The 3.7 GW batteries now have 10 GWh available for flex._
_Suppose the user changes the slider to 50% -> The 3.7 GW batteries now have 50 GWh available for flex._

**So the installed capacity stays the same, only the volume of the battery changes.**

@antw Is this interpretation correct?


> To make matters worse, the query used to show EV flexibility in the LV demand chart is using the wrong node; it refers to the "driving demand" node rather than the flexibility node. Corrected, the difference between P2P and EV flexibility is quite obvious

Are you sure the original query was wrong? As far as I can see the chart shows total electricity demand on the LV grid. So I would expect the 'electric vehicles' series to show "driving demand", not flex demand. Shouldn't EV flex rather be included in the "Flexibility" series (together with households P2P)?

**Comment by antw** [comment]
> So the installed capacity stays the same, only the volume of the battery changes.
> 
> @antw Is this interpretation correct?

Indeed.

> Are you sure the original query was wrong? As far as I can see the chart shows total electricity demand on the LV grid. 

You're absolutely right. I've reverted my change to this query and will add EV P2P to the flexibility series.

**Comment by antw** [comment]
I'm ready to fix this. We have two options:

1. Use a single slider which sets both the available storage volume *and* the available input capacity for flexibility.
2. Use separate sliders, one which sets the available storage volume, and one which sets the input capacity.

I strongly favour (1) from a code point of view. It's simple to have a slider set the availability of the flex node, and have this affect both the volume and capacity simultaneously. It and means we can get rid of the `reserved_fraction` attribute, which was only used on this one node. (2) means having to treat input capacity and volume differently in code: input capacity affected by availability, but volume _not_ affected.

I also think option 1 is clearer for users: with option 2, users may be confused why they moved one of the sliders and didn't see any P2P occurring.

With option 1, if the user sets the EV flexibility slider to 20% this means that 20% of the buffer, and 20% of the EV capacity will be available for flex:

#### Before (Passenger EV share = 100%)

| Slider position | EV flex capacity in MO | Avail. for flex |
| :--- | --: | --: |
| 20% | 29,522 MW | 159,581 MWh |
| 50% | 29,522 MW | 398,954 MWh |
| 100% | 29,522 MW | 797,908 MWh |

#### After (Passenger EV share = 100%)

| Slider position | EV flex capacity in MO | Avail. for flex |
| :--- | --: | --: |
| 20% | 5,904 MW | 159,581 MWh |
| 50% | 14,761 MW | 398,954 MWh |
| 100% | 29,522 MW | 797,908 MWh |

**Comment by ChaelKruip** [comment]
> I strongly favour (1)

Me too! Also discussed with @michieldenhaan and he agrees. Let's go for it!
