### ISSUE TITLE
Reconsider hiding flex-options in the flex-Merit Order as they are not installed

### ISSUE THREAD

**Issue by ChaelKruip** [quintel/etmodel#3336]
From https://github.com/quintel/etmodel/issues/3335#issuecomment-621795821:

> I think we should revisit the decision to hide flex options with no capacity, but that's a discussion which I'll take elsewhere.

The hiding keeps the list nice and clean but has the annoying side-effect that you have to re-position a technology that you have (temporarily) removed by setting its capacity to zero. This happens quite easily and it turns out to be very hard to remember revisiting the flex MO every time you re-introduce a technology.

Perhaps we can grey-out non-installed technologies instead of hiding them? Or remember their place in the MO from before even when they have been removed so they can re-appear where the user left them?

**Comment by antw** [comment]
I prefer greying them out rather than hiding them completely. Doing so...

* Allows you to arrange technologies in the flexibility order *then* set the capacities of the technologies, rather than forcing you to do it the other way around.
* Might spur some to investigate and learn more about the options available in the ETM. The default, which contains only "Export" doesn't help the user understand that there are flexibility options they aren't using.

**Comment by AlexanderWirtz** [comment]
I agree with greying out
