### ISSUE TITLE
Power-to-kerosene should work again

### ISSUE THREAD

**Issue by marliekeverweij** [quintel/etmodel#3341]
[Mechanical turk failed on power-to-kerosene](https://semaphoreci.com/quintel/mechanical_turk/branches/master/builds/2506) on beta. If I install power-to-kerosene capacity, no kerosene is produced, so the CO2 emissions do not decrease. I am guessing that it has something to do with [this commit](https://github.com/quintel/etengine/commit/1a792fde45c591ab194775dd6359512eeb6d5ee9), as MT fails since Friday.
![Screenshot 2020-05-04 at 16 09 55](https://user-images.githubusercontent.com/32833996/80976441-c5197180-8e23-11ea-911e-da18f3dfeb23.png)

**Comment by antw** [comment]
I've pushed a fix, but I consider is kind of temporary. This touches on the same issue I discussed [on Basecamp](https://3.basecamp.com/3797409/buckets/4288548/messages/2634621015), which is that how we define capacity (and use it in ETEngine/Merit) is quite unclear and error-prone

In quintel/etengine@1a792fd I changed it so that a Merit Order participant with no "valid" input or output slot would have zero input or output capacity respectively. For example, the P2L node has no electricity output, therefore Merit would see that it has an output_capacity of 0 (but input_capacity of 10). This screwed up the calculation of demand (FLS × output_capacity × NoU).

There are two related things we should consider:

1. Input and output capacities are not _clearly_ defined in ETSource (IMO).
2. Merit might need to do better accounting of input and output flows of flexibles.

I'll close this issue since [the Basecamp discussion]((https://3.basecamp.com/3797409/buckets/4288548/messages/2634621015)) is about the first of these, and the second is something I can investigate when time permits.
