### ISSUE TITLE
Use more colours in Electricity price per hour chart

### ISSUE THREAD

**Issue by michieldenhaan** [quintel/etmodel#3375]
It now looks like a David Hockney iPad drawing of an overcast autumn day

![Electricity interconnector 4 - Import and export of electricity - Energy Transition Model - beta-pro energytransitionmodel com 2020-06-10 09-41-36](https://user-images.githubusercontent.com/32056448/84240668-aa12df00-aafe-11ea-901d-b4214eadd07a.png)

**Comment by ChaelKruip** [comment]
> It now looks like a David Hockney iPad drawing of an overcast autumn day

😂

**Comment by redekok** [comment]
Not sure if more colours will make it much better though. I'm afraid we would then get a blossoming spring day instead of an overcast autumn day. 😉  Would there be other ways to create a clearer overview of these price curves? Perhaps thinner lines for the interconnector prices? And a more dominant one for the hourly price? Not sure what would work best here..
