### ISSUE TITLE
Interconnection in regional scenarios has too many decimals

### ISSUE THREAD

**Issue by MartLubben** [quintel/etmodel#3388]
![image](https://user-images.githubusercontent.com/33415156/84475362-b75dd400-ac8c-11ea-9ed0-be77e3ac0468.png)

**Comment by noracato** [comment]
Can you tell me what region this is? I have Bloemendaal running locally and can't recreate your issue:
<img width="489" alt="Interconnector capacity for Bloemendaal" src="https://user-images.githubusercontent.com/14875123/84482433-00675580-ac98-11ea-81c1-37d548f9eca7.png">

**Comment by marliekeverweij** [comment]
I also found this issue for the dataset 'Alphen-Chaam':

![Screenshot 2020-06-12 at 16 14 34](https://user-images.githubusercontent.com/32833996/84512175-dd549a00-acc7-11ea-9562-58211888d7d9.png)

Do not understand how this is possible, as the input element has `- step value = 0.1` @noracato do you know what's going on?

I am removing the deploy milestone as I do not think it's deploy critical and it's also already on PRO :)

**Comment by antw** [comment]
> Do not understand how this is possible, as the input element has `step value = 0.1`

The number of decimal places [is increased](https://github.com/quintel/etengine/blob/1d6d814eafa9b8db388507e2d208de380f969ae7/app/models/scenario_scaling.rb#L86-L96) because this is a scaled/derived dataset.

I'm guessing this is a *really* tiny region?

**Comment by marliekeverweij** [comment]
> The number of decimal places is increased because this is a scaled/derived dataset.

Okay, that's why! @michieldenhaan and I have chosen to put the interconnector capacity for regional datasets to a large number and not scale it anymore, because:

_Interconnection is not relevant for (most) local datasets as "imported" electricity comes from surrounding regions via the HV grid, not from other countries via an interconnector. To prevent electricity demand to be limited by available interconnection capacity (= blackouts), it is set to a large number (60 GW)._ (pull request: https://github.com/quintel/etsource/pull/2306)

Good to know for everybody! Notifying @DorinevanderVlies , @redekok , @jorisberkhout , @ChaelKruip , @AlexanderWirtz , @MartLubben , @antw , @noracato , @michieldenhaan
