### ISSUE TITLE
Dutch scenario reports (national/regional) are unclear about change in CO2-emissions

### ISSUE THREAD

**Issue by jorisberkhout** [quintel/etmodel#3401]
It is unclear from the text if there is an increase or decrease. I would suggest using negative numbers for decrease.

![Screenshot 2020-06-15 at 11 37 24](https://user-images.githubusercontent.com/4669028/84644762-e334c000-aeff-11ea-8b09-59dc1a41a4d6.png)

![Screenshot 2020-06-15 at 11 37 40](https://user-images.githubusercontent.com/4669028/84644772-e5971a00-aeff-11ea-9774-b1f075f1de5f.png)

**Comment by marliekeverweij** [comment]
Good one! I cannot quickly figure out how to create negative numbers for CO2 reduction. As this issue is already on pro, I think it's not deploy critical. Assigning @MartLubben . If it's possible to fix it tomorrow morning before the deploy, that would be nice! But we could also cherry-pick it to production.

**Comment by MartLubben** [comment]
It already works with negative numbers. The exampe See:
![Screenshot 2020-06-16 at 09 07 36](https://user-images.githubusercontent.com/33415156/84742549-e1770500-afb0-11ea-9cdb-9ff9081124f0.png)

However, these number below should **not be 0 %**. 
![Screenshot 2020-06-16 at 09 08 42](https://user-images.githubusercontent.com/33415156/84742942-8691dd80-afb1-11ea-9ec1-e348af2e0ae4.png)
