### ISSUE TITLE
Electricity supply and demand do not balance in some scenarios

### ISSUE THREAD

**Issue by marliekeverweij** [quintel/etmodel#3421]
In [this scenario](https://pro.energytransitionmodel.com/saved_scenarios/9347) the electricity sankey does not balance. Production on the left is 65 PJ higher than demand on the right. I cannot figure out what the reason is:
![Screenshot 2020-06-25 at 16 23 23](https://user-images.githubusercontent.com/32833996/85745677-2e23b400-b706-11ea-98e4-1812c1dbb8d4.png)

I did figure out part of the reason: solar pv curtailment is included in the 'flexibility' node on the right. However, it is already subtracted from the 'solar' production node on the left. I've removed solar pv curtailment from the 'flexibility' query on [this branch](https://github.com/quintel/etsource/compare/balance-electricity-sankey?expand=1). This is 9 PJ, so there is still a difference of 56PJ

I've checked the queries, so I am guessing there's something going on in the graph, but not sure. I thought there was already a GitHub issue about the calculation of excess electricity, but couldn't find it in any repository on GitHub, so probably it's closed. @antw @michieldenhaan

**Comment by antw** [comment]
> Electricity [...] does not balance

I don't know if it's related, but there's a large imbalance in the HV node as well.

![Screenshot 2020-06-25 at 17 51 57](https://user-images.githubusercontent.com/4383/85763506-9f666580-b70c-11ea-9006-bef6e3673631.png)

It never ends. :cry:

**Comment by antw** [comment]
> I don't know if it's related, but there's a large imbalance in the HV node as well.

Perhaps this isn't a (huge?) problem. It's because of:

```
capacity_of_energy_hydrogen_flexibility_p2g_electricity: 42000.0
```

I guess P2G isn't connected to the HV network, so the electricity is produced but *disappears* from the HV node and then reappears in the flexibility node.

**Comment by marliekeverweij** [comment]
> I guess P2G isn't connected to the HV network, so the electricity is produced but disappears from the HV node and then reappears in the flexibility node.

It seems that [P2G is connected to the HV net.](https://github.com/quintel/etsource/blob/4b0ec54b904343f5a0e74685c60a54f25a3cf3cb/nodes/energy/energy_hydrogen_flexibility_p2g_electricity.ad#L10)

However, the three P2H options in this scenario are connected to the MV net, for example [P2H in chemical industry](https://github.com/quintel/etsource/blob/4b0ec54b904343f5a0e74685c60a54f25a3cf3cb/nodes/industry/industry_chemicals_other_flexibility_p2h_hydrogen_electricity.ad#L10). These technologies use 45 PJ excess electricity in this scenario, so that does not explain the imbalance in the HV node.

**Comment by marliekeverweij** [comment]
Here is an overview of total electricity production and demand in this scenario:
![Screenshot 2020-06-26 at 10 27 53](https://user-images.githubusercontent.com/32833996/85836941-b4d4a180-b797-11ea-85e7-21fc830b47c0.png)

Here's the file: [checking sankey.xlsx](https://github.com/quintel/etmodel/files/4835866/checking.sankey.xlsx)

Maybe this will help with figuring out why electricity demand is higher than production in this scenario!

**Comment by antw** [comment]
> It seems that P2G is connected to the HV net.

It's not connected to the HV *node*: its input is `energy_production_excess_electricity`, which doesn't have any input. The `merit_order.level` value is used in the network calculation only, and has no effect on the flow of energy in the graph. Energy disappears from the HV node, and reappears in the excess node, causing an imbalance there. The tendency for excess energy to "jump" around the graph without flowing through edges makes this harder to debug.

However, as long as the excess flexibility options are accounted for in the sankey chart, I doubt this is the reason for the missing 56.1PJ. My first guess would be that some production technology is absent from the chart, or a demand has been accidentally counted twice.

**Comment by marliekeverweij** [comment]
> It's not connected to the HV node: its input is energy_production_excess_electricity, which doesn't have any input. The merit_order.level value is used in the network calculation only, and has no effect on the flow of energy in the graph. Energy disappears from the HV node, and reappears in the excess node, causing an imbalance there. The tendency for excess energy to "jump" around the graph without flowing through edges makes this harder to debug.

Thank you. I did not know that there is a difference between the `merit_order.level` value for flexibility options and the connection to nodes in the graph. So all excess electricity for flex technologies disappears from the HV node in the graph regardless of their `merit_order.level`?

I had another look at the scenario I had sent (without the [solar pv curtailment fix](https://github.com/quintel/etsource/compare/balance-electricity-sankey?expand=1) because I don't have the scenario locally) and I found:

- the imbalance on the HV net is 262.6 PJ (= 1079.05 - 816.45)
- the excess electricity going to flex technologies is 318.72 PJ (= `V(energy_production_excess_electricity,demand)`)

From your explanation I expect these two numbers to be the same, because the HV net imbalance is caused by the disappaerence of excess electricity to the `energy_production_excess_electricity` node. However, excess electricity going to flex is higher than the imbalance on the HV-net node. And the mismatch is exactly 56.1 PJ (318.7 - 262.6 PJ), which is the same imbalance that the sankey reflects!

Why is there a difference between the imbalance on the HV net and the demand of the `energy_production_excess_electricity` node? Does this have anything to do with losses?

**Comment by antw** [comment]
> Why is there a difference between the imbalance on the HV net and the demand of the energy_production_excess_electricity node? Does this have anything to do with losses?

I'm not sure. Perhaps because some of the flexibility technologies are storing energy from sources which aren't connected to the HV network? For example, energy from solar panels stored in a household P2P would not have energy flowing through the HV node.

One way to narrow this down is to go through the scenario inputs, remove whole chunks of them at a time and see if it fixes the imbalance in the sankey.

* If the imbalance is still present, add the removed inputs back in and remove the half you didn't remove.
* If the imbalance goes away you know one (or more) of them are responsible. Then you can add half of them back in and continue the process.

**Attempt one:**

```
input_one: 1
input_two: 2
input_three: 3
input_four: 4
```

Result: Imbalance. The problem could be caused by any input. Let's remove half.

**Attempt two:**

```
input_one: 1
input_two: 2
```

Result: No imbalance. Inputs one and two are unlikely to be the cause. Add them back in and remove half of those that weren't removed (add one and two, keep three, remove four).

**Attempt three:**

```
input_one: 1
input_two: 2
input_three: 3
```

Result: No imbalance. The problem is caused likely caused by input four.

**Attempt four:**

```
input_one: 1
input_two: 2
input_four: 4
```

Result: Imbalance. We've confirmed that input four is the cause, _or_ an interaction between one, two, and four. We can try removing one and two and see if the problem is still present. If it is, then input_four is the sole reason for the issue. If the problem goes away then some interaction between one, two, and four is the reason.

**Attempt five:**

```
input_four: 4
```

Result: Imbalance. Input four is the reason for the problem.

With this kind of process you can fairly quickly narrow down which input(s) are responsible.

**Comment by marliekeverweij** [comment]
Thank you, I'll try that!

> Perhaps because some of the flexibility technologies are storing energy from sources which aren't connected to the HV network? For example, energy from solar panels stored in a household P2P would not have energy flowing through the HV node.

The only flex technologies installed in the scenario are P2H in industry and P2G and both technologies convert energy from sources that are connected to the HV network (I suppose). So I think this doesn't explain the difference between the imbalance on the HV net and the demand of the energy_production_excess_electricity node.

I was wondering if this question in my previous post is true (I guess not on the basis of your above post ;) ):
So all excess electricity for flex technologies disappears from the HV node in the graph regardless of their `merit_order.level`?

**Comment by antw** [comment]
> The only flex technologies installed in the scenario are P2H in industry and P2G and both technologies convert energy from sources that are connected to the HV network (I suppose)

I don't think it matters which level the P2H and P2G are at. If they were to take excess energy from an MV or LV source, then this might explain why they appear to have more energy than is missing from the HV node. There do indeed appear to be hours where solar production might be used:

![Screenshot 2020-06-26 at 14 51 24](https://user-images.githubusercontent.com/4383/85864518-89b07900-b7bc-11ea-940d-58d39e183b94.png)

I think this might be one of those cases where the graph not being time-resolved results in wonky numbers in the graph (households are likely not [supplied almost exclusively by solar PV](https://engine.energytransitionmodel.com/inspect/766269/converters/households_locally_available_electricity), but that's what happens in the graph when we convert hourly loads back to an annual demand).

> Thank you. I did not know that there is a difference between the merit_order.level value for flexibility options and the connection to nodes in the graph. So all excess electricity for flex technologies disappears from the HV node in the graph regardless of their merit_order.level?

Energy produced by technologies attached to the HV node, and then used for flexibility, will disappear from the HV node. But electricity production at the MV or LV level won't disappear from the HV node, because it was never there in the first place.

**Comment by marliekeverweij** [comment]
Two findings:

1. The electricity imbalance is only present when the interconnector-toggle is switched ON and disappears when the toggle is switch OFF.
![Screenshot 2020-07-13 at 15 35 52](https://user-images.githubusercontent.com/32833996/87313356-0ca63300-c522-11ea-9bb6-dc34b255d565.png)
![Screenshot 2020-07-13 at 15 35 37](https://user-images.githubusercontent.com/32833996/87313363-0fa12380-c522-11ea-8c39-fb35529571c9.png)
2. The imbalance of 56 PJ is not only present in the electricity sankey and in the graph, but is also in visible when comparing the 'Electricity production' chart and the 'Use of excess electricity' chart.
![Screenshot 2020-07-13 at 16 03 54](https://user-images.githubusercontent.com/32833996/87313638-76bed800-c522-11ea-86dc-96e486c9e819.png)

So it probably has something to do with the new electrical interconnectors functionality.

**Comment by marliekeverweij** [comment]
This query can be used to quickly calculate the imbalance:
`Q(total_electricity_produced)/BILLIONS - Q(demand_in_source_of_electricity_production) - Q(electricity_exported) - Q(electricity_curtailed) - V(energy_production_excess_electricity,demand)/BILLIONS`
What this query does: TOTAL ELECTRICITY PRODUCTION - TOTAL ELECTRICITY DEMAND
In [the scenario discussed above](https://pro.energytransitionmodel.com/saved_scenarios/9347) it starts with - 56PJ: which means 56 PJ more electricity is used than produced

To explore the dependencies of the imbalance, I started with a fresh NL scenario and took the following steps:. For each step I calculated the imbalance:

1. 50 GW offshore wind -> imbalance is: 9.4e-10 (= nothing)
2. interconnector toggle ON -> imbalance is: 9.4e-10 (= nothing)
3. implement several combinations of flex technologies and interconnectors settings one by one:

   - 50 GW Underground pumped hydro storage  -> **imbalance is: -51.0 PJ**
   - 50 GW Underground pumped hydro storage  + IC toggle OFF  -> **imbalance is: -49.8 PJ**
   - 50 GW Underground pumped hydro storage  + 0 GW IC capacity -> **imbalance is: -49.8 PJ**
   - 50 GW Large-scale batteries  -> **imbalance is: -23.5 PJ**
   - 50 GW Large-scale batteries  + IC toggle OFF  -> **imbalance is: -19.6 PJ**
   - 50 GW Large-scale batteries  + 0 GW IC capacity -> **imbalance is: -19.6 PJ**
   - 50 GW P2G -> **imbalance is: -9.8 PJ**
   - 50 GW P2G + IC toggle OFF -> imbalance is: 9.4e-10 (= nothing)
   - 50 GW P2G + 0.0 IC capacity ->  imbalance is: 9.4e-10 (= nothing)
   - 3 GW P2H in food industry -> **imbalance is: -4.2 PJ**
   - 3 GW P2H in food industry + IC toggle OFF -> imbalance is: 9.4e-10 (= nothing)
   - 3 GW P2H in food industry + 0.0 IC capacity -> imbalance is: 9.4e-10 (= nothing)
 
______
What I learn from this is that:
>The electricity imbalance is only present when the interconnector-toggle is switched ON and disappears when the toggle is switch OFF.
- The statement in my previous post is not true! The imbalance also occurs when the IC toggle is switched OFF
- When the IC toggle is switched OFF, the imbalance occurs when installing underground pumped hydro storage and large-scale batteries. It does not occur when using P2G and P2H. The former are storage technologies and the latter are conversion technologies, maybe it has something to do with that!
- When the IC toggle is switched ON, the imbalance occurs for all flex technologies above
____
@antw , I think it's important for us to investigate the origin of the imbalance as it also happens when the IC toggle is switched OFF. Would you have time to look into this? And do you have enough input with this comment to start investigating?

**Comment by antw** [comment]
> Would you have time to look into this?

I haven't had the time to do so yet, sorry I haven't been much help yet. I can look into this once "featured scenarios" are complete; likely sometime next week.

**Comment by antw** [comment]
I've not had much luck with this yet, so I'm still investigating.

The load curves in Merit, and the demand of the corresponding nodes in the graph, *do* match. Therefore, as far as I can tell, there is no disagreement between Merit and the graph.

I have noticed that [energy_flexibility_hv_opac_electricity](https://github.com/quintel/etsource/blob/8a71341a1f716d0942d903fc6cb1c1cf3f1394ec/nodes/energy/energy_flexibility_hv_opac_electricity.converter.ad) has an electricity output capacity, but does not have any outgoing electricity links. This is almost certainly incorrect. Either the node should have electricity edges – so that the stored energy may be used – or it should have zero electricity output capacity. The non-zero capacity means that Merit treats the stored electricity as useable for meeting demand.

**Comment by ChaelKruip** [comment]
> I have noticed that energy_flexibility_hv_opac_electricity has an electricity output capacity, but does not have any outgoing electricity links. This is almost certainly incorrect. 

Is this a related issue? It seems to me that @marliekeverweij has shown that the discrepancy occurs even when nog OPAC is installed.

**Comment by antw** [comment]
> Is this a related issue?

Nope; just something I noticed while investigating yesterday. Though it did lead me down the wrong path yesterday: I thought that the cause of this issue might be incorrect capacities for other technologies, but I no longer believe this is the case.

**Comment by marliekeverweij** [comment]
> I have noticed that energy_flexibility_hv_opac_electricity has an electricity output capacity, but does not have any outgoing electricity links. This is almost certainly incorrect. Either the node should have electricity edges – so that the stored energy may be used – or it should have zero electricity output capacity. The non-zero capacity means that Merit treats the stored electricity as useable for meeting demand.

I think this issue is related! 

The imbalance occurs both when the IC toggle is switched OFF and ON. I think this issue is related to the imbalances that are present when the IC toggle is switched OFF and here's the reasoning:
From my example above: when the IC toggle is switched OFF, the imbalance is present for large-scale batteries ánd OPAC. For P2G and P2H there is no imbalance when the IC toggle is switched OFF! And large-scale batteries en OPAC both do not have electricity output edges:
![Screenshot 2020-07-28 at 14 10 19](https://user-images.githubusercontent.com/32833996/88663988-ab16c480-d0dc-11ea-86f6-029934eadaa6.png)
As you can see, this also goes for pumped hydro storage. I have checked the imbalances for pumped hydro storage and they also appear when the IC toggle is switched OFF! (Test: open Germany scenario -> 100 GW offshore wind + 50 GW pumped hydro storage -> imbalance = -65.8 PJ)

So it could be that if we add the electricity output edges to these three technologies, that the imbalance could not appear when the IC toggle is switched OFF. I think we should try that! 

For the imbalances that occur when the IC toggle is switched ON, I do not know have possible cause unfortunately.....

**Comment by antw** [comment]
> So it could be that if we add the electricity output edges to these three technologies, that the imbalance could not appear when the IC toggle is switched OFF. I think we should try that! That could fix half of this issue ;)

I tried this locally, by setting the output capacity of the two storage technologies to zero, and turning off the dispatchable toggle. There is indeed no imbalance with these settings.

Adding edges to route the electricity to the appropriate place in the graph should help.

> For the imbalances that occur when the IC toggle is switched ON, I do not know have possible cause unfortunately.....

"Unfortuantely", but also fortunately. 😄 This at least helps narrow down where the cause might be.

**Comment by antw** [comment]
The more I look at this, the less convinced I am that there is a genuine electricity imbalance. Every node demand exactly matches the merit order load curve. It is of course possible that Merit is wrong, and that some technologies are calculated incorrectly, but I don't believe this is the case as the merit supplies and demands are perfectly balanced.

I created [a scenario](https://pro.energytransitionmodel.com/scenarios/769809) with excess solar and household P2P, and the sankey again shows missing production:

```yaml
capacity_of_energy_power_solar_pv_solar_radiation: 150000.0
households_flexibility_p2p_electricity_market_penetration: 100.0
```

![Screenshot 2020-07-28 at 17 02 21](https://user-images.githubusercontent.com/4383/88690943-20da5a80-d0f4-11ea-8e61-228d63d965fe.png)

Except... I don't think this *is* missing production. I think P2P energy is being counted as consumption twice: [it is included in "Flexibility"](https://engine.energytransitionmodel.com/inspect/769814/gqueries/p2p_producing_converters_sankey) *and* in whatever sector the electricity is eventually used in. P2P is not a destination for electricity: it passes through and ends up somewhere else.

If I remove household P2P from the "flexibility" part of the Sankey, we get something that looks much more reasonable:

![Screenshot 2020-07-28 at 17 12 05](https://user-images.githubusercontent.com/4383/88692008-7d8a4500-d0f5-11ea-8236-24582b96712a.png)

Actually it looks like there's slightly *too much* production. I think this can be explained by the battery storing more energy than is actually used. Roughly 5PJ more energy flows into the battery than leaves (99PJ in vs 94PJ out).

We don't do a good job of representing unused and decayed energy from (electricity) storage technologies; Merit accounts for them but the graph does not. We should almost certainly update our storage nodes to be like [the heat network storage node](https://engine.energytransitionmodel.com/inspect/769815/nodes/energy_heat_network_storage). That node has two outputs edges: one for heat which is used, one ("dumped") for heat which decays and remains in the buffer at the end of the calculation year.

[The query from Marlieke](https://github.com/quintel/etmodel/issues/3421#issuecomment-659478437) shows a significant imbalance still:

```ruby
Q(total_electricity_produced) / BILLIONS -
    Q(demand_in_source_of_electricity_production) -
    Q(electricity_exported) - Q(electricity_curtailed) -
    V(energy_production_excess_electricity,demand) / BILLIONS

# => -94.60263934538163
```

This number is almost exactly the P2P output (ignoring conversion losses):

```ruby
PRODUCT(
  SUM(V(households_flexibility_p2p_electricity, electricity_output_curve)),
  MJ_PER_MWH
)

# => 94.60169386815615
```

My guess is the query is also counting P2P twice: both as `Q(demand_in_source_of_electricity_production)`, and again in `V(energy_production_excess_electricity, demand)`.

---

Note! The P2P electricity output curve fails to account for the conversion losses. This should probably be fixed at the same time as we add a "dumped" output (otherwise the curve will still be wrong, as it will include energy that isn't actually used).

**Comment by ChaelKruip** [comment]
> I think P2P energy is being counted as consumption twice: it is included in "Flexibility" and in whatever sector the electricity is eventually used in. 

Eureka! This is a very promising observation indeed. Would this mean that we can solve this at the GQL level (and the graph was actually correct)? 

> Note! The P2P electricity output curve fails to account for the conversion losses. This should probably be fixed at the same time as we add a "dumped" output (otherwise the curve will still be wrong, as it will include energy that isn't actually used).

Yes. Very sharp. 👍

**Comment by antw** [comment]
> Would this mean that we can solve this at the GQL level (and the graph was actually correct)?

Indeed. I think the solution is as simple as [not including P2P in the "flexibility" series](https://github.com/quintel/etsource/blob/861e10fd8a519040f7aa4ddef55a4ec4c9a9cf3b/gqueries/output_elements/output_series/sankey_electrical_interconnection/network_to_flexibility_in_sankey.gql#L9).

**Comment by marliekeverweij** [comment]
Thanks for looking into this Anthony and finding the solution!!!

It's nice that the solution is as simple as that, but it's also a bit painful that I haven't thought of this earlier...

So we should:

- [ ] not include P2P in the flexibility series
- [ ] add the output electricity edges to OPAC, MV batteries, pumped storage

One more question: this does not explain the imbalances that show up when using P2G and P2H right?
50 GW offshore wind + IC ON + 50 GW P2G -> imbalance is: -9.8 PJ
50 GW offshore wind + IC ON 3 GW P2H in food industry -> imbalance is: -4.2 PJ

**Comment by antw** [comment]
> One more question: this does not explain the imbalances that show up when using P2G and P2H right?

Good point. I'll look into these.

**Comment by marliekeverweij** [comment]
> 50 GW offshore wind + IC ON + 50 GW P2G -> imbalance is: -9.8 PJ

Ah I think that for P2G the same kind of double-counting issue could occur. The produced hydrogen with P2G could be used to produce electricity and that's counted as final demand. So this should also be included in the flexibility query somehow 😅 However, in my test I did not install any hydrogen power plants.

**Comment by antw** [comment]
> 50 GW offshore wind + IC ON + 50 GW P2G -> imbalance is: -9.8 PJ
> 50 GW offshore wind + IC ON 3 GW P2H in food industry -> imbalance is: -4.2 PJ

This is a bug in Merit. It's taking energy out of P2G and P2H to export as electricity. It happens because export is allowed to take energy from other flexible technologies when the dispatchable toggle is on. We calculate how much energy can be taken from the flexible technology like this:

```ruby
available = max_load - current_load
```

This makes sense for dispatchables where both the max load and current load are always zero or larger. For example, a dispatchable may have a max load of 100, and a current load (used to satisfy other demands) or 10.

```ruby
available = 100 - 10 = 90
```

This doesn't work for flexible where we represent inputs (charging) with negative numbers and output (discharging) with positives. P2G has a max load of 0 as it is not allowed to discharge, but if it has received electricity to convert into gas, its current load will be negative.

```ruby
available = 0 - (-10) = 10
```

The calculation thinks P2G can discharge 10 energy to be exported. The price-sensitive export is tested with always-on and dispatchables (and both together), but not with flexibles. 🤦 

A really simple fix would be to disallow exporting energy stored in flexibles. This would make some sense considering household P2P, but perhaps not so much for larger-scale P2P options. I suspect I need to create a proper fix.

This has also inadvertently revealed that the load curves of P2P will be incorrect if the P2P tech is used to satisfy "normal" demand _and_ for price-sensitive export. I think I can fix this by preventing storage from discharging in the same hour as it charges.

**Comment by marliekeverweij** [comment]
Nice work!!! We can close this issue now :D
