### ISSUE TITLE
Power to heat to heat network is missing in chart heat_network_production @LIVE

### ISSUE THREAD

**Issue by MartLubben** [quintel/etmodel#3437]
![image](https://user-images.githubusercontent.com/33415156/87014365-54e4ee80-c1cc-11ea-8a5d-b38547f516fe.png)

**Comment by MartLubben** [comment]
It is also missing in this chart:

![image](https://user-images.githubusercontent.com/33415156/87015214-67abf300-c1cd-11ea-8aac-d215380cd04d.png)

**Comment by marliekeverweij** [comment]
Weird! It's also missing in the excess electricity bar chart... I will have a look

**Comment by marliekeverweij** [comment]
Somehow all these ETModel migrations are not included in YModel anymore. That's why the HHP table is gone aswell: https://github.com/quintel/etmodel/issues/3424 

![Screenshot 2020-07-09 at 10 59 19](https://user-images.githubusercontent.com/32833996/87019736-3e8e6100-c1d3-11ea-8358-eb7f54d3ff5a.png)

I am now adding these migrations by hand to ETModel, think that's the quickest way. Or do you know a better way @antw ?
