### ISSUE TITLE
Scaling scenario's returns errors for ccs-technologies

### ISSUE THREAD

**Issue by DorinevanderVlies** [quintel/etmodel#3482]
The (new) ccs-technologies for hydrogen return errors when scaling scenarios.

I tried to scale some self-made scenarios and presets to 1000 households. This returned the following errors, see details below.

Presets:
- Urgenda: `share_of_energy_hydrogen_steam_methane_reformer_ccs`
- NvdT internationale sturing: `share_of_energy_hydrogen_biomass_gasification_ccs`

Scaling empty scenario's with sliders set for CCS:
- `capacity_of_energy_hydrogen_biomass_gasification`
- `capacity_of_energy_power_combined_cycle_coal`
- `capacity_of_energy_power_ultra_supercritical_coal`
- `capacity_of_energy_power_combined_cycle_network_gas`
- `capacity_of_energy_hydrogen_steam_methane_reformer_ccs`

The industry sector and DAC scaling works appropriately.

Example of error presets:
![image](https://user-images.githubusercontent.com/19907658/98658776-b87e5480-2343-11eb-8eec-cb1325af672b.png)

Example of error scenario with CCS slider set:
![image](https://user-images.githubusercontent.com/19907658/98662624-5aa03b80-2348-11eb-8095-b0467860bf68.png)

Notifying @marliekeverweij 
Assigning @michieldenhaan , please reassign when appropriate

**Comment by michieldenhaan** [comment]
Thanks @DorinevanderVlies. I'm not sure how this scaling works exactly and whether anyone still uses it. If not, I would prefer disabling this feature rather than maintaining it. Do you have any statistics on this @antw? 

And does anyone have an opinion on keeping/removing it? Notifying @ChaelKruip, @marliekeverweij.

**Comment by DorinevanderVlies** [comment]
I am ok with removing this feature now. I do not know anyone who uses it.
Let's focus on improved features for projecting scenario's on other areas.

**Comment by marliekeverweij** [comment]
> I am ok with removing this feature now. I do not know anyone who uses it.
> Let's focus on improved features for projecting scenario's on other areas.

I agree!

**Comment by antw** [comment]
Sounds good to me. From the ETEngine side, the feature is used in about 4% of scenarios created. However the ETModel side shows a different picture: less than 1% of *saved* scenarios are scaled scenarios. I also think it's fine to retire this feature.

**Comment by antw** [comment]
I think this is scaling related after all and is caused by determining start values for inputs on uncalculated graphs (unscaled scenarios determine input values based on a cached, calculated graph).

The true cause if the "share_of_energy_hydrogen_biomass_gasification_ccs" input has the start value:

```ruby
DIVIDE(
  V(energy_hydrogen_biomass_gasification_ccs, "number_of_units * typical_input_capacity"),
  SUM(
    V(energy_hydrogen_biomass_gasification_ccs, "number_of_units * typical_input_capacity"),
    V(energy_hydrogen_biomass_gasification, "number_of_units * typical_input_capacity")
  )
)
```

... but the number_of_units is dynamic (not defined in the node file) and based on the demand of the node. The node has no demand prior to it being calculated. Again: not a problem for unscaled graphs, since they *will* have a demand calculated prior to running the `start_value_gql`.

We can remove the scaling feature in the front end, which will prevent new scenarios from being created that might exhibit this error. Given this input is quite new, I don't think old scaled scenarios would be affected; though my personal preference would be to remove the feature _entirely_ – including in ETEngine – making old scaled scenarios unusable in the process.

**Comment by ChaelKruip** [comment]
> We can remove the scaling feature in the front end, which will prevent new scenarios from being created that might exhibit this error. Given this input is quite new, I don't think old scaled scenarios would be affected; though my personal preference would be to remove the feature entirely – including in ETEngine – making old scaled scenarios unusable in the process.

👍

**Comment by DorinevanderVlies** [comment]
@antw thanks!
Closing, @antw please reopen if you think I closed this too soon
