### ISSUE TITLE
Auto scaling of slider units

### ISSUE THREAD

**Issue by michieldenhaan** [quintel/etmodel#3500]
The ETM includes quite a few sliders with 'absolute' units. E.g. power plant capacity in MW, captured CO<sub>2</sub> in Mton, imported heat in PJ etc. For some smaller areas in the ETM, these units are too big to be meaningful. It would be nice if the slider units automatically scale to smaller units for those areas (capacities to kW, CO<sub>2</sub> to kT, PJ to TJ or GJ etc.)

**Comment by Geoneer** [comment]
#3505

**Comment by michieldenhaan** [comment]
I noticed that in datasets with less than 50k inhabitants, the population slider does not work. I think this is related to the start value, which is 0.0 million (the slider unit is millions and the step value is 100k), causing the slider to break. If I remember correctly, this did work fine before.

@antw Do you see a quick fix for this?

![image](https://user-images.githubusercontent.com/32056448/100426178-bf6dcc80-3090-11eb-80ea-9c18de531d65.png)

**Comment by antw** [comment]
> If I remember correctly, this did work fine before.

I thought at first this might be because we changed it so the configured step value is always respected, but reverting that commit didn't have any effect. I'm struggling to see where the step values may have been previously scaled; we do scale step values for small datasets in ETEngine, but ETModel doesn't use those step values (it configures its own, per-slider). It doesn't seem that the removal of the scenario scaling feature in ETModel is the culprit either.

I've sent a PR which will scale step values of sliders when the step is too large to be useful.

**Comment by michieldenhaan** [comment]
Thanks! Both @redekok and I (vaguely) remember that we did have some form of auto-scaling of slider units not so long ago. E.g. we both remember local datasets with installed capacities in kW rather than MW. I also encountered a local scenario someone made via the front-end which has 130 TJ heat import. With the current slider (unit PJ, step size 0.1) this is impossible: when entering 0.13 PJ in the slider box it gets rounded to 0.1 PJ, so 100 TJ.

**Comment by antw** [comment]
> E.g. we both remember local datasets with installed capacities in kW rather than MW.

You're right, and I found the code that does it. The code to scale the units from – for example – from MW to kW doesn't run anymore since we don't do anything with the scaling information sent by ETEngine (as it'll likely be removed once support for scaled scenarios is removed from ETE). As far as I can tell this information was only sent for scaled scenarios, not for smaller datasets.

We can enable this code for _all_ scenarios and datasets but this is more likely to have side-effects.

It works by taking the starting value of an input and determining if there's a more appropriate unit to use. For example, if the slider unit is MW and the start value is 0.5, the unit for the slider will be converted to kW instead. Similarly, if the start value was 5000, then the slider would instead use GW as the unit.

For small datasets this is unlikely to present an issue, but for larger ones it would result in inconsistent units used on adjacent sliders. For example, Supply → Electricity → Coal Plants in an NL scenario:

| Slider | Start value | Would scale to... |
| :---: | --: | --: |
| Pulverized coal | 2438 MW | 2.438 GW |
| Pulverized coal with co-firing | 486 MW | 486 MW |
| Coal IGCC | 0 MW | 0 W |
| etc... | ... | ... |

Clearly we'd need a smarter heuristic for determining when to scale, and when not to. Using the maximum value, or maybe the 50% point – rather than the start value – would be a good start.
