### ISSUE TITLE
Possible to query (CSV) curves rather than input/ouput curves?

### ISSUE THREAD

**Issue by michieldenhaan** [quintel/etmodel#3518]
For the user-defined curves project, we would like to add a chart that displays the curves that are/can be customised by the user. I was thinking about the chart type used for "Hourly production of solar PV" as this allows users to select separate curves using a dropdown:

![image](https://user-images.githubusercontent.com/32056448/102097679-840c2580-3e26-11eb-9939-69ccf6f56c09.png)

The 'usual' way to make the chart series, i.e. querying an input or output curve from a node, can lead to some problems here:
- some curves may be zero in certain scenarios
- some customisable curves do not correspond directly to an input/output curve of a node. E.g. the user may want to customize the 'charging from home' curve, but the electricity input curve of the relevant node (`transport_car_using_electricity`) is determined dynamically based on a mix of chosen charging strategies.

I don't think these issues are a huge deal breaker, but still it would be nice to be able to query a curve directly from an uploaded CSV file or preset dataset curve file. Is this possible at the moment? If not, what would it take to implement this?

The "Electricity price per hour" chart is able to display (uploaded) CSV files but the queries seem to be rather specific for marginal costs.

**Comment by antw** [comment]
This will require some more thought, because I'm not sure how to do this. The profiles themselves are not stored on the technology nodes (nor am I convinced they should be), but we cannot simply read the profile file itself: some are dynamically generated by Causality depending on the user's choices.

For example, EV charging profiles are interpolated using several files depend on the charging strategies chosen. Wind profiles are generated _based_ on a profile, but then altered to match the FLH of the individual technology.

I'm not really certain how to make this available to a gquery. The building of profiles happens deep within the Causality plugin, so it's neither easy nor desirable to expose this directly.

Also, I don't think the solar PV chart will be useful without additional changes:

* It stacks the series, which isn't suitable behaviour for profiles.
* A "profile" chart should probably just show a single profile at a time.
* I think a line chart might be better since we're just describing the shape of a profile; the area beneath doesn't really mean anything.

**Comment by michieldenhaan** [comment]
TY!

> I'm not really certain how to make this available to a gquery. The building of profiles happens deep within the Causality plugin, so it's neither easy nor desirable to expose this directly.

To double-check: I was referring to querying the 'raw' profiles (as defined in the CSV files on ETSource), so before any Causality magic happens. Still, if this is complicated then we should skip this for now and simply use the regular way of querying node input and output curves. The two 'problems' I mentioned are not that big of a deal and can also be seen as features (e.g. if the chart shows no curve because the node has no demand, there is no point in uploading a custom curve and the chart can help us to communicate this).

> It stacks the series, which isn't suitable behaviour for profiles.
You're right, my interpretation was that the stacking series was optional. The solar chart shows individual series for households, buildings and energy sector and then a 'total' series stacking. In our case, it would suffice to only show the individual series. But looking at the chart YML it seems that the total series is added automatically. Maybe we could add an option to disable it?

> I think a line chart might be better since we're just describing the shape of a profile; the area beneath doesn't really mean anything.
Agree. Though I don't see too much harm in colouring in the area beneath, it does make the chart more lively. 

I think about this some more, it mainly depends on how much time it would take to create a new chart type vis-a-vis making  changes to the existing chart type, as well as which option would be the cleanest/best maintainable.

**Comment by antw** [comment]
> To double-check: I was referring to querying the 'raw' profiles

Yeah, I got that; sorry if I wasn't clear with my own explanation. We could add a GQL function to get the contents of a raw CSV file, but raw profile CSVs aren't used for any technology whose profile is either `weather/...` or `dynamic: ...` (or `self: ...`, but that's not relevant to this feature).

If, for example, you want to show a chart with each of the five EV CSVs – rather than showing the final profile which is *really* used – we can do that reasonably easily.

**Comment by michieldenhaan** [comment]
Thanks! I think we should stick with the regular `carrier_input_curve` and `carrier_output_curve` queries for now. Closing this issue, let's discuss the chart elsewhere.
