### ISSUE TITLE
Error when quickly switching between new flex charts slides

### ISSUE THREAD

**Issue by mabijkerk** [quintel/etmodel#3530]
In the new Overview sidebar item in the Flexibility part of the model (Beta), an error sometimes occurs when I switch between the different slides. This error then prevents any following charts from loading.

The error as shown in the Developer Tools in my browser:
<img width="572" alt="Screenshot 2021-01-06 at 11 24 46" src="https://user-images.githubusercontent.com/67338510/103758036-ed401c80-5011-11eb-957f-83cb38fa1187.png">

Once this error has occurred, opening any new slide will show the chart stuck loading:
<img width="713" alt="Screenshot 2021-01-06 at 11 26 39" src="https://user-images.githubusercontent.com/67338510/103758155-12348f80-5012-11eb-8c67-98f6741e91b0.png">

As far as I have been able to determine the error **only** occurs in the new Overview sidebar item in the Flexibility part of the model. It happens when I switch to another slide **before** the chart of the current slide has been loaded. If I wait for the chart to load and then switch to another slide, the error does not occur. For any of the other charts it does not seem to make a difference whether you wait for the previous chart to load before switching slides or not.

**Comment by ChaelKruip** [comment]
> For any of the other charts it does not seem to make a difference whether you wait for the previous chart to load before switching slides or not.

We have witnessed this behaviour before with other hourly charts. @antw have we every found a way to solve this with previous charts?

**Comment by antw** [comment]
I've been able to reproduce this. I expect it's because there are multiple on-going requests to ETEngine.

1. Request for data needed by the original non-hourly charts.
2. Request for data used by the hourly chart.

The chart gets loaded, and when the results of request 1 arrive the chart expects that it contains the data needed to render. It doesn't, and we get the error.

I'll take care of it during the current sprint.
