### ISSUE TITLE
Green gas should be clearly shown in the energy flow sankeys

### ISSUE THREAD

**Issue by marliekeverweij** [quintel/etmodel#3533]
A client pointed this out to me and I agree! At the moment green gas falls under 'biomass & waste' in the sankey and this category does not clearly state that it includes green gas:
![Screenshot 2021-01-06 at 15 48 07](https://user-images.githubusercontent.com/32833996/103781557-d102a680-5036-11eb-9591-5d73624f1161.png)

I think there are several ways to fix this:

1. rename the category 'green gas, biomass & waste'
2. include green gas in the 'natural gas' category and rename this category to 'network gas' or 'methane'
3. add the 3 green gas production methods as one block to the sankey. then the route would be 'biomass & waste' -> green gas production -> 'green gas'

I am in favour of option 2, as the Sankey is already quite full for option 3 and option 1 is a bit messy IMO. If someone has an opinion about this, share it below!

Additionally, I would like to propose to remove the term 'network gas' everywhere in the ETM as the term is not often used by other organizations. This is actually a separate issue I realize now, so I've opened this issue: https://github.com/quintel/etmodel/issues/3534

**Comment by michieldenhaan** [comment]
With the recent update of the CO2 sankey we decided to include green gas (and bio oil) in the biomass category rather than the network gas (and oil) category. I think the main reason was that it is not clear to many people what 'network gas' is. I would prefer to go with option 1 as that takes 5 seconds to implement. In any case, whatever we do we should update the CO2 sankey as well.

**Comment by mabijkerk** [comment]
My preference would be to keep green gas separate from network gas (or natural gas), so that users can quickly recognise which energy sources are renewable. Therefore I would not go for option 2.

I think that option 3 is the most accurate, as the chart would then show the conversion losses that occur when biogas is made from wet biomass. The argument against option 3 is that it might make the chart 'messy' and that it is more difficult to implement. If this argument weighs strongly enough, then my preference would be to go for option 1.
