### ISSUE TITLE
Create a permanent link to the what's new page

### ISSUE THREAD

**Issue by marliekeverweij** [quintel/etmodel#3562]
Now that a deploy takes place every month, @noracato and I thought it would be a good idea if we would automatically put up the deploy-banner on PRO and also take it offline again.

I think 2 different banners should be implemented
1. Before the deploy, telling users the exact date and time when the deploy will take place so they know what to expect when. Start date banner: one week before the deploy. End date banner: deploy!
2. After the deploy, informing users that the deploy has taken place and directing users to the what's new page. I think this banner should only be shown if a significant update has taken place. So maybe this banner could be depended on if there are any new sections added to the What's new page.....
Start banner: deploy! End banner: one week after??

I actually think there should always be a link to the What's new page explaining the newest features, so we could also choose to add a permanent link.

What do other people think?

**Comment by antw** [comment]
I'm not so sure about it being automatic, because deploy dates and times *might* change.

> After the deploy, informing users that the deploy has taken place and directing users to the what's new page. [..] I actually think there should always be a link to the What's new page explaining the newest features, so we could also choose to add a permanent link.

I don't think we should show a banner *after* the update. If we do this we'll have a big yellow banner on the ETM 50% of the time. Instead we can show a box on the main page below "Start an existing scenario", with a brief description of recent updates and a link to the "What's new?" page. I'd suggest this stays there permanently.

![Screenshot 2021-01-22 at 16 29 39](https://user-images.githubusercontent.com/4383/105517726-4b862400-5ccf-11eb-8a81-9c3e580ec985.png)

**Comment by marliekeverweij** [comment]
> I don't think we should show a banner after the update. If we do this we'll have a big yellow banner on the ETM 50% of the time. Instead we can show a box on the main page below "Start an existing scenario", with a brief description of recent updates and a link to the "What's new?" page. I'd suggest this stays there permanently.

I like it! And it looks as if it's already implemented, great 😜

**Comment by noracato** [comment]
I like this as well! Is this something we want to get done before the deploy?

**Comment by marliekeverweij** [comment]
Yes, I would say yes :) It's nice to have a permanent link to the What's new page, so users can see where we've been working on. @ChaelKruip and other people, what do you think?

**Comment by ChaelKruip** [comment]
I like it! 👍
