### ISSUE TITLE
Downloading a chart as PNG should always capture the whole chart area

### ISSUE THREAD

**Issue by marliekeverweij** [quintel/etmodel#3578]
Sometimes the chart PNG-download does not capture the whole chart area. However, I cannot really figure out what triggers this. I first thought that it had to do with the size of my browser window, but it doesn't seem to correlate.

A few examples:
![Piekbelasting vraag en aanbod per maand(3)](https://user-images.githubusercontent.com/32833996/106150314-81b61e80-617b-11eb-8ac1-a1d9742f91e5.png)

![Behoefte aan seizoensflexibiliteit](https://user-images.githubusercontent.com/32833996/106151049-3bad8a80-617c-11eb-953b-d6d6e97aac28.png)

**Comment by antw** [comment]
I encountered exactly this issue when developing the feature, but the charts would be offset *vertically* rather than horizontally.

It happens because your browser window is too narrow to fit the sidebar, slides, and chart, so you've scrolled to the right to see the whole chart. The result is that the chart is offset in the PNG by the same amount as your window was scrolled.

**Comment by marliekeverweij** [comment]
Okay, thanks for the explanation and quick fix!
