### ISSUE TITLE
Do we want users to be able to ask questions while creating a scenario?

### ISSUE THREAD

**Issue by marliekeverweij** [quintel/etmodel#3582]
I really like the new Feedback-button!

![Screenshot 2021-01-28 at 16 09 13](https://user-images.githubusercontent.com/32833996/106157598-2b4cde00-6183-11eb-8e4f-e1db1623a9d0.png)

But what if users have questions about how something works? Should they then also use this button? I think that in that case it would be nice that they can also leave their contact details, so we can respond. We do have the https://energytransitionmodel.com/contact where you can leave your contact details, but that's a bit "far away" when you're working on a scenario. I would be in favour of adding some kind of "Question?" button aswell or changing it to a "Feedback/Question?" button. The goal of the "Question?" button is that we are more approachable to help out users when they're stuck, so they do not drop out. But it could also be that we do not want to do this :)

Curious what you think @quintel/core !

**Comment by antw** [comment]
IMO, no. The goal of this feature was to collect feedback on the ETM as easily as possible, rather than be another means to provide support. Every extra thing we add to this form is a barrier that prevents them from quickly typing and sending their thoughts.

There's text that links the visitor to our contact information if they want to start a dialogue, and for users who are signed in the e-mail sent to us *does* include their contact information so that we can reply.

I get what you're going for and I think there's value in your suggestion, but for now I'd much prefer to leave the form as one simple field so that we may collect as much feedback as possible prior to the refresh. Once we (hopefully) have that, I'd not be opposed to revisiting this.

**Comment by marliekeverweij** [comment]
Okay, clear! Where do you collect the ideas for the refresh? GitHub / Basecamp? Could you add this?
