### ISSUE TITLE
Present and Future energy flows charts result in error

### ISSUE THREAD

**Issue by AlexanderWirtz** [quintel/etmodel#3608]
Whenever I try and load one of these charts, I get an error:
![image](https://user-images.githubusercontent.com/308563/107382973-c71a0a80-6af0-11eb-8da7-20b8ea6c2a09.png)

More specifically:

>0: "p2p_to_electricity_prod_in_sankey may not be requested via the API"
>1: "p2p_to_conversion_loss_in_sankey may not be requested via the API"

The charts (and any subsequent ones) then result in a:
![image](https://user-images.githubusercontent.com/308563/107383034-dd27cb00-6af0-11eb-9cd3-fa7dbb89def6.png)

Resetting will allow other charts to be loaded, or course. 

Feel free to reassign

**Comment by antw** [comment]
A fix is on its way.

This is because of [an ETEngine change I made](https://github.com/quintel/etengine/commit/a8b80abc25e9723e181ee4909d9b1d44d67fd6ec) yesterday. A user of the API was requesting queries whose `unit` is "nodes". These queries result in a collection of nodes which we then use in *other* queries; they're not intended for public use and cause an error if you try to fetch them through the API.

It seems two queries used by the sankey wrongly had their `unit` set to "nodes". I've changed them to "MJ".
