### ISSUE TITLE
Build P2P hourly stored volume chart in ETModel and add translations

### ISSUE THREAD

**Issue by marliekeverweij** [quintel/etmodel#3614]
This chart should show the hourly stored volumes for all P2P technologies. 

Chart characteristics:
• X-axis: 8760 hour
• Y-axis: stored volume in Wh
• A drop-down menu allows the user to choose which P2P technology is displayed. We also add the option to display the total stored volume of all P2P technologies. So it will look a lot like our current solar pv curtailment chart! 
![Screenshot 2021-02-17 at 12 23 10](https://user-images.githubusercontent.com/32833996/108197613-e7624e80-711a-11eb-8f8d-1c10d1df31ba.png)

Let me know if anything is unclear!

**Comment by antw** [comment]
> So it will look a lot like our current solar pv curtailment chart!

It sounds like you're describing the solar curtailment chart exactly. 😄 

I think everything you've described is possible already using that chart: set the unit to "Wh" and you should be good-to-go. 

You have two options for the series drop-down:

1. **Do nothing** and the drop-down will be populated automatically with each series. However there isn't an option to display all simultaneously.
2. **Provide a custom `config.serie_selections` option for the chart**, [as in the solar curtailment chart](https://github.com/quintel/etmodel/blob/fa8c3c778f393fc3c987574711fbd7c3d268ef34/config/interface/output_elements/flexibility.yml#L170-L175). Each option is matched against the gquery keys. For example is you have a "p2p" option in the `serie_selections`, all series whose gquery keys contain "p2p" will be shown.

Is there anything else needed for this chart that isn't yet supported by the curtailment chart?

---

Another option would be to convert the electricity demand chart to D3v6 so that you could instead use clickable legends, rather than a drop-down.

**Comment by marliekeverweij** [comment]
> Is there anything else needed for this chart that isn't yet supported by the curtailment chart?

No, this is great 😀 Then I think we're there! 
I will rename this to-do to creating this chart on ETModel and assign @mabijkerk 

> Another option would be to convert the electricity demand chart to D3v6 so that you could instead use clickable legends, rather than a drop-down.

We have little budget for this chart, so this is unfortunately too time-consuming for now.
