### ISSUE TITLE
Shall we show the % difference wrt current costs in the dashboard instead of the absolute total costs?

### ISSUE THREAD

**Issue by marliekeverweij** [quintel/etmodel#3656]
I think it's more interesting to see the change in total costs compared to the present total costs, than the absolute total costs. Because then you know if and how much you have to invest! What do you think @quintel/core ?
You can always see the total costs when going to the costs chart.

![Screenshot 2021-03-10 at 17 16 49](https://user-images.githubusercontent.com/32833996/110661044-761b3600-81c4-11eb-92dd-cee6f4bf2fb9.png)

**Comment by AlexanderWirtz** [comment]
At first sight, I am not a fan of this idea. Our cost calculation is a bit of a mess and this difference would perhaps put a magnifying glass on all the things that we do or do not take into account. But perhaps I am just old and naturally resistant to change. I am open to being convinced

**Comment by marliekeverweij** [comment]
I think that we now put a bigger or the same size magnifying glass on the costs by showing them like this. 🕵🏻‍♀️

**Comment by DorinevanderVlies** [comment]
I share @AlexanderWirtz's worries.

Furthermore I think showing absolute difference without reference to current costs provides little insight. The same goes for absolute costs, I always have to check 2020 or a reference scenario to make sense of it.
 
Perhaps we can solve the second point (and maybe also the worries) by showing %difference wrt the current costs instead of absolute costs of absolute difference.

**Comment by ChaelKruip** [comment]
> Perhaps we can solve the second point (and maybe also the worries) by showing %difference wrt the current costs instead of absolute costs of absolute difference.

Do you suggest to show only %difference? I like that but think that the user should still be able to open the chart that shows how the total costs are built up.

**Comment by marliekeverweij** [comment]
> Perhaps we can solve the second point (and maybe also the worries) by showing %difference wrt the current costs instead of absolute costs of absolute difference.

This was also my plan, but I see now that I hadn't clearly explained it! So indeed I would propose to show a % difference.

> Do you suggest to show only %difference? I like that but think that the user should still be able to open the chart that shows how the total costs are built up.

And then when you click on the dashboard item you see the same chart as now! 
![Screenshot 2021-03-12 at 09 32 50](https://user-images.githubusercontent.com/32833996/110913851-ebe2e700-8315-11eb-8df1-f7b9328a2ac0.png)

**Comment by marliekeverweij** [comment]
I am not sure if I will be able to pick up this issue today or tomorrow. Does anybody have time left to fix it? @quintel/core Otherwise we will add it to the next deploy milestone :)

**Comment by MartLubben** [comment]
A bit late probably, but I am also not fan of showing the % difference to the current costs.  It will become too easy to draw the wrong lessons. The obvious lesson people learn is that 'is becoming much more expensive'. Costs are advanced assumptions in our workflow. These are very often not touched by users, (not even in our KEV scenario) which means they will compare the current optimised energy system with a future system without taking into account future costs assumptions. It will become too easy to draw the wrong conclusions.

It is much more interesting to compare future scenario's with each other. Or compare the current scenario including costs of externalities. 

I do not have a problem with the current absolute costs in the dashboard. It learns people the lessen that we currently spend 30 billions a year  burning fossil fuels.

**Comment by AlexanderWirtz** [comment]
I am not sure that a comparison between now and the future is relevant for the ETM. Our greenfield approach lends itself better to a comparison between different scenarios. Since we are facing a complete transformation of the energy system, why is it that relevant to see how future costs differ from present costs. We currently do not price in the external costs of polluting the atmosphere with CO2. An example:

I also agree with @MartLubben points.
