### ISSUE TITLE
Electricity storage chart show should zero instead of "no data"

### ISSUE THREAD

**Issue by mabijkerk** [quintel/etmodel#3660]
During the year, electricity storage technologies are filled and depleted. In some scenarios, it is possible that an electricity storage technology is empty for an entire week: the stored electricity volume during this period is 0 MWh. When this happens the new `Hourly stored volume of electricity` chart states "There is no data to display for this chart", even though there are multiple hourly datapoints (with value 0.0).

The following chart is made for _II3050 National governance_, with the `Batteries in households` slider set at 50% and without any other adjustments:
<img width="400" alt="Screenshot 2021-03-15 at 15 45 19" src="https://user-images.githubusercontent.com/67338510/111171707-742aeb80-85a5-11eb-88cb-4659227f7745.png">

When you zoom in on the week "25 Jun - 2 Jul" this happens:
<img width="400" alt="Screenshot 2021-03-15 at 15 46 11" src="https://user-images.githubusercontent.com/67338510/111171832-9290e700-85a5-11eb-9836-cb31a54b5fb9.png">

Preferably the chart would not show that there is no data, but it would just show the line 0.

**Comment by antw** [comment]
This message was recently requested, and added in #3590. We can't differentiate between a chart with no data (because a technology isn't installed) and a chart where the series values are all zero (because the technology *is* installed, but unused). The reason is that a load curve containing only zeros could be either.

We can:

1. Remove the message entirely; or,
2. Add a custom translation – [`output_elements.empty.flexibility_hourly_p2p_storage`](https://github.com/quintel/etmodel/blob/66d038ebfc99bc5defb7e0faf4fe596bddb4598b/config/locales/interface/output_elements/labels_groups/en_labels.yml#L14-L39) – with a more informative message about why there's no data. For example: "There is no data for this chart, or the selected technologies are not used in your scenario."

**Comment by mabijkerk** [comment]
As I understand it, the issue described in #3590 is slightly different from what I'm trying to describe here. In this case, the hourly curve is neither empty nor zero for the entire year. What does happen is that there is a specific period in the year where all values happen to be zero (in this case a specific week on which the user has zoomed in).

Judging from your answer I assume that the chart only considers the part of the series on which the user has zoomed in. If this is the case, then my question would be whether we **can** differentiate between curves that are entirely zero or empty, and curves that are empty for a specific selection but not for the entire year.

**Comment by antw** [comment]
Sorry, I misunderstood the original message. And I'm not sure how, since you were crystal clear. :blush: I've pushed an improvement to the flex-charts-front-end branch.
