### ISSUE TITLE
Gquery coal_in_source_of_electricity_production returns an error

### ISSUE THREAD

**Issue by redekok** [quintel/etmodel#3679]
Not really sure how to reproduce this error though.. I was playing around with renewable electricity production and flex technologies in the II3050 national scenario (in which no coal is supposed to be used for electricity production I guess?) and suddenly this error came up.

![image](https://user-images.githubusercontent.com/5946498/113299892-a48cbc80-92fd-11eb-8e1f-d356922e8642.png)

**Comment by mabijkerk** [comment]
I changed some of the underlying queries for coal production as part of etsource [#2435 ](https://github.com/quintel/etsource/pull/2435). It is probably related to [this](https://github.com/quintel/etsource/commit/b1049644f5ad2cee32d14757cb674464b358c925#) commit. I'll look into it.

**Comment by mabijkerk** [comment]
Since lignite was removed from the query `electricity_producing_coal_converters`, the only node that was returned from this query in the II3050 national scenario was `industry_chp_ultra_supercritical_coal`. The .sum method that was applied in the query `electricity_produced_from_coal` then crashed because it expected multiple values to sum over.

This issue has been fixed by https://github.com/quintel/etsource/commit/ac7a0d2f47d479c786ecc713ba247a938e989768.
