### ISSUE TITLE
The numbers on the CO2 factsheet differ from the CO2 chart/table ones

### ISSUE THREAD

**Issue by redekok** [quintel/etmodel#3694]
This is (at least) occurring for https://pro.energytransitionmodel.com/saved_scenarios/10515

Industry seems to be the culprit:

![image](https://user-images.githubusercontent.com/5946498/114730858-871a1280-9d41-11eb-8365-5336bacfc392.png)
![image](https://user-images.githubusercontent.com/5946498/114731044-b0d33980-9d41-11eb-985c-84494f4f4089.png)
![image](https://user-images.githubusercontent.com/5946498/114731205-d52f1600-9d41-11eb-88f5-b0c574952a42.png)

Notifying @michieldenhaan

**Comment by Charlottevm** [comment]
I struggle to find why this is the case.., @michieldenhaan do you have any idea? 

This is the industry query that is used in the dashboard:
![afbeelding](https://user-images.githubusercontent.com/74194356/114736477-6902e100-9d46-11eb-8de7-3b8b2ed55e71.png)

and this one is used within the sheet to define industry emissions:
![afbeelding](https://user-images.githubusercontent.com/74194356/114736728-a2d3e780-9d46-11eb-8bcd-4de2f9ff4395.png)

**Comment by michieldenhaan** [comment]
`industry_unused_local_production_steam_hot_water` seems to be missing from the CO2 sheet query. We've recently added that to the final demand group (and hence CO2 calculation).

The scenario has quite a bit of that:
<img width="615" alt="image" src="https://user-images.githubusercontent.com/32056448/114740382-162b2880-9d4a-11eb-9e2e-fbcb1e51812f.png">

Also the chemical sector is missing from the second screenshot, but I guess that's just in the screenshot (otherwise we would have noticed this before)

**Comment by marliekeverweij** [comment]
I have added the issue to our next deploy milestone!

**Comment by marliekeverweij** [comment]
@Charlottevm is it possible to fix this issue before our deploy? That would be nice :)
