### ISSUE TITLE
Chart security of supply does not include all must-run production

### ISSUE THREAD

**Issue by mabijkerk** [quintel/etmodel#3778]
The chart "Security of supply" includes to types of production: volatile production capacity and dispatchable production capacity. Must-run production seems to be missing from the chart:

<img width="500" alt="Screenshot 2021-07-28 at 14 12 27" src="https://user-images.githubusercontent.com/67338510/127320197-553335a6-fb8d-4238-a47b-5b7ec3b8641d.png">

The queries in the chart make use of the volatile_production group and the dispatchable_production groups.
The two must-run converters, `energy_power_supercritical_waste_mix` and `energy_chp_local_engine_biogas` (see the must_run_electricity_production group), are not included in the volatile_production group. The converter `energy_power_supercritical_waste_mix` **is** included in the dispatchable_production group, so it shows up in the chart, even though it is not in the right group.

This chart should be adapted to properly include must-run production, either as a separate label or part of a new label "Must-run and volatile production capacity". Additionally, `energy_power_supercritical_waste_mix` should be removed from the dispatchable_production group. Effects on other charts/queries should be checked. What do you think @marliekeverweij?

**Comment by marliekeverweij** [comment]
Good catch and good proposal!

**Comment by redekok** [comment]
Just a quick question for @michieldenhaan and/or @mabijkerk before merging the pull requests solving this issue: is the `energy_power_supercritical_waste_mix` supposed to be a must-run producer? I always thought the biogas CHP was the only one.

**Comment by redekok** [comment]
@michieldenhaan and I just had a short chat about this. Our preliminary conclusion is that it's inconsistent to model a must-run waste incinerator while the waste CHP is modeled as a dispatchable producer. It would make more sense to model the two as the same type of producer (both must-run or both dispatchable). We're not sure yet whether it makes more sense to make them must-run or dispatchable though. There is a continuous supply of waste which has to be incinerated, which argues for a must-run producer. Perhaps it's also possible to direct the waste flows a bit, and control how much is wasted at what time. The latter could argue for a dispatchable producer. 

@AlexanderWirtz, what are your thoughts on this?

**Comment by AlexanderWirtz** [comment]
I would argue that in principle a must-run producer is better. It is very hard to determine its profile or future full load hours, however. Now these are set in the ETDataset analysis, but just to get the production to result in the right FLH. These indicate a baseload plant. 
Since the marginal costs are quite low even for the CHP, I think in practice it will run as a baseload plant, which should be sufficient. 

So, let's make them both dispatchable and keep an eye on those marginal costs to check if they are baseload plants. NOw the waste-fired CHP only has nuclear II as competition.

![image](https://user-images.githubusercontent.com/308563/129339939-1673edd6-5dcc-4968-842f-fbb36c54d7f9.png)

**Comment by mabijkerk** [comment]
I've changed the waste incinerator to a dispatchable producer. @redekok could you review the updated branches https://github.com/quintel/etsource/pull/2508 and https://github.com/quintel/etmodel/pull/3788.
