### ISSUE TITLE
English scenario report for an NL scenario is referring to an outdated Dutch emission target

### ISSUE THREAD

**Issue by jorisberkhout** [quintel/etmodel#3794]
See screenshot. I think 49% makes more sense.

<img width="725" alt="Screenshot 2021-08-11 at 14 30 39" src="https://user-images.githubusercontent.com/4669028/129033048-75672132-7e3c-443d-a80e-db749074524e.png">

Assigning interim-deploy manager @mabijkerk . Re-assign at will.

**Comment by mabijkerk** [comment]
I have updated the values.

This issue is a good reminder that the scenario reports are (over)due for an update, especially the English versions (see issue #3638). Another example is that the EU target for 2050 is "80% - 95%". As far as I know the EU now aims for climate neutrality, though I don't think that this target has been ratified yet.
