### ISSUE TITLE
Should the "net flow of refinery products" sankey be updated based on the new oil mix structure?

### ISSUE THREAD

**Issue by redekok** [quintel/etmodel#3814]
Possibly, the "Net flow of refinery products" sankey has to be updated as well after adding the functionality to specify the oil mix for heating in the industry.

**Comment by mabijkerk** [comment]
During investigation of this issue I ran into some smaller issues:

- The slide for oil mix sliders states: "Spaces and buildings in all sectors can be heated by oil fired heaters." In most cases, such the industry, the heaters do not actually heat spaces and buildings. Instead they represent process heat. This should be changed in the description.
- The mekko does not specify what type of demand and supply is being compared. I would make it explicit that the mekko shows final demand. I would also consider renaming "Supply" and "Demand" because basically the mekko shows final demand split per sector and final demand split per fuel type.
- I can pick up these issues and will add them to the `refinery-sankey` branch on ETModel, which already includes some changes to the locales.

The core of this issue however is in the refinery Sankey itself. Preferably the new final fuel demands should be added to this Sankey. What complicates this is that the categorisation in the oil mix mekko and sliders does not align with the categorisation in the Sankey. For example, the Sankey explicitly includes `gasoline`, while the oil mix implicitly includes it under `other oil`.

- It will take me some time to determine how to align the mekko and Sankey, so this issue will not be fixed before the coming Deploy.

**Comment by mabijkerk** [comment]
Flows that had been missing due to the addition of new oil mix sliders for industry, agriculture, buildings and households. These have now been added.

Additionally, a synthetic kerosene flow has been added and the loss query has been updated.
