### ISSUE TITLE
Grid lines are missing in several charts using the Safari browser.

### ISSUE THREAD

**Issue by lottevanvlimmeren** [quintel/etmodel#3821]
When opening the II3050 International scenario in Safari, a grid line is missing in the charts 'Final energy demand in passenger transport' (at 150 PJ); 'Final energy demand in public transport' (at 15 PJ); 'Final energy demand in paper industry'; 'Hourly use of flexibility options for excess electricity'; and 'Costs of CO2 transport'.

![image](https://user-images.githubusercontent.com/89903998/131816490-bd90259c-d2e3-45bf-b83e-014b7cc19db5.png)

![Schermafbeelding 2021-09-02 om 10 59 53](https://user-images.githubusercontent.com/89903998/131815225-adf4f87e-a612-46e1-8cab-a608beb7691c.png)

**Comment by antw** [comment]
I've added a `viewBox` attribute to the charts: at one point in the past this seemed to resolve the issue, but in another more recent project it didn't.

@lottevanvlimmeren When you have the time, can you give this a spin on [beta](https://beta-pro.energytransitionmodel.com/) and see if you still have the problem in Safari?

---

I can't reproduce this myself, but I have seen exactly this issue from time to time in Chrome. No amount of trying has ever been able to reproduce it in Firefox which leads me to think it's something specific to the renderer in Safari and Chrome (they both have a common ancestor). In Chrome I found that resizing the browser window even slightly would cause the missing line to appear and disappear at random. I haven't actually seen this in Chrome for quite a long time; I had hoped it was resolved.

I think this is because we use `shape-rendering: crispEdges` on grids, to ensure they always snap to a pixel and to prevent them from looking blurry. Even though the lines are set to be 1px thick, sometimes Chrome and Safari don't snap the line correctly and it disappears.

For the chart(s) in the front-end refresh project, I opted to render the grid lines using `<rect>` elements instead of `<path>`, as rects seem unaffected. Unfortunately, I don't think the charts in the current front-end will allow us to do that.

**Comment by lottevanvlimmeren** [comment]
I quickly checked the charts I mentioned before in Safari, and for these the issue seems to be resolved. In Chrome, I haven't noticed missing lines yet, but I will keep it in mind for future testing.
