### ISSUE TITLE
Enable both positive and negative stacked areas in flex chart

### ISSUE THREAD

**Issue by mabijkerk** [quintel/etmodel#3831]
For the flex-improvement project the aim is to implement an updated version of the current chart `Hourly use of flexibility options for excess electricity`. A mockup of the chart is shown below, with capacity in GW on the y-axis and hours in the year on the x-axis:

<img src="https://user-images.githubusercontent.com/67338510/132511871-34293cc3-e4ac-4277-9fc1-ed8501b02870.png" width="600" >

The main requirements of the chart are:

- Show a line that can become both positive and negative over time: the residual load curve of electricity supply and demand.
- Show a series of stacked areas that are positive: the electricity production of flexible supply technologies such as dispatchable power plants.
- Show a series of stacked areas that are negative: the electricity consumption flexible demand technologies such as power-to-gas.
- The stacked areas are stacked on the 0 line of the y-axis.

This is not possible with the current chart types, so some changes have to be made. Notifying @michieldenhaan.

**Comment by antw** [comment]
@mabijkerk I have pushed changes to this chart on the **price-sensitive-flex** branch:

1. The chart type has been reverted to the newer flexibility chart type rather than the old "demand_curve" type. It proved much easier to change the flex chart than to hack negative series into the older chart. *(In fact, with these changes, I'm fairly certain the flex chart could replace the "demand_curve" everywhere we use it).*
2. Area series will now stack on the zero-baseline, instead of the baseline being set by the total demand series.
3. Both the area series and the demand line may appear above and below zero.

When you have time, please give this a go and let me know if you have any difficulties or if you think further changes are needed.
