### ISSUE TITLE
New flexibility category_bar chart has minor bugs

### ISSUE THREAD

**Issue by mabijkerk** [quintel/etmodel#3841]
The new `category_bar` chart on the `price-sensitive-flex` branch, called `flexibility_integral_costs` has minor bugs:

![Screenshot 2021-09-21 at 11 23 35](https://user-images.githubusercontent.com/67338510/134146199-5f9c653e-01e3-44ab-b974-fe682df91c8c.png)

- The y-axis unit euro/MWh is cropped from the chart visualisation so that it seems to state euro/MW.
- The values that are shown in the table or when hovering above bars are all displayed in two decimals, which is good since some small values can occur. However for the y-axis units, no decimals would be better.
- The x-axis group labels overlap.

Could you look into these issues @antw?

**Comment by antw** [comment]
> The y-axis unit euro/MWh is cropped from the chart visualisation so that it seems to state euro/MW

I'll see what can be done about this, but it's tricky since we have to reserve space for the axis labels ahead of time; before we know how long the labels really are. In assigning more space for this chart, we end up with extra whitespace in other charts of the same type. It might be that removing the two decimal places for this chart does the trick.

> The x-axis group labels overlap.

I'm pretty certain this is unfixable. The charts are rendered using SVG which does not support any form of text wrapping; getting text to wrap requires that [we implement it manually](https://bl.ocks.org/mbostock/7555321). This would also require dynamically sizing the bottom margin of the chart to make room for the wrapped text. This is all doable in theory, but I don't think we can get to it right now.

We may have to revert to "P2H" instead of "Power-to-heat" to get the label to fit.

**Comment by antw** [comment]
> * The y-axis unit euro/MWh is cropped from the chart visualisation so that it seems to state euro/MW
> * However for the y-axis units, no decimals would be better.

Both of these have been dealt with. I don't think I can do anything about the overlapping labels in the short term so I suggest shortening them as "P2H for ..." for now.
