### ISSUE TITLE
Make nl 2019 the standard scenario

### ISSUE THREAD

**Issue by mabijkerk** [quintel/etmodel#3852]
Because `nl 2019` is now the new standard dataset for the Netherlands, `nl 2015` has been hidden in beta. An unintended side-effect of this is that Belgium now is the first dataset that a user sees when opening beta (see screenshot below).

@antw could you set the `nl 2019` dataset as the standard selected dataset when users open the model?

![image](https://user-images.githubusercontent.com/67338510/135222513-3d602f15-d5e0-42cf-ab1a-e1743a0af16e.png)

**Comment by antw** [comment]
The last time we updated the NL dataset the new version became "nl" and the old version was retired. In this case, since we might want to maintain compatibility for the 2015 scenarios, I'd suggest:

* nl becomes nl2015
* nl2019 becomes nl

If desired, we can migrate recently created and protected "nl" scenarios to instead use "nl2015".

This maintains the convention that country datasets (de, nl, uk) represent the latest data, and nl2015 would join the ranks of nl2016, nl2017, and nl2018.

### Pros

1. Code across our apps assumes "nl" is the default dataset: ETEngine, ETModel, ETFlex, etc. We won't have to change this code; this assumption may be in many places and it may not be possible to track them all down prior to the deploy.
2. API users will continue using "nl" and will get the latest data. I expect confusion if an API scenario is created with "nl" which doesn't match what they see with a blank Netherlands (nl2019) scenario in ETModel.
3. We don't have to explain in our documentation why you can use "be", "de", or "es" (without a year), but you must use "nl2019" for the Netherlands.

### Cons

1. API users who expect "nl" to remain stable may be surprised by changes in new scenarios. I think this is a short-term problem.
2. We may have to change some names/folders in ETDataset and [a config file in ETSource](https://github.com/quintel/etsource/blob/master/datasets.yml).

---

@michieldenhaan and @ChaelKruip: I would appreciate your input on this.

**Comment by michieldenhaan** [comment]
Good suggestion! We also have to revisit the [flag icons on ETModel](https://github.com/quintel/etmodel/commit/0fdaf2783b4bc4c063520d6b54c4be246430ab3e) but that's also a minor thing.

**Comment by ChaelKruip** [comment]
Fine suggestion!

**Comment by antw** [comment]
For now, I've made nl2019 the default in ETModel.

There isn't enough time prior to the deployment to rename the datasets, write migrations in ETEngine, ETModel, and ETLocal, and allow some time to find any unexpected issues.

I have opened a new issue for renaming the datasets: https://github.com/quintel/etsource/issues/2555
