### ISSUE TITLE
Sankey transport loss falls out of chart margins

### ISSUE THREAD

**Issue by mabijkerk** [quintel/etmodel#3928]
In a blank EU-27 scenario, the transport loss of the Sankey for future energy flows is out of chart margins:

<img width="634" alt="Screenshot 2022-03-22 at 09 57 30" src="https://user-images.githubusercontent.com/67338510/159443805-c0e0d246-99c8-4d21-8408-22b075f7a779.png">

**Comment by louispt1** [comment]
I can't recreate this issue because I don't have the password for this dataset. Would you mind sharing it @mabijkerk? That's the contents of the .password file in Etsource.

It doesn't seem to be an issue in other scenarios at least, although the Sankey's do sometimes struggle to fit everything in which might be something we want to also look at in this issue.

![image](https://github.com/user-attachments/assets/25878e29-f63f-4412-a186-f2170af6f482)

**Comment by mabijkerk** [comment]
I think you need to use the `EU27_european_union_27_countries` dataset, instead of `eu`. Let me know if this works!

**Comment by louispt1** [comment]
It's this one right?
![Screenshot 2024-07-24 at 11 42 08](https://github.com/user-attachments/assets/9ef0d986-6b0e-4737-95fc-7b8f58c8fc08)

I just get this error as soon as I open it.
![Screenshot 2024-07-24 at 11 42 25](https://github.com/user-attachments/assets/e6397989-d282-417e-a1c4-2ed9f6f49ab2)

**Comment by louispt1** [comment]
Although I can replicate the issue on the server, locally it doesn't occur. @noracato is there any way this could be related to the server configuration / do you have advice on how to troubleshoot?

![image](https://github.com/user-attachments/assets/22773690-d40d-42f8-8680-ad4d40508789)
![image](https://github.com/user-attachments/assets/256633cc-4279-47f7-9c8e-e5acc79bbc6d)

**Comment by louispt1** [comment]
Fixed already on Beta!
