### ISSUE TITLE
Multi year charts: changing slider settings does not work

### ISSUE THREAD

**Issue by DorinevanderVlies** [quintel/etmodel#3933]
Changing slider settings in the MYC front-end does not work.

[MYC for a random French scenario](https://myc.energytransitionmodel.com/906411,906412,906413,906414/inputs): setting the sliders in the MYC tool **does not** work.

<img width="1167" alt="image" src="https://user-images.githubusercontent.com/19907658/160811364-184ffe14-979e-4d90-b10c-abe806087b8b.png">

I also made link to MYC for previously made scenario's. Remarkably I find that in this case I can change sliders through the MYC front-end.

[MYC for a mix of self-made scenario's](https://myc.energytransitionmodel.com/906411,906412,906413,906414/inputs): setting the sliders in the MYC tool **does** work.

<img width="1167" alt="image" src="https://user-images.githubusercontent.com/19907658/160823317-0631cf06-c282-48c1-958b-6257df7f8148.png">

**Comment by antw** [comment]
Oh darn! This is because of https://github.com/quintel/etengine/issues/1209, where protected scenarios were made to be read-only. MYC scenarios are marked as protected when we create them, and this results in being unable to move the sliders.

I'll discuss this with Chael and Nora in our sprint meeting on Monday (it's not urgent IMO since practically no one uses this feature).

**Comment by antw** [comment]
Fixed (on beta) by https://github.com/quintel/etmodel/commit/217767d3bcc4221145223e28e15640e80f23a057.
