### ISSUE TITLE
Dashboard and charts should be consistent for export and import

### ISSUE THREAD

**Issue by MartLubben** [quintel/etmodel#3958]
Dashboard showing positive import (13.2%) while the chart shows net export (-0.6 PJ): https://pro.energytransitionmodel.com/scenarios/906129

It seems like the biomass imports (1.3 PJ) are missing in the chart. 

![image](https://user-images.githubusercontent.com/33415156/166675688-c43700f2-74f5-4d59-9a82-86b22f438a61.png)

**Comment by mabijkerk** [comment]
Biomass products are included in the query for 'biogenic fuels': [biomass_in_future_energy_imports](https://github.com/quintel/etsource/blob/master/gqueries/output_elements/output_series/waterfall_76_future_energy_imports/biomass_in_future_energy_imports.gql). In the underlying query, [net_import_of_biomass_derivatives](https://github.com/quintel/etsource/blob/master/gqueries/general/import_export/net_import_of_biomass_derivatives.gql), the output of [carrier_group_biomass_products](https://github.com/quintel/etsource/blob/master/gqueries/general/carrier_groups/all_carriers/carrier_group_biomass_products.gql) is taken for the `energy_import` group.

The issue is that the import of biomass consists mainly of wet biomass, dry biomass, and oily biomass. The nodes that import these products **are included** in the `energy_import` group. The products however **are not included** in the carrier_group_biomass_products, because they are not part of primary demand. The result is that biomass imports from these three products do not show up in the chart.

@marliekeverweij I encountered this issue in the Sankey as well: primary demand is located on other nodes, for other products than the imports. Do you know why this is the case?

**Comment by marliekeverweij** [comment]
> @marliekeverweij I encountered this issue in the Sankey as well: primary demand for biomass is located on other nodes, for other products than the biomass imports. Do you know why this is the case?

In [this Basecamp post](https://3.basecamp.com/3797409/buckets/12394612/messages/1944496848 ) you can find the reasoning: "_In the previous biomass project we decided not to add the bio sources (corn, rapeseed etc.) to the primary demand group as these are not included in official statistics. Instead, the products produced with these bio sources (biodiesel, greengas etc.) are considered primary._"

For the record, the following carriers are primary:
- wood_pellets
- torrefied_biomass_pellets
- biogas
- greengas (NOTE: if greengas is made from biogas, biogas is primary, if it is made from dry/wet biomass greengas is primary)
- biogenic_waste
- bio_kerosene
- biodiesel
- bio_ethanol
- bio_oil
- bio_lng

**Comment by mabijkerk** [comment]
Thanks for linking the clear explanation. I understand that the products that we use as primary demand align with the energy balance products. The question then becomes how we can still query imports of biomass products. I think there are two ways to go about this:

- **Query the energy imports of the actual importing products**: dry biomass, wet biomass and oily biomass. The energy demand of imports then exceeds their proportion the primary demand of biomass products, since the primary demand nodes come after transformation losses e.g. from wet biomass to biogas.
- **Query the share of import for the primary energy products**: the energy demand is then proportionate to the primary demand.

Since this chart focuses on **imports** I think we don't have to align with the primary energy demand method here. I would propose to implement the first option. What do you think @marliekeverweij, do you think anyone else should weigh in on this?

**Comment by marliekeverweij** [comment]
I agree with the first option! These are the actual imports, so I think it's good to include those in the chart.

Good to double-check the dashboard items "Energy imports" & "Biomass imports" if these match with the chart
