### ISSUE TITLE
Sankey losses seem out of place

### ISSUE THREAD

**Issue by Charlottevm** [quintel/etmodel#4194]
In an empty scenario for Drenthe the sankey portrays large losses while these do not occur in the scenario (see below).

![afbeelding](https://github.com/quintel/etmodel/assets/74194356/241921ac-8032-4ca6-a1b9-71f38f8141be)

**Comment by mabijkerk** [comment]
@kaskranenburgQ or @kndehaan could you look into this at some point?

**Comment by kaskranenburgQ** [comment]
This issue exists due to the absence of non biogenic waste in the Sankey chart. 
Since Drenthe has a high percentage of power production via waste, this becomes clear in this dataset.
If we were to add non-biogenic waste, the sankey would add up:
![Screenshot 2024-05-29 at 09 37 37](https://github.com/quintel/etmodel/assets/150331345/74a3cb59-f5e9-48c8-96d9-54d4f5b99577)

The losses of non biogenic waste are at the moment calculated within the losses accounted to biomass products, within the query `conversion_loss_biomass_products_to_electricity`. 
In this query, `conversion_loss_waste_mix_to_electricity` is not multiplied by the share of biogenic waste in the waste mix. 

Because of this we see extra losses in the picture by @Charlottevm. 


@mabijkerk I can't remember the reason why we did not add non-biogenic waste to the sankey chart,  both a label, a color, and queries are ready for this carrier. Do you?

Furthermore, since the query conversion_loss_biomass_products_to_electricity does not seem to be used correctly and is used in the sankey download, we should investigate whether this is the case.

**Comment by mabijkerk** [comment]
> I can't remember the reason why we did not add non-biogenic waste to the sankey chart, both a label, a color, and queries are ready for this carrier. Do you?

I think we have simply glanced over it?

**Comment by kaskranenburgQ** [comment]
Since waste mix has been added to the sankey energy flow overview, I will close this issue.
