### ISSUE TITLE
Clarify units in 'Hybrid heat pump threshold COP for space heating' chart

### ISSUE THREAD

**Issue by AlexanderWirtz** [quintel/etmodel#4219]
The unit on the y-axis is not always recognized. Suggest that instead of 
`ct / MJ heat` we use `€ct / MJ heat`.

The same might be needed for the slider units for:
` input_element_households_flexibility_consumer_gas_price`     and
` input_element_households_flexibility_consumer_electricity_price` 

Re-assign as needed.

**Comment by mabijkerk** [comment]
@KoenvanB / @kaskranenburgQ perhaps one of you can pick this up while working on the hybrid oil heater?

**Comment by KoenvanB** [comment]
All three mentioned interface elements now refer to `€ct / MJ heat`.

Personally, I still find it confusing that the unit of choice here is cents rather than euros. As far as I know, this is the only place in the ETM that refers to cents. However, changing the units to euros means diving into the inner workings of the chart and that is out of scope for now.

I will include this point in a future issue on updating the cost optimal threshold chart.
