### ISSUE TITLE
Need to fix featured scenario's for West-midden Brabant

### ISSUE THREAD

**Issue by kaskranenburgQ** [quintel/etmodel#4241]
On the website we have 2 featured scenario's for West-midden Brabant. 

![Screenshot 2024-04-15 at 16 02 22](https://github.com/quintel/etmodel/assets/150331345/102f2386-55e6-4196-b44f-c816159fa664)

If you click on one of them, nothing happens. 
Since no introduction page for the featured scenario opens, it is not possible to remove them.

After a short consultation from the @noracato we discovered that this is possibly broken since the area code of the scenario does no longer exist.

A migration thus needs to be written which replaces the area code for all scenario's.

Notifing @mabijkerk, will pick this up myself.

**Comment by mabijkerk** [comment]
I wonder whether these scenarios are still relevant enough to keep them as featured scenarios.

**Comment by mabijkerk** [comment]
To add to my previous comment, these scenario likely refer to the region code `RGNB01` (see the [Dataset Manager](https://data.energytransitionmodel.com/datasets/RGNB01)). This region is still maintained on ETLocal but no longer available on ETSource (see the [datasets](https://github.com/quintel/etsource/tree/master/datasets)).

Writing a migration therefore will likely have no effect, since the region is no longer available. The two options are then:

1. Remove the featured scenarios
2. Re-install the region in ETSource using the available data on ETLocal

Finally, notifying @noracato, it would be useful at some point to add some error routing for this. Something like: "The region modelled in this scenario is no longer available in the model, contact Quintel for questions". What do you think?

**Comment by noracato** [comment]
> it would be useful at some point to add some error routing for this

For the featured scenarios that would be a great idea. To keep the featured page, but without the open button. 

Also handy because currently we run into the problem that, without being able to view the scenario's featured page, there is no way to press the 'unfeature' button anymore. I have to go manually into the database now to unfeature it...

**Comment by mabijkerk** [comment]
> I have to go manually into the database now to unfeature it...

Could you pick this up at some point @noracato?
