### ISSUE TITLE
Find new place for windmill capacity slider

### ISSUE THREAD

**Issue by kaskranenburgQ** [quintel/etmodel#4257]
The windmill capacity slider can be found inside the [Energy mix infographic](https://energytransitionmodel.com/scenario/data/data_visuals/energy-mix-infographic) slide. See screenshot below.

<img width="443" alt="Screenshot 2024-05-02 at 16 26 47" src="https://github.com/quintel/etmodel/assets/150331345/19a34bd5-a6fc-43a4-bf61-b49e0a42fb19">

I think this slider should either be removed or placed in the Costs & efficiencies section under [Renewable electricity](https://energytransitionmodel.com/scenario/costs/specs_renewable_electricity/wind-turbines) 

@mabijkerk,@kndehaan What do you think?

**Comment by kndehaan** [comment]
I'm currently updating the Energy mix infographic where I came across this slider as well. This slider is only used for the infographic where the number of installed onshore wind turbines will be shown based on the slider value and the total installed capacity. 

However, for the number of offshore wind turbines a hard-coded value of 10 MW is used to calculate this number from total installed capacity. So if we want to keep this slider, I think we should add one for capacity offshore wind turbines as well rather than using the hard-coded value. Potentially also add sliders for adjusting the Wp per panel for PV panels, where the total number of PV panels can be calculated from. 

If we decide to keep the slider, I would say not to move it to a different location since the input is only relevant for the Energy mix infographic.

**Comment by mabijkerk** [comment]
> So if we want to keep this slider, I think we should add one for capacity offshore wind turbines as well rather than using the hard-coded value. Potentially also add sliders for adjusting the Wp per panel for PV panels, where the total number of PV panels can be calculated from.

Good suggestions, but for now I would not add functionality to the Energy Mix, only fix any remaining bugs.
