### ISSUE TITLE
Integrate changelog mail in mailchimp

### ISSUE THREAD

**Issue by mabijkerk** [quintel/etmodel#4300]
**Background**
Currently we have a manually updated mailing list for the Deploy changelog mail in Excel. This mailing list exists for 'power users' who work with the API and therefore value updates on changed/new/deleted inputs. There might be users that would also value such a changelog mail, but that we do not know of. These users in their turn do not know of the changelog mail.

**Goal**
Instead of a manual Excel mailing list, manage mail subscriptions to the changelog in the same way as the newsletter. We can then integrate the option of subscribing for the changelog, similar to the newsletter, in the ETM account:

<img width="800" alt="Screenshot 2024-07-15 at 16 17 49" src="https://github.com/user-attachments/assets/13078198-9689-4f5a-9517-55b18728be38">

- [x] Setup mailchimp for changelog mail
- [x] Integrate changelog mail option in ETM account
- [ ] Refer to changelog mail option where relevant, for example in What's new and/or API docs
- [ ] Add users from Excel to new mailing list

@noracato @louispt1 does this feel like a complete set of to-do's?

**Comment by louispt1** [comment]
<img width="1296" alt="image" src="https://github.com/user-attachments/assets/736fef7f-aa28-48d4-9707-9db7c6542acb">

Before I continue with this, I wanted to check that we definitely want to go down the Mailchimp route. Currently (and in the past) we've been on a free Mailchimp plan. Now we have more than 500 contacts, they want us to pay. The Mailchimp 'newsletters' have not been sent since April 2022.

Note that the below prices are for the 500-1500 contact range. We are currently at ~950. The prices do increase slightly with more contacts.

<img width="1600" alt="Screenshot 2024-07-24 at 08 53 22" src="https://github.com/user-attachments/assets/d7bf8ef6-88fe-46ab-a799-ddf70afc5334">

@mabijkerk any thoughts on this?

**Comment by mabijkerk** [comment]
Thanks for this @louispt1, I'll discuss it coming Monday.
